### ISSUE TITLE
Add `axis=None` functionality to `ak.to/from_regular`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1037]
### Description of new feature

I believe we discussed this on Gitter (or perhaps elsewhere) @jpivarski. I'm opening this issue to track the feature as I don't have time just now to work on it, but want to keep tabs on it.

It would be useful if there were an `axis=None` variant of the to/from regular functions such that the entire layout may be converted to/from regular contents.

**Comment by jpivarski** [comment]
This is being addressed in v2, as an application of a simplified `recursively_apply` interface.

https://github.com/scikit-hep/awkward-1.0/blob/8981e2dd1ac813d62d46c3d98b5d38007803c954/src/awkward/_v2/operations/structure/from_regular.py#L38-L70
