### ISSUE TITLE
Awkward array to numpy structured array fills in None with garbage

### ISSUE THREAD

**Issue by rocurley** [scikit-hep/awkward#1066]
### Version of Awkward Array

1.4.0

### Description and code to reproduce

**Code:**
```python3
import awkward as ak
tab = ak.Array({"A": [1,2,3], "B": [4, None, 5]})
print(tab.to_numpy())
```
**Output:**
```
[(1,               4) (2, 0) (3,               5)]
```
**Expected Output:**
Something like

```
[(1,               4) (2, --) (3,               5)]
```
Specifically, I expected to get a masked array, or failing that, an error.

If I construct the array using pyarrow instead:
```python3
import pyarrow as pa
import awkward as ak

tab = pa.table(
    {
        "A": pa.array([1, 2, 3], type=pa.int32()),
        "B": pa.array([4, None, 6], type=pa.int32()),
    }
)
aktab = ak.from_arrow(tab)
print(aktab.to_numpy())
```
I'm able to get what looks like uninitalized memory (changes each run). Presumably this is an artifact of how pyarrow constructs nullable arrays, and awkward re-using the buffer.
```
[(1,     4) (2, 32607) (3,     6)]
```

**Comment by jpivarski** [comment]
The `np.ma.MaskedArray` and its mask were getting lost while constructing a structured array. I hadn't thought about the combination of these two things (actually, didn't know it was possible: the mask must be a structured array as well).

https://github.com/scikit-hep/awkward-1.0/blob/f9aab6f25e6afe6cce42b7b2590fa4bdff4cc205/tests/test_1066-to_numpy-masked-structured-array.py#L11-L16
