### ISSUE TITLE
"path too long for Windows" when calling `ak.from_json` with a long json string on Windows

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/awkward#1084]
### Version of Awkward Array

not sure

### Description and code to reproduce

Discovered by a student in a course (who was working on Windows). We were going through the bikeroutes example:

```python
import awkward as ak
import urllib
url = "https://raw.githubusercontent.com/Chicago/osd-bike-routes/master/data/Bikeroutes.geojson"
bikeroutes_json = urllib.request.urlopen(url).read()
bikeroutes = ak.from_json(bikeroutes_json)
```

Gave him the following error:

```
ValueError Traceback (most recent call last)
<ipython-input-25-171b38169686> in <module>
----> 1 bikeroutes = ak.from_json(bikeroutes_json)

~\Anaconda3\lib\site-packages\awkward\operations\convert.py in from_json(source, nan_string, infinity_string, minus_infinity_string, complex_record_fields, highlevel, behavior, initial, resize, buffersize)
1054 is_path, source = ak._util.regularize_path(source)
1055
-> 1056 if os.path.isfile(source):
1057 layout = ak._ext.fromjsonfile(
1058 source,

~\Anaconda3\lib\genericpath.py in isfile(path)
28 """Test whether a path is a regular file"""
29 try:
---> 30 st = os.stat(path)
31 except OSError:
32 return False

ValueError: stat: path too long for Windows
```

unfortunately i currently have no windows Installation available to reproduce it

**Comment by agoose77** [comment]
I don't have a Windows to hand to confirm this, but it looks very plausible — Windows has a 260 char path limit IIRC, and we check whether source is a path first.

**Comment by jpivarski** [comment]
If the path is too long, then it can't be a real file, so this should have an easy fix: we can catch the ValueError and go into the mode of assuming that the string is JSON.

For the bike routes example, `ak.from_iter(py_bikeroutes)` is an alternative to `ak.from_json(js_bikeroutes)`.
