### ISSUE TITLE
Implement `__awkward_function__` and `__awkward_array__` protocols

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1126]
### Description of new feature

As discussed in the Awkward-Dask meeting, it would be useful (both for v2 and for Dask) to allow other libraries to share the Awkward high-level API with alternative array class implementations. 

We suggested closely following the [NEP18 specification](https://numpy.org/neps/nep-0018-array-function-protocol.html), but with a different name: `__awkward_function__`.

Additionally, perhaps we would want to implement an `__awkward_array__` interface, like `__array__`, to allow third-party libraries to define conversion routines from their array types to Awkward.

**Comment by jpivarski** [comment]
@nsmith- This is the issue I was referring to earlier today; I had forgotten who opened it!

**Comment by agoose77** [comment]
THe `__awkward_function__` protocol has now been added in #2531.

**Comment by jpivarski** [comment]
I'm going to call this done because you've implemented `__awkward_function__`. We can revisit the idea of an `__awkward_array__` protocol if it's ever needed.

In general, these kinds of protocols should be like PEPs or NEPs or SPECs, if we can come up with a good acronym...

**Comment by agoose77** [comment]
Hehe, what about Awkward Improvement Mechanism (AIM)? ;)

**Comment by jpivarski** [comment]
That's great! I was trying to come up with things yesterday, but had nothing as good as this. It allows the "awkward" to be an adjective. And an "AIM" can be missed...
