### ISSUE TITLE
ak.where seems to lose the array behavior

### ISSUE THREAD

**Issue by lauridsj** [scikit-hep/awkward#1152]
### Version of Awkward Array

1.5.1

### Description and code to reproduce

I use the `LorentzVector` behavior implemented in `coffea`. When using `ak.where` to choose between two arrays of lorentz vectors, the resulting array seems to lose its behavior. Setting the behavior manually (using `arr.behavior`) does not seem to fix this. See the attached code for a reproducible example.

```
import awkward as ak
import numpy as np

from coffea.nanoevents.methods import vector

N = 10

# Producing some random Lorentz vector arrays
v1 = ak.Array({
        "x": np.random.normal(size=N), "y": np.random.normal(size=N), "z": np.random.normal(size=N),
        "t": np.random.normal(size=N)}, with_name="LorentzVector",
        behavior=vector.behavior)

v2 = ak.Array({
        "x": np.random.normal(size=N), "y": np.random.normal(size=N), "z": np.random.normal(size=N),
        "t": np.random.normal(size=N)}, with_name="LorentzVector",
        behavior=vector.behavior)

# Choosing randomly between the two arrays using ak.where
arr = ak.where(np.random.uniform(0,1,N)>0.5, v1, v2, axis=0)

# The type of the records is still there, but the behavior is gone
print(arr.type)
print(arr.behavior)

# Using the add operation on the array results in a ValueError

res = arr[0:5] + arr[5:10] # gives an error

# Adding the behavior manually fixes the addition, but fields such as mass are still unavailable

arr.behavior = arr1.behavior

res = arr[0:5] + arr[5:10]

arr.mass # gives an error

# For whatever reason, this fixes the fields even though it should do nothing

arr = arr[:]

arr.mass
```

**Comment by agoose77** [comment]
Looking at [the source code](https://github.com/scikit-hep/awkward-1.0/blob/06dfff9deed9d072b7353ab45357e99c4edd51e5/src/awkward/operations/structure.py#L1747) of `ak.where`, we are passing in layouts to `ak.behavior` (which [expects `Array` objects](https://github.com/scikit-hep/awkward-1.0/blob/06dfff9deed9d072b7353ab45357e99c4edd51e5/src/awkward/_util.py#L488)).

**Comment by jpivarski** [comment]
Yup, thanks! I'm fixing that in a branch, and I'm also seeing if I can make assignment to `ak.Array.behavior` change the array class, as that's what @lauridsj was expecting (and only got when he took a trivial slice, `arr[:]`, which went through the `ak.Array` constructor, which _does_ change the array class).

**Comment by agoose77** [comment]
Ah, sorry — I posted this whilst moving between devices, and it was a partial reply!

I also noticed that we do this in a couple of other routines in `structure.py` - would you like me to make a list of them?

**Comment by jpivarski** [comment]
> would you like me to make a list of them?

Yes, please! Getting these consistent would be a big deal. I'm also copying all of these corrections into v2 so that they're not lost in the upgrade.

**Comment by jpivarski** [comment]
PR #1153 fixes `ak.where`'s behavior-setting and also adds this:

```python
>>> v1 = ak.Array({
...         "x": np.random.normal(size=N), "y": np.random.normal(size=N), "z": np.random.normal(size=N),
...         "t": np.random.normal(size=N)}, with_name="LorentzVector")
>>> type(v1)
<class 'awkward.highlevel.Array'>
>>> v1.behavior is None
True
>>> v1.behavior = vector.behavior
>>> type(v1)
<class 'coffea.nanoevents.methods.vector.LorentzVectorArray'>
>>> v1.behavior is None
False
```

Setting the behavior reevaluates what the class ought to be, so that new methods (like `.mass`) become available immediately after that assignment.

If you give me a list of other functions to fix, I can do that—or you can push directly to the PR branch. Just coordinate with me so that we know when to merge it.

**Comment by jpivarski** [comment]
With the latest commit, 8528b25f9611d38912c4b64a1874813151a50e8d, you can also unset it:

```python
>>> v1 = ak.Array({
...         "x": np.random.normal(size=N), "y": np.random.normal(size=N), "z": np.random.normal(size=N),
...         "t": np.random.normal(size=N)}, with_name="LorentzVector")
>>> type(v1)
<class 'awkward.highlevel.Array'>
>>> v1.behavior = vector.behavior
>>> type(v1)
<class 'coffea.nanoevents.methods.vector.LorentzVectorArray'>
>>> v1.behavior = None
>>> type(v1)
<class 'awkward.highlevel.Array'>
```

(and if different behaviors are set, each mapping to a different class, it won't get stuck on the first one).

**Comment by agoose77** [comment]
We also seem to pass layouts in `src/awkward/operations/structure.py`:
* L1747 `concatenate`
* L4420 `isclose`

WIll check the other files.

**Comment by jpivarski** [comment]
`ak.concatenate` is already using the high-level `arrays` from the argument list, not the `contents` derived from `to_layout`:

https://github.com/scikit-hep/awkward-1.0/blob/06dfff9deed9d072b7353ab45357e99c4edd51e5/src/awkward/operations/structure.py#L1639-L1650

But for `ak.isclose`, you're right: `a` and `b` are the high-level arrays, while `one` and `two` are the layouts:

https://github.com/scikit-hep/awkward-1.0/blob/06dfff9deed9d072b7353ab45357e99c4edd51e5/src/awkward/operations/structure.py#L4420

Fixed in daf4fbfc93ef75dc9484489b055524e8b734d5fd.

**Comment by jpivarski** [comment]
If you don't see any more, we can merge the PR.

**Comment by agoose77** [comment]
I did another search and I couldn't see anything. Maybe we should add some tests to catch this for all the high level ops?

**Comment by jpivarski** [comment]
Perhaps, although I'd be satisfied by merging the PR now. A suite of tests would have to construct non-erroneous examples for each function, and that would take quite a bit of time.

**Comment by lauridsj** [comment]
Thanks a lot for this fix - this was very quick!
