### ISSUE TITLE
`ak.values_astype` produces incorrect results for 2D NumPy array

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1173]
### Version of Awkward Array

1.5.1

### Description and code to reproduce

```python3

>>>  x = ak.Array(ak.layout.NumpyArray(np.array([[0,1],[2,0]])))
>>> ak.values_astype(x, np.bool_)
<Array [[False, True], [False, False]] type='2 * 2 * bool'>
>>> ak.values_astype(ak.to_regular(x), np.bool_)
<Array [[False, True], [True, False]] type='2 * 2 * bool'>
```

It *looks* like we're just missing the dimension hidden inside the `NumpyArray` !

**Comment by jpivarski** [comment]
Yes, the "False, False" in the second fixed-length array is random memory because the copy only went over 2 items, rather than 4. The PR fixes it and will be auto-merged.

**Comment by agoose77** [comment]
Fab, that's what I was thinking - I feel as though we fixed a similar bug this past year!

Thanks for the _rapid_ PR.
