### ISSUE TITLE
`explode_records=True` leads to empty results for layouts without records

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#1176]
### Version of Awkward Array

1.7.0

### Description and code to reproduce

Based on the docstring for `ak.to_arrow_table`, you would think that `explode_records` would have no effect on arrays without records:
https://github.com/scikit-hep/awkward-1.0/blob/ab26ed33c8e2ab18b70bcc190ba8933ad86a7d1b/src/awkward/operations/convert.py#L2540-L2542

Yet using this option with a record-less array leads to an empty table:

```python
>>> import awkward as ak
>>> a = ak.Array([1])
>>> ak.to_arrow_table(a)
pyarrow.Table
: int64 not null
>>> ak.to_arrow_table(a, explode_records=True)
pyarrow.Table

```

The issue is here:

https://github.com/scikit-hep/awkward-1.0/blob/ab26ed33c8e2ab18b70bcc190ba8933ad86a7d1b/src/awkward/operations/convert.py#L2566-L2570

In the example, `a` has no keys, so you end up with no contents. The same thing appears in `ak.to_parquet`, which has the `explode_records` option as well.

Perhaps the solution is as simple as adding a clause to the `if` here, checking whether there are any keys at all?

**Comment by jpivarski** [comment]
See more detail in my response to ssl-hep/ServiceX_Uproot_Transformer#29, but `explode_fields` is being deprecated in Awkward version 2. There's an example workaround there.

**Comment by jpivarski** [comment]
(This wasn't really a bug; it was intended behavior, though I understand how it would be confusing. You can't use `explode_records` indiscriminately on all data, but then again, it's restructuring the data so it's something you'd have to be paying attention to, anyway. In retrospect, I probably should have never added this option, but instead I should have written documentation on how to do the exploding manually when an Arrow error message comes up.)
