### ISSUE TITLE
MacOS tests randomly segfault

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1209]
### Version of Awkward Array

HEAD

### Description and code to reproduce

For a while now (weeks?), the MacOS `tests/**/*.py` have been failing with low probability—there's about a 1 in 5 chance that one of the tests (based on Python 3.6, 3.7, 3.8, 3.9, and 3.10) raises a segfault. [Here is an example.](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=8629&view=logs&j=a8b274c7-ba97-5314-7052-52a2bff17ff3&t=70094b08-aa59-59b5-e85c-b680ecf0ab0f) When that happens, the error code may be one of several signals, such as 6, 10, or 11. It often fails while running v2 tests, but that might just be because the v2 tests are after than the v1 tests. The fact that it hasn't been failing consistently in the same test suggests that the signal is invoked during a garbage collection, but the actual error is earlier.

If this really is due to a v1 segfault, it's rare enough that we could even ignore it—there won't be many more v1 versions released. If it's due to something in v2, then we really must take care of it. (And if it's narrowed down to an easy v1 issue, then we'd also want to fix it in that case.)

If this had been a Linux segfault, I would run the tests locally many times in order to reproduce it (e.g. run it 100 times to virtually guarantee the P ≈ 1/25 case, then I would bisect the tests to find at least one that raises it. It might be necessary to insert explicit `gc.collect()` calls to trigger it in absence of many other tests. However, the bug only manifests itself on MacOS, and I don't have access to a Mac to do that intensive testing on. (Doing it through CI would be awful because it would add the compilation time to each run.)

Does anyone (@ianna, @ioanaif, @swishdiff, @agoose77, ...) have a Mac and is willing to try that bisection search? Maybe my first question should be if any Mac users have encountered this in their local tests (assuming you've been running enough tests recently).

**Comment by sw5sh** [comment]
I unfortunately don't have access to a Mac Device too, but there could be a way to run macOS as a docker image. I can't test it right now, but a quick search brings this up. 
https://github.com/sickcodes/Docker-OSX

**Comment by ianna** [comment]
I'll try to chase it.

**Comment by jpivarski** [comment]
Thanks! If it doesn't present itself after just running the test some 5‒10 times, we'll stop and rethink. (I've been thinking about it, and maybe running it many times on the _same_ computer might not trigger it, because triggering it has something to do with how memory happens to be laid out, and it resets itself after each run...)

**Comment by ianna** [comment]
I wonder if this can be an issue https://stackoverflow.com/questions/24126799/python-garbage-collection-causes-segfault-when-destructing-a-c-object

**Comment by jpivarski** [comment]
That's the kind of thing it probably is, though not as an analogy to take too closely. (It's probably some double-free because it happens at random times, and therefore I guess it's in a garbage collection, but the specific StackOverflow question was about Boost Python, not pybind11, and we also track array buffer memory separately from explicit Python objects.)

Since it's not giving us any clues about itself, I don't think it would be useful to try to solve it deductively. Just finding out which test is at fault via bisection would be a huge improvement.

**Comment by agoose77** [comment]
I've just seen this, I don't have a Mac unfortunately :( Maybe we can hack something together using Darling if no-one has access to a Mac?

**Comment by jpivarski** [comment]
@ianna has started to look at it, though it took 1000 runs to get 2 failures. (CI has a higher rate than that.) If there's anything that can trigger the segfault more consistently, then that would be the first step toward bisecting and finding it.

I was thinking of adding `gc.collect()` at the end of every test (suggested it to @ianna this morning). That is, turn each

```python
def test_something(asdf):
```

into

```python
def test_something(asdf):
    original_test_something(asdf)
    gc.collect()

def original_test_something(asdf):
```

so that the garbage collector would be collecting symbols that were defined in the original `test_something` (being called after that scope is closed).

The way it manifested itself at random times, I suspect it's a double-free when garbage collecting, and therefore doing it at deterministic times would help narrow down where the invalid pointer operation is happening.

**Comment by ianna** [comment]
@jpivarski - yes, I've added it, but the crash is still not reproducible :-(

**Comment by ianna** [comment]
```
tests/v2/test_0449-merge-many-arrays-in-one-pass.py::test_lists gc: collectable <cell 0x11ff85ed0>
gc: collectable <cell 0x11ff869e0>
gc: collectable <tuple 0x11ff38c80>
gc: collectable <function 0x11ffa5360>
True
PASSED
tests/v2/test_0449-merge-many-arrays-in-one-pass.py::test_records Fatal Python error: Aborted

Current thread 0x0000000109252e00 (most recent call first):
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/logging.py", line 335 in reset
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/logging.py", line 693 in _runtest_for
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/logging.py", line 708 in pytest_runtest_setup
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_callers.py", line 34 in _multicall
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/runner.py", line 311 in from_call
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/runner.py", line 120 in runtestprotocol
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/main.py", line 323 in _main
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/site-packages/pytest/__main__.py", line 5 in <module>
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 86 in _run_code
  File "/Users/yana/.pyenv/versions/3.10.1/lib/python3.10/runpy.py", line 196 in _run_module_as_main

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator (total: 13)
```

**Comment by jpivarski** [comment]
@ianna I think you said before that "merge many" is where it failed before, when it failed. I had been thinking it was in a garbage collection pass and not actually related to the mergemany method or this test. But if it's always failing (when it fails) in `test_0449-merge-many-arrays-in-one-pass.py` even though it enters that function with all garbage already collected, that's suggesting new information: that it _really is_ something in `test_0449-merge-many-arrays-in-one-pass.py` that's the problem.

If you run just that one test file, `test_0449-merge-many-arrays-in-one-pass.py` obscenely many times (10× or 100× your current runs, because it's just one file), does it ever segfault? If so, it's bracketed and we can narrow in.

**Comment by ianna** [comment]
@jpivarski - I run all the tests (with forced garbage collection after each one) in a 100x loop. It doesn't look good: there is a random segmentation fault on exit (it happened 4 times in addition to 7 aborts). It makes me think that the C++ destructors of the wrapped instances are called in an order we do not expect.

Firstly, I will update to a master where we do not mix v1 and v2 in tests. Then I'll backtrace destructors and, finally, try to revert to `shared_ptr`. 

```
(base) yana@iannas-macbook-pro-2 awkward-1.0 % grep Seg /tmp/yana/*
/tmp/yana/gc-tests.2022.01.13-09.54.17.log:Fatal Python error: Segmentation fault
/tmp/yana/gc-tests.2022.01.13-10.31.26.log:Fatal Python error: Segmentation fault
/tmp/yana/gc-tests.2022.01.13-11.51.44.log:Fatal Python error: Segmentation fault
/tmp/yana/gc-tests.2022.01.13-11.54.33.log:Fatal Python error: Segmentation fault
(base) yana@iannas-macbook-pro-2 awkward-1.0 % grep Abo /tmp/yana/*
/tmp/yana/gc-tests.2022.01.13-09.49.45.log:tests/v2/test_0557-min-max-initial-argument.py::test Fatal Python error: Aborted
/tmp/yana/gc-tests.2022.01.13-10.29.17.log:tests/v2/test_0404-array-validity-check.py::test_RecordArray Fatal Python error: Aborted
/tmp/yana/gc-tests.2022.01.13-10.51.17.log:tests/v2/test_0449-merge-many-arrays-in-one-pass.py::test_records Fatal Python error: Aborted
/tmp/yana/gc-tests.2022.01.13-11.16.37.log:tests/v2/test_0449-merge-many-arrays-in-one-pass.py::test_lists Fatal Python error: Aborted
/tmp/yana/gc-tests.2022.01.13-11.21.45.log:tests/v2/test_0449-merge-many-arrays-in-one-pass.py::test_lists Fatal Python error: Aborted
/tmp/yana/gc-tests.2022.01.13-11.30.33.log:tests/v2/test_0449-merge-many-arrays-in-one-pass.py::test_lists Fatal Python error: Aborted
/tmp/yana/gc-tests.2022.01.13-11.43.48.log:tests/v2/test_0449-merge-many-arrays-in-one-pass.py::test_records Fatal Python error: Aborted
```

**Comment by ianna** [comment]
@jpivarski - you were right, the segfault seems to be unrelated to the `unique_ptr`  -  I have managed to reproduce it after reversing to a previous implementation based on `shared_ptr`. The good news is that the segfault happens only in the v2 tests (both with and without `unique_ptr`s). It is good because it's faster to reproduce. I run the v1 and the v2 tests separately. The bad news is that it happens in v2.

v1 arrays are immutable, that is if we need to modify them, we allocate new memory with `awkward_malloc` (e.g. `new` that is always paired with `delete []`).

It does look like we are overwriting memory, I'm trying to narrow it down. Also I'm going through the code and checking  for heap memory errors:

- [ ] Attempting to free memory already freed.
- [ ] Freeing memory that was not allocated.
- [ ] Attempting to read/write memory already freed.
- [ ] Attempting to read/write to memory which was never allocated.
- [ ] Memory allocation error.
- [ ] Reading/writing to memory out of the bounds of a dynamically allocated array

and stack (local variables) memory errors:

- [ ] Reading/writing to memory out of the bounds of a static array. (array index overflow - index too large/underflow - negative index)
- [ ] Function pointer corruption: Invalid passing of function pointer and thus a bad call to a function.

**Comment by jpivarski** [comment]
v2 arrays are also immutable. Once constructed, we should never be overwriting any of their buffers, and the Python objects are replaced, rather than modified in place.

The fact that the segfault is in v2 is in another way good news: we can eliminate a variety of ways that v1 can produce errors. v2's NumPy handling introduces significantly fewer avenues for segfaults than v1's pointer handling. But there are a few that remain:

   * v2 arrays built via `from_iter` (perhaps indirectly through the highlevel `Array` constructor) are supposed to be allocated and owned by NumPy (in pybind11 C++ code, [calling NumPy to allocate and own the buffers here](https://github.com/scikit-hep/awkward-1.0/blob/5f5687fde4bd15ba67707c12370b7cc15bcdae43/include/awkward/python/content.h#L83-L90), [exposed to Python here](https://github.com/scikit-hep/awkward-1.0/blob/5f5687fde4bd15ba67707c12370b7cc15bcdae43/src/python/content.cpp#L1045-L1054), and [assembled into a v2 array here](https://github.com/scikit-hep/awkward-1.0/blob/5f5687fde4bd15ba67707c12370b7cc15bcdae43/src/awkward/_v2/operations/convert/ak_from_iter.py#L73-L78)). The fact that we copy from unique pointers now makes this a lot safer than it used to be.
   * v2 arrays build via `from_numpy` (perhaps indirectly through the highlevel `Array` constructor) are definitely allocated and owned by NumPy; there's no C++ involved.
   * v2 arrays are either modified by NumPy (through nplike), which is completely safe, or they're modified by passing them to kernels via ctypes. It could be a problem if the kernel function oversteps the bounds without checking—a bug in the kernel—though that sort of thing should have been caught by v1. However, :shrug:, maybe the bug has always been there but it's only getting triggered now, due to slightly different tests or (more likely) slightly different memory layouts (since it's platform-dependent and doesn't even happen on all MacOS runs). Another way the ctypes call could go wrong is if NumPy deallocates the buffer while the kernel is still running, but I think both Python's argument refcount rules prohibit that (`sys.getrefcount` always returns at least `2`) and we also follow a convention of only passing arguments in a kernel call with `someindex.to(nplike)`, so the `someindex` name stays in scope beyond the lifetime of the kernel call, anyway. (We never construct objects in the argument list. But like I said, I think Python has friendly semantics for that, anyway.)

In v1, there are other ways to get segfaults, but I'm pretty sure the above is a complete list for v2. If you can narrow down which tests cause it, we have a short list of possible causes.

**Comment by ianna** [comment]
@jpivarski - as suggested I put one test in a loop: `test_IndexedArray` from
```
tests/v2/test_0404-array-validity-check.py
```
occasional failures confirm that the array data gets corrupted: an Index of an IndexedOptionArray in this case:
```python
>       assert to_list(indexedarray.unique(axis=-1)) == [
            [6.6, 7.7, 8.8, 9.9],
            [5.5],
            [3.3, 4.4],
            [],
            [0.0, 1.1, 2.2],
        ]
E       assert [None, [6.6, ...3.3, 4.4], []] == [[6.6, 7.7, 8....0, 1.1, 2.2]]
E         At index 0 diff: None != [6.6, 7.7, 8.8, 9.9]
E         Full diff:
E         - [[6.6, 7.7, 8.8, 9.9], [5.5], [3.3, 4.4], [], [0.0, 1.1, 2.2]]
E         ?                                             ---------------- -
E         + [None, [6.6, 7.7, 8.8, 9.9], [5.5], [3.3, 4.4], []]
E         ?  ++++++

tests/v2/test_0404-array-validity-check.py:701: AssertionError
```
Here is a short test that can reproduce it:

```python
    def orig_test_IndexedArray():
        listoffsetarray = ak._v2.operations.convert.from_iter(
            [[0.0, 1.1, 2.2], [], [3.3, 4.4], [5.5], [6.6, 7.7, 8.8, 9.9]], highlevel=False
        )
    
        index = ak._v2.index.Index64(np.array([4, 3, 2, 1, 0], dtype=np.int64))
        indexedarray = ak._v2.contents.IndexedArray(index, listoffsetarray)
        assert to_list(indexedarray) == [
            [6.6, 7.7, 8.8, 9.9],
            [5.5],
            [3.3, 4.4],
            [],
            [0.0, 1.1, 2.2],
        ]
 
>       assert to_list(indexedarray.unique(axis=-1)) == [
            [6.6, 7.7, 8.8, 9.9],
            [5.5],
            [3.3, 4.4],
            [],
            [0.0, 1.1, 2.2],
        ]
E       assert [None, None, None, None, None] == [[6.6, 7.7, 8....0, 1.1, 2.2]]
E         At index 0 diff: None != [6.6, 7.7, 8.8, 9.9]
E         Full diff:
E         - [[6.6, 7.7, 8.8, 9.9], [5.5], [3.3, 4.4], [], [0.0, 1.1, 2.2]]
E         + [None, None, None, None, None]

tests/v2/test_0404-array-validity-check.py:701: AssertionError
```

**Comment by jpivarski** [comment]
This is great—it looks like you've cornered it. Are the wrong values being assigned in a kernel?

(If so, then all platforms and also Awkward 1.x were affected, though we didn't know until now.)

**Comment by ianna** [comment]
fixed in https://github.com/scikit-hep/awkward-1.0/pull/1232

**Comment by henryiii** [comment]
Should be closed, I think.

**Comment by jpivarski** [comment]
You're right!
