### ISSUE TITLE
Adding a `__delitem__``` method to awkward arrays in V2

### ISSUE THREAD

**Issue by MoAly98** [scikit-hep/awkward#1253]
### Description of new feature

Tthis issue is linked to the discussion discussion #1251. I think it would be useful to have a `__delitem__` method for `ak.Array`/`ak.Record`/etc..  objects in v2 to allow a user to remove a field from an awkard array. Ideally with some wrapping function that does the opposite to `with_field` (e.g. `ak.drop_field`) 
For example:
```
array = ak.Array([{"x": 20, "y": [1, 2, 3, 4, 5]}])
array.__delitem__("x") 
array.fields
>>> ["y"]
```

Thanks, 
Mo

**Comment by jpivarski** [comment]
I just noticed that this is the same as #663. It still needs to be done, but here I'm linking the two issues so that they both get closed when it is done.

**Comment by jpivarski** [comment]
I'm deleting the duplicate issue, now that the original (#663) is in a prioritized list.
