### ISSUE TITLE
v2 ListArray, ListOffsetArray, and RegularArray's 'validityerror' must check string conditions

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1336]
### Version of Awkward Array

HEAD

### Description and code to reproduce

When a ListArray, ListOffsetArray, or RegularArray has `parameters={"__array__": "string"}` or `"bytestring"`, then the following other conditions must hold:

  * The `content` must be a NumpyArray.
  * That NumpyArray must have dtype `uint8`.
  * That NumpyArray must have`parameters={"__array__": "char"}` or `"byte"`, depending on the list type's parameter.

In v2, if any list type is a string, it just _skips_ tested testing:

https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/awkward/_v2/contents/listarray.py#L1196-L1226

https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/awkward/_v2/contents/listoffsetarray.py#L1901-L1931

https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/awkward/_v2/contents/regulararray.py#L1004-L1013

I think, in the translation from v1, they lost the equivalent of `validityerror_parameters`, which is a helper function to do ListArray, ListOffsetArray, and RegularArray in a consistent way:

https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/libawkward/array/ListArray.cpp#L903-L938

https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/libawkward/array/ListOffsetArray.cpp#L914-L951

https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/libawkward/array/RegularArray.cpp#L786-L806

That helper function also ensures that non-list-type arrays don't have `"string"` and `"bytestring"` as `__array__`, and it also checks IndexedArray and IndexedOptionArray for a correct use of the `"categorical"` `__array__`.

https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/libawkward/Content.cpp#L1748-L1899

**Comment by agoose77** [comment]
I think we do reimplement the v1 helper, it's just hidden in the base class:
https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/awkward/_v2/contents/content.py#L1030-L1125

On `main`, I can see that both the `NumpyArray` and `char` conditions are checked for a `RegularArray`. I don't test this for any other layouts, but it should all use the same base class impl.

**Comment by jpivarski** [comment]
Aha! Thanks for finding this. Then the thing that's wrong is that it's only applied at top-level:

https://github.com/scikit-hep/awkward-1.0/blob/d977b04facb196a4c8584f256b36280a4e105b14/src/awkward/_v2/contents/content.py#L1127-L1131

The recursive `_validityerror` does not check it. This test would miss invalid strings inside of some list or records. I can do a quick fix.

**Comment by jpivarski** [comment]
Nope: I'm wrong. The recursive functions are named `_validityerror`, but they recurse on `validityerror` (no underscore). This is performing all the checks it's supposed to.

So, no bug—false alarm—sorry!

(It tripped me up because my expectation was that the entry function would have no underscore and the recursive one would have an underscore and recurse on itself, the one with the underscored name. It's a _pattern_ I was expecting and this is different from that pattern. However, that may just be a personal pattern. It's not good to go against design patterns, for exactly the reason that it's quicker to scan code for correctness that way, but those design patterns need to be known to everybody writing the code. I don't know that this one is. If it's breaking an established design pattern, then we should flag it with comments or straighten it out.)

**Comment by agoose77** [comment]
> It tripped me up because my expectation was that the entry function would have no underscore and the recursive one would have an underscore and recurse on itself, the one with the underscored name.

@jpivarski to be fair, I did find the naming convention surprising too: normally the non-underscored name is public (and the entrypoint), but here it is the _underscored_ name is the entry-point.

I.E., I'd be in favour of changing the naming to suit both our expectations ;) I believe that this would involve renaming `validityerror_parameters` to `_validityerror_parameters`
