### ISSUE TITLE
Regular indexing behaves like jagged index for RegularArray (v2)

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1358]
### Version of Awkward Array

c2ddda2f67abf2d7b3112e5752c7c34c3467052d

### Description and code to reproduce

```pycon
>>> array = ak.from_numpy(np.arange(4 * 4).reshape(4, 4))
>>> array[array > 4].ndim
2
>>> (array > 4).layout.purelist_isregular
True
>>> array[ak.to_numpy(array > 4)].ndim
1
```

### Cause

The NumPy-like indexing checks for `NumpyArray`, not `RegularArray`. We should use something like `maybe_toNumpyArray` beforehand to fulfil this.

**Comment by agoose77** [comment]
What should `array[EmptyArray()]` return? Currently it is returning a `NumpyArray` with `int64`. This seems wrong to me, but there is no clear idea of what would be right. Maybe this should be an error?

**Comment by jpivarski** [comment]
```python
array[[]]
```

should interpret the typeless list as though it were an array of integers, and the return value would be an empty array with the same type as `array`.

If the slicer has a type, then we use that: boolean, integers, strings.
