### ISSUE TITLE
`ak.sort` and `ak.argsort` should refuse to sort RecordArrays (raise a TypeError)

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1361]
### Version of Awkward Array

2e8ce817

### Description and code to reproduce

```python
import awkward as ak
import numpy as np
from awkward._v2.tmp_for_testing import v1_to_v2, v2_to_v1

# Check non branching cases
a = ak.layout.NumpyArray(
    np.array([1, 50, 100, 200, 500, 1000])
)

b = ak.layout.ListOffsetArray64(
    ak.layout.Index64(np.array([0, 2, 4, 6])),
    a
)

assert (ak.to_list(a.sort(-1, False, False)) == ak.to_list(
    v2_to_v1(v1_to_v2(a).sort(-1, False, False))))

assert (ak.to_list(b.sort(-1, False, False)) == ak.to_list(
    v2_to_v1(v1_to_v2(b).sort(-1, False, False))))

# Check branching cases
this = ak.layout.RecordArray(
    [a, a[::-1]],
    None
)
assert ak.to_list(this.sort(-1, False, False)) == ak.to_list(
    v2_to_v1(v1_to_v2(this).sort(-1, False, False)))

that = ak.layout.RecordArray(
    [a[:3], b],
    None
)
assert ak.to_list(that.sort(-1, False, False)) == ak.to_list(
    v2_to_v1(v1_to_v2(that).sort(-1, False, False)))

```

**Comment by ioanaif** [comment]
In v2 sorting was a subject of debate for `RecordArrays` and `Records`, the consensus was to remove the sorting facility as we do not have any order defined for records. Thus, sorting across record boundaries would destroy the identities of those records. (see discussion #1451 ) 

As of now, if no fields are present, `sort` will output an empty array. However, do we want to keep sorting if there are no `fields` present and throw a `TypeError` if `fields` is not None? 

@jpivarski 
@ianna 
@agoose77

**Comment by agoose77** [comment]
Thanks @ioanaif! I revisited the discussion that you linked, and [my personal preference has shifted](https://github.com/scikit-hep/awkward/discussions/1451#discussioncomment-3105892) towards fixing the sort to be lexicographic, and extending the API to `ak.sort` and `ak.argsort` so that users don't use the new behaviour silently.

I.e.

```python
ak.sort(
    array,
    axis=-1,
    ascending=True,
    stable=True,
    highlevel=True,
    behavior=None,
    allow_records=False,  # < -- new, temporary, flag
)
```

**Comment by jpivarski** [comment]
Lexicographic is the most reasonable definition for a sort order for records, but I think that defining it will be a big job. I'm thinking of the "removal of record-sorting" as a temporary solution, to make sure that people don't silently get the wrong behavior, or, worse yet, rely on it. That's a necessary prerequisite for coming back and implementing it properly in the future.

Since record fields can also contain lists, we'd need a sort order for lists as well. This project is a rabbit hole.

**Comment by agoose77** [comment]
OK, as it looks like @ioanaif is working on this, I'm not going to push any significant amount of extra work their way! 
I was thinking of defining sorting for primitive fields, but that just makes it fragile with lists.

Let's do the simplest option first, as you say.

**Comment by jpivarski** [comment]
This is an old bug, and it's still around!

```python
>>> import awkward as ak
>>> import numpy as np

>>> a = ak.contents.NumpyArray(
...     np.array([1, 50, 100, 200, 500, 1000])
... )
>>> b = ak.contents.ListOffsetArray(
...     ak.index.Index64(np.array([0, 2, 4, 6])),
...     a
... )

>>> this = ak.contents.RecordArray(
...     [a, a[::-1]],
...     None
... )

>>> ak.Array(this)
<Array [(1, 1000), (50, 500), ..., (...), (1000, 1)] type='6 * (int64, int64)'>

>>> ak.sort(ak.Array(this))
<Array [] type='0 * int64'>
```

The `sort` and `argsort` functions should simply refuse to sort records. When the recursion gets down to the level where it sees a record, it should raise a TypeError.

**Comment by agoose77** [comment]
* Unless we provide an overload mechanism; it is fairly trivial to define a sort ordering in some cases, and we could use that to determine the `IndexedArray` that gets built.
