### ISSUE TITLE
`ak.zip` does not accept generator expressions for `arrays`

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#1363]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

Very simplistic example of a use case for this:
```python
>>> import awkward as ak
>>> array = ak.Array([0])
>>> ak.zip((array + i for i in range(3)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/iris-hep/lib/python3.9/site-packages/awkward/operations/structure.py", line 630, in zip
    to_record = num_scalars == len(arrays)
TypeError: object of type 'generator' has no len()
```

`help(ak.zip)` says that `arrays` should be a "dict or iterable of arrays", which a generator expression that yields arrays is, so I would expect this to work.

**Comment by jpivarski** [comment]
Good point—there's a difference between "iterable" and "sized iterable," and I was always assuming the latter. The fix is in PR #1364.
