### ISSUE TITLE
Strange and inconsistent ordering behavior with `ak.sum`

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#1371]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

I basically expect `ak.sum` with `axis=0` to add all rows together. So behavior like this makes sense:
```python
>>> ak.sum([[[], [1]],
...         [[], [3]]], axis=0)
<Array [[], [4]] type='2 * var * int64'>
```

Just appending one element to each of the non-empty lists in the above example somehow changes ordering in the output:

```python
>>> ak.sum([[[], [1, 2]],
...         [[], [3, 4]]], axis=0)
<Array [[4, 6], []] type='2 * var * int64'>
```

I of course expected to get `[[], [4, 6]]`, so I'm not sure what's going on here.

**Comment by agoose77** [comment]
I can confirm this in both v2 and v1, and I can't find a particular commit that introduces it within `1.5 → HEAD`
