### ISSUE TITLE
awkward.argsort does not return correct types for None lists

### ISSUE THREAD

**Issue by mmarchegiani** [scikit-hep/awkward#1386]
### Version of Awkward Array

1.8.0

### Description and code to reproduce

ak.argsort does not return an index-type in the case that the input list array is full of None values.
```
>>> import awkward as ak
>>> ak.__version__
'1.8.0'
>>> x = ak.Array([[13.2, 14], [67.8]])
>>> x
<Array [[13.2, 14], [67.8]] type='2 * var * float64'>
>>> masked = ak.mask(x, [False, False])
>>> masked
<Array [None, None] type='2 * option[var * float64]'>
>>> ak.argsort(masked)
<Array [None, None] type='2 * option[var * float64]'>
```
Therefore if the resulting array is used for slicing, we get the following ValueError:
```
>>> masked[ak.argsort(masked)]

ValueError: only arrays of integers or booleans may be used as a slice
```
The expected behavior is:
```
>>> ak.argsort(masked)
<Array [None, None] type='2 * option[var * int64]'>
```
so that `ak.argsort(masked)` can be used for slicing.

**Comment by jpivarski** [comment]
> ak.argsort does not return an index-type in the case that the input list array is full of None values.

You're right about that qualifier: it does work if they're not _all_ None:

```python
>>> import awkward as ak
>>> x = ak.Array([[13.2, 14], [67.8]])
>>> masked = ak.mask(x, [True, False])
>>> masked[ak.argsort(masked)]
<Array [[13.2, 14], None] type='2 * option[var * float64]'>
```

Just if every value is None:

```python
>>> masked = ak.mask(x, [False, False])
>>> masked[ak.argsort(masked)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/awkward-1.0/awkward/highlevel.py", line 991, in __getitem__
    tmp = ak._util.wrap(self.layout[where], self._behavior)
ValueError: only arrays of integers or booleans may be used as a slice

(https://github.com/scikit-hep/awkward-1.0/blob/1.8.0/src/libawkward/array/NumpyArray.cpp#L3136)
```

Moreover, this is something that version 2 gets right:

```python
>>> import awkward._v2 as ak
>>> x = ak.Array([[13.2, 14], [67.8]])
>>> masked = ak.mask(x, [True, False])
>>> masked[ak.argsort(masked)]
<Array [[13.2, 14], None] type='2 * option[var * float64]'>
>>> masked = ak.mask(x, [False, False])
>>> masked[ak.argsort(masked)]
<Array [None, None] type='2 * option[var * float64]'>
```

But we're still fixing bugs in version 1, so I'm looking into it now.

**Comment by jpivarski** [comment]
Ah, I missed an important bit of information that you gave me:

> ```python
> >>> ak.argsort(masked)
> <Array [None, None] type='2 * option[var * float64]'>
> ```

Since this is the output of an `argsort`, it should have integer type. I bet the original floating-point type got passed through because something (an array of non-Nones) was empty. We've been cracking down on such "optimizations" in v2 because they can get the types wrong, like this. (In v2, it comes up because it makes Dask predict the wrong type.)

**Comment by agoose77** [comment]
@jpivarski this is linked to the case I mentioned the other day, where we have a fast-path in the return.

**Comment by jpivarski** [comment]
Could you link that here? I don't remember it and I don't want to miss an issue.

Fast-path returns are bad, especially now with the type-tracer.

**Comment by agoose77** [comment]
I can't remember if we ever opened an issue for it, but it looks like you've found it :) https://github.com/scikit-hep/awkward-1.0/blob/80579c7b67d508ea0c916b7b62a7dfe5826fe981/src/libawkward/array/ListOffsetArray.cpp#L1931

**Comment by jpivarski** [comment]
That's that this PR fixes. So if that was causing problems elsewhere, they'll be gone now.
