### ISSUE TITLE
`ListArray._getitem_next_jagged` fails for `slicecontent` where `starts[0] != 0` (v1 & v2)

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1406]
### Version of Awkward Array

1.8.0

### Description and code to reproduce
In particular, where the `slicecontent` is an `IndexedOptionArray` of a `ListOffsetArray`.

This code-path is near identical between v1 and v2, so it's most likely a legacy bug. In short, the indices of the **indexed** array's outermost list (`[1, 3]`) do not start at zero. This is not accounted for in the `ListArray._getitem_next_jagged` implementation. The kernels used do not have any notion of the `ListArray`'s starts or stops, so this is not a kernel bug.

<details>
<summary>Fails</summary>

```python3
array = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([1, 3], dtype=np.int64)),
        ak.layout.ListOffsetArray64(
            ak.layout.Index64(np.array([0, 2, 2, 3], dtype=np.int64)),
            ak.layout.NumpyArray(np.array([0, 1, 2], dtype=np.int64)),
        ),
    ),
    check_valid=True,
)

index = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([0, 2], dtype=np.int64)),
        ak.layout.IndexedOptionArray64(
            ak.layout.Index64(np.array([0, 1], dtype=np.int64)),
            ak.layout.ListOffsetArray64(
                ak.layout.Index64(np.array([0, 0, 1], dtype=np.int64)),
                ak.layout.NumpyArray(np.array([0], dtype=np.int64)),
            ),
        )
    ),
    check_valid=True,
)

array[index]
```

</details>

<details>
<summary>Succeeds (remove option type in index)</summary>

```python3
array = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([1, 3], dtype=np.int64)),
        ak.layout.ListOffsetArray64(
            ak.layout.Index64(np.array([0, 2, 2, 3], dtype=np.int64)),
            ak.layout.NumpyArray(np.array([0, 1, 2], dtype=np.int64)),
        ),
    ),
    check_valid=True,
)

index = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([0, 2], dtype=np.int64)),
        ak.layout.ListOffsetArray64(
            ak.layout.Index64(np.array([0, 0, 1], dtype=np.int64)),
            ak.layout.NumpyArray(np.array([0], dtype=np.int64)),
        ),
    ),
    check_valid=True,
)

array[index]
```

</details>

<details>
<summary>Succeeds (start array offsets at 0)</summary>

```python
array = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([0, 2], dtype=np.int64)),
        ak.layout.ListOffsetArray64(
            ak.layout.Index64(np.array([2, 2, 3], dtype=np.int64)),
            ak.layout.NumpyArray(np.array([0, 1, 2], dtype=np.int64)),
        ),
    ),
    check_valid=True,
)

index = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([0, 2], dtype=np.int64)),
        ak.layout.IndexedOptionArray64(
            ak.layout.Index64(np.array([0, 1], dtype=np.int64)),
            ak.layout.ListOffsetArray64(
                ak.layout.Index64(np.array([0, 0, 1], dtype=np.int64)),
                ak.layout.NumpyArray(np.array([0], dtype=np.int64)),
            ),
        )
    ),
    check_valid=True,
)

array[index]
```

</details>

<details>
<summary>Succeeds (replace empty lists with non-empty)</summary>

```python3
array = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([1, 3], dtype=np.int64)),
        ak.layout.ListOffsetArray64(
            ak.layout.Index64(np.array([0, 1, 2, 3], dtype=np.int64)),
            ak.layout.NumpyArray(np.array([0, 1, 2], dtype=np.int64)),
        ),
    ),
    check_valid=True,
)

index = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([0, 2], dtype=np.int64)),
        ak.layout.IndexedOptionArray64(
            ak.layout.Index64(np.array([0, 1], dtype=np.int64)),
            ak.layout.ListOffsetArray64(
                ak.layout.Index64(np.array([0, 1, 2], dtype=np.int64)),
                ak.layout.NumpyArray(np.array([0, 0], dtype=np.int64)),
            ),
        )
    ),
    check_valid=True,
)

array[index]
```

</details>

**Comment by agoose77** [comment]
This also fails in v2. The path that I took to determine this is a bit circular, but I'm confident that the fix/bug is the same for v1 and v2, as it seems to occur in code that is mostly 1:1.

It looks like the issue is probably rooted somewhere in `awkward_ListArray_getitem_jagged_shrink`, which prepares `nextcarry`, or ``awkward_ListArray_getitem_jagged_numvalid`` which prepares the inputs for this kernel. 

This test case undergoes the wrong carry in `ListArray`:

```python3
array = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([1, 3], dtype=np.int64)),
        ak.layout.ListOffsetArray64(
            ak.layout.Index64(np.array([0, 2, 2, 3], dtype=np.int64)),
            ak.layout.NumpyArray(np.array([2, 2, 2], dtype=np.int64)),
        ),
    ),
    check_valid=True,
)

array_good = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([0, 2], dtype=np.int64)),
        ak.layout.ListOffsetArray64(
            ak.layout.Index64(np.array([0, 0, 1, 3], dtype=np.int64)),
            ak.layout.NumpyArray(np.array([2, 2, 2], dtype=np.int64)),
        ),
    ),
    check_valid=True,
)

index = ak.Array(
    ak.layout.ListOffsetArray64(
        ak.layout.Index64(np.array([0, 2], dtype=np.int64)),
        ak.layout.IndexedOptionArray64(
            ak.layout.Index64(np.array([0, 1], dtype=np.int64)),
            ak.layout.ListOffsetArray64(
                ak.layout.Index64(np.array([0, 0, 1], dtype=np.int64)),
                ak.layout.NumpyArray(np.array([0], dtype=np.int64)),
            ),
        )
    ),
    check_valid=True,
)

def as_v2(array):
    layout = ak.to_layout(array)
    layout_v2 = ak._v2.tmp_for_testing.v1_to_v2(layout)
    return ak._v2.Array(layout_v2)

print(array_good, index)
as_v2(array_good)[as_v2(index)]
print("-"*64)
print(array, index)
as_v2(array)[as_v2(index)]
```

**Comment by agoose77** [comment]
Upon further digging, I think it's `awkward_ListArray_getitem_jagged_shrink`. This builds `nextcarry` that is used to slice the `ListArray` content. As such, we know that `nextcarry` needs to account for the sliced content's `starts` and `stops`. The `awkward_ListArray_getitem_jagged_shrink` kernel doesn't accept any arguments that (in)directly refer to `stops` or `starts`. It only looks at the slice indices. Hence, we see an Exception when slicing a `ListArray` with a non-zero start.

More concretely, in the above reproducer, at some point we end up in `ListArray._getitem_next_jagged(self, ...)`, where `self` is the `array` that is being sliced (converted from a `ListOffsetArray`):
```
<ListArray len='1'>
    <starts><Index dtype='int64' len='1'>[1]</Index></starts>
    <stops><Index dtype='int64' len='1'>[3]</Index></stops>
    <content><ListOffsetArray len='3'>
        <offsets><Index dtype='int64' len='4'>[0 2 2 3]</Index></offsets>
        <content><NumpyArray dtype='int64' len='3'>[2 2 2]</NumpyArray></content>
    </ListOffsetArray></content>
</ListArray>
```

Our `slicestarts` and `slicestops` are 
```
<Index dtype='int64' len='1'>[0]</Index>
<Index dtype='int64' len='1'>[2]</Index>
```

The `missing` array is actually the wrapped `IndexedOptionArray` index, so it indicates where the `None` values (sublists, in this case) are. Using this, the `awkward_ListArray_getitem_jagged_numvalid` kernel determines that we have `2` valid values between `slicestarts` and `slicestops`.

Now we move onto `awkward_ListArray_getitem_jagged_shrink`, which builds the `carry` index for the `ListArray's` contents. Approximately, this just places `range(slicestarts, slicestops)` into the `nextcarry` array.

Just like with https://github.com/scikit-hep/awkward-1.0/issues/910, I believe the problem is that we're then applying this `carry` that indexes into the slicer's `IndexedOptionArray` to the sliced-array's content (which is unrelated):
https://github.com/scikit-hep/awkward-1.0/blob/edfce3800ccd1f8b90734cf9594c3b5c117441ff/src/awkward/_v2/contents/listarray.py#L452-L476

**Comment by jpivarski** [comment]
@agoose77, you and other core developers can call any bug you find "verified".
