### ISSUE TITLE
Awkward tutorials site says that Uproot 4 does not write jagged arrays to ROOT files yet

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1424]
### Which documentation?

Tutorials site

### What needs to be documented?

https://awkward-array.org/how-to-convert-uproot.html#from-awkward-to-root-with-uproot-4

is wrong: Uproot 4 does support writing Awkward Arrays (only certain types, but that would always be true). It needs to be updated because it's giving people the wrong impression.

**Comment by jpivarski** [comment]
@agoose77 I was prioritizing your issue when I came across this. Point you to it because you're doing the documentation, though I think if you came across a comment about Uproot 4 not being able to write TTrees, you'd see that it's out of date. (Actually, any mention of Uproot 3 can now be purged...)

**Comment by jpivarski** [comment]
The documentation doesn't even mention Uproot anymore. There should at least be a pointer to the Uproot documentation site for users interested in ROOT files.

At least it's no longer wrong.

**Comment by agoose77** [comment]
We technically link to reading via uproot in the toctree:
https://uproot.readthedocs.io/en/latest/basic.html#reading-a-tbranch-as-an-array

![image](https://user-images.githubusercontent.com/1248413/199107870-a5a4eafd-ab9a-48e4-8ad6-7d2546ca6176.png)

We might want to do more here, but this was a stop-gap in the meantime

**Comment by jpivarski** [comment]
I wonder why I didn't find it with a search.
