### ISSUE TITLE
Improve potentially misleading array repr cut-off for multi-dimensional arrays

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/awkward#1441]
### Description of new feature

When an array contains such content that the point where the cutoff happens in the repr aligns with the end of a level of "indentation", the corresponding bracket does not appear and a comma appears in its place. This can make the array appear to have a different shape than it does:
```python
$ ipython
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:24:38)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import awkward as ak

In [2]: ak.from_iter([[0.08, -0.08], [0.01882, -0.01882]])
Out[2]: <Array [[0.08, -0.08], [0.0188, -0.0188]] type='2 * var * float64'>

In [3]: ak.from_iter([[0.0808, -0.0808], [0.01882, -0.01882]])
Out[3]: <Array [[0.0808, -0.0808, ... 0.0188, -0.0188]] type='2 * var * float64'>
```

Everything looks normal in the first example. In the second example, the bracket after `-0.0808` is replaced by a comma. The comma then to me look as if there were additional values following at the same level of indentation.

I ran into this while looking at how an array changed after dividing it by some number. The repr made it seem like the shape had changed during the division. Certainly an edge case though!

I am unsure whether much can be done here in general. One idea I had was to allow the repr to be longer such that all brackets that would appear next do not get cut off: ensuring that the cut-off doesn't happen when indentation levels change, but only when the next object at a given level of indentation would appear.

In my case at least, looking at arrays frequently happens in the context of reshaping operations, as a way to ensure the shape comes out correctly. This edge case might cause confusion in these scenarios. Related: https://github.com/scikit-hep/awkward-1.0/issues/1281, configurable print options can also solve this.

**Comment by jpivarski** [comment]
This was already done in v2: https://github.com/scikit-hep/awkward-1.0/issues/838#issuecomment-949042273

It's a completely different algorithm that has the property of always closing any open brackets, with the trade-off that there may be many "`...`" instead of just one.

This kind of major change is appropriate for a 1 → 2 version boundary, and if it's better, at least it will be a draw to use the new system. (Which is [available now](https://github.com/scikit-hep/awkward-1.0/wiki#current-status), by the way.)

```python
from awkward._v2.tmp_for_testing import v1_to_v2, v2_to_v1

v2array = ak._v2.Array(v1_to_v2(v1array.layout))
# use ak._v2.* functions on v2array

v1array = ak.Array(v2_to_v1(v2array.layout))
# ak.* functions on v1array
```

If the v2 repr is sufficient, I think we can close this issue.

**Comment by alexander-held** [comment]
The repr in the link looks great, I think this perfectly addresses what I had in mind. Thank you!

**Comment by jpivarski** [comment]
Great!
