### ISSUE TITLE
Error when using ak.copy in v2

### ISSUE THREAD

**Issue by philippemiron** [scikit-hep/awkward#1482]
### Version of Awkward Array

1.9.0rc4

### Description and code to reproduce

```
import awkward._v2 as ak

array = ak.Array([
    [{"x": 1.1, "y": [1]}, {"x": 2.2, "y": [1, 2]}, {"x": 3.3, "y": [1, 2, 3]}],
    [],
    [{"x": 4.4, "y": [1, 2, 3, 4]}, {"x": 5.5, "y": [1, 2, 3, 4, 5]}]
])

ak.copy(array)
```

Expect a copy of the array, but I get this:

```
File ~/miniconda3/envs/research/lib/python3.9/site-packages/awkward/_v2/operations/ak_copy.py:57, in copy(array)
     10 """
     11 Returns a deep copy of the array (no memory shared with original).
     12 
   (...)
     51 a mutable third-party library, so this function allows you to make a true copy.
     52 """
     53 with ak._v2._util.OperationErrorContext(
     54     "ak._v2.fill_none",
     55     dict(array=array),
     56 ):
---> 57     return _impl(array)
...
...
...
TypeError: cannot pickle 'module' object
```

**Comment by agoose77** [comment]
I took a quick look at this and I suspect that it's the `_module` object of the `nplike` associated with the various contents.

Having only just glanced over the code, I think we might want to replace the existing `deep_copy` method with a `__deepcopy__` implementation which ensures that nested layouts are also handled to avoid trying to pickle the module.

In the mean-time, if you really need a deep copy, you *could* use `ak.to_buffers` with `copy.deepcopy`, e.g.

```python
import copy

array_copy = ak.from_buffers(
    *copy.deepcopy(
        ak.to_buffers(array)
    )
)
```

Though in practice, there are not usually that many instances where one actually wants a deep copy given that Awkward Arrays are partially immutable.

**Comment by jpivarski** [comment]
That's sounding right. I had intended to look into this, but you beat me to it!

Now that I think of it, all of our arrays have a link to the `nplike` singleton, and the one corresponding to NumPy holds a reference to the actual `numpy` module. We don't want to copy that! So yes, we'll need a custom `__deepcopy__` (and probably also `__copy__`), and its implementation can be our `deep_copy`. It could possibly be renamed, as long as everything that's currently calling `deep_copy` goes and calls `__deepcopy__` instead.

**Comment by philippemiron** [comment]
> I took a quick look at this and I suspect that it's the `_module` object of the `nplike` associated with the various contents.
> 
> Having only just glanced over the code, I think we might want to replace the existing `deep_copy` method with a `__deepcopy__` implementation which ensures that nested layouts are also handled to avoid trying to pickle the module.
> 
> In the mean-time, if you really need a deep copy, you _could_ use `ak.to_buffers` with `copy.deepcopy`, e.g.
> 
> ```python
> import copy
> 
> array_copy = ak.from_buffers(
>     *copy.deepcopy(
>         ak.to_buffers(array)
>     )
> )
> ```
> 
> Though in practice, there are not usually that many instances where one actually wants a deep copy given that Awkward Arrays are partially immutable.

I was actually creating a copy to return a subset version of the array and keep a copy of the original, but just realized that it was not needed. Thanks for the advice.

**Comment by jpivarski** [comment]
(We should fix it anyway, thanks!)

What you need might be `ak.packed`. Ordinarily, when you slice something, it doesn't actually make a copy, so the original is still entirely in memory. Packing ensures that only the parts you can see in the array you have are linked, so that a subset actually uses less memory.
