### ISSUE TITLE
User-supplied behaviors shouldn't replace ak.behavior; they should be merged with it.

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#149]
In this sense:

```python
behavior = dict(ak.behavior)
behavior.update(user_supplied)
```

Although that might be a lot of dict-copying every time an `ak.Array` gets constructed...

**Comment by henryiii** [comment]
I think it's a shallow copy (could be made explicit with copy.copy(ak.behavior), and you could skip this step if `user_supplied` is None (assuming you are then okay with changing ak.behavior also changing here - otherwise you always need a copy).

**Comment by jpivarski** [comment]
This Mapping applies overrides if they exist and defaults if they don't, without a shallow copy every time. (It happens quite frequently, before every `ak.Array` constructor, and the number of behavioral overrides may be large.)

Also, it enforces the equivalence between missing keys and `None` values, so that an application can't accidentally rely on the distinction. Thus, it is always possible for overrides to explicitly opt out of certain defaults, by overriding them with `None`.

https://github.com/scikit-hep/awkward-1.0/blob/5a16540bf171814a2f405e66bc0d8359a32f80ce/src/awkward1/_util.py#L34-L63

The `items` method is explicitly implemented because it is used a lot—much more than `__iter__`.

Also note that this is not public API (it's in `awkward1._util`).
