### ISSUE TITLE
`ak._v2` missing `size`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1553]
### Version of Awkward Array

HEAD

### Description and code to reproduce

v1 implements `ak.size` but we have not ported it over to v2.

**Comment by jpivarski** [comment]
That was intentional. Let me get back to this.

**Comment by jpivarski** [comment]
Actually, `np.size` isn't even part of the NumPy API. NumPy arrays have a [size property](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html), but this would be meaningless for an Awkward Array. The v1 `ak.size` was to satisfy Pandas, a feature we gave up on in #350.

So this function _should not_ be reimplemented in v2. We're taking advantage of the chance to change the API with a major release boundary.

See also discussion on https://gitter.im/Scikit-HEP/awkward-array at around this date: 2022-07-19 at 10:14am CDT.

**Comment by agoose77** [comment]
Wait, you're right! :facepalm:. I'm pretty sure I've made this exact assumption before. Apologies for the noise everyone
