### ISSUE TITLE
Get `pip install -e .` working and deprecate localbuild.py

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1599]
Although it has been convenient to incrementally build Awkward Array's C++ part, there won't be much C++ code left after the 2.0 release, and most of the actual development (in which you need quick turn-around times) is in Python now.

Once `pip install -e .` works (probably easier after the v1 code is removed), we should remove localbuild.py. This includes documentation and CONTRIBUTING.md.

It's already a liability: it doesn't work on Windows (#1471) and although that's probably an easy fix, it can only easily be fixed by a developer on Windows who is familiar with how localbuild.py works. This error went uncaught for a long time because we don't test localbuild.py in CI. (In CI, we build the module _properly_, using `pip install .`.)

So localbuild.py's days are numbered. When it's gone, we can remove this issue, and I'm going to remove #1471 now as a wont-fix.

**Comment by agoose77** [comment]
I'd like to move to a non-setuptools backend at some point too. It might be that we can move to a new scikit-build by then, or just write a simple plugin for another build backend e.g. hatch. But, depending upon timing, we might need to do this in two separate phases.

**Comment by jpivarski** [comment]
I _think_ hatchling is just for pure Python projects. But scikit-build definitely. I should probably write that up as an upcoming project, since it's one that @henryiii has in mind (Awkward is a part of his broad scikit-build project).

**Comment by agoose77** [comment]
I've used hatchling a fair bit, and the idea would be that we'd use a build-plugin for the compiled part. This would just invoke cmake as we do in setuptools. The benefit really is just fewer LoC, better build-backend integration, and using forward looking backends, but right now we'd be writing that build plugin ourselves (even if it's probably quite straightforward).

Yes, I recall hearing that, and I don't want to step on any toes (or take on another project just yet).

**Comment by henryiii** [comment]
We are planning to write an extensions PEP & add support to the extensionlib library, probably around end of the year or next. Awkward will need this form when Rust is added.

**Comment by jpivarski** [comment]
We're not 100% sure that Rust is going to be needed. A lot of the string functions that we need are also in pyarrow, which we need for other reasons. (@martindurant)

**Comment by martindurant** [comment]
Correct, I was no longer pursuing rust for uft8 handling given the set of vectorised ops available via [pyarrow._compute](https://arrow.apache.org/docs/cpp/compute.html?highlight=utf8#string-predicates).
