### ISSUE TITLE
Drop support for Python 3.6 and split git into `main` and `main-v1`

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1626]
Timeline:

   * [x] Make a final rc release of 1.9.0rcX with support for Python 3.6.
   * [x] Release 1.9.0.
   * [x] Drop Python 3.6 using #1661.
   * [x] Release 1.10.0 _without_ support for Python 3.6, maybe with an rc1 release just to make sure it's going to work.
   * [x] Split git into `main` (v2 series) and `main-v1` (v1 backports).
   * [x] Set VERSION_INFO to "2.0.0rc1" in `main`.
   * [x] Start dismantling v1 from `main`.

I'm hoping that `main-v1`/1.10.x won't need much maintenance. The existence of a git branch is just to make that less painful than it would otherwise be. Note that 1.10.x will always support Pythons 3.7 through 3.11 (only!) because that's what's set up in the `main-v1` CI. Hopefully, we won't have to make bug-fixes at a time in the future when Python 3.7 is hard to deploy.

**Note:** I edited the above to reflect the modifications @henryiii suggested.

**Comment by jpivarski** [comment]
@henryiii's suggestion: 1.9.0 with Python 3.6 and then 1.10.x as the bug-fix series for v1.

And then not need to keep any rc releases.

**Comment by agoose77** [comment]
I think we're done here!
