### ISSUE TITLE
The getitem system needs to be annotated with expected types

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1655]
### Which documentation?

Other (please explain)?

### What needs to be documented?

This could be comments or actual type-annotations, but since the types of the arguments of Content methods with "getitem" in their names are fixed (having been ported over from C++), they should be expressed in the codebase. @agoose77 spent a lot of time wandering in that dungeon, and it needs a map.

The conversation in #1597 is primarily about pre-processing the slice types that are going to be passed around the getitem system. They are normalized to a specific set of types, listed in https://github.com/scikit-hep/awkward/pull/1597#issuecomment-1227754769 and duplicated here:

   * `int` (really a Python `int`, not a NumPy scalar or anything) for integer-slicing
   * `slice` for range-slicing
   * `str` for single field-slicing
   * `list` for multiple field-slicing; if we ever see a bare Python `list` after normalization, we _assume_ it's a list of strings
   * `np.newaxis`/`None` for newaxis-slicing
   * `Ellipsis` for ellipsis-slicing
   * `Index64` (not any other integer-width) for rectilinear array-slicing: so not an actual NumPy array (or CuPy, etc.); note that a single integer gets broadcasted to this when used in the same slice as a rectilinear array
   * `ListOffsetArray` (and not `ListArray`) for ragged array-slicing
   * `IndexedOptionArray` (and not any other option-type) for missing value-slicing

though this happens in a round-about way. The `prepare_advanced_indexing` function is the last step that puts them into this final form.

Then all the Content methods listed in https://github.com/scikit-hep/awkward/pull/1408#issuecomment-1232286520 (not duplicated here; it's very long) have known argument types; they just haven't been listed. Having them written in some form would greatly help the next developer.

Also in that long list, there are a few items labeled "!?!" that seem to be wrong: they're not in agreement with the normalized types in the bullet-points above. Presumably, this means that there aren't any tests for them, so the first step would be to design some tests that would cover them.

**Comment by agoose77** [comment]
This is pretty much done at this point. I think we can close the issue.
