### ISSUE TITLE
Assigning array to nested record doesn't change value

### ISSUE THREAD

**Issue by grst** [scikit-hep/awkward#1662]
### Version of Awkward Array

main@c751d4eb

### Description and code to reproduce

When I assign an array to a nested record (`a["a"]["a2"] = np.array(...)`) nothing happens. 
I'd expect this to either actually change the value or raise an Error. 

```python
>>> import awkward._v2 as ak
>>> a = ak.Array(
        [
            {
                "a": {
                    "a2": [1, 2, 3],
                },
                "b": [2, 3, 4],
            }
        ]
    )
>>> ak.to_json(a)
'[{"a":{"a2":[1,2,3]},"b":[2,3,4]}]'

# Let's assign a different array to `a2`
>>> a["a"]["a2"] = np.array([42, 42, 42])]
# What does the array look like now? Oh, it's still the same...
>>> ak.to_json(a)
'[{"a":{"a2":[1,2,3]},"b":[2,3,4]}]'
```

CC @ivirshup

**Comment by agoose77** [comment]
This is a subtle mutability problem. Arrays _are_ mutable, but their layouts are not.

When you assign `array['field']`, only the top-level `ak.Array` is actually modified, by replacing its inner `layout` with another one.
```python
x = ak.Array(
        [
            {
                "a": {
                    "a2": [1, 2, 3],
                },
                "b": [2, 3, 4],
            }
        ]
    )
# Perform shallow copy
y = ak.Array(x) 
assert x.layout is y.layout


# Update array with new layout through `__setitem__`
x['b'] = [[5,1,2]]
assert x.layout is not y.layout

print(x.b, y.b)
```

When you perform `x['a']['a2']`, you're actually evaluating two separate array slices:
1. `tmp = x['a']`
2. `tmp['a2']`

So, in an assignment, only the temporary array is modified (and then discarded). You can use `x['a', 'a2'] = ...` to replace the layout in the top-level Array (as you're slicing only a single array).

**Comment by grst** [comment]
I see, thanks!

**Comment by jpivarski** [comment]
It is subtle, and I wish this misleading case didn't exist, but it follows as an unintended consequence from `__getitem__` and the way Python syntax works (can't pass variables as with `&` in C).

**Comment by agoose77** [comment]
@jpivarski I did think about suggesting we prevent `__setitem__` altogether in favour of `ak.with_field` but I think that might be fairly impossible in the near term.
