### ISSUE TITLE
Type-unification of "string" and "option[unknown]" should return "option[string]", not a union.

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1669]
Just trying this out now, and running into an issue. I can get the expected result from:

```python
awk_a = ak.Array([
    {"a": [1, 2, 3], "b": [1, 2]},
    {"a": [4, 5], "b": [3, 4]},
    {"a": [6], "b": [5]},
])


awk_b = ak.Array([
    {"a": [1, 2, 3]},
    {"a": [4, 5]},
    {"a": [6]},
])

ak.concatenate([awk_a, ak.with_field(awk_b, None, "b")]).type.show()
```

```
6 * {
    a: var * int64,
    b: option[var * int64]
}
```

However, I get a `union` from:

```python
awk_c = ak.Array([
    [{"a": 1, "b": "foo"}],
    [{"a": 2, "b": "bar"}, {"a": 3, "b": "baz"}]
])

awk_d = ak.Array([
    [{"a": 4}, {"a": 5}],
    [{"a": 6}],
    [{"a": 7}],
])

ak.concatenate([awk_c, ak.with_field(awk_d, None, "b")]).type.show()
```

```
5 * union[
    var * {
        a: int64,
        b: string
    },
    var * {
        a: int64,
        b: ?unknown
    }
]
```

Is this expected?

_Originally posted by @ivirshup in https://github.com/scikit-hep/awkward/discussions/1647#discussioncomment-3561037_

I think you found a bug: we want "string" and "option[unknown]" to unify to "option[string]", and it's not recognizing that. It should first notice that one of the two is "option" and make the result type "option", then unify "string" (or "X") with "unknown" to get "string" ("X"), since "unknown" is an identity in type-unification. I _think_ this is supposed to happen somewhere in [simplify_uniontype](https://github.com/scikit-hep/awkward/blob/1bcfd70629aec4c1ef26bbf929d9183c28dbe491/src/awkward/_v2/contents/unionarray.py#L471-L661). It's interesting that it got it right when "X" is a primitive type, int64, but not when it's a list type. This is something we should promote into an issue.

**Comment by agoose77** [comment]
I think this is caused by the check to `_parameters_equal`, which fails whenever a string is encountered:
```python
import awkward._v2 as ak

awk_c = ak.Array([
    {"a": 1, "b": "foo"},
    {"a": 2, "b": "bar"},
    {"a": 3, "b": "baz"}
])

awk_d = ak.Array([
    {"a": 4},
    {"a": 5},
    {"a": 6},
])

ak.concatenate([awk_c, ak.with_field(awk_d, None, "b")]).type.show()
```

**Comment by jpivarski** [comment]
That makes sense. (So it doesn't happen if you have raw lists, rather than strings?) Differing parameters means that the types can't be unified: `T1 | T2 != T1` or `T2`, but the "unknown type is the identity of `|`" should be a rule that overrides all: `T1 | U = T1` and `U | T1 = T1`.

If (for some weird reason), the unknown type has any parameters, I think they should still be merged, but the known type's parameters should take precedence.

------

By the way, I completely made up this `|` operator to mean "unify types." Some examples: `int | float = float`, `list(int) | list(float) = list(float)`, `int | string = int | string` (i.e. it can't be simplified).

**Comment by agoose77** [comment]
Yes, I think this is a good rule:
- EmptyArray behaves as the identity:
   - Parameters do not need to be equal, and non-`EmptyArray` type takes precedence
