### ISSUE TITLE
`RegularArray._mergeable` / `RegularArray.mergemany` (and `NumpyArray`) promote `NumpyArray`s twice

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1678]
### Version of Awkward Array

main

### Description and code to reproduce

#1671 fixes merging of `NumpyArray` and `RegularArray`, but does so by promoting `NumpyArray`s to `RegularArray` twice; once in `_mergeable,` and another time in `mergemany`. This is something we should avoid. 

Perhaps the merge implementation can replace `mergeable(self, other: Content) -> bool` with `as_mergeable(self, other: Content) -> tuple[Content, Content] | None` that allows the layout to return the type that it would be converted to if it were to be merged.

**Comment by jpivarski** [comment]
I'm going to drop this one: it's a performance consideration in metadata manipulation, and not big metadata like RecordArrays, either. The first conversion from `NumpyArray` to nested `RegularArrays` can be (a little bit) costly if the original array was not C-contiguous, but any subsequent conversions only shift values between `inner_shape` and `RegularArray` objects.

**Comment by agoose77** [comment]
Originally the concern was that it was performing 2x data copies. But, I think there's now a helper that produces a bogus array whose contents aren't allocated. As such, unless that collapses (is allocated), it's not an issue iirc.
