### ISSUE TITLE
Categoricals are not correctly represented in datashape string

### ISSUE THREAD

**Issue by ivirshup** [scikit-hep/awkward#1680]
### Version of Awkward Array

1.10.0.rc1

### Description and code to reproduce

Categorical values are not shown to be categorial in the datashape type string.

```python
import awkward._v2 as ak

a = ak.Array(["foo", "foo", "bar"])
a_cat = ak.behaviors.categorical.to_categorical(a)

assert a.typestr == a_cat.typestr
a_cat.typestr  # '3 * string'
```

According to a comment form @jpivarski (https://github.com/scverse/anndata/pull/647#discussion_r963133794), the data shape representation should show these values are categorical:

> Categorical strings have a different type than non-categorical strings. We're just following Datashape, in which [categorical](https://datashape.readthedocs.io/en/latest/types.html#categorical) is represented by a different type string, so we're calling it distinct.

**Comment by jpivarski** [comment]
You're right! But this was _just_ fixed yesterday, in PR #1671. (See fca3e66f5f10d3279f90e5d334aa3a48221c1971.)

@agoose77 and I (@agoose77 especially) have been focusing on issues surrounding type representations, broadcasting strings, and categoricals, triggered by your use-cases but including anything that we find along the way.
