### ISSUE TITLE
Rename the `is_XXXType` flags in `Content` et al.

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1681]
### Version of Awkward Array

main

### Description and code to reproduce

Right now, these create confusion (as evidenced in https://github.com/scikit-hep/awkward/discussions/1654#discussioncomment-3527347), and we could choose a better name. `is_list_like` might be a better variant of `is_ListType`.

**Comment by agoose77** [comment]
@jpivarski I'm thinking `is_list`, `is_option` here?

**Comment by jpivarski** [comment]
Sure. Actually, if you have opinions about what these words should be, I'll assign it to you.

You can send it back to me if you want. (This is not a big effort; what matters is that they get changed to something better, for some definition of better.)
