### ISSUE TITLE
`ak.packed` casts categorical to value type

### ISSUE THREAD

**Issue by ivirshup** [scikit-hep/awkward#1688]
### Version of Awkward Array

1.10.0.rc2

### Description and code to reproduce

`ak.packed` seems to get rid of categoricals

```python
import awkward._v2 as ak

a = ak.Array(["foo", "foo", "bar"])
a_cat = ak.to_categorical(a)

assert a_cat.typestr == ak.packed(a_cat).typestr, f"'{a_cat.typestr}' != '{ak.packed(a_cat).typestr}'"
```

```pytb
      3 a = ak.Array(["foo", "foo", "bar"])
      4 a_cat = ak.to_categorical(a)
----> 6 assert a_cat.typestr == ak.packed(a_cat).typestr, f"'{a_cat.typestr}' != '{ak.packed(a_cat).typestr}'"

AssertionError: '3 * categorical[type=string]' != '3 * string'
```

This makes sense in that the indexed array is projected, but I did not expect `ak.packed` to change the type of an array.

The docstring also says this:

> Returns an array with the same type and values as the input, but with packed inner structures

**Comment by agoose77** [comment]
I suspect this is a manifestation of #1685

**Comment by agoose77** [comment]
No, actually this is just that projecting out categoricals is not the correct behaviour

**Comment by jpivarski** [comment]
Yeah, this

https://github.com/scikit-hep/awkward/blob/31f3afb6bd31949bb2014d3be4b86194a63a573c/src/awkward/_v2/contents/indexedarray.py#L1246-L1247

should only project itself if _not_ categorical. Otherwise, it should pass on the recursive packing to its `content`, but not change itself.

```python
    def packed(self): 
        if self.parameter("__array__") == "categorical":
            return self.copy(content=content.packed())
        else:
            return self.project().packed() 
```

**Comment by jpivarski** [comment]
Actually, @agoose77 just pointed out in Slack that we should also remove unreachable items from `content`, which is the purpose of `packed`. I stand corrected: it's more complicated than my suggested fix.

**Comment by ivirshup** [comment]
Would unreachable items include categories that are no longer present, or just values from the integer array that aren't referenced?

**Comment by agoose77** [comment]
Yes; the simplest fix is just to pack the _content_ of the categorical indexed array, but if we want to do this properly, we should produce a new indexed type which only includes the items that are referenced in `index`. That corresponds to keeping only the categories that are referred to by at least one index.

**Comment by ivirshup** [comment]
> we should produce a new indexed type which only includes the items that are referenced in index. That corresponds to keeping only the categories that are referred to by at least one index.

I would argue against this.

I think the set of categories shouldn't be modified by this function. I may only have a subset of the categories present in one instance, but would want to combine it with another instance that has the full set. If I know my set of categories ahead of time, I would like to just have all my arrays refer to them so I don't have to re-map the codes. This could also cause the codes to lose meaning if their order was important.

I think this is why some categorical array implementations model the categories as being part of the type, e.g. pandas [`CategoricalDtype`](https://pandas.pydata.org/docs/user_guide/categorical.html#categoricaldtype).

**Comment by jpivarski** [comment]
In that case, the simple implementation in https://github.com/scikit-hep/awkward/issues/1688#issuecomment-1240737263 is all we need.

**Comment by agoose77** [comment]
I can see the merit in what you're saying. In-fact I had discounted this because I didn't think we exposed the array's catgories to the user. However, we _do_ expose them with `ak.categories`, so I'm now agreed that we want a simple categories-only packing.
