### ISSUE TITLE
`RegularArray.zeros_length` should be part of its form? (no!)

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1696]
### Version of Awkward Array

[8a338cb](https://github.com/scikit-hep/awkward/commit/8a338cbefba831a45671c8b28a3ee44b2b2af885)

### Description and code to reproduce

In exploring #1695, I noticed that `RegularArray` doesn't round-trip through `ak._v2.from_buffers(*ak._v2.to_buffers(array))`if its length is set by `zeros_length`. It seems to me that we want the `zeros_length` of this layout node to be a part of its form. Unlike the other list-types, which do not need this parameter (as they do not use the content's length to determine their own length), we need this information to be able to faithfully reconstruct a `RegularArray`.

There are some ramifications of this; we need to be particularly careful about when to set `zeros_length=self._zeros_length` (for form-idempotent operations like `array.copy()`), and when to set `zeros_length=new_length` (where we want to ensure that e.g. a slice operation has the right length). On the one hand, this feels like a footgun - now we have *another* parameter to worry about setting incorrectly. However, if we agree that this bug (#1696) is a problem, then we either must store `zeros_length` or `length`. The latter isn't appropriate for the form, which should be agnostic with respect to the contents of the buffers that accompany it. Making concrete length information part of the form leads to a dependency of the form on the particular buffer lengths.

Are there any serious ramifications to adding `zeros_length` as part of the `RegularArray` form?

**Comment by agoose77** [comment]
Not sure what I was testing, but this actually does work! :fireworks: It would only be an issue at the outermost dimension, and we return the lengths from `to_buffers` for this.

**Comment by jpivarski** [comment]
You're right: `zeros_length` should _not_ be part of RegularForm because Forms don't encode lengths.

The round trip should work, though it depends on outside-of-Form information, the `length` parameter passed to `from_buffers`. The length of an embedded RegularArray might be computed from the original `length` that the user passes (not identical to it), but it's ultimately derived from that `length`.

**Comment by agoose77** [comment]
Yes, everything currently works as expected. This was probably me forgetting about the top-level `length` item that `to_buffers` returns; required to avoid this issue.
