### ISSUE TITLE
Add CI workflow to test third party packages against master

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1702]
### Version of Awkward Array

main

### Description and code to reproduce

boost-histogram clones hist's master, and checks that it works against boost-histogram. We could do this to ensure that we don't break people e.g. `anndata` (if they have a test suite).

- vector 
- anndata

@henryiii mentioned `mypy_primer` as the inspiration for this.

If we pin, then we can treat these as workflow tests (non-required).

**Comment by jpivarski** [comment]
I think this evolved into https://github.com/CoffeaTeam/integration-test.
