### ISSUE TITLE
Add a thin `awkward._v2` → `awkward` alias

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1729]
### Description of new feature

For months, early adopters of v2 have been accessing it by

```python
import awkward._v2 as ak
```

and now it has been merged into the main module with #1721, so

```python
import awkward as ak
```

References to `awkward._v2` will now break, including those in Uproot, and it can be tricky to try to coordinate releases. Although the non-existence of `awkward._v2` is a good test of being 2.0.0 release-ready, coordinating breaking changes across packages is annoying.

It should be possible to add a submodule named `awkward._v2` that contains 100% of the symbols in the `awkward` module (object graphs are not trees), and doing so would provide backward compatibility for early adopters. In principle, it could stay there forever, or for a year or two, and as an underscored name, it's not guaranteed public API. We can tell users that they _should_ drop the "`_v2`" as soon as their build matrix only has new-enough versions of Awkward that it will work.

Before #1721, not all of the symbols that are now in `awkward` were in `awkward._v2`, such as `awkward.nplike` and `awkward._ext`, but having too many symbols wouldn't hurt backward compatibility, just too few.

**Comment by agoose77** [comment]
I was thinking about this myself, and also believe this is a good idea.

**Comment by agoose77** [comment]
Closed by #1730

**Comment by philippemiron** [comment]
Thanks for adding this; it will make the transition easier once v2 is officially out!
