### ISSUE TITLE
An operation to change the number type

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#173]
There's no `astype`, and a general one might want to change such things as non-optiontype arrays into UnmaskedArrays or filter/rearrange the order of record fields. Before we need something like that, though, it would be useful to simply change the leaf types (like what NumPy's `astype` does). Should it be named `ak.withleaftype(array, np.int32)`?

**Comment by ianna** [comment]
> There's no `astype`, and a general one might want to change such things as non-optiontype arrays into UnmaskedArrays or filter/rearrange the order of record fields. Before we need something like that, though, it would be useful to simply change the leaf types (like what NumPy's `astype` does). Should it be named `ak.withleaftype(array, np.int32)`?

or `ak.leaf_astype(array, np.int32)`?

**Comment by jpivarski** [comment]
Maybe. The data analyst-level Python names tend to avoid underscores because they slow down typing. Also, whereas you or I think of these nodes as leaves of a tree, that's not the first metaphor that might come to mind during data analysis. A data analysis is more likely to be thinking of these as "the numbers," though some of them are boolean or text characters.

**Comment by jpivarski** [comment]
#346 was merged.
