### ISSUE TITLE
v2 implementation of `to_arraylib` is missing cases from the original v1 `to_numpy`

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1765]
### Version of Awkward Array

HEAD

### Description and code to reproduce

Lost in translation (and evidence that we need more tests).

v2 `to_arraylib`:

https://github.com/scikit-hep/awkward/blob/3401e2bf53b2c53b877c9d29a5eb0b36e7e01582/src/awkward/_util.py#L753-L806

v1 `to_numpy`:

https://github.com/scikit-hep/awkward/blob/f2092ee90e78c9ce00c54b3f5d9612bd218336ee/src/awkward/operations/convert.py#L208-L370

The libraries other than NumPy won't be able to use some of those other layout node types, but they general implementation should have them anyway. At least, when this is used by `to_numpy`, they need to be there.

**Comment by ioanaif** [comment]
It seems that what looks like it was lost in translation, is actually rewired:
@jpivarski 
```
elif ak.operations.describe.parameters(array).get("__array__") == "bytestring": 
     return numpy.array( 
         [ 
             ak.behaviors.string.ByteBehavior(array[i]).__bytes__() 
             for i in range(len(array)) 
         ] 
     ) 
  
 elif ak.operations.describe.parameters(array).get("__array__") == "string": 
     return numpy.array( 
         [ 
             ak.behaviors.string.CharBehavior(array[i]).__str__() 
             for i in range(len(array)) 
         ] 
     ) 
```

this is now: 

```
elif ak.operations.parameters(array).get("__array__") in (
            "bytestring",
            "string",
        ):

            raise ak._errors.wrap_error(
                ValueError(f"{module.__name__} does not support arrays of strings")
            )
```

However, this still works for numpy because that code is only called by `jax` and `cupy`, whenever we use numpy we fall back on `to_numpy`:

```
if module.__name__ in ("jax.numpy", "cupy"):
        return _impl(array)
    elif module.__name__ == "numpy":
        layout = ak.operations.to_layout(array, allow_record=True, allow_other=True)

        if isinstance(layout, (ak.contents.Content, ak.record.Record)):
            return layout.to_numpy(allow_missing=allow_missing)
        else:
            return module.asarray(array)
```

Proof:

```
>>> aa = ak.contents.NumpyArray(np.frombuffer(b"hellothere", "u1"), parameters={"__array__": "bytestring"})
>>> b = ak._util.to_arraylib(np, aa, False)
>>> b
array([104, 101, 108, 108, 111, 116, 104, 101, 114, 101], dtype=uint8)
>>> c = ak.contents.NumpyArray(np.array([0, 1577836800], dtype='datetime64[s]'))
>>> ak._util.to_arraylib(np, c, False)
array(['1970-01-01T00:00:00', '2020-01-01T00:00:00'], dtype='datetime64[s]')
```

The same is true for:

```
elif isinstance(array, ak.contents.RecordArray): 
     raise ak._errors.wrap_error( 
         ValueError(f"{module.__name__} does not support record structures") 
     ) 
```

When using `numpy`:

```
>>> recordarray = ak.contents.RecordArray([ak.contents.NumpyArray(np.array([1, 2, 3, 4, 5], dtype=np.int64))],fields=["one"])
>>> ak._util.to_arraylib(np, recordarray, False)
array([(1,), (2,), (3,), (4,), (5,)], dtype=[('one', '<i8')])
```

**Comment by jpivarski** [comment]
When I reported this, I didn't go so far as to test it with a CuPy array and a JAX array, so if I had overlooked code elsewhere that makes it work, then that would be good enough to close the issue.

Actually, I just added your tests as a PR that would close this issue. If you approve, go ahead and set that to auto-merge and this issue will be a quick fix.

Thanks!
