### ISSUE TITLE
RedirectArray

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#178]
An array type containing a `std::weak_ptr` to another node. This is the only way to make circular references (a data structure that is more general than a DAG).

The value of this `std::weak_ptr` should be the only array node object that is mutable by design. Since Python/C++ has no lazy semantics (like Scala), you have to build the tree without interconnections before attaching the interconnections.

**Comment by jpivarski** [comment]
Ultimately, the reason we want a RedirectArray is to allow nodes in a tree to point to "ancestor" or "cousin" nodes in the same tree. Nodes that are strictly "descendants" or thought of as being in another tree are already covered by normal `content` inclusion.

## Option 1: a new RedirectArray node type

This was my original thought, but it's going to require rethinking of some basic things, like how to build Forms or Types of trees with redirects. There will need to be placeholder objects and breadcrumbs in the recursive functions to avoid infinite loops. (All of those "`seen"` sets and dicts in Awkward0 recursive functions should probably be called "breadcrumbs.")

Also, RedirectArray would be the one and only mutable node type. One mutable exception in a world of immutability could have unforeseen consequences.

## Option 2: every node has a weak_ptr to parent, RedirectArray is a path with `".."` in it

Giving every node a `std::weak_ptr` to its parent would be less of a can of worms than the above since `content` or `contents` can only be assigned in a node's constructor (because they're immutable), this assignment can be a variation on `shallow_copy` with the exception that it would replace the `parent` of the node that it is given with a new `parent`.

With access to node parents, RedirectArray doesn't have to be a pointer, it can be a path, like a filename path that includes `".."` or some other kind of `up` token. This path would need `up` tokens, strings (to follow RecordArrays down) and integers (to follow UnionArrays down). The `up` tokens don't have to be a special type: they are only useful at the beginning of a path so they could be replaced by an integer. A path would then be a number of steps up followed by mixed strings and integers to step down.

This might be the only solution here that can work in Numba: the `ArrayView` expands a tree out as an array of integers, which becomes an infinite array if the type is cyclic. (It doesn't matter whether the data are cyclic, although electrons with a "closest photon" and photons with a "closest electron" is a "cousin" relationship that can easily be cyclic.)

Being a path also makes it explicit that RedirectArrays are only for links within a tree. If we're ever linking "outside" of a tree, that's equivalent to just adding a new `content`.

## Option 3: we can already do it with VirtualArrays

Nodes are immutable and we want to insert node A as the `content` of node B, but node A might not exist yet when we're building node B. [Scala's solution to that is lazy val](https://blog.codecentric.de/en/2016/02/lazy-vals-scala-look-hood/), which attaches an attribute to a class without evaluating it until it is accessed.

We have lazy semantics: VirtualArrays. So we can already make cyclic dependencies exactly the way that Scala does it.

```python
import numpy as np
import awkward1 as ak

value = ak.layout.NumpyArray(np.array([1.23, 3.21, 9.99, 3.14, 2.71, 5.55, 8.00, 9.00, 0.00]))
left_index = ak.layout.Index64(np.array([1, 3, 5, 7, -1, -1, -1, -1, -1]))
right_index = ak.layout.Index64(np.array([2, 4, 6, -1, 8, -1, -1, -1, -1]))

hold = None
def generate():
    return hold

virtual = ak.layout.VirtualArray(ak.layout.ArrayGenerator(generate))

left = ak.layout.IndexedOptionArray64(left_index, virtual)
right = ak.layout.IndexedOptionArray64(right_index, virtual)

records = ak.layout.RecordArray({"value": value, "left": left, "right": right})
hold = records
tree = records[0]
```

Now `ak.to_list(tree)` is

```python
{'left': {'left': {'left': {'left': None, 'right': None, 'value': 9.0},
                   'right': None,
                   'value': 3.14},
          'right': {'left': None,
                    'right': {'left': None, 'right': None, 'value': 0.0},
                    'value': 2.71},
          'value': 3.21},
 'right': {'left': {'left': None, 'right': None, 'value': 5.55},
           'right': {'left': None, 'right': None, 'value': 8.0},
           'value': 9.99},
 'value': 1.23}
```

If I had slipped up and made a cyclic value reference in this cyclic type reference, the graph would not be a tree and `ak.to_list` or `ak.to_json` would try to build an infinite structure and then crash. Perhaps that's what `ak.to_json` should do, but `ak.to_list` should create a cyclic reference among the Python objects. That would require adding breadcrumbs to the `tolist` implementation.

A lot of methods would have to be protected, because a cyclic dependence could appear anywhere. That was the reason I wanted to create an explicit RedirectArray in Awkward1: the fact that Awkward0's cyclic references could be anywhere because they were just Python references meant that everything had to be protected. It also meant that two objects could be equal without this being apparent because of where the check starts. Suppose that one node A contains another node B, which contains A. I could have another B that contains A that contains B, which is an identical graph, but depending on where you break it to make the check finite, it could appear to be a different graph.

In particular, calling a function like `ak.type` on the `tree` above causes an infinite loop and eventually a segfault. Rather than being good news that we already have a solution for cyclic references, it's bad news because it's an unprotected way to get a segfault in Python.

However, I'm going to ignore it because fixing it would be hard and it's something that only an expert would think of trying. (Insert grim reaper GIF here.)

## Option 4: the array is a plain array of integers, but high-level behaviors interpret it as references

Instead of making this a low-level thing, perhaps the low-level array could just be integers, but we add a high-level behavior to interpret it as references. This solves the issue of not having to rewrite all the low-level methods to be recursion-aware. It gives the redirects that second-class status that I wanted, so that A → B → redirect(A) is different from B → A → redirect(B). It can also work in Numba because high-level behaviors can be overriden in Numba.

However, the main place where redirects act is in `__getitem__`, and `__getitem__` is a deeply recursive C++ function. Adding a behavioral override for `__getitem__` would mean getting information about `behavior` into the C++ call. It will be hard to find a way to do that without making the C++ codebase depend on pybind11.

Also, this puts the responsibility for dealing with references into every behavioral override. That might be putting too much work on framework-developers for something that could be handled once for all.

## Semi-conclusion: I'm thinking of going with Option 2.

Thoughts, @nsmith-?

**Comment by nsmith-** [comment]
For now, after implementing the new masked getitem behavior in #322 I was able to implement option 4 in NanoEvents.
It works like this: a `NanoEventsFactory` object is constructed, and the `factory.events()` method constructs the `events` array. As long as the factory object is alive, it holds a reference to the array so subsequent calls can return the cached copy. A unique key is generated when the factory is instantiated, and the `NanoEventsFactory` class holds a class member that is a weak value dictionary mapping this key to the factory instance. All collections in the `events` have a parameter `events_key` that can be used by the `NanoEventsFactory.get_events(key)` classmethod to retrieve the parent `events` that the collection belongs to. As long as users _only mask entries_ in the events and child collections (never reducing the length) then the cross-references can be computed, masking entries where the calling collection no longer has any information.

**Comment by nsmith-** [comment]
In a revision of NanoEvents, I started using the `behavior` attribute of high-level arrays to carry a sticky reference to an initial array, which the derived arrays can reference into using integers in a high-level behavior method. So, in summary, option 4 still seems to work reasonably well.

**Comment by jpivarski** [comment]
Being realistic, this isn't going to happen. (It's late to be adding new node types now.)
