### ISSUE TITLE
Segmentation fault with nested pair-wise comparison

### ISSUE THREAD

**Issue by yimuchen** [scikit-hep/awkward#1784]
### Version of Awkward Array

1.9.0 and 1.10.0

### Description and code to reproduce

Used as part of coffea package: 

```python
from coffea.nanoevents import NanoEventsFactory
from coffea.nanoevents.schemas import TreeMakerSchema
import awkward as ak

events = NanoEventsFactory.from_root(
    "root://cmseos.fnal.gov//store/user/lpcsusyhad/ExoEMJAnalysis2020/Run2ProductionV20Skimmed/Summer20UL16/GJets_DR-0p4_HT-100To200_TuneCP5_13TeV-madgraphMLM-pythia8/0_RA2AnalysisTree.root",
    schemaclass=TreeMakerSchema,
    treepath="TreeMaker2/PreSelection",
    entry_start=10000,
    entry_stop=20000).events()

jets = events.Jets[events.Jets.pt > 100]
tracks = events.Tracks[events.Tracks.pt > 1.0]

_, tracks = ak.unzip(ak.cartesian([jets.eta, tracks], nested=True))
tracks['deltaR'] = jets.delta_r(tracks)

t_index = ak.argmin(tracks.deltaR, axis=-2)
j_index = ak.local_index(jets.pt, axis=-1)
_, t_index = ak.unzip(ak.cartesian([j_index, t_index], nested=True))
tracks = tracks[j_index == t_index]

tracks = tracks[tracks.deltaR < 0.4]
```

The above segmentation faults at different point for different input files. Usually around the `ak.cartesian` calls, but also when adding variables to the array. Segmentation fault was observed for both awkward 1.9.0 and awkward 1.10.0, but never occurred for awkward 1.8.0

**Comment by agoose77** [comment]
Hi @yimuchen, could you provide a copy of the file to test against? I don't have auth to read from the given XRootD server.

You can create a file `events.pickle.txt` with:
```python3
import pickle
form, length, container = ak.to_buffers(events)
data = (form.tojson(), length, container)
with open("events.pickle.txt", "wb") as f:
    pickle.dump(data, f)
```

**Comment by yimuchen** [comment]
Of course, here is a 100-event file that crashes similarly. This `ak.to_buffers` call was performed using awkward 1.8.0

[events_awkward1.9.0_issue.pickle.txt](https://github.com/scikit-hep/awkward/files/9775067/events_awkward1.9.0_issue.pickle.txt)

**Comment by agoose77** [comment]
This is definitely a bug, and it's being triggered by [one of our kernels](https://github.com/scikit-hep/awkward/blob/b315e6519eb78c8083e088e3ca065cfdb3af5d31/src/cpu-kernels/awkward_ListOffsetArray_reduce_nonlocal_outstartsstops_64.cpp#L33), where we're writing to an out-of-bounds value during the computation of 
```python3
ak.argmin(tracks.deltaR, axis=-2)
```
I think the kernel is behaving properly (although `k` is computed to be `>= outlength`) but we're just passing in either the wrong value for `outlength`, or the wrong array of `gaps`.

**Comment by agoose77** [comment]
My approach to fixing this is currently "write a load of documentation comments on the reduction logic until I understand what is going wrong". This is not a particularly fast process; if e.g. @ianna can easily spot the root-cause then feel free to open a PR whilst I take my time ;)

**Comment by agoose77** [comment]
This reproducer, which I obtained by slicing over the example file, seems also to produce a crash. 
```python
import awkward as ak
import numpy as np

small = ak.Array(
    ak.contents.ListOffsetArray(
        ak.index.Index64(np.array([0, 0, 2])),
        ak.contents.ListOffsetArray(
            ak.index.Index64(np.array([0, 2, 4])),
            ak.contents.NumpyArray(
                np.array([0.00470849, 2.5028446, 3.020969, 3.950173], dtype=np.float32)
            ),
        ),
    )
)

t_index = ak.argmin(small, axis=-2)

```

Some quick variable definitions:
- `gaps`: tracks the integer difference between successive `parents` values. `1` if each distinct parent is the successive integer of the previous distinct parent. `>1` otherwise. Length of `outlength`, because there can be at most `outlength` distinct parent values.
- `distincts`: an array whose shape is `outlength * max_sublist_length`. This _seems_ to map from a `nextparents` value into a zero-based dense _non-empty_ row index.
   I say "row", because in the `nonlocal_preparenext` kernel, the `j` value that is written to `distincts` is reset for each outer loop iteration. This outer loop effectively iterates over the sublists.

In the `_reduce_next` call that segfaults, we have 
- `gaps=[2 *]`, where `*` is uninitialised memory
- `distincts=[-1 -1 0 0]`
- `nextparents=[2 2 3 3]`
These values look correct for the inputs.

I think this crash is newly introduced by e55c914704860cbaaacc72d32a26ecf7c7ecfde2, which adjusts the initial value of `maxdistinct = -2`. This means that for our `distincts=[-1 -1 0 0]` array, the `j` counter increments twice. `j` is used to index into `gaps` before incrementing, and it can be seen that `gaps[1]` is not initialised. 

I already pinged Ianna, but I realised that @jpivarski touched this exact bit of code more recently. Could you confirm whether my interpretation of `distincts` is correct?

**Comment by ianna** [comment]
@agoose77 - strange that I do not get a crash in my case (MacOS and '1.10.0rc1')

**Comment by ianna** [comment]
Here is where it fails:
```c++
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x101400000)
    frame #0: 0x0000000144ffd710 _ext.cpython-39-darwin.so`::awkward_ListOffsetArray_reduce_nonlocal_outstartsstops_64(outstarts=0x0000000100673e50, outstops=0x00000001006240e0, distincts=0x000000010068c920, lendistincts=4, gaps=0x0000000100610710, outlength=2) at awkward_ListOffsetArray_reduce_nonlocal_outstartsstops_64.cpp:33:22
   30  	      }
   31  	
   32  	      for (int64_t gappy = 0;  gappy < numgappy;  gappy++) {
-> 33  	        outstarts[k] = i;
   34  	        outstops[k] = i;
   35  	        k++;
   36  	      }
```

**Comment by agoose77** [comment]
@ianna that looks like the same result I'm observing; can you confirm whether the value of `numgappy` looks like uninitialised memory?

**Comment by ianna** [comment]
> @ianna that looks like the same result I'm observing; can you confirm whether the value of `numgappy` looks like uninitialised memory?

```
(int64_t) maxcount = 2
(int64_t) j = 1
(int64_t) k = 33774
(int64_t) maxdistinct = 0
(int64_t) lasti = 2
(int64_t) i = 2
(int64_t) extra = 1
(int64_t) numgappy = 3458764514096627209
(int64_t) gappy = 33772
```

**Comment by agoose77** [comment]
My current line of thinking is that I find it surprising to be indexing into `gaps` with an integer whose value depends upon the number of distinct values in `nextparents`. `nextparents` is used by the reduction of the child; the reduction result is wrapped according to `parents` & `gaps` is computed for `parents`. I might be barking up the wrong tree here, but it feels like this might be using the wrong array. I doubt that I'm right - this is highly used code, and what I'm suggesting would radically change its function, so I'm going to keep investigating.

**Comment by agoose77** [comment]
OK, I think I got this working:
```python
            if not (self._nplike.known_data and self._nplike.known_shape):
                self._handle_error(
                    self._nplike[
                        "awkward_ListOffsetArray_reduce_nonlocal_outstartsstops_64",
                        outstarts.dtype.type,
                        outstops.dtype.type,
                        distincts.dtype.type,
                        gaps.dtype.type,
                    ](
                        outstarts.data,
                        outstops.data,
                        distincts.data,
                        distincts.length,
                        gaps.data,
                        outlength,
                    )
                )
            else:
                # The goal of this kernel is to find the offsets into the reduction result
                # that satisfy our parents. There may be multiple nextparents per parent
                # so we'll use nextparents to figure out which parent we're in. Each
                # parent value corresponds to a sublist in the result.
                k = 0
                last_parent = -1
                last_distinct = -2
                for i in range(len(distincts)):
                    # If the reduction result has this value
                    if distincts[i] != -1:
                        # `distincts` gives us the (dense) sublist index into the final result
                        # it is not the *actual* sublist index, as it does not consider empty sublists
                        # so, test here whether the current sublist has changed
                        if distincts[i] != last_distinct:
                            # Determine the sublist we're currently in
                            parent = i // maxcount
                            # Open as many sublists as required to fill in the gaps
                            # and then open one more, for *this* sublist
                            # parent - last_parent is 1 for no gaps
                            for _ in range(parent - last_parent):
                                outstarts[k] = i
                                outstops[k] = i
                                k += 1

                            last_parent = parent
                            last_distinct = distincts[i]

                        # Close previous list
                        outstops.data[k - 1] = i + 1
```

This logic fails one test that might be a trivial fix, and it's determined from first-principles. I can look at how to reduce e.g. the number of floor divisions by using something like gaps.

**Comment by agoose77** [comment]
OK, I think I got this working:
```python
            if not (self._nplike.known_data and self._nplike.known_shape):
                self._handle_error(
                    self._nplike[
                        "awkward_ListOffsetArray_reduce_nonlocal_outstartsstops_64",
                        outstarts.dtype.type,
                        outstops.dtype.type,
                        distincts.dtype.type,
                        gaps.dtype.type,
                    ](
                        outstarts.data,
                        outstops.data,
                        distincts.data,
                        distincts.length,
                        gaps.data,
                        outlength,
                    )
                )
            else:
                # The goal of this kernel is to find the offsets into the reduction result
                # that satisfy our parents. There may be multiple nextparents per parent
                # so we'll use nextparents to figure out which parent we're in. Each
                # parent value corresponds to a sublist in the result.
                k = 0
                last_parent = -1
                last_distinct = -2
                for i in range(len(distincts)):
                    # If the reduction result has this value
                    if distincts[i] != -1:
                        # `distincts` gives us the (dense) sublist index into the final result
                        # it is not the *actual* sublist index, as it does not consider empty sublists
                        # so, test here whether the current sublist has changed
                        if distincts[i] != last_distinct:
                            # Determine the *actual* sublist we're currently in
                            parent = i // maxcount
                            # Open as many sublists as required to fill in the gaps
                            # and then open one more, for *this* sublist
                            # parent - last_parent is 1 for no gaps
                            for _ in range(parent - last_parent):
                                outstarts[k] = i
                                outstops[k] = i
                                k += 1

                            last_parent = parent
                            last_distinct = distincts[i]

                        # Close previous list
                        outstops.data[k - 1] = i + 1
```

This logic fails one test that might be a trivial fix, and it's determined from first-principles. I can look at how to reduce e.g. the number of floor divisions by using something like gaps.

The fix for our existing kernel is just the guard `if distincts[i] != -1`. However, our kernel is using `gaps` *and* performing a floor division. We can get rid of gaps (I think) if we require a divide, though we might be able to remove the division and keep the gaps array. This is probably better performance-wise (if we have long sublists), though it's really just an exercise at this point.

**Comment by ianna** [comment]
@agoose77 - it does not crash in `v2`. Though, `v2` in `1.10.0rc1` produces:
```python
>>> t_index
<Array [[None, None], []] type='2 * var * ?int64'>
```
while in `2.0.0rc1` the result is:
```python
>>> t_index
<Array [[], []] type='2 * var * ?int64'>
```

**Comment by agoose77** [comment]
Thanks @ianna, that's interesting :thinking:. Let's see if #1796 fixes v2, too (it had better! :pray:)
