### ISSUE TITLE
Write output files into a temporary directory during tests.

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1802]
See https://github.com/scikit-hep/awkward/commit/b315e6519eb78c8083e088e3ca065cfdb3af5d31#r87085384, quoted below. It's a follow-up on #1781.

These (lines [30](https://github.com/scikit-hep/awkward/blob/580f3fad01327a6b1d8c2e1edbaf324f35fb7796/tests/test_1781-rdataframe-snapshot.py#L30) and [47](https://github.com/scikit-hep/awkward/blob/580f3fad01327a6b1d8c2e1edbaf324f35fb7796/tests/test_1781-rdataframe-snapshot.py#L47)) need to use the `tmp_path` fixture, like

https://github.com/scikit-hep/awkward/blob/580f3fad01327a6b1d8c2e1edbaf324f35fb7796/tests/test_1619-from-parquet-empty-field.py#L13-L29

so that it doesn't leave `test-integers.root` and `test-listarray.root` files in the main directory after running.

Thanks!

**Comment by ianna** [comment]
fixed in https://github.com/scikit-hep/awkward/pull/1804
