### ISSUE TITLE
URL mapping in new docs

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1808]
### Which documentation?

Tutorials site

### What needs to be documented?

https://github.com/scikit-hep/uproot5/issues/760 points out a dead link in the Uproot docs:

https://awkward-array.readthedocs.io/en/latest/ak.types.Type.html

That's an indication that this link used to work and it has probably been shared beyond just the Uproot docs. It doesn't have the `_auto` in the URL because it was one of the hand-written reST files, not one made by `prepare_docstrings.py`.

Looking in the `docs` branch by swapping `latest` with `docs`, it still doesn't exist, but

https://awkward-array.readthedocs.io/en/docs/reference/generated/ak.types.Type.html

does exist, and it's where this URL is supposed to go. So we'll need a redirect.

Also, the layout URLs that are now

https://awkward-array.readthedocs.io/en/docs/reference/generated/ak.contents.Content.html

(unfortunately!) need a redirect from "`ak.layout.`" to "`ak.contents.`" (all the Content classes). Similarly for "`ak.layout.Record`" (only one Record) → "`ak.record.Record`" and "`ak.layout.Index`" → "`ak.index.Index`" (all the Index classes). Unless we want those links to fail as an indicator to users that the name no longer exists? Maybe better, a page briefly describing the name change (rather than an automated redirect)?

**Comment by agoose77** [comment]
Ah, we do have redirects, but it seems like we lost a directory component somehow. Should be a quick fix!
