### ISSUE TITLE
Awkward v2 mixins not propagated upwards

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#1834]
### Version of Awkward Array

2.0.0rc1

### Description and code to reproduce

Coffea tests with awkwardv2 fail with: `E   AttributeError: module 'awkward.behaviors' has no attribute 'mixin_class'`

`awkward.mixin_class` has moved to `awkward.behaviors.mixins.mixin_class`, along with all other mixin decorators.

**Comment by agoose77** [comment]
This is probably something we should fix, as it is a high-level function. I've made a PR #1835
