### ISSUE TITLE
Concatenate for axis != 0

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#184]
This was an oversight: it's really needed but I closed the "concatenate" issue (#76) once the function existed, though there's a NotImplementedError in it:

https://github.com/scikit-hep/awkward-1.0/blob/afaa40f3993819d7beac903f701a4a1fb7f69897/src/awkward1/operations/structure.py#L151-L154

This operation is known to be useful from Awkward0; it was even an external contribution (https://github.com/scikit-hep/awkward-array/pull/80).

In Awkward1, it can probably be implemented as a broadcast in Python + specialized C++ method on ListArray, ListOffsetArray, and RegularArray (nothing else). That would allow all possible `axis` values.

**Comment by jpivarski** [comment]
I'm calling it a bug because it's not optional, though I suppose that's stretching the terminology.

**Comment by Ellipse0934** [comment]
I want to work on this. I think a specialized C++ method which concatenates two arrays at a time with Python calling it repeatedly for all input arrays should do it.

Writing it in Python as a recursive function:
```python
def concat(arrays, axis=0, mergebool=True, highlevel=True):
    if axis != 0:
        res = [subarr for subarr in arrays[0]]
        for arr in arrays[1:]:
            for i in range(len(arrays[0])):
                res[i] = concat([res[i], arr[i]], axis=axis-1, mergebool=mergebool, highlevel=highlevel)
        return ak.Array(res)
    else:
        return ak.concatenate(arrays, mergebool=mergebool, highlevel=highlevel)
```
```python
>>> x = ak.Array([[[1, 2, 3], [4, 5]], [[6, 7]]])
>>> y = ak.Array([[[], [8, 9]], [[10, 11]]])
>>> x, y
(<Array [[[1, 2, 3], [4, 5]], [[6, 7]]] type='2 * var * var * int64'>,
 <Array [[[], [8, 9]], [[10, 11]]] type='2 * var * var * int64'>)

>>> concat([x, y], axis = 0).tolist()
[[[1, 2, 3], [4, 5]], [[6, 7]], [[], [8, 9]], [[10, 11]]]

>>> concat([x, y], axis = 1).tolist()
[[[1, 2, 3], [4, 5], [], [8, 9]], [[6, 7], [10, 11]]]

>>> concat([x, y], axis = 2).tolist()
[[[1, 2, 3], [4, 5, 8, 9]], [[6, 7, 10, 11]]]
```
To use a iterative solution instead of a recursive one we will need to track the index at each depth. At each depth we need to rewrite the Array's `Index` and `Content` and at `depth=axis` we need to call `merge`, not sure about the `Identities` and `Parameters` part yet, maybe I'll figure it out as I start working.
Hopefully no time pressure on this task as well.

**Comment by jpivarski** [comment]
This is the correct behavior, and you're right that it should be recursive. The identities should be `Identities::none()`, so that's easy, and the parameters should probably be the parameters of the first array. I should think about what the policy should be when combining arrays with different parameters, and maybe introduce a function that merges them in a standardized way.

You're also right that this needs to be a custom C++ function—the [old solution in pure Python](https://github.com/scikit-hep/awkward-array/blob/a2645fdaed1a6997c4677ae47cbb2cd0663e8a21/awkward/array/jagged.py#L1643-L1726) was very complicated and only worked for `axis=1`. However, any operation that involves more than one array needs a Python part to do the broadcasting:

https://github.com/scikit-hep/awkward-1.0/blob/ef401a044dc6b5b48443caa9223d1e3d6aecec78/src/awkward1/_util.py#L382

Broadcasting in Awkward Array not only involves expanding dimensions of length 1 as it does for NumPy, but also dealing with IndexedArrays, RecordArrays, UnionArrays, and the rest. It's written in Python because testing for all of these types would involve a lot of `dynamic_casts` in C++, but it's more manageable in Python. For example, if one array is

   * ListOffsetArray → IndexedArray → ListArray → RecordArray,

and another is

   * IndexedArray → ListArray → IndexedArray → ListOffsetArray → RecordArray,

then they have equivalent structure without even needing to "broadcast" in the NumPy sense. Checking for all of those cases in C++ would be a mess! (The `merge` function behind concatenate for `axis=0` has to deal with this complexity at one level of depth, and it's [quite messy](https://github.com/scikit-hep/awkward-1.0/blob/ef401a044dc6b5b48443caa9223d1e3d6aecec78/src/libawkward/array/ListArray.cpp#L739-L1000). It exists to concentrate that mess in one place, so that it can be used elsewhere.)

Therefore, I don't think this is a "good first issue." I'd appreciate the help, but I think this one would be too much without more background in the internals.

**Comment by nsmith-** [comment]
Can this feature be reprioritized? Axis-1 (or deeper) concatenate can be very useful for some common operations, e.g. merging lepton collections.

**Comment by jpivarski** [comment]
That would be reasonable. I'll get to it soon after dealing with Arrow 1.0, which seems to have broken everything.

**Comment by jpivarski** [comment]
@ianna I was just thinking about this: what would you think about taking this on? It would use the negative axis you just finished. Do you see what it's supposed to do?

(Personally, I don't know what it ought to do if the desired axis is deeper than a record layer. Maybe we could exclude that case.)

**Comment by jpivarski** [comment]
This wasn't linked to the new PR, #539, so it didn't automatically close. But it's done!
