### ISSUE TITLE
ak.type does not understand `numpy.<type>` style dtypes

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#1840]
### Version of Awkward Array

2.0.0rc1

### Description and code to reproduce

numpy = 1.23.4

```python3
>>> import awkward as ak
>>> import numpy as np
>>> x = np.random.normal(size=100)
>>> ak.type(x)
```
results in:
```
Traceback (most recent call last):
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_type.py", line 99, in _impl
    out = ak.types.numpytype._dtype_to_primitive_dict[array.dtype.type]
KeyError: <class 'numpy.float64'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_type.py", line 60, in type
    return _impl(array)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_type.py", line 101, in _impl
    raise ak._errors.wrap_error(
TypeError: while calling

    ak.type(
        array = numpy.ndarray([ 0.27824033 -1.483569   -0.61108357 ...
    )

Error details: numpy array type is unrecognized by awkward: <class 'numpy.float64'>
```

`np.float64` (or `np.<type>` in general) is a fairly common way for folks to denote typing, we should probably support it.

**Comment by jpivarski** [comment]
Here's where it can go: in awkward/operations/ak_type.py, there's a case-catcher for

https://github.com/scikit-hep/awkward/blob/c0336973a8bacbbc86438aa69ef4c1bd48186c8b/src/awkward/operations/ak_type.py#L67-L73

The keys of that dict are actual `np.dtype` objects, but you want the `type` instances, which are obtained via `some_dtype_object.type`.

They can be identified as

```python
isinstance(array, type) and issubclass(array, np.generic)
```

**Comment by lgray** [comment]
Wouldn't this be fixed instead by asking for `array.dtype` instead of `array.dtype.type` (which gives the class as opposed to the dtype). Here: https://github.com/scikit-hep/awkward/blob/main/src/awkward/operations/ak_type.py#L99

?

**Comment by agoose77** [comment]
Thanks for this @lgray. We should be testing the comprehensive `dtype` here rather than the underlying type.
