### ISSUE TITLE
ak.combinations drops types when accessing components

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#1866]
### Version of Awkward Array

2.0.0rc2

### Description and code to reproduce

NanoEvents objects lose their behavior when run through combinations.

reproducer:
```
$ git clone https://github.com/CoffeaTeam/coffea.git -b awkward2_dev
$ cd coffea
$ pip install -e '.[dev]'
$ python
>>> from coffea.nanoevents import NanoEventsFactory
>>> factory = NanoEventsFactory.from_root("tests/samples/nano_dy.root")
>>> events = factory.events()
>>> events.Muon[4][0] + events.Muon[4][1] # to show it works in the first place
>>> combos = ak.combinations(events.Muon, 2)
>>> dimuons = combos["0"] + combos["1"]
```

Fails to add pairs of muon objects together.

You can add print outs for the behaviors of the objects and you will find that they are `None` while `events.Muon` is not.

**Comment by lgray** [comment]
Hmm, this doesn't fail in more minimal cases, checking it out...

**Comment by lgray** [comment]
Ah - got it, it's in the operators:
```
import awkward as ak
import numpy as np

@ak.mixin_class(ak.behavior)
class Point:
    def distance(self, other):
        return np.sqrt((self.x - other.x) ** 2 + (self.y - other.y) ** 2)

    @ak.mixin_class_method(np.equal, {"Point"})
    def point_equal(self, other):
        return np.logical_and(self.x == other.x, self.y == other.y)

    @ak.mixin_class_method(np.abs)
    def point_abs(self):
        return np.sqrt(self.x ** 2 + self.y ** 2)

test = ak.Array([[{"x": float(i), "y": float(i)}, {"x": float(i)*0.5, "y": float(i)*0.5}] for i in range(100)], with_name="Point")

print(test + test)  # fails here                                                                                                                                                                                                                             

combos = ak.combinations(test, 2)

print(combos["0"] + combos["1"])
```

Pleasantly self-contained within awkward, fails in 2.0.0rc2. @jpivarski @agoose77

**Comment by lgray** [comment]
Wait a second, still not quite right... Apologies.

**Comment by lgray** [comment]
OK - I think this may be interface changes re: NanoEvents. Digging.

**Comment by lgray** [comment]
Ah! I think I found it, it's because I'm not using the global behavior namespace. It appears that more "private" behaviors are not propagated like they are in awkward1.

Here is a repro without any coffea:
```python3
import awkward as ak
import numpy as np

behavior = {}

@ak.mixin_class(behavior)
class Point:
    def distance(self, other):
        return np.sqrt((self.x - other.x) ** 2 + (self.y - other.y) ** 2)

    @ak.mixin_class_method(np.equal, {"Point"})
    def point_equal(self, other):
        return np.logical_and(self.x == other.x, self.y == other.y)

    @ak.mixin_class_method(np.abs)
    def point_abs(self):
        return np.sqrt(self.x ** 2 + self.y ** 2)

    @ak.mixin_class_method(np.add, {"Point"})
    def point_add(self, other):
        return ak.zip(
            {"x": self.x + other.x, "y": self.y + other.y}, with_name="Point",
        )

test = ak.Array([[{"x": float(i), "y": float(i)}, {"x": float(i)*0.5, "y": float(i)*0.5}] for i in range(100)], with_name="Point", behavior=behavior)

print(test + test)

combos = ak.combinations(test, 2)

print(combos["0"] + combos["1"])  # fails here because of lost behavior
```

@jpivarski @agoose77 here - this is the properly worked out issue in awkward 2.0.0rc2 alone. The above program executes successfully (and I'm pretty sure also correctly from a functional standpoint) in awkward 1.10.1. 

Apologies for the spam, trying to make the issue exactly known took some digging.

**Comment by jpivarski** [comment]
The intention is to propagate private behaviors in Awkward v2 exactly as they had been in Awkward v1.

If you remember, though, we had to discover these cases of lost behavior-passing by exhaustion in the early history of Awkward and Coffea. The fact that Coffea passes behaviors locally has been very useful for finding these oversights!

In principle, there should be a lot fewer lost behaviors to find and fix because the v2 implementation was copied from the v1 implementation. But if a test didn't explicitly check for lost behavior in a particular situation (as seems to be the case here), then it could have been lost in the translation from C++ to Python.
