### ISSUE TITLE
Bad error message for decimal type

### ISSUE THREAD

**Issue by martindurant** [scikit-hep/awkward#1870]
### Version of Awkward Array

main

### Description and code to reproduce

If you attempt to load a parquet file containing decimal columns, you get a ValueError, which is expected, but the message is:
```
"Arrow arrays containing pickled Python objects can't be converted into Awkward Arrays"
```
which looks like it's been copied from somewhere else.

https://github.com/scikit-hep/awkward/blob/main/src/awkward/_connect/pyarrow.py#L476

**Comment by jpivarski** [comment]
Thanks! That's a bad copy-paste from the `pyarrow.lib.PyExtensionType` case.
