### ISSUE TITLE
Long-range metadata checks during ak.Array creation

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1910]
### Description of new feature

In https://github.com/scikit-hep/awkward/pull/1904#discussion_r1029626522, I said that a particular construction (`IndexedArray` of `IndexedOptionArray`) doesn't need to be considered because it's not a valid array, and while we try to use `simplify_optiontype` and `simplify_uniontype` to ensure that these things don't exist, erroneous cases have slipped through in the past, and they might again.

First of all, we even need a way of talking about these states. @agoose77 suggested "canonical representation," but there are multiple levels of canonicity.

- Level 0, short-range metadata constraints: `Content` node with wrong-type or out-of-range metadata, like a `RegularArray` with a `size` of `"some_string"` or `-12`. This is already prohibited by the `Content` constructors and can never exist as an object.
- Level 1, long-range metadata constraints: `Content` node with metadata that is incompatible with another `Content` node, such as its direct child `content`. The above-mentioned `IndexedArray` of `IndexedOptionArray` is an example. These states are allowed to exist in the midst of a calculation, but they need to be fixed before handing them off to the user.
- Level 2, long-range value constraints: `Content` node with array values that are incompatible with itself or another node (in practice, always a direct child), such as an `IndexedArray` with a negative value in `index`, or with a value in `index` that is greater than or equal to the length of its `content`. The `validity_error` tests (`check_valid` argument of the `ak.Array` constructor) check these, as well as some long-range metadata constraints, like the fact that a `"string"` should be a list-type array that contains a `"char"` `NumpyArray`.

The level 2 checks are _O(n)_ where _n_ is the length of the array, so they have to be invoked by user request. Adding them to the `ak.Array` constructor, for instance, would be a bad performance regression, and almost always unnecessary.

(Also note that if a kernel function needs a particular level 2 constraint to be satisfied, it performs that check as part of its operation. That's usually inexpensive because the _O(n)_ loop was happening anyway and the relevant data are already in fast memory anyway.)

Level 1 checks, however, scale with the size of the tree but not with the lengths of any arrays. Low-level arrays (layouts) are allowed to be level-1 invalid while we work on them, but if we're ever wrapping them as high-level `ak.Arrays`, they should already be simplified: i.e. the `simplify_optiontype` method should be called on an `IndexedArray` of `IndexedOptionArray` to turn it into a single-level `IndexedOptionArray`. (Similarly for `simplify_uniontype`.)

Scaling with the size of the tree might still be a problem if it happens frequently: our internal code pulls layouts out of `ak.Arrays` and re-wraps them as new `ak.Arrays` quite a lot, and some records have thousands of fields. We wouldn't want the same checks to be performed on the same layouts, over and over. Perhaps the best way is to add a `_metadata_checked: bool` attribute to every `Content` instance. If `not _metadata_checked` in the `ak.Array` or `ak.Record` constructor, a check should be performed to either set it to `True` or to raise an error. Since Awkward Arrays are immutable, a `True` value of `_metadata_checked` at any level means that `_metadata_checked` is true for all nested children.

Some node types never need to be checked:

```python
class EmptyArray(Content):
    _metadata_checked = True
```

and

```python
class NumpyArray(Content):
    _metadata_checked = True
```

can be class attributes, `True` for all instances of the class. Similarly,

```python
class Content:
    _metadata_checked = False
```

as a class attribute would set the default that is only overridden with a new reference to the `True` PyObject when a check is actually performed, so this has zero overhead for temporary layouts that never get into any `ak.Array.

The use of the word "metadata" in level 1 checks won't ever be confused with level 0 because level 0 fails at [RAII time](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization).

Adding the long-range metadata check as an "always on" consistency test means that it can (and should) be removed from the `validity_error` tests, which would then focus exclusively on long-range value checks.

Whatever we implement for normal arrays will also work for `TypeTracerArrays` because we're only accessing the metadata. Maybe a little special care would be needed for `RecordArray`, whose `length` must be less than or equal to the `length` of all of its `contents`, as a long-range metadata constraint. This might need to speculatively pass at the `TypeTracerArray` stage (i.e. Dask graph creation) and fail when real arrays are executed (Dask worker nodes).

The value of all of this is to learn very quickly about any missing calls to `simplify_optiontype` or `simplify_uniontype`. I think that this should go in _after the 2.0.0 release_, rather than adding more work to the remaining time in the schedule. Technically, this would turn situations that might happen to work into situations that raise errors, but turning a silent error into a noisy one can hardly be called an API change.

**Comment by jpivarski** [comment]
As described in https://github.com/scikit-hep/awkward/issues/1193#issuecomment-1326617840, the full set of non-canonical nestings at level 1 is:

* `self.is_indexed and self.content.is_indexed`
* `self.is_indexed and self.content.is_option`
* `self.is_option and self.contend.is_indexed`
* `self.is_option and self.content.is_option`
* `self.is_option and self.content.is_union`  ← we're following Arrow's choice on this (the alternative would be to exclude union of option, but let's follow their lead)

In addition, an `__array__: "string"` parameter on a list implies that its content should have `__array__: "char"` and be a NumpyArray, and similarly for bytestrings and categoricals, which are the level-1 non-canonical cases that are being checked in `validity_error`. Those would instead be part of the level 1 canonicity test.

**Comment by agoose77** [comment]
What is confusing to me is that we seem to have conflicting ideas here; on the one hand
> These states are allowed to exist in the midst of a calculation, but they need to be fixed before handing them off to the user.

but on the other hand,
> a particular construction (IndexedArray of IndexedOptionArray) doesn't need to be considered because it's not a valid array

Whilst I do think that restricting ourselves to a subset of the layout combinations is the right move long term (as it allows us to simplify our internals), we probably need to be rigorous about it. As Jim rightly notes
> while we try to use simplify_optiontype and simplify_uniontype to ensure that these things don't exist, erroneous cases have slipped through in the past, and they might again.

Indeed, there's nothing currently stopping us from passing an "invalid" array to a function that expects a canonicalised layout.

My main question is — where do we draw this line? Within *only* the high level `ak.operations.*` functions? i.e. do we not check third-party libraries using only the layout APIs? Or, do we also have routines withing layouts e.g. `layout._drop_none()` that require canonicity? Should this be an assertion, i.e. it's an error to encounter a non-canonical layout, or a guarantee i.e. we canonicalise all layouts before reaching a certain function?

Based upon the current discussion, I think we clearly do have a notion of what an L1 canonical layout looks like, so we can encode that as a lazy property of the array. I'm not really worried about performance here either; these checks should be on the order of tens to hundreds within a normal high-level operation (guess).

So, depending upon the answer to the above, we either have `layout.assert_canonical()` or `layout.as_canonical()`. Is this what you're thinking @jpivarski 

@jpivarski RE the L1 rules, how do we feel about things like `Indexed(Record([Indexed(...), Indexed(...)]))`? I assume we are fine with such a layout (your rules don't need touching), because it's a performance regression to require the contents of a RecordArray to be indexed by the same index array (which would require a copy)?

**Comment by jpivarski** [comment]
We can draw lines: this is not something that will get out of hand. When I say that these non-canonical layouts exist only within one of our implementations, it's usually

```python
return UnionArray(
    ...
).simplify_union()
```

The possibly invalid `UnionArray` exists for the duration of half an expression, and the whole point of building it is to immediately call `simplify_union` (similarly for `simplify_option`) and make it canonical before it leaves the function scope. The bad situation that we're trying to catch is forgetting to call `simplify_union`/`simplify_option`.

What we can't do is forbid the non-canonical union/option in the `UnionArray`/etc. constructors. Then, we wouldn't be able to write the above expression. Every place where we want to do this would have to express the logic of "if such and such _would be_ non-canonical, don't construct it" inline.

----------------

Unless... (yes, I am just realizing this now) we introduce `maybe_simplify_*` functions that contain the logic of what is canonical and what isn't, and then the `Content` constructors can restrict themselves to canonicity upon construction.

When I opened this issue, I _had been_ thinking about drawing the line at `ak.Array` construction time: non-canonical layouts would be allowed until they get wrapped as a high-level array, and that effectively allows non-canonicity in our internal functions (and also downstream developers' internal functions). It would prevent non-canonicity from spreading too far, allowing us to assume that user input to an `ak.*` operation is canonical.

But another possibility is to draw the line much tighter, at layout construction time. There would be 6 new functions:

  * `maybe_simplify_UnionArray`
  * `maybe_simplify_IndexedArray`
  * `maybe_simplify_IndexedOptionArray`
  * `maybe_simplify_ByteMaskedArray`
  * `maybe_simplify_BitMaskedArray`
  * `maybe_simplify_UnmaskedArray`

that all take the same arguments as the `UnionArray`, `IndexedArray`, ... `UnmaskedArray` constructors, but might not return an instance of the corresponding class—they might instead return something simplified.

A way this could be implemented (reusing as much existing code as possible) would be to build an instance of the corresponding class with `__new__`, to bypass its constructor, as its constructor would now be checking for canonicity, and then immediately call `simplify_union`/`simplify_option` on it and return that.

The advantages of this over letting non-canonical layouts live for a short period are:

  * There will be no ways for non-canonical layouts to slip through.
  * We won't have to do an expensive, tree-scanning check in `ak.Array` construction, and won't have to introduce a new "already checked" cache (`_metadata_checked` above).

Downstream developers might complain that layouts are more difficult to build, but we could help with that by making the `maybe_simplify_*` functions public (tucked away inside the `ak.contents` submodule).

The `simplify_union` and `simplify_option` methods, _used by_ `maybe_simplify_*`, should then become private (get underscores) because they would become useless on a properly-constructed (no `__new__`) layout.

------------------

> @jpivarski RE the L1 rules, how do we feel about things like `Indexed(Record([Indexed(...), Indexed(...)]))`? I assume we are fine with such a layout (your rules don't need touching), because it's a performance regression to require the contents of a RecordArray to be indexed by the same index array (which would require a copy)?

That's allowed/canonical. When the RecordArray is constructed, we don't know if the IndexedArray of each field is the same index or a different index, and checking would be a level 2, long-range value constraint. RecordArray's `_carry` favors creating an IndexedArray because RecordArrays with thousands of fields are common enough for it to be an important performance consideration. Any combination of checking field-IndexedArrays against each other and/or merging the IndexedArray around a RecordArray with the IndexedArrays of fields have bad performance consequences.

But most importantly, our internal code does not assume that `Indexed(Record([Indexed(...), Indexed(...)]))` can't happen. All of our implementations should work, given such a thing. When a user projects out a field (i.e. calls `__getattrib__` or calls `__getitem__` with a string), there _should_ be a call to `simplify_option` somewhere to merge the outer IndexedArray with the inner IndexedArray (for that one field: not a performance issue). Doing the above-mentioned conversion of `simplify_option` to `maybe_simplify_IndexedArray` could catch cases that _should_ but _do not_.

--------------------------

Since this affects layout constructors, turning currently allowed cases into error cases, it looks like it needs to be done before `next-release`. I'll self-assign, but before implementing it, I'll measure the size of the problem, to see if it's going to be feasible.
