### ISSUE TITLE
ak.is_none is off-by-one with negative axis and doesn't handle an edge case of positive axis

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1914]
### Version of Awkward Array

HEAD

### Description and code to reproduce

Here's an array with missing values at many levels, including unequal branches through a RecordArray:

```python
>>> array = ak.Array([
...     None,
...     [None],
...     [{"x": None, "y": None}],
...     [{"x": [None], "y": [None]}],
...     [{"x": [1], "y": [[None]]}],
...     [{"x": [2], "y": [[1, 2, 3]]}],
... ])
```

For `axis=0`, we expect item `0` to be `True` and the rest to be `False`, which is correct in v1 and v2 (only v2 is shown):

```python
>>> ak.is_none(array, axis=0).show(type=True)   # v2
type: 6 * bool
[True,
 False,
 False,
 False,
 False,
 False]
```

For `axis=1`, we expect item `0` to be `None`, item 1 to be a singleton list containing `True`, and all the rest to be singleton lists containing `False`, which is correct in v1 and v2:

```python
>>> ak.is_none(array, axis=1).show(type=True)   # v2
type: 6 * option[var * bool]
[None,
 [True],
 [False],
 [False],
 [False],
 [False]]
```

For `axis=2`, we expect similar pass-throughs on items `0` and `1`, and item `2` also passes through because record fields are at the same level of `axis` depth as the record itself. (That's a design decision across all of Awkward Array; we can't change it.) Item `3` contains singleton `[True]` for both fields because they're both missing at this level. v1 and v2 are both correct:

```python
>>> ak.is_none(array, axis=2).show(type=True)   # v2
type: 6 * option[var * ?{
    x: option[var * bool],
    y: option[var * bool]
}]
[None,
 [None],
 [{x: None, y: None}],
 [{x: [True], y: [True]}],
 [{x: [False], y: [False]}],
 [{x: [False], y: [False]}]]
```

For `axis=3`, we expect pass-throughs on items `0`, `1`, `2`, and `3`, but item `4` should pass-through on field `x` (`axis=3` is deeper than that field) while field `y` is `[[True]]`. Only v1 gets it right (showing v1):

```python
>>> ak.is_none(array, axis=3).tolist()   # v1
[None, [None], [{'x': None, 'y': None}], [{'x': [None], 'y': [None]}], [{'x': [1], 'y': [[True]]}], [{'x': [2], 'y': [[False, False, False]]}]]
```

v2 raises an AxisError:

```python
>>> ak.is_none(array, axis=3).show(type=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/awkward/src/awkward/operations/ak_is_none.py", line 28, in is_none
    return _impl(array, axis, highlevel, behavior)
  File "/home/jpivarski/irishep/awkward/src/awkward/operations/ak_is_none.py", line 72, in _impl
    raise ak._errors.wrap_error(
numpy.AxisError: while calling

    ak.is_none(
        array = <Array [None, ..., [{x: [2], ...}]] type='6 * option[var * ...'>
        axis = 3
        highlevel = True
        behavior = None
    )

Error details: axis=3 exceeds the depth (2) of this array
```

It looks like there's an "and" when there ought to be an "or," or something like that.

--------------------------

Now for negative `axis`. For `axis=-1`, I would expect

```
type: 6 * option[var * ?{
    x: var * bool,
    y: option[var * bool]
}]
[None,
 [None],
 [{x: None, y: None}],
 [{x: [True], y: [None]}],
 [{x: [False], y: [[True]]}],
 [{x: [False], y: [[False, False, False]]}]]
```

because `axis=-1` goes all the way down to the option-type integers in field `y` and all the way down to the option-type integers in field `x`, which are different depths.

Instead, `axis=-1` in v1 and v2 implements what I would expect for `axis=-2`:

```python
>>> ak.is_none(array, axis=-1).show(type=True)   # v2
type: 6 * option[var * ?{
    x: bool,
    y: option[var * bool]
}]
[None,
 [None],
 [{x: True, y: None}],
 [{x: False, y: [True]}],
 [{x: False, y: [False]}],
 [{x: False, y: [False]}]]
```

```python
>>> ak.is_none(array, axis=-1).tolist()   # v1
[None, [None], [{'x': True, 'y': None}], [{'x': False, 'y': [True]}], [{'x': False, 'y': [False]}], [{'x': False, 'y': [False]}]]
```

There seems to have always been an off-by-one error in this accounting. It only needs to be fixed in v2.

Incidentally, if we make an array just like above but without `x`, it's still wrong in the same way. This second bug is not due to confusion about the record-branching, it's a constant off-by-one error.

```python
>>> array = ak.Array([None, [None], [{"y": None}], [{"y": [None]}], [{"y": [[None]]}], [{"y": [[1, 2, 3]]}]])

>>> ak.is_none(array, axis=-1).show(type=True)   # v2
type: 6 * option[var * ?{
    y: option[var * bool]
}]
[None,
 [None],
 [{y: None}],
 [{y: [True]}],
 [{y: [False]}],
 [{y: [False]}]]
```

```python
>>> array = ak.Array([None, [None], [{"y": None}], [{"y": [None]}], [{"y": [[None]]}], [{"y": [[1, 2, 3]]}]])

>>> ak.is_none(array, axis=-1).tolist()   # v1
[None, [None], [{'y': None}], [{'y': [True]}], [{'y': [False]}], [{'y': [False]}]]
```

**Comment by agoose77** [comment]
@jpivarski I'm not fixing this yet, but I did look at it. What we're seeing in (1) is happening because we're using the `branch_depth` to compute the maximum axis. Of course, in this example, the branch depth is the `min` depth. The behaviour that you're describing used to work because we didn't directly validate the `axis`; `ak.is_none(array, axis=100)` also succeeds. 

I assume what we want to do here is check that the axis is below `minmax_depth[1]`. I am not sure whether this applies to all awkward functions; it seems off the top of my head that we sometimes would want to stop at the branch for some functions.

As for (2), I have not yet taken a look :)

**Comment by jpivarski** [comment]
What all Awkward functions are supposed to do with `axis=-1` (or any negative `axis`) is count from the bottom, up from any records or unions (any branching). So `axis=-1` has a different meaning for each field when the fields are different depths.

The reason why I'm saying this one is wrong is because `axis=-1` didn't let you address the innermost depth of one of the fields.
