### ISSUE TITLE
Ensure all release documentation is up-to-date

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1916]
### Version of Awkward Array

main

### Description and code to reproduce

When we release 2.0.0, we will need to be confident that our documentation and contributing guides are up-to-date. We should _explicitly_ check the following (and anything else that people remember, please edit this issue)

- [x] README.md
- [x] CONTRIBUTING.md
- [x] documentation
- [x] docstrings

**Comment by jpivarski** [comment]
Jim will take CONTRIBUTING.md and README.md and moving the list of talks from README to QuickStart.

Angus: "Loopy and unloopy programming tchniques" typo.

**Comment by jpivarski** [comment]
The [wiki](https://github.com/scikit-hep/awkward/wiki) is done.

I still need to do README.md and CONTRIBUTING.md.
