### ISSUE TITLE
ak.to_json/ak.from_json should be revamped/organized for v2

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#192]
How can we get the C `FILE` object from a Python file?

This will also require a new function in the `_io` module.

**Comment by jpivarski** [comment]
The same could be said of ak.tojson: it takes a string to be a file name, not a `FILE`.

**Comment by martindurant** [comment]
Ideally there should be a path to use arbitrary python file-like objects, not just C-files. I understand that might come with quite a performance penalty for local files, and you might  want to split the loading code.

**Comment by jpivarski** [comment]
In that case, I guess it would be using the RapidJSON function that converts to strings; that would be the "performance penalty." It must also be possible to convince RapidJSON to output an iterable of strings (that can be consumed in a memory-efficient way by Python), but I haven't delved into it.

**Comment by martindurant** [comment]
It is a general point though - I would love to see all of the IO work for remote file-systems via python. That will often amount to processing in-memory bytes objects, but hopefully can use the existing read-block API to avoid having to hold entire files in memory.

**Comment by jpivarski** [comment]
Maybe the right place to do it is in ChunkedArray (issue #56, which is soon-to-do on my list).

Awkward0 had a ChunkedArray, and it's been causing problems in people's analyses because it's not correctly implemented for all methods. Making it a `Content` type like everything else (i.e. that can be nested anywhere) was too ambitious, and it only really makes sense to have chunkability at the root and leaves of the tree. At the root, you get partitioning for parallel processing, and at the leaves, you get paging for I/O systems.

My plan is to add ChunkedArray at the root (an alternative NumpyArray for chunked leaves would be left for indefinitely later: paged I/O is good, but you can usually concatenate all of those 1-d arrays before using them in an analysis). Since this defines the partitioning, it might not be necessary to also iterate over chunks of JSON output because each chunk of a ChunkedArray can be written to JSON in its entirety and that's the chunked stream.

If the system wants the sequence of JSON chunks to collectively form a single JSON, that just means replacing the last `]` with `,` and the first `[` with nothing...

**Comment by martindurant** [comment]
> If the system wants the sequence of JSON chunks to collectively form a single JSON, that just means replacing the last ] with , and the first [ with nothing...

(or a line terminator, since line-deliminated JSON is extremely common)

**Comment by jpivarski** [comment]
For future reference:

   * The many-JSON case is done in #543. They can be separated by a line terminator, though they don't have to be (JSON syntax defines its own end-of-object).
   * Passing in a Python object with a `read` method has not been done.

Such an implementation should not read in the whole file and pass it as a string to the existing method—it should read in the data and let RapidJSON parse it in small steps. That's fine: the SAX-like interface and StringStream that we're already using from RapidJSON is well-suited to this style of interface.

What it would take for the latter: a variant of `do_parse`

https://github.com/scikit-hep/awkward-1.0/blob/68087850eabafd39f0c0de37ed96487fa44cc69f/src/libawkward/io/json.cpp#L662-L704

that repeatedly calls `reader.Parse` without erroring out if the parsing is not done for a given batch of string data and a variant of `rj::StringStream` in

https://github.com/scikit-hep/awkward-1.0/blob/68087850eabafd39f0c0de37ed96487fa44cc69f/src/libawkward/io/json.cpp#L706-L716

that is configured to call the Python object's `read` function for data. Such a thing would use pybind11, so it belongs in the `src/python` directory. (References to pybind11 are not allowed in the `src/libawkward` codebase.) There are other objects like this, which are called from `src/libawkward` but defined in `src/python`, such as the `PyArrayGenerator` and `PyArrayCache` in https://github.com/scikit-hep/awkward-1.0/blob/main/src/python/virtual.cpp . We use a Java-like interface: abstract class in `src/libawkward`, concrete class in `src/python`.

**Comment by jpivarski** [comment]
I'm expanding the scope of this old issue to be the `ak.to_json`/`ak.from_json` work that's needed for v2. There are several functions that need to become options in a single interface.
