### ISSUE TITLE
`pytest -n 8 tests` segfaults about 10% of the time on MacOS

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1929]
### Version of Awkward Array

HEAD

### Description and code to reproduce

While testing on MacOS, I've been using

```bash
pytest -n 8 tests
```

to run the tests quickly, but occasionally (~10% of the time), there are 9 segfaults:

```
FAILED tests/test_1374-to-rdataframe.py::test_two_columns - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
FAILED tests/test_1374-to-rdataframe.py::test_two_columns_as_rvecs - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
FAILED tests/test_1374-to-rdataframe.py::test_two_columns_as_vecs - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
FAILED tests/test_1374-to-rdataframe.py::test_two_columns_transform_filter - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
FAILED tests/test_1374-to-rdataframe.py::test_jims_example1 - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
FAILED tests/test_1625-multiple-columns-from-rdataframe.py::test_rdata_frame_rvecs_as_records - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
FAILED tests/test_1781-rdataframe-snapshot.py::test_data_frame_integers - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
FAILED tests/test_1781-rdataframe-snapshot.py::test_data_frame_vec_of_vec_of_real - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
FAILED tests/test_1829-to-from-rdataframe-bool.py::test_filters_as_well - cppyy.ll.SegmentationViolation: vector<string> ROOT::RDF...
```

I've only seen this on MacOS, not Linux. My ROOT version is

```
% root --version
ROOT Version: 6.26/06
Built for macosxarm64 on Aug 07 2022, 00:21:00
From @
```

from conda-forge. I'm a little worried about the installation because I tried uninstalling `root` and `root_base`, and yet `import ROOT` still worked... which is weird...

I'm labeling this as `bug (unverified)` because if @ianna can't reproduce it, we'll blame my conda installation and I'll try to reinstall that from scratch (and see if it's still there). Once you reproduce it, @ianna, you can change the label to `bug`. Note: this is not a `next-release` priority, since fixing it won't change the public API.

**Comment by agoose77** [comment]
Does this happen only in the latest `main` versions? I.e., can we narrow a commit, or is it a longstanding issue?

Incidentally, I also noticed the `SystemError` failure to raise that happens in one of the RDF tests. I recall you mentioning it before, Jim. It's not related to this issue, but I thought I'd include it here.

**Comment by ianna** [comment]
@jpivarski - Unfortunately, I cannot reproduce it. My environment has the following ROOT:
```
(my-ppp-talk) yana@iannas-macbook-pro-2 awkward % python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:43:44) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> ROOT.__version__
'6.26/06'
```
and 
```
% root --version
ROOT Version: 6.26/06
Built for macosx64 on Aug 06 2022, 09:12:00
From @
```

**Comment by jpivarski** [comment]
Even if you run the tests some 10 to 20 times? I found it to be intermittent, and I agree with @agoose77 that the "DID NOT RAISE SystemError" on Linux seems to be happening about as often and in the same places as the segfault on MacOS.

**Comment by jpivarski** [comment]
I ran

```
pytest -n 8 tests/*rdataframe*.py
```

13 times and no segfault, on a Mac, so I'll close this issue now.
