### ISSUE TITLE
`type_to_form` returns non-JSON string in case of error

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1932]
### Version of Awkward Array

main

### Description and code to reproduce

When using the `RDataFrame` integration, users attempting to work with unsupported column types see a cryptic error message. This occurs because `type_to_form` returns the string `"unsupported type"` for unsupported types, which then triggers an exception when Awkward attempts to call `json.loads` on the generated form.

Could we use `std::variant` here to catch the error case?

**Comment by agoose77** [comment]
@jpivarski is this next-release? It's a *new* feature, with a hard-to-decode error message for unsupported use, so I'm 50-50 on it

**Comment by jpivarski** [comment]
No, this issue is not about changing the API of the RDataFrame bridge, it's about fixing a bug.

The touchstone is, "Could someone's workflow start to depend on this, and then they'd have to adjust when we fix it?" I think it's pretty clearly "no" in this case.

**Comment by agoose77** [comment]
:partying_face: less work! I'm _all_ about the principle of least action.

For clarity; I was trying to gauge our pain threshold for the first release.
