### ISSUE TITLE
`array['x'] = 1` raises an `AttributeError`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#1936]
### Version of Awkward Array

main

#### Replacement with scalar
Replacing with an array with a scalar throws an `AttributeError`

```python
array = ak.Array({
    "x": [1, 2, 3]
})
array['x'] = 4
```

It seems that this also fails in `1.10.0`.

This should be an easy fix, and I think it should be next release as it is fairly fundamental.

#### Replacement with array
Replacing with an array doesn't broadcast, but adding a new field with an array does.

```python
array = ak.Array({
    "x": [1, 2, 3]
})
array['x'] = [1]
array["x"]
```

I'm currently working on docs, so I'm filing the issues I find here in the mean time.

**Comment by agoose77** [comment]
Relatedly, setting `array['x'] = [1]` does _not_ broadcast against the existing value of the array: 
```python
>>> array['x'] = [1]
>>> array.show()
[{x: 1}]
```

This doesn't match the behavior for a bare NumPy array:
```python
>>> x = np.arange(3)
>>> x[:] = 1
>>> x.tolist()
[1, 1, 1]
```

I'm not actually sure whether it's clear cut that this is wrong, though; the in-place assignment `x[:]` is not the same as the direct assignment. So, perhaps this is just policy. 

That said, if we have multiple fields, then the result does broadcast, so I'm inclined to say that it should always broadcast (and not change length):
```python
>>> array['y'] = array.x
>>> array['x'] = [1]
>>> array.show()
[{y: 1, x: 1},
 {y: 2, x: 1},
 {y: 3, x: 1}]
```

**Comment by jpivarski** [comment]
Yes, this only applies to assigning a new field whose name is the same as an existing field. If different names are used,

```python
>>> array = ak.Array({
...     "x": [1, 2, 3]
... })

>>> array["y"] = 4
>>> array.show()
[{x: 1, y: 4},
 {x: 2, y: 4},
 {x: 3, y: 4}]

>>> array["z"] = [1]
>>> array.show()
[{x: 1, y: 4, z: 1},
 {x: 2, y: 4, z: 1},
 {x: 3, y: 4, z: 1}]
```

I think the proper behavior for setting a new column with the same name as an old column is to broadcast (as above) but replace the old column. So, it would work like this:

```python
>>> array = ak.Array({
...     "x": [1, 2, 3]
... })

>>> array["x"] = 4
>>> array.show()
[{x: 4},
 {x: 4},
 {x: 4}]
```

What's preventing that from happening is probably just the order of operations in the implementation. We want to first use the original to broadcast, and then remove the old column, and then add the new column. (Maybe those last two steps are a single assignment.)

But that makes this a straightforward bug and not an API-changing issue. (The old behavior is "wrong.")

**Comment by agoose77** [comment]
> I think the proper behavior for setting a new column with the same name as an old column is to broadcast (as above) but replace the old column. So, it would work like this:

Agreed, this is also my feeling.

So, we have _two_ bugs here (although both would be solved with broadcasting, so likely the same cause). I'll update the issue
