### ISSUE TITLE
ak.choose MUST be renamed, maybe ak.cross, too

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#199]
NumPy has an [np.choose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.choose.html) function and it's something that could conceivably be NEP18-overloaded someday. Awkward can't have an [ak.choose](https://awkward-array.readthedocs.io/en/latest/_auto/ak.choose.html) function that does something different, or we'd never be able to overload NumPy's (and it would be confusing to users, anyway).

Perhaps the right name is "combinations", since [itertools.combinations](https://docs.python.org/2/library/itertools.html#itertools.combinations) is exactly what our function does. Moreover, the `diagonal=True` option should probably be "replacement" because [itertools.combinations_with_replacement](https://docs.python.org/2/library/itertools.html#itertools.combinations_with_replacement) (too long of a name, in my opinion) is exactly what that option does.

On a similar note, perhaps [ak.cross](https://awkward-array.readthedocs.io/en/latest/_auto/ak.cross.html) should become "product" because then we'd be consistently getting our names from itertools: [itertools.product](https://docs.python.org/2/library/itertools.html#itertools.product). I'm a little afraid that "product" would be confused with multiplication—in particular, ak.prod (so named because of [np.prod](https://docs.scipy.org/doc/numpy/reference/generated/numpy.prod.html)).

Thoughts? I'm asking everyone who's had opinions on Awkward naming before: @HDembinski, @henryiii, @nsmith-, @masonproffitt, @eduardo-rodrigues, @chrisburr, @lgray, @ianna, @lukasheinrich...

I need to pick a final name before I do a tutorial on April 8, which will definitely include combinatorics. At that point, the names would be "out in the wild" and much harder to change again.

**Comment by nsmith-** [comment]
`ak.combinations` is fine by me, I originally picked `choose` as it is N-choose-k which gives the number of combinations and is slightly shorter, but sadly numpy has stole our name.  For `cross`, how about `ak.cartesian_product`? I might consider this acceptable verbosity since anyway `cross` can be implemented using broadcasting tricks.

**Comment by lgray** [comment]
I think ak.cross -> ak.outer should work well (np.outer is ak.cross for rectilinear data structures).

ak.choose -> ak.combinations is fine to me and very clear. I like the connection to itertools.

**Comment by jpivarski** [comment]
> I think ak.cross -> ak.outer should work well (np.outer is ak.cross for rectilinear data structures).

[np.outer](https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html) doesn't make tuples; it actually multiplies, so it's different. itertools.product, however, makes tuples.

**Comment by lgray** [comment]
Ah - true it really is the product. I think in the same style, `ak.cartesian` should work well, as Nick was suggesting. I don't think we need to add `_product` onto everything.

**Comment by jpivarski** [comment]
We're back from the GitHub outage! I'm thinking of going with

   * `choose` → `combinations`
   * `diagonal` → `replacement`
   * `cross` → `product`

The first two seem pretty uncontroversial, and for the third, we have to decide between

   * confusing `product` with multiplication (maybe tab-complete would show that there's both `prod` and `product`?)
   * lack of symmetry with combinations/getting names from itertools. (Sorry, Descartes.)

Thanks for the super-informal survey. I think I'll wait on closing that PR until tomorrow, in case there are any other comments, but I want to be ready to press "go" if it's fine.

**Comment by jpivarski** [comment]
I'm making a few more last-minute renamings on #201 in case anyone would like to chime in. Speak now...

**Comment by jpivarski** [comment]
I will merge all the name changes enacted in #201 tomorrow unless somebody complains.

**Comment by chrisburr** [comment]
> confusing product with multiplication (maybe tab-complete would show that there's both prod and product?)

I think this is perfectly acceptable:
* In my opinion `prod` and `product` do the "obvious" thing once you know `awkward1` is aiming to copy `itertools` and `numpy`
* It's unlikely that using the wrong one would give a sensible result

**Comment by masonproffitt** [comment]
+1 for `ak.cartesian()`, following the style of `np.dot()`, `np.inner()`, `np.outer()`, and `np.kron()`. I agree that `combinations` and `replacement` seem perfectly fine.

**Comment by jpivarski** [comment]
It is possible for `ak.product` and `ak.cartesian` to both exist as synonyms (a fact that, if suspected, is easily checked if one of them `is` the other). I'm holding out the possibility that `ak.tolist` will someday be added as a synonym for `ak.to_list`. In that case, the question is whether `ak.product` would exist first with the option to add `ak.cartesian` or vice-versa.

(I'm not going to add synonyms right away because they're easy to add and hard to remove. Only if there's a large number of people who want it, after the library has been in use for a while.)

So instead of asking who's in favor of `ak.cartesian`, is anyone against `ak.product`? Is the existence of that function a problem that later adding an `ak.cartesian` synonym wouldn't fix?

**Comment by lgray** [comment]
I think `ak.product` is too close to `ak.prod`, in letter space and that makes them want to be close in concept space. If some one just types 'product' programming away they're probably gonna expect multiplication first, if they're coming from numpythonic background. It will make sense to itertools users, but that might not be the largest cross section of people this package encounters.

`ak.cartesian` at least has that first level of "what exactly do they mean by cartesian??",  and it'll show up quickly when searching in the repository for functions.

**Comment by jpivarski** [comment]
How does everyone else feel if I make it `ak.cartesian` first with the option of possibly later adding `ak.product`? With `ak.cartesian` being first, this also means that all the documentation and tutorials will say `ak.cartesian`, leading users in that direction. There would also be some resistance against adding a synonym for the reason Lindsey described, and just because synonyms are hard to get rid of.

I personally preferred agreement with itertools, but I'm willing to go with majority opinion (as I was with the [underscores between words](https://github.com/scikit-hep/awkward-array/issues/240) and the [80-character width](https://github.com/scikit-hep/awkward-1.0/pull/183) if the community is clear).

**If I don't hear a complaint,** I'll change `ak.product` to `ak.cartesian`. **If there isn't consensus,** I will leave it as `ak.product` (because I get the deciding vote if the community's opinion isn't strongly one way).

**Comment by jpivarski** [comment]
It sounds like everybody's okay with `ak.cartesian` and some are actively for it. I'll change to `ak.cartesian`; that will be the primary (and probably only) name for this function.

**Comment by jpivarski** [comment]
Going, going, gone!

(It's `ak.cartesian`.)
