### ISSUE TITLE
Trying to get a non-standard entry in awkward array gives an error (code worked in 1.X.X)

### ISSUE THREAD

**Issue by thoglu** [scikit-hep/awkward#2006]
### Version of Awkward Array

2.0.0

### Description and code to reproduce

I have an awkward array where one field is of non-std (string) type. I have it saved in a parquet file, load up the array in awkward (with from_parquet), and query the first item with arr[*field_name*][0] .. it produce the following errror
`site-packages/awkward/highlevel.py", line 1751, in __getitem__
    return ak._util.tobytes(out.raw(numpy)).decode(
AttributeError: 'NumpyArray' object has no attribute 'raw'. Did you mean: '_raw'?`

*edit*: I check to change raw into _raw and that seemd to work... does version 2.0.0 require an older numpy version, or is this an internal command?

**Comment by jpivarski** [comment]
This is #1993, which is now fixed and waiting to get into a release. To make that `awkward` release, we'll need to make an `awkward-cpp` release first, and that's waiting on #1904 and #2001.

So it's in the pipeline!
