### ISSUE TITLE
Checking isinstance of a Protocol is slow

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#2028]
### Version of Awkward Array

2.0.2

### Description and code to reproduce

In a profiling run of a coffea processor with awkward2 (eager mode) I found that 20% of the time was spent in the following line:
https://github.com/scikit-hep/awkward/blob/7e6f504c3cb0310cdbe0be7b5d662722ee73aaa7/src/awkward/contents/content.py#L94
![image](https://user-images.githubusercontent.com/6587412/209037377-c6ad3e62-7349-470c-a340-d0dd223f0a90.png)
This instance check would normally be very fast but I suspect because the type is a `@runtime_checkable` protocol, it is doing more work.
https://github.com/scikit-hep/awkward/blob/7e6f504c3cb0310cdbe0be7b5d662722ee73aaa7/src/awkward/_backends.py#L42-L45

Perhaps there is a way to have it first check the class `__mro__` and then fall back to the protocol?

If this time is removed from the profile, the remaining time is in line with what I get running the same processor in awkward 1.

**Comment by agoose77** [comment]
> I found that 20% of the time was spent in the following line:

Wow, that's particularly slow. 

> Perhaps there is a way to have it first check the class __mro__ and then fall back to the protocol?

Internally, we probably mostly care about protocol invariants being satisfied rather than inheritance trees, but as we need to type-check the external inputs, we're always going to need something like this in our layout constructors.

Thankfully, we can probably just forgo the protocol entirely here; protocols are super useful. But this is an internal abstraction that we don't want people to bring their own classes to, so it might even make sense to require that a backend is a subclass.

**Comment by agoose77** [comment]
@nsmith- would you be able to test [this PR](https://github.com/scikit-hep/awkward/pull/2029)? 

The instructions for installing from a branch are [here](https://github.com/scikit-hep/awkward#installation-for-developers).

You'll only need `git`, `python`, and `nox` binaries in your `PATH` (or `pipx run nox`).

**Comment by nsmith-** [comment]
I tested it and can confirm the time has essentially vanished. Here is the same call:
<img width="719" alt="Screen Shot 2022-12-22 at 10 19 04 AM" src="https://user-images.githubusercontent.com/6587412/209177232-db65d120-0904-4ac9-9a2f-dd12e5ac9bb0.png">
now taking a total of 100ms in the program vs. previously 7.4s. This is a sampling profiler so the 100ms should come with a healthy uncertainty bar--it may even be less.

**Comment by agoose77** [comment]
Fantastic! Thanks for filing the report.

**Comment by jpivarski** [comment]
> a total of 100ms in the program vs. previously 7.4s

Wow. Yeah, that was necessary. I guess the reason is that it's in the constructor of every layout node instance, and those are created quite often.
