### ISSUE TITLE
Simplify min/max by another quantity through wrapper functions

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#203]
[The technique described here](https://nbviewer.jupyter.org/github/jpivarski/2020-04-08-eic-jlab/blob/master/2020-04-08-eic-jlab-EVALUATED.ipynb#Reducing-from-combinations) works and is fully general, but confusing and more intricate than a data analyst should have to deal with when they just want to min/maximize by some parameter.

Perhaps there should be a `ak.minby` and `ak.maxby` pair to do all the steps, though this means that an index derived from one collection can't be used multiple times. Maybe `ak.pick`, which takes output from `ak.argmin`/`ak.argmax`. Maybe it should have a similar status to `ak.mask` in having a method as well:

```python
array.pick[ak.argmax(array.pt)]
```

like

```python
array.mask[array.pt > 5]
```

**Comment by jpivarski** [comment]
This is a "good first issue" because it's pure Python, wrapping up the singleton/firsts business in the advanced part of this tutorial:

https://github.com/jpivarski/2020-04-08-eic-jlab#readme

into a more convenient function. I'm favoring the `array.pick[...]` approach, which would use `ak.singletons` to expand the output of `ak.argmax` into the right form for jagged integer indexing, and then the result of that would be passed through `ak.firsts` to produce the result.

This is all done manually in the demo, making "select one jagged array by the maxima of another" seem more complicated than it is. The higher-level function would wrap up that technique in an easy-to-use interface.

**Comment by jpivarski** [comment]
@nsmith- I don't know about `array.pick[...]` anymore. It does seem to be more general than specialized `ak.minby` and `ak.maxby`, but is it how a user would expect to do things?

**Comment by nsmith-** [comment]
Honestly, give the discussion in #434 and elsewhere it seems clear we want `minby` and `maxby` because we keep talking about it :)
Something something desire path...

**Comment by jpivarski** [comment]
`ak.minby`/`ak.maxby` is more guessable, certainly if you see it in a list or set of tab-completions.

**Comment by agoose77** [comment]
Can we close this now that we have `keepdims`? It's not perfect (it requires the original array to be entirely jagged), but that might be a separate issue.

That said, I *do* think we want something like `.pick` to force Awkward indexing. I'm also not against something like adding `axis=None` to `ak.from_regular` to convert an arg into a fully jagged array, but that might be a separate API improvement to making Awkward indexing. 

For posterity, I do a reasonable amount of work with mixed regular and jagged arrays, and have written a helper `make_jagged` to ensure that index arguments behave as Awkward does. Finding a way to make this nicer would be useful :)

**Comment by jpivarski** [comment]
Although there's a way to do it (using `keepdims`, which actually had been there from the beginning, but I didn't recognize that they solved this problem until @nsmith- pointed it out), although there's a way to do it, it's not easy to discover. The other things talked about in this issue, `array.pick` or more simply `ak.minby` and `ak.maxby`, are still potentially useful.

And actually, if we take the `ak.minby`, `ak.maxby` route, they would be simple implementations, a good-first-issue. On the other hand, if a user learns it this way, they'll have even less chance of discovering the route of integer arrays, and will probably end up re-computing the selector a hundred times to apply it to a hundred arrays. (Adding a convenient `cut` argument to [uproot.TTree.arrays](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TTree.TTree.html#arrays) has led to the impression that this is the _only_ way to apply cuts, and people have developed some illegible and inefficient workflows to force all their cuts into this string-valued argument.)

Maybe we should just close it because it's borderline and we have so many open issues. Okay, I'll do it.
