### ISSUE TITLE
TypeError when introspecting ak.highlevel.Record

### ISSUE THREAD

**Issue by swang373** [scikit-hep/awkward#205]
I see the following TypeError when calling `dir()`  on instances of `ak.highlevel.Record`:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-fb278c25e68f> in <module>
----> 1 dir(rec)

~/miniconda3/envs/awkward/lib/python3.8/site-packages/awkward1/highlevel.py in __dir__(self)
   1620         that can be accessed as attributes.
   1621         """
-> 1622         return sorted(set(dir(super(Array, self))
   1623                           + [x for x in self._layout.keys()
   1624                                if _dir_pattern.match(x) and

TypeError: super(type, obj): obj must be an instance or subtype of type
```

I can reproduce the exception by running the following snippet on:
* macOS 10.15.4, Python 3.8.2, awkward1==0.2.10
* Ubuntu 18.04, Python 3.7.4, awkward1==0.2.10

```python
import awkward1 as ak

# Introspecting the class is fine
dir(ak.highlevel.Record)

rec = ak.from_iter({
    'numbers': [1, 2, 3],
    'letters': ['a', 'b', 'c'],
})

# Introspecting an instance raises TypeError
dir(rec)
```

The traceback leads me to the implementation of `Record.__dir__`:
https://github.com/scikit-hep/awkward-1.0/blob/8215351f09de3773b14318815538ec0faaeb6235/src/awkward1/highlevel.py#L1617-L1625

I think the issue can be fixed by changing the first argument in the call to `super()` from Array to Record, but in case I'm not seeing something I defer to the authors on what the passed type should be.

**Comment by jpivarski** [comment]
I think you're right: this is a copy-paste error. I checked for additional errors of the same kind, but didn't find any. If this passes CI, I'll release a new bugfix version.

Thanks!

**Comment by swang373** [comment]
Thanks, Jim! A votre santé 🍻
