### ISSUE TITLE
`ak.ArrayBuilder` loses data when initalising builder outside of Numba

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2053]
### Version of Awkward Array

main

### Description and code to reproduce

The following reproducer does not preserve values set outside of Numba:

```python3
import awkward as ak
from numba import njit


@njit
def func(builder):
    builder.begin_record()
    builder.field("time").real(2.0)
    builder.end_record()
    return builder


builder = ak.ArrayBuilder()
builder.begin_record()
builder.field("time").real(0.0)
builder.end_record()

func(builder)

builder.begin_record()
builder.field("time").real(5.0)
builder.end_record()

print(builder.snapshot())

```

### Observations
This only seems to happen if the record is not given a name AND if the Python `ak.ArrayBuilder` operations occur before the njitted function.

**Comment by agoose77** [comment]
Calling `field_check` instead of `field_fast` from Numba fixes this bug, so I'll take a look over there.

**Comment by agoose77** [comment]
I think this is the same problem as #2054.

The fast field optimisation means that upon the second `field()` call (the one in the jitted function), the array already has length 1, and yet does not match any field pointers (because they come from different memory "pools"). This is considered the "row 1 and row 2 have different fields" scenario, and so the option type is added. I presume that when `to_buffers()` is called, `keys_` then has two identical field names, which is not expected / supported.

If we assume that the performance bottleneck is finding an existing field rather than adding new ones (which should hold given that records are not supposed to be wide), perhaps we can extend the pointer test mechanism. We don't need it to function outside of Numba, so perhaps:
1. The non-fast API sets the string pointers to `nullptr`
2. The fast API interprets `nullptr` as "this needs to be set".

Then, if the fast-path finds no matching fields, it can walk over the non-`nullptr` pointers and perform a `strcmp`. This should be fast-enough, as it is not linear in the fields (it walks over each field until a match, but it does not test each field with `strcmp`).

**Comment by jpivarski** [comment]
The difference in performance between `field_check` and `field_fast` (as between `beginrecord_check` and `beginrecord_fast`) has never been quantified; it is not known whether this is an important optimization or not. If switching to the `_check` versions of these functions fixes everything, that would be a quick fix, leaving the study of `_check`-vs-`_fast` as a future, optional optimization study.

The use of ArrayBuilder at all is already a performance bottleneck compared with other ways of producing arrays from compiled code. The particular step of whether strings are deeply compared or not might not be a leading one anyway.

On this subject, some of the `*Builder` subclasses still inherit from `std::enable_shared_from_this`, which was needed when they had `std::shared_ptrs`, but now they're based on `std::unique_ptrs`. I'm pretty sure `std::enable_shared_from_this` is now unnecessary, and I _do not know_ whether it matters for performance, or how it compares with the `_check`-vs-`_fast` distinction. (C++ might be inserting something to enable "shared from this" that slows down indirection. After all, why else would this feature be optional?)

So the short story is, don't go out of your way to harmonize `_check`-vs-`_fast` if switching everything to `_check` would be a quick fix. The `_fast` is not known to be valuable.
