### ISSUE TITLE
release tarball is missing files

### ISSUE THREAD

**Issue by veprbl** [scikit-hep/awkward#207]
The current release tarball
https://files.pythonhosted.org/packages/24/81/9798b934e4c9313abb5d4ffe8af86f7a5cf87eb873de463b294813518eea/awkward1-0.2.11.tar.gz
is missing requirements-docs.txt and requirements-dev.txt, which are still required by setup.py

**Comment by jpivarski** [comment]
Thanks for pointing this out! I'll be pushing a version 0.2.12 soon; that one should be okay.

By the way, is there a reason you're compiling from source? What combination of OS and Python version do you have—is it failing to find a binary wheel for you?

**Comment by jpivarski** [comment]
When [this build](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=1801&view=logs&j=4a2b32f2-8889-5075-9c47-2644e2b42452) is done, version 0.2.12 will be [on PyPI](https://pypi.org/project/awkward1/).

**Comment by veprbl** [comment]
@jpivarski I maintain `awkward1` in nixpkgs https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/awkward1/default.nix , was trying to bump the version to see if it fixes the tests.

**Comment by veprbl** [comment]
The failure I am dealing with right now:
https://hydra.nixos.org/job/nixpkgs/trunk/python37Packages.awkward1.x86_64-linux

My last time I bisected the problem to find that https://github.com/NixOS/nixpkgs/commit/aecc14b52b08b59f57595a9968cf22def0f9bb7b was where awkward1 first broke for us.

**Comment by jpivarski** [comment]
You will have to bump the Awkward version number: 0.1.38 will not work on recent versions of Numba.

   1. Early this year, Numba changed the name of the `numpy_arange_1` function, which they considered not part of the public API. I was using it, it broke, and I adjusted. (I can't easily find the version where I fixed it, but that's moot for reasons below.)
   2. I [showed how I was using Numba's API](https://github.com/scikit-hep/awkward-1.0/blob/master/docs-demo-notebooks/2020-01-22-numba-demo-EVALUATED.ipynb) on January 22, 2020, including a list of all the functions I'm using. Not all of them had been declared as public API.
   3. This prompted [Numba to do a survey](https://github.com/numba/numba/issues/5214) of who is using what in their Numba extensions.
   4. They used this information to reorganize their libraries into more clearly defined public and private.
   5. Meanwhile I [completely rewrote my Numba extension](https://github.com/scikit-hep/awkward-1.0/pull/118), using what I had learned from their feedback. Not a single line of the original exists—trying to get Awkward 0.1.38 to work is not useful.
   6. With the new Numba extensions API, the names are different again. When [Numba 0.49](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/U9ijrsVU6eU) is no longer a release candidate, that will become the minimal version Awkward will accept.
   7. PR #189 is waiting for Numba 0.49 to become a regular release; when it does, I'll be ready with the new names. Until then, I should keep using the old names.

**Comment by jpivarski** [comment]
Awkward 0.2.12 is [on PyPI](https://pypi.org/project/awkward1/). Does it work for you?

**Comment by veprbl** [comment]
> Awkward 0.2.12 is [on PyPI](https://pypi.org/project/awkward1/). Does it work for you?

Yes, this issue is resolved by 0.2.12. Thank you!

> You will have to bump the Awkward version number: 0.1.38 will not work on recent versions of Numba.

I've pushed a bump to 0.2.12, and it seems to work fine on linux. However I still get errors on macOS
https://gist.github.com/veprbl/60e1ffb1374a5ae617651ef57675d320
Looks like some RTTI problem.

**Comment by jpivarski** [comment]
What is RTTI? I don't recognize this "missing boxer for subtype..." error.

**Comment by veprbl** [comment]
@jpivarski 
https://en.wikipedia.org/wiki/Run-time_type_information
https://github.com/scikit-hep/awkward-1.0/blob/7bf1434f28fdb669a0e1cc4fbd1c11aa840458d3/src/python/layout/content.cpp#L122

**Comment by jpivarski** [comment]
Thanks for finding it—I didn't recognize my own error message. (I was searching the web for it!)

So it looks like `dynamic_cast` will always fail if the compiler has RTTI disabled, and that's probably what's happening here. I'm looking into ways of ensuring that RTTI is always enabled in CMake. In my continuous integration, it's apparently enabled in all three systems: Linux, MacOS, and Windows.

Would you be able to test from a GitHub branch? It would be time-consuming to have to push PyPI versions just to find out if a compiler option is on. (Thanks!)
