### ISSUE TITLE
Pickle of array includes `array.__class__`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2106]
### Version of Awkward Array

main

### Description and code to reproduce

This might not be ideal; we'd prefer e.g. that behaviours defined in Awkward aren't included in the pickle explicitly.

**Comment by agoose77** [comment]
I think we want to use `__reduce__` for this, rather than `__getstate__`.

**Comment by agoose77** [comment]
@jpivarski can we be sure to hold the Python release until this issue has been fixed? Can do it today, later.

**Comment by jpivarski** [comment]
Okay. I'll put it at the end of the queue and check on it when I get there.
