### ISSUE TITLE
typeinfo mismatch in separate Python extension modules that both produce Awkward Arrays

### ISSUE THREAD

**Issue by veprbl** [scikit-hep/awkward#211]
This issue is to document test failure reported in https://github.com/scikit-hep/awkward-1.0/issues/207#issuecomment-612451163 . From the looks of it, this is an instance of https://github.com/pybind/pybind11/issues/912.

### Context
Everything presented here is done with MacOS 10.14 + nixpkgs (5c72e8416984879bd7bd884a392b7c915c28171a).
```
# clang -v
clang version 7.1.0 (tags/RELEASE_710/final)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /nix/store/xbd074qa4p62sjbcmkvbzrb1d4zcj79n-clang-7.1.0/bin
# ld -v
@(#)PROGRAM:ld  PROJECT:ld64-450.3
BUILD 08:28:49 Apr  2 2020
```

The following options are unset, which, I guess, is the default.
```
_LIBCXX_DYNAMIC_FALLBACK
_LIBCPP_HAS_NONUNIQUE_TYPEINFO
_LIBCPP_NONUNIQUE_RTTI_BIT
```

dlopen flags:
```
>>> import sys; sys.getdlopenflags() == os.RTLD_NOW
True
```

### Steps to reproduce
```
>>> import awkward1; awkward1.from_json("[1,2,3]", highlevel=False)[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: missing boxer for Content subtype
```

### Analysis
What happens under the hood is `awkward1.from_json` is calling into `awkward1._io.fromjson`
https://github.com/scikit-hep/awkward-1.0/blob/77c3e7ff7304734f7e917c9223adf473eace521b/src/awkward1/operations/convert.py#L418
which allocates an instance of ak::NumpyArray:
https://github.com/scikit-hep/awkward-1.0/blob/77c3e7ff7304734f7e917c9223adf473eace521b/src/libawkward/builder/Int64Builder.cpp#L61-L68
one part I don't understand is how it is able to return ak::Content:
https://github.com/scikit-hep/awkward-1.0/blob/77c3e7ff7304734f7e917c9223adf473eace521b/src/python/_io.cpp#L20-L25
Because pybind should not know about `ak::Content` as a python class without "awkward1.layout" which defines it in
https://github.com/scikit-hep/awkward-1.0/blob/77c3e7ff7304734f7e917c9223adf473eace521b/src/python/layout/content.cpp#L807-L810
When we call into `__getitem__` we definitely get into awkward1.layout
https://github.com/scikit-hep/awkward-1.0/blob/77c3e7ff7304734f7e917c9223adf473eace521b/src/python/layout/content.cpp#L570-L572
and that somehow is dispatched to `NumpyArray::getitem_at_nowrap` in the "awkward1._io" library. There it allocates another NumpyArray:
https://github.com/scikit-hep/awkward-1.0/blob/77c3e7ff7304734f7e917c9223adf473eace521b/src/libawkward/array/NumpyArray.cpp#L776-L783
That we then attempt to box (why do even need the box, didn't we just successfully return `ak::Content` from the `awkward1._io.fromjson`? what happens with the ownership of `content`?)
https://github.com/scikit-hep/awkward-1.0/blob/77c3e7ff7304734f7e917c9223adf473eace521b/src/python/layout/content.cpp#L12-L25
but "awkward1.layout" fails to recognise an instance of `NumpyArray` and finally fails:
https://github.com/scikit-hep/awkward-1.0/blob/77c3e7ff7304734f7e917c9223adf473eace521b/src/python/layout/content.cpp#L121-L124

Inspecting typeinfo for the classes I found that:
1. Both `typeid(*content.get()).name()` and `typeid(ak::NumpyArray).name()` have the same mangled typeinfo name "N7awkward10NumpyArrayE"
2. `typeid(*content.get()).hash_code()` differs from `typeid(ak::NumpyArray).hash_code()`
3. `typeid(*content.get()) != typeid(ak::NumpyArray)`

Now, in principle, some implementations may choose to compare type_info instances by comparing their names only. [1][2] I've tried enabling that, it has some interesting behaviour depending on the value of _LIBCPP_NONUNIQUE_RTTI_BIT. For small values (like 0xF) there is no apparent difference, for very large values it crashes in the dynamic loader, for an intermediate value I get an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.7/site-packages/awkward1/__init__.py", line 16, in <module>
    import awkward1.layout
ImportError: generic_type: type "IndexU8" is already registered!
```

There is also _LIBCXX_DYNAMIC_FALLBACK [3].

### Inspecting the symbols

The next logical step was to look for a duplicate symbol for the typeinfo for akward::NumpyArray. We first examine the object files to see if different typeinfo's are present in different translation units.

Using nm:
```
# find . -name "*.o" | xargs nm -o | grep N7awkward10NumpyArrayE | c++filt -_ | grep "typeinfo for aw"     
./_io.dir/src/python/_io.cpp.o:                  U typeinfo for awkward::NumpyArray
./layout.dir/src/python/layout/content.cpp.o:                  U typeinfo for awkward::NumpyArray
./awkward-objects.dir/src/libawkward/array/NumpyArray.cpp.o: 000000000002ce90 S typeinfo for awkward::NumpyArray
```

Or objdump:
```
# find . -name "*.o" | xargs objdump -tC | grep 'typeinfo for awkward::NumpyArray' 
0000000000000000 g       01 UND    00 0000 typeinfo for awkward::NumpyArray
0000000000000000 g       01 UND    00 0000 typeinfo for awkward::NumpyArray
000000000002ce90 g       0f SECT   08 0000 [.const_data] typeinfo for awkward::NumpyArray
```

This looks very reasonable - only one translation unit has an instance of the typeinfo. The undefined symbol in ./_io.dir/src/python/_io.cpp.o can be easily removed by dropping `make_fromroot_nestedvector`, but that doesn't help the problem.

Now we take a look at the final python libraries:

```
# find result/ -name "*.so" | xargs nm -o | grep N7awkward10NumpyArrayE | c++filt -_ | grep "typeinfo for aw"
result/lib/python3.7/site-packages/awkward1/layout.cpython-37m-darwin.so: 00000000004acf60 S typeinfo for awkward::NumpyArray
result/lib/python3.7/site-packages/awkward1/_io.cpython-37m-darwin.so: 0000000000205440 S typeinfo for awkward::NumpyArray
result/lib/python3.7/site-packages/awkward1/types.cpython-37m-darwin.so: 00000000002499e0 S typeinfo for awkward::NumpyArray
# find result/ -name "*.so" | xargs objdump -tC | grep 'typeinfo for awkward::NumpyArray' 
0000000000000000      d  20 GSYM   00 0000 typeinfo for awkward::NumpyArray
00000000004acf60 g       0f SECT   0d 0000 [.const_data] typeinfo for awkward::NumpyArray
0000000000000000      d  20 GSYM   00 0000 typeinfo for awkward::NumpyArray
0000000000205440 g       0f SECT   0d 0000 [.const_data] typeinfo for awkward::NumpyArray
0000000000000000      d  20 GSYM   00 0000 typeinfo for awkward::NumpyArray
00000000002499e0 g       0f SECT   0d 0000 [.const_data] typeinfo for awkward::NumpyArray
```

I assume, "GSYM" supposed to denote a global symbol, not sure how loader deals with the three available pieces.

This is how symbol tables look for the *.so files in the awkward1-0.2.12-cp37-cp37m-macosx_10_9_x86_64.whl:

```
# find . -name "*.so" | xargs nm -o | grep N7awkward10NumpyArrayE | c++filt -_ | grep "typeinfo for aw"      
./layout.cpython-37m-darwin.so: 0000000000443738 S typeinfo for awkward::NumpyArray
./_io.cpython-37m-darwin.so: 000000000020ee60 S typeinfo for awkward::NumpyArray
./types.cpython-37m-darwin.so: 0000000000245f80 S typeinfo for awkward::NumpyArray
# find . -name "*.so" | xargs objdump -tC | grep 'typeinfo for awkward::NumpyArray'                             
0000000000443738 g       0f SECT   0c 0000 [.const_data] typeinfo for awkward::NumpyArray
000000000020ee60 g       0f SECT   0c 0000 [.const_data] typeinfo for awkward::NumpyArray
0000000000245f80 g       0f SECT   0c 0000 [.const_data] typeinfo for awkward::NumpyArray
```

The problem is not seen with `python3` and `python3Packages.numpy` from nixpkgs and awkward from the wheel:
```
>>> import awkward1; awkward1.from_json("[1,2,3]", highlevel=False)[0]
1
```

### Summary

The problem itself seems to stem from having objects passed across multiple python libraries. Perhaps, it is triggered by some specific toolchain or libc++ version?

[1] https://reviews.llvm.org/D38599?id=118502
[2] https://dholmes215.github.io/c++/2017/06/30/fun-with-typeid.html
[3] https://github.com/llvm-mirror/libcxxabi/blob/master/src/private_typeinfo.cpp

**Comment by jpivarski** [comment]
Wow—this is incredibly detailed! Thanks!

In the pybind11 issue that you linked, there was a suggestion to set dlopen flags to `os.RTLD_NOW | os.RTLD_GLOBAL` instead of `os.RTLD_NOW` before loading the extension module. Does this work as a work-around?

In #209, I'm combining all of Awkward's extension modules into one, but this problem would reemerge for dependent projects written in C++ with Python interfaces on MacOS. Based on your description of the above, I think this would be a problem only when dependent project _produce_ arrays (though that's probably the more important use-case for dependent projects).

To answer your question,

> That we then attempt to `box` (why do even need the `box`, didn't we just successfully return `ak::Content` from the `awkward1._io.fromjson`?)

The motivation for `box` is that some outputs are not `Content` subclasses on the Python side. A zero-dimensional NumpyArray should become a Python number and `ak::None` should become Python None. I don't think JSON → Awkward for only a number or only JSON `null` are supported; if so, those cases would require a `box`.

On the other hand, maybe stronger boxing can protect the arrays across boundaries... In our design, these array nodes be immutable (#176 and #177) and are inexpensive to copy (compared to the array buffers). If this is a problem in the future, I could add a protocol to replace the `ak::Content` subclasses with generic objects (_not_ copying the buffers, but everything else), pass them over the boundary, and reconstruct `ak::Content` subclasses on the other side. Then each library—Awkward and its dependent projects—would each have its own private symbols, though each dependent project would have to know about this stronger boxing/unboxing protocol.

**Comment by ihnorton** [comment]
Cross-linking some discussion from the ITK library dealing with this issue a few years ago (it looks like you've already gone down much the same path in 209, but could help w/ the separate module issue here):

- https://insightsoftwareconsortium.atlassian.net/browse/ITK-3490 (esp the linked article:  http://www.russellmcc.com/posts/2013-08-03-rtti.html)
- https://review.source.kitware.com/%23/c/21805/7/
- https://review.source.kitware.com/%23/c/21755/6/

**Comment by veprbl** [comment]
> In the pybind11 issue that you linked, there was a suggestion to set dlopen flags to `os.RTLD_NOW | os.RTLD_GLOBAL` instead of `os.RTLD_NOW` before loading the extension module. Does this work as a work-around?

I did not check, but I believe it would work. Enabling `RTLD_GLOBAL` is bound to cause some obscure platform-dependent bugs in the future, so I don't think we need to investigate this.

**Comment by jpivarski** [comment]
I don't know how much of this is still valid, but since this looks most useful as a search result, I'm going to close it.
