### ISSUE TITLE
Singletons does not complete successfully on a typetracer

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2123]
### Version of Awkward Array

2.0.6

### Description and code to reproduce

Running `ak.singletons` on a typetracer (in particular this was a `_meta` is dask_awkward) results in:
```
E       AssertionError: bug in Awkward Array: attempt to set values of a TypeTracerArray
E       
E       See if this has been reported at https://github.com/scikit-hep/awkward-1.0/issues
```

**Comment by agoose77** [comment]
@lgray  can you provide a reproducer for this? It might be closed now? 🤞

**Comment by agoose77** [comment]
I think this has been fixed, so I shall close it :)
