### ISSUE TITLE
Support unknown lengths in `RegularArray` forms

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2161]
### Version of Awkward Array

main

### Description and code to reproduce

Although Dask might not end up needing this, it would be helpful to be able to represent unknown size information even if it can't be used for anything. We should move to using `None` for this instead of `unknown_length`, because that aligns with the Array API.

We should also merge `known_shape` and `known_length` into a single value, and update the `shape` type ifnormation. After this change, we'd likely need to coerce `unknown_scalar` to `None` in places that accept user input.

**Comment by agoose77** [comment]
@jpivarski right now `len(array)` fails in typetracer, because `len(x)` should always be an integer. I haven't seen any need for this feature, but I wanted to raise it anyway. 

I suppose `ak.num(x, axis=0)` does this, are happy to let that be the "safe" way to get an int-like object representing the length of a high level array?

**Comment by jpivarski** [comment]
Layouts, Indexes, and such have a `length` property, which differs from `__len__` in that it's allowed to return non-integers, to allow for typetracers.

`len(array)` where `array` is a high-level array filled with typetracers can't give a meaningful answer. But arrays like that are hidden in a `dak.Array`'s `_meta`, right? `dak.Array` must have some way of giving the length, and dask-awkward code needs to be careful to not call `len(self._meta)` for this reason.

Oh, this is just for our own code. In that case, we need to use the layout's `length` property when an `ak.Array` might contain typetracers, and if we can't avoid some `len(array)`, then that has to be a typetracer-specialized code branch.

**Comment by agoose77** [comment]
> len(array) where array is a high-level array filled with typetracers can't give a meaningful answer. But arrays like that are hidden in a dak.Array's _meta, right? dak.Array must have some way of giving the length, and dask-awkward code needs to be careful to not call len(self._meta) for this reason.

We also expose this through `ak.to_backend(..., "typetracer")`, so it would be possible to discover it there, too.

**Comment by agoose77** [comment]
Closed by #2229
