### ISSUE TITLE
run cpp tests in CI 

### ISSUE THREAD

**Issue by ianna** [scikit-hep/awkward#2164]
### Version of Awkward Array

2.0.6

### Description and code to reproduce

@agoose77 and @jpivarski - I think, we need to have at least one node to run the cpp tests.

**Comment by agoose77** [comment]
Agreed! IIRC the C++ tests are only testing the shared libraries, right? Perhaps they should be moved back into the root Git directory, and then built as a dedicated target. We can discuss today :)
