### ISSUE TITLE
Schema is not preserved when reading an empty `RecordArray` from parquet

### ISSUE THREAD

**Issue by dsavoiu** [scikit-hep/awkward#2193]
### Version of Awkward Array

2.0.6

### Description and code to reproduce

Hi!

I ran into what looks like a bug (or rather a non-implemented feature) when reading an `ak.RecordArray` stored in a Parquet file. The schema/type is not preserved when converting back to awkward if the stored array has no content (all columns have length zero).

This happens occasionally in a distributed workflow I'm running that involves merging a large number of arrays with the same structure (some of which could be empty) stored across multiple Parquet files. Preserving the schema even for the empty ones would make this easier to automate without having to filter out the empty arrays beforehand.

Here's a minimal example with an assertion on the array type to check schema preservation:
```python
import awkward as ak

# create a RecordArray with some content
a = ak.zip({"field_1": [1, 2], "field_2": [3, 4]})

# get an empty array (preserve schema)
a_empty = a[a['field_1'] < 0]

# write and read parquet
ak.to_parquet(a_empty, "test_empty.parquet")
a_empty_from_parquet = ak.from_parquet("test_empty.parquet")  # raises NotImplementedError

# check schema preserved
assert (a_empty_from_parquet.type == a_empty.type)
```

The `from_parquet` line raises a `NotImplemented` error:
```
Traceback (most recent call last):
  File "/.../awkward/test_parquet_empty.py", line 11, in <module>
    a_empty_from_parquet = ak.from_parquet("test_empty.parquet")  # gives NotImplementedError
  File "/.../awkward/src/awkward/operations/ak_from_parquet.py", line 75, in from_parquet
    return _load(
  File "/.../awkward/src/awkward/operations/ak_from_parquet.py", line 224, in _load
    _read_parquet_file(
  File "/.../awkward/src/awkward/operations/ak_from_parquet.py", line 304, in _read_parquet_file
    return ak.operations.ak_from_arrow._impl(
  File "/.../awkward/src/awkward/operations/ak_from_arrow.py", line 51, in _impl
    out = awkward._connect.pyarrow.handle_arrow(
  File "/.../awkward/src/awkward/_connect/pyarrow.py", line 1005, in handle_arrow
    raise ak._errors.wrap_error(NotImplementedError)
NotImplementedError:
```

This doesn't happen when round-tripping the array through Arrow, so it seems to be Parquet-related:
```python
a_empty_via_arrow = ak.from_arrow(ak.to_arrow(a_empty))  # works as expected
assert (a_empty_via_arrow.type == a_empty.type)
```

**Comment by jpivarski** [comment]
Oh yeah,

https://github.com/scikit-hep/awkward/blob/4cc61df3fb08fff965b132f8a5411aed7a3b77ef/src/awkward/_connect/pyarrow.py#L1003-L1005

is just a missing feature. And now that `form_handle_arrow` exists, it shouldn't be too hard to implement: we get the Arrow schema from `obj` (a `pyarrow.Table`), find its Awkward Form, and then use `Form.length_zero_array` (also a new function that didn't exist when this `FIXME` was stubbed) to make the array.

**Comment by dsavoiu** [comment]
Hi @jpivarski, thanks for the quick reaction! I actually came up with a fix for this (see PR above) but wanted to open an issue first. Haven't considered using `Form.length_zero_array`, although that does sounds like a cleaner approach.
