### ISSUE TITLE
ak.count with axis=0 is producing invalid arrays

### ISSUE THREAD

**Issue by zinebaly** [scikit-hep/awkward#222]
I am trying to count the number of elements in a nested data structure using `awkward1.count` following the [docs](https://awkward-array.readthedocs.io/en/latest/_auto/ak.count.html), I tried to apply different `axis` values to count elements at different levels of nesting.

```
axis (None or int) – If None, combine all values from the array into a single scalar result; if an int, group by that axis: 0 is the outermost, 1 is the first level of nested lists, etc., and negative axis counts from the innermost: -1 is the innermost, -2 is the next level up, etc.
```

Here is how I proceed:

```python
import uproot
import numpy as np
import awkward1 as ak1

fit = ak1.Array(uproot.open(my_file)["E/Evt/trks/trks.fitinf"].array())
print(fit)
>>> [[[0.00496, 0.00342, -295, 142, 99.1, 1.8e+308, 4.24e-12, 10, ... [], [], [], []]]
type(fit)
>>> awkward1.highlevel.Array
```
1) Counting the outermost level of nesting: `axis=0`

I tried the following to get the outermost level of nesting:
 
```python
ak1.count(fit, axis=0)
```
this raises the following error:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    682     """A pprint that just redirects to the normal repr function."""
    683     # Find newlines and replace them with p.break_()
--> 684     output = repr(obj)
    685     lines = output.splitlines()
    686     with p.group():

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/awkward1/highlevel.py in __repr__(self, limit_value, limit_total)
   1134         value = awkward1._util.minimally_touching_string(limit_value,
   1135                                                          self._layout,
-> 1136                                                          self._behavior)
   1137 
   1138         name = getattr(self, "__name__", type(self).__name__)

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/awkward1/_util.py in minimally_touching_string(limit_length, layout, behavior)
    997             leftlen += len(l)
    998 
--> 999         r = next(rightgen)
   1000         if r is not None:
   1001             if (leftlen + rightlen + len(r)

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/awkward1/_util.py in forever(iterable)
    976 
    977     def forever(iterable):
--> 978         for token in iterable:
    979             yield token
    980         while True:

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/awkward1/_util.py in backward(x, space, brackets, wrap)
    938                 sp = ""
    939                 for i in range(len(x) - 1, -1, -1):
--> 940                     for token in backward(x[i], sp):
    941                         yield token
    942                     sp = ", "

ValueError: in ListArray64 attempting to get 27, starts[i] != stops[i] and stops[i] > len(content)
```
It seems like there is an error with the `repr` of the returned object, I tried the following:

```python
t = ak1.count(fit, axis=0)
print(t.shape)
>>> (56,)
``` 
So this did not raise an error, but the shape of `t` can't be 56.

The expected result of the outermost nesting level count is 10:

```python
ak1.num(fit, axis=0)
>>> 10
```
same with 

```python
len(fit)
>>>10
```

2) Counting the first level of nesting: `axis=1`

```python
counts = ak1.count(fit, axis=1)
counts
>>> <Array [[20, 20, 20, 20, 20, ... 1, 1, 1, 1]] type='10 * var * int64'>
np.array(counts)
>>> array([[20, 20, 20, 20, 20, 20, 20, 20,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [19, 19, 19, 19, 19, 19, 19, 19,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [20, 20, 20, 20, 20, 20, 20, 20,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [20, 20, 20, 20, 20, 20, 20, 20,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [20, 20, 20, 20, 20, 20, 20, 20,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [20, 20, 20, 20, 20, 20, 20, 20,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [20, 20, 20, 20, 20, 20, 20, 20,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [20, 20, 20, 20, 20, 20, 20, 20,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [18, 18, 18, 18, 18, 18, 18, 18,  2,  2,  2,  1,  1,  1,  1,  1,
         1],
       [20, 20, 20, 20, 20, 20, 20, 20,  2,  2,  2,  1,  1,  1,  1,  1,
         1]])
```
So I understand from this result that `fit` has 10 elements (the outermost nesting level), in element 0, there are 17 elements (let's call this the first nesting level):

```python
counts[0]
>>> <Array [20, 20, 20, 20, 20, ... 1, 1, 1, 1, 1] type='17 * int64'>
```
But I am not sure if this result actually makes sense? I am not able to interpret these values.

When I check to verify if this counting is correct, I do the following: 

```python
np.array(ak1.num(fit, axis=1))
>>> array([56, 55, 56, 56, 56, 56, 56, 56, 54, 56])
``` 
both results don't match? am I misundersting something here?

same with 

```python
[len(i) for i in fit]
>>> [56, 55, 56, 56, 56, 56, 56, 56, 54, 56]
```

2) Counting the second level of nesting: `axis=2`

This one seems to work fine:

```python
counts = ak1.count(fit, axis=2)
>>> <Array [[17, 11, 8, 8, 8, ... 0, 0, 0, 0, 0]] type='10 * var * int64'>
counts[0]
>>> <Array [17, 11, 8, 8, 8, 8, ... 0, 0, 0, 0, 0] type='56 * int64'>
```
checking the results with `awkward1.num`

```python
counts_with_num = ak1.Array([ak1.num(i, axis=1) for i in fit])
counts_with_num
>>> <Array [[17, 11, 8, 8, 8, ... 0, 0, 0, 0, 0]] type='10 * var * int64'>
counts_with_num[0]
>>> <Array [17, 11, 8, 8, 8, 8, ... 0, 0, 0, 0, 0] type='56 * int64'>
```
and with a simple loop

```python
[len(i) for i in fit[0]]
>>> [17, 11, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

I also tried to apply `awkward1.count`  on one element of my `fit` data using `axis=1` and it worked just fine:

```python
ak1.count(fit[0], axis=1)
>>> <Array [17, 11, 8, 8, 8, 8, ... 0, 0, 0, 0, 0] type='56 * int64'>
```

I also noticed that the same behaviour is true for `awkward1.count_nonzero`, when `axis=1` is specified: 

```python
np.array(ak1.count_nonzero(fit, axis=1))
>>> array([[20, 20, 20, 20,  1,  1, 20, 20,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [19, 19, 19, 19,  1,  1, 19, 19,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [20, 20, 20, 20,  1,  1, 20, 20,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [20, 20, 20, 20,  1,  1, 20, 20,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [20, 20, 20, 20,  1,  1, 20, 20,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [20, 20, 20, 20,  1,  1, 20, 20,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [20, 20, 20, 20,  1,  1, 20, 20,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [20, 20, 20, 20,  1,  1, 20, 20,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [17, 17, 18, 18,  1,  1, 18, 18,  2,  2,  2,  0,  0,  1,  1,  1,
         1],
       [20, 20, 20, 20,  1,  1, 20, 20,  2,  2,  2,  0,  0,  1,  1,  1,
         1]])
```
when `axis=2` it works just fine:

```python
counts_nonzero = ak1.count_nonzero(fit, axis=2)
counts_nonzero[0]
>>> <Array [15, 9, 6, 6, 6, 6, ... 0, 0, 0, 0, 0] type='56 * int64'>
```

when `axis=0` an error is raised:

```python
ak1.count_nonzero(fit, axis=0)
>>> ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    682     """A pprint that just redirects to the normal repr function."""
    683     # Find newlines and replace them with p.break_()
--> 684     output = repr(obj)
    685     lines = output.splitlines()
    686     with p.group():

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/awkward1/highlevel.py in __repr__(self, limit_value, limit_total)
   1134         value = awkward1._util.minimally_touching_string(limit_value,
   1135                                                          self._layout,
-> 1136                                                          self._behavior)
   1137 
   1138         name = getattr(self, "__name__", type(self).__name__)

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/awkward1/_util.py in minimally_touching_string(limit_length, layout, behavior)
    997             leftlen += len(l)
    998 
--> 999         r = next(rightgen)
   1000         if r is not None:
   1001             if (leftlen + rightlen + len(r)

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/awkward1/_util.py in forever(iterable)
    976 
    977     def forever(iterable):
--> 978         for token in iterable:
    979             yield token
    980         while True:

~/miniconda3/envs/km3pipe/lib/python3.7/site-packages/awkward1/_util.py in backward(x, space, brackets, wrap)
    938                 sp = ""
    939                 for i in range(len(x) - 1, -1, -1):
--> 940                     for token in backward(x[i], sp):
    941                         yield token
    942                     sp = ", "

ValueError: in ListArray64 attempting to get 27, starts[i] > stops[i]
```

The file I am reading data from is attached to this git issue.

[aanet_v2.0.0.root.zip](https://github.com/scikit-hep/awkward-1.0/files/4504532/aanet_v2.0.0.root.zip)

Thank you for your help.

I ping @tamasgal

**Comment by jpivarski** [comment]
What you're showing is consistent with the original `fit` array being malformed—having `starts` and `stops` that point beyond its `contents`. The `repr` will fail if this is the case. You might want to try

   * [ak.is_valid](https://awkward-array.readthedocs.io/en/latest/_auto/ak.is_valid.html): returns False if malformed.
   * [ak.validity_error](https://awkward-array.readthedocs.io/en/latest/_auto/ak.validity_error.html): returns a string describing the error if malformed.

Both of these accept `exception=True` to halt execution if you have a malformed array. Perhaps validity checking should be part of `repr`, but it's a potentially expensive operation because it has to scan all fields of an array, which might be a big "events" dataset with lots of fields.

The second question is how did it get into this state? I hadn't thought of passing an Awkward0 array (from Uproot) directly into the `ak.Array` constructor; there's a

   * [ak.from_awkward0](https://awkward-array.readthedocs.io/en/latest/_auto/ak.from_awkward0.html): converts from Awkward0 to Awkward1

function for that, but it shouldn't be allowed to do crazy things like this. I'd like to see this file.

Finally, you might not be interested in

   * [ak.count](https://awkward-array.readthedocs.io/en/latest/_auto/ak.count.html): a _reducer_ that follows NumPy reduction rules for each `axis`

rather than

   * [ak.num](https://awkward-array.readthedocs.io/en/latest/_auto/ak.num.html): returns the number of values at some level of depth.

For example,

```python
>>> array = ak1.Array([[[0, 0, 0, 0, 0],
...                     [0, 0, 0],
...                     [0, 0, 0, 0]],
...                    [[0, 0],
...                     [0, 0, 0, 0, 0]]])
>>> ak1.count(array, axis=None)
19
>>> print(ak1.count(array, axis=0))
[[2, 2, 1, 1, 1],
 [2, 2, 2, 1, 1],
 [1, 1, 1, 1]]
>>> print(ak1.count(array, axis=1))
[[3, 3, 3, 2, 1],
 [2, 2, 1, 1, 1]]
>>> print(ak1.count(array, axis=2))
[[5, 3, 4],
 [2, 5]]
```

All `axis != -1` (i.e. `axis != 2` for this doubly jagged array) count laterally across objects. If you have a jagged array of particles in events, `axis = 0` asks questions like, "How many first particles are there, added up across all events?" and "How many second particles are there?"

The `ak.num` function gives you something you can use in cuts, like

```python
>>> print(ak1.num(array, axis=0))
2
>>> print(ak1.num(array, axis=1))
[3, 2]
>>> print(ak1.num(array, axis=2))
[[5, 3, 4], [2, 5]]
```

**Comment by jpivarski** [comment]
Regarding the new title, it's this line

```python
fit = ak1.Array(uproot.open(my_file)["E/Evt/trks/trks.fitinf"].array())
```

that I'm worried might be producing invalid arrays, and it's probably taking the `ak.from_iter` path.

**Comment by jpivarski** [comment]
I just noticed that you do, in fact, provide data. Triaging now.

**Comment by jpivarski** [comment]
I was wrong. `ak.from_iter` is producing valid arrays; `ak.count` with `axis=0` is producing invalid ones.

```python
>>> ak.validity_error(ak.count(fit, axis=2))
>>> ak.validity_error(ak.count(fit, axis=1))
>>> ak.validity_error(ak.count(fit, axis=0))
'at layout (ListArray64): start[i] > stop[i] at i=20'
```

and we see crazy values in the ListArray's `starts` and `stops` by looking at the low-level layout:

```python
>>> ak.count(fit, axis=0).layout
<ListArray64>
    <starts>
        <Index64 i="[0 17 34 51 68 ... 510 520 530 540 549]" offset="0" length="56"/>
    </starts>
    <stops>
        <Index64 i="[17 28 42 59 76 ... 1 1 1 1 1]" offset="0" length="56"/>
    </stops>
    <content>
        <NumpyArray format="l" shape="331" data="10 10 10 10 10 ... 8 8 8 8 8"/>
    </content>
</ListArray64>
```

(Sometimes those 500-ish numbers are like `94008244174849`.) Looking into it.

**Comment by zinebaly** [comment]
Sorry my issue was probably too cluttered with lots of unecessary information. 

But the main problem is that both `ak.count` and `ak.count_nonzero` seem to provide invalid outputs when used with `axis=0` and `axis=1` when the data had 2 levels of nesting.

**Comment by jpivarski** [comment]
In fact, all reducers do; it shows up when `axis` is less than the nesting depth and there are trailing empty lists in the output. The `starts` and `stops` of the trailing lists were left uninitialized, rather than being set to equal values (indicating an empty list).

I just fixed it. Actually, the new system is quite nice to debug! Since there are for loops at the deepest level, I can insert print statements. `:)`

**Comment by zinebaly** [comment]
Oh great! Thank you very much for the prompt reply! I will test the fix :)

Looking forward to the official release of version 1 of `awkward1` :)

**Comment by jpivarski** [comment]
It will be in the next release, which will probably wait for #216. I'm deploying releases a little less often than I used to because these include a lot of binaries and PyPI is instituting a quota.

What you want for your analysis/framework is probably not `ak.count` with `axis=0`. I don't know exactly what you want to do, but it probably involves `ak.num`.

**Comment by zinebaly** [comment]
What I needed for my analysis is `ak.count` with `axis=2`, which is already working fine. But when I noticed that `ak.count` with `axis=0` and `axis=1` seemed buggy, I thought I should report it. That's all :)
So basically I am not stuck in my analysis, so no worries :)

**Comment by jpivarski** [comment]
Okay, good. You might want to write `axis=-1`, which will always be the last one, no matter how deep.

Negative axis has been implemented for reducers and will be for everything else, but some of them rely on a soon-to-be-written function.

Thanks for reporting the issue!
