### ISSUE TITLE
Documentation on Contents

### ISSUE THREAD

**Issue by ivirshup** [scikit-hep/awkward#2230]
### Which documentation?

Documentation website

### What needs to be documented?

I think it would be quite useful if the structure of each content class was documented somewhere.

I keep forgetting the specifics of how each content class works. To figure this out, I have been instantiating the class, then calling `to_buffers`. It would be great if the docs for either the Forms or Conents classes would say things like:

> ListOffsets consist of an integer valued offset array and a data array. The data array is any other ak.contents.Content subclass. The buffer array has length (len(array) + 1) and ...

This would be very helpful for low level construction and manipulation of awkward arrays, and also for potential contributors the library.

**Comment by jpivarski** [comment]
We had some documentation on this, but in v1 it was free-floating (reST files, not docstrings) because the Content classes were all in C++. I'll just port that over.

**Comment by jpivarski** [comment]
We're waiting for a

![image](https://user-images.githubusercontent.com/1852447/217934646-f7d8acc6-9ef7-44d6-95c3-37c0c66d73fa.png)

button to appear, then click

![image](https://user-images.githubusercontent.com/1852447/217934779-f0e1c540-58db-47ca-90bf-cd9036dabe6f.png)

and they should be documented under the "Low-level array layouts" on the left side-bar.

**Comment by jpivarski** [comment]
http://preview.awkward-array.org.s3-website.us-east-1.amazonaws.com/jpivarski/docstrings-for-content-classes/reference/generated/ak.contents.BitMaskedArray.html

and following.

**Comment by ivirshup** [comment]
Thanks for adding this!
