### ISSUE TITLE
`awkward.numba._register` is not called

### ISSUE THREAD

**Issue by ianna** [scikit-hep/awkward#2242]
### Version of Awkward Array

main

### Description and code to reproduce

`ak.numba._register()` is not being called when Numba imports, and therefore Numba does not recognize Awkward Arrays on startup:

```python
>>> import awkward as ak
>>> import numba as nb
>>> nb.typeof(ak.Array([1, 2, 3]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/mambaforge/lib/python3.9/site-packages/numba/core/typing/typeof.py", line 42, in typeof
    raise ValueError(msg)
ValueError: Cannot determine Numba type of <class 'awkward.highlevel.Array'>
```

The above should not be an error. If a user explicitly calls `ak.numba.register_and_check()` (as our tests do), then they can fix the above, but this is not how it's supposed to work: Numba is supposed to call `ak.numba._register()` when it is first imported.

In its current state, if a user tries to write a Numba-JITed function with Awkward Arrays in it, as described in our documentation, they'll get a lot of error messages saying that Awkward Arrays are unrecognized/not allowed in Numba functions, strongly suggesting that the feature does not exist.

This used to work. Did it stop working when setup.py was converted to setup.cfg or when setup.cfg was converted to pyproject.toml?

Useful links:

 * [registering Numba extension points](https://numba.pydata.org/numba-doc/latest/extending/entrypoints.html)
 * [the entry point mechanism in general](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#)
 * [all the projects on GitHub that use Numba in pyproject.toml](https://github.com/search?type=code&q=numba_extensions%20language%3ATOML)

From the last link, it looks like we're using it correctly, but apparently not.

**Comment by agoose77** [comment]
It turns out this is a Numba "bug" — they don't register their entrypoints until a jitted function is executed. So, I don't think we can be doing any more here besides documenting the fact that one must call `ak.numba.register_and_check()` if one is using Numba like this?

**Comment by jpivarski** [comment]
Oh! You're right. The test,

```python
>>> nb.typeof(ak.Array([1, 2, 3]))
```

is not checking what we want. This is:

```python
>>> import awkward as ak
>>> import numba as nb
>>> @nb.njit
... def f(array):
...     return array[0]
... 
>>> f(ak.Array([1, 2, 3]))
registering...
1
```

Okay, it hadn't occurred to me that Numba wouldn't run the entry points until it starts compiling. I suppose they have their reasons for that.

Sorry for the false alarm!
