### ISSUE TITLE
Implement precedence for nominal types

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2243]
### Description of new feature

It would be helpful if library authors could define type hierarchies so that arrays with different `__array__` parameters could safely be merged, e.g. `Momentum3D + Vector3D → Vector3D`

**Comment by jpivarski** [comment]
Or `Electron → Lepton`, `Muon → Lepton`. I think there was an old issue asking for `ak.behavior` class hierarchies. I couldn't find it in the issues list, but I know it has been discussed.

**Comment by agoose77** [comment]
#2433 is a duplicate of this, but has more discussion. Therefore, I'm closing this in preference.
