### ISSUE TITLE
Cannot create empty option type with `values_astype`

### ISSUE THREAD

**Issue by grst** [scikit-hep/awkward#2254]
### Version of Awkward Array

2.0.8

### Description and code to reproduce

I would have expected 
```python
>>> ak.values_astype(ak.Array([None, None]), int)
```

to create an array of type `2 * ?int`, however, it creates

```python
[None,
 None]
------------------
type: 2 * ?unknown
```

I can create an empty option type like this: 
```python
>>> ak.Array([5, None, None])[1:]
[None,
 None]
----------------
type: 2 * ?int64
```

**Comment by agoose77** [comment]
@grst `values_astype` accepts an `including_unknown` argument. If you set this to `True`, then it will also coerce `EmptyArray`.

**Comment by grst** [comment]
oops, RTFM! sorry!

**Comment by agoose77** [comment]
No problem! This issue is useful as secondary documentation ;)
