### ISSUE TITLE
better name/way of handling cuda extension

### ISSUE THREAD

**Issue by ianna** [scikit-hep/awkward#2257]
> As long as this explicit extension is needed, we want the name to be memorable enough that users don't need to look it up. Creating a JIT-compiled function is something one does at the start of a project or in a new Python prompt on the fly—when having to look up a name would cause real friction.

_Originally posted by @jpivarski in https://github.com/scikit-hep/awkward/pull/1809#discussion_r1112364851_

**Comment by jpivarski** [comment]
This is about renaming

```python
ak.numba.array_view_arg_handler
```

to be something like

   * `ak.numba.cuda`
   * `ak.numba.cuda_ext`
   * `ak.numba.cuda_extension`

since (until https://github.com/numba/numba/issues/8609 is resolved) it has to be passed explicitly into

```python
@nb.cuda.jit(extension=[name_of_this_thing])
```

and we want that name to be memorable.
