### ISSUE TITLE
Segfault in derived virtual array

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#230]
With
```python
rec = ak.zip(
    {
        "x": ak.virtual(lambda: ak.Array([1, 2, 3, 4]), length=4),
    },
    depth_limit=1
)
```

The following line segfaults: `rec.x[1:]*2`
Possibly related, `rec.x[1:]` by itself throws an error in the VirtualArray constructor:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/awkward1/highlevel.py", line 1155, in __repr__
    highlevel=False)
  File "/usr/local/lib/python3.7/site-packages/awkward1/operations/structure.py", line 2325, in with_cache
    awkward1.operations.convert.to_layout(array), getfunction)
  File "/usr/local/lib/python3.7/site-packages/awkward1/_util.py", line 762, in recursively_apply
    return custom()
  File "/usr/local/lib/python3.7/site-packages/awkward1/operations/structure.py", line 2316, in <lambda>
    layout.generator,
ValueError: VirtualArray's generator is not a Python function
```

**Comment by jpivarski** [comment]
The first head-palm issue is that a `SlicedGenerator` (what you get if you single-level slice a VirtualArray) is not a `PyArrayGenerator`. But it's ridiculous to not be able to get a Python reference to it. These sorts of things should bubble up to Python as zero-argument callables.

**Comment by jpivarski** [comment]
I think it was a mistake making a distinction between regular ArrayGenerators and SlicedGenerators because it also makes it hard to manage caches in the SlicedGenerators (which are opaque to Python). It should be a nested VirtualArray that performs a slice. The new VirtualArray has to not be lazy about slicing, though, or else the whole thing would infinite-loop, so `bool lazyslice` should be a VirtualArray constructor argument.

**Comment by jpivarski** [comment]
Are you online? I'm not finding a satisfactory way to deal with lazy slices and I need to be reminded why we cared so much. Skype?

**Comment by jpivarski** [comment]
This is the ampersand that was causing all the segfaults (00f69138a714733bca7b649be7707ae5b8a139a1).

```diff
@@ -89,7 +89,7 @@ namespace awkward {
                     const std::string& post) const override;
 
   protected:
-    const ArrayGeneratorPtr& generator_;
+    const ArrayGeneratorPtr generator_;
     const Slice slice_;
   };
 }
```
