### ISSUE TITLE
Make a function that assigns types to unknowns from an overall type/Form description

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2338]
Note to self: the "prototype method" of assigning a type is a good hint of how to write that type-setting function. We have a way of turning a Form into a length-0 array (it's an L2 function), and if you concatenate that length-0 array onto the array with unknowns, it would give the appropriate type to those unknowns. If the types conflict, you'd get unions, which might be the right thing.

This should be turned into an issue, for brainstorming how to make that function.

_Originally posted by @jpivarski in https://github.com/scikit-hep/awkward/issues/2337#issuecomment-1481370021_

**Comment by agoose77** [comment]
@jpivarski is this covered by #2365?

**Comment by jpivarski** [comment]
That's exactly what this is. It can go in that PR as "Successfully merging this pull request may close these issues."
