### ISSUE TITLE
Remove `__array__` support from `NumpyArray` and `Index`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2339]
### Description of new feature

We are moving towards having "one way to do X" in Awkward, and most of the time that means using the `ak.operations.ak_XXX` function instead of duplicating this on the L2 types. An exception is the `to_XXX` methods, that are useful (though we've not concretely said that they won't disappear in the fullness of time).

The ability to read `Index` and `NumpyArray` as NumPy arrays is suboptimal; one can already pull out `.data` from these objects, and I think we want to err on the side of restricting the L2 API. 

I'll expand my thoughts here in future!

**Comment by jpivarski** [comment]
This is now #2969 (closing in favor of the new issue).
