### ISSUE TITLE
ak.with_field is has an overzealous check for excluding RecordArrays

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2385]
### Version of Awkward Array

HEAD

### Description and code to reproduce

One should be able to add new fields to a `RecordArray` with no fields:

```python
>>> no_fields = ak.Array([{}, {}, {}, {}, {}])
>>> no_fields["new_field"] = ak.Array([1, 2, 3, 4, 5])
```

but there's an error:

```
ValueError: no tuples or records in array; cannot add a new field

This error occurred while calling

    ak.Array.__setitem__(
        self = <Array [{}, {}, {}, {}, {}] type='5 * {}'>
        field_name = 'new_field'
        field_value = <Array [1, 2, 3, 4, 5] type='5 * int64'>
    )
```

This happens because

https://github.com/scikit-hep/awkward/blob/be60b5330f7f872fd01b34c44d2686eeafa9bbfc/src/awkward/operations/ak_with_field.py#L86-L87

is protecting the subsequent code from having to check for the case that `base` doesn't even have a `RecordArray`, but `base.fields == []` isn't the way to do it: you can also get that from a `RecordArray` with no fields.

Instead, that guard needs to check for the existence of a `RecordArray` some other way. Perhaps the following?

```python
try:
    ak._do.recursively_apply(no_fields.layout, lambda x, **kwargs: None, allow_records=False)
except ValueError:
    pass
else:
    raise ValueError("no tuples or records in array; cannot add a new field") from None
```

I'm not entirely happy about repurposing an anti-guard for one function as a guard for another. Also, it should complain if any of the branches of a `UnionArray` are not `RecordArrays`.

**Comment by agoose77** [comment]
@jpivarski I'll take this, unless you want to!

**Comment by jpivarski** [comment]
Please, go ahead! I don't have a good idea for what to replace `len(base.fields) == 0` with, other than building a new Form method like `purelist_isregular` (for `purelist_isrecord`).

**Comment by agoose77** [comment]
I think we can just test this in the existing visitor; setting a flag if we encounter the layout?

**Comment by agoose77** [comment]
That said, a `purelist_isrecord` would be useful for testing the branches of the union, so perhaps I'll add that.
