### ISSUE TITLE
The header-only.zip assets need to be automatically attached to new releases

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2402]
In https://github.com/scikit-hep/awkward/releases/tag/v2.1.3 or https://github.com/scikit-hep/awkward/releases/tag/v2.1.2

**Comment by agoose77** [comment]
Currently this is a manual process. We should definitely improve the sitiuation. I'd thought this would be complex as we'd want to create a release workflow, but actually it might be easier - we can simply edit the release for the matching tag to attach the assets.

**Comment by jpivarski** [comment]
Ah, in that case, @ManasviGoyal will need one for the recent version, but it can wait until next week. Eventually, it will need to be automatic, so that's what this issue will be asking for.

**Comment by agoose77** [comment]
Closed by #2406
