### ISSUE TITLE
Is it the case that ak.to_parquet partitions row_groups if the "array" argument is a non-Awkward iterable?

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2422]
### Which documentation?

Python docstrings

### What needs to be documented?

I vaguely remember implementing something like this, and @nsmith- just asked about it, so I looked at [the documentation](https://awkward-array.org/doc/main/reference/generated/ak.to_parquet.html) (which is passing through the docstring). It says,

![image](https://user-images.githubusercontent.com/1852447/234060788-87a3acef-21f3-4c0b-a267-729819453793.png)

which would be hiding this special feature if it, in fact, exists. If I'm wrong, then this issue should become a feature request to make it possible to

```python
def generator(data, num_entries):
    start = stop = 0
    while stop < len(data):
        stop = min(stop + num_entries, len(data))
        yield data[start:stop]
        start = stop

ak.to_parquet(generator(data, 1000), "output.parquet")
```

(for arbitrarily defined iterables, without necessarily loading everything into memory).

If I'm right, then we just need a note in the documentation saying that this is possible, and maybe also a small example to highlight it.

**Comment by nsmith-** [comment]
To be clear, I was more thinking in the distributed context, i.e. whether `dak.to_parquet` allowed repartitioning the distributed dask-awkward array. @lgray indicated that this does not exist at present.

**Comment by jpivarski** [comment]
Oh, I see. If it's distributed, then each worker has to fill a separate file, and a common metadata file should be created after they're all done. That's something `dak.to_parquet` could do, since it could add the final-metadata task in the DAG.

But the issue still stands: I think we have this memory-saving (but not time-saving) feature in `ak.to_parquet` which is also useful for making the file more granular upon reading.

**Comment by agoose77** [comment]
This is not currently the case; currently `ak.to_layout` is used to load data into a layout. We could add this, though; I'll make that a feature request.

**Comment by jpivarski** [comment]
I think it might be a lost feature, then. But it was pretty well hidden, too, and maybe we should rethink the API to provide it in a more obvious way. We certainly wouldn't want someone to pass in a jagged array as a list (non-array iterator) and get a separate row group for every short nested list.

I'll close this issue and think about it offline.
