### ISSUE TITLE
ak.is_none doesn't seem to touch input data? should it?

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2463]
### Version of Awkward Array

2.2.0

### Description and code to reproduce

The following script:
```python3
import json
import awkward as ak
import numpy as np

fromjson = {
    "class": "RecordArray",
    "fields": ["muon"],
    "contents": [
        {
            "class": "ListOffsetArray",
            "offsets": "i64",
            "content": {
                "class": "RecordArray",
                "fields": ["pt", "eta", "phi", "crossref", "thing1"],
                "contents": [
                    {
                        "class": "NumpyArray",
                        "primitive": "int64",
                        "inner_shape": [],
                        "parameters": {},
                        "form_key": "muon_pt!",
                    },
                    {
                        "class": "NumpyArray",
                        "primitive": "int64",
                        "inner_shape": [],
                        "parameters": {},
                        "form_key": "muon_eta!",
                    },
                    {
                        "class": "NumpyArray",
                        "primitive": "int64",
                        "inner_shape": [],
                        "parameters": {},
                        "form_key": "muon_phi!",
                    },
                    {
                        "class": "ListOffsetArray",
                        "offsets": "i64",
                        "content": {
                            "class": "NumpyArray",
                            "primitive": "int64",
                            "inner_shape": [],
                            "parameters": {},
                            "form_key": "muon_crossref_content!",
                        },
                        "parameters": {},
                        "form_key": "muon_crossref_index!",
                    },
                    {
                        "class": "NumpyArray",
                        "primitive": "int64",
                        "inner_shape": [],
                        "parameters": {},
                        "form_key": "muon_thing1!",
                    },
                ],
                "parameters": {},
                "form_key": "muon_record!",
            },
            "parameters": {},
            "form_key": "muon_list_outer!",
        },
    ],
    "parameters": {},
    "form_key": "outer!",
}

form = ak.forms.from_json(json.dumps(fromjson))

ttlayout, report = ak._nplikes.typetracer.typetracer_with_report(form, forget_length=True)

ttarray = ak.Array(ttlayout)

masked_pt = ak.mask(ttarray.muon.pt, ttarray.muon.eta > 0)

nones = ak.is_none(masked_pt)

print(report.data_touched)
```

prints out:
```
['muon_list_outer!', 'muon_eta!']
```

Should it also include `muon_pt` once we ask for the is_none?

A symptom of this is:
https://github.com/dask-contrib/dask-awkward/issues/260

Where dak is touching some random data and not delivering `Muon_pt` as `events.Muon.pt` to the form.

**Comment by agoose77** [comment]
In this particular reproducer, the mask is applied to the leaves (wrapping `pt` with a mask derived from `eta`), i.e. at `axis > 0`. Meanwhile, the default axis for `is_none` is `axis=0`, which is a list. From the type alone, it's discernible that there are no `None` values at `axis=0`.

Even if we check `is_none` on `axis=1`, this does not require `pt` to have real data to perform the check; we only read the mask, which is derived from `eta` and already triggers the touching for that field.

**Comment by lgray** [comment]
Ok good then this is more a conceptual problem in dak as to how to deal with this operation. i.e. for option type leaves it should know to reach through to touch the underlying data when `.compute()` is requested?

**Comment by agoose77** [comment]
I believe the motivation for this PR was dask-contrib/dask-awkward/issues/260, right? That's a symptom of our existing optimisation logic — we drop the untouched buffers from Parquet loading, which manifests as missing fields for operations that still need "something" to represent the buffer, e.g. `ak.zip`. 

The PR that will fix this is dask-contrib/dask-awkward/pull/184, which performs a secondary rehydration step to rebuild the layout to comply with the non-projected form. It does this by introducing "dummy" `Index` (and soon `NumpyArray`) nodes that don't contain any data.

**Comment by lgray** [comment]
I guess then that all makes sense. My major issue then is someone requires it to continue moving their porting work for their analysis forward. 

Will a manual data-touch likely work around what's to be fixed by https://github.com/dask-contrib/dask-awkward/pull/184? Or is the time for that pull to be completed short?

**Comment by agoose77** [comment]
The only fix at the touching level is to disable culling and always touch everything. However, I know that we don't want that. `ak.typetracer.empty_if_typetracer` can be used to do this on a per-array basis, although subsequent code might fail if it expects an array with non-zero length for some reason.
