### ISSUE TITLE
Conform better to Datashape: complex numbers and units

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2516]
### Description of new feature

* [Complex data types in Datashape](https://datashape.readthedocs.io/en/latest/types.html#default-complex) look like `complex[float64]` instead of `complex128`. We should adhere to Datashape here.
* Datashape has units, though they [only seem to be used for datetimes](https://datashape.readthedocs.io/en/latest/types.html#date-time-and-datetime). The format is `units['name_of_unit', type]`. We can use that for our future `__units__`, but let's not use it for dates because Datashape either hard-assumes 100 ns for the time-unit or assumes that they're recognizable as time units in the first argument of `units` (using [ICU datetime unit conventions](https://unicode-org.github.io/icu/userguide/)). NumPy allows arbitrary granularity, like `15s`, which is not in general recognizable. Also, we don't want to cause confusion between the `__units__` units (which Pint will manage) and the datetime units (which NumPy manages).

**Comment by agoose77** [comment]
What do we think should be the datashape for `complex128` _with_ parameters?

1. `complex[float64, foo=bar]`
2. `complex[float64][foo=bar]`

I think (1) without considering the ease of implementation.

**Comment by jpivarski** [comment]
I'd also prefer (1) aesthetically and because I think it's more in keeping with Datashape style.

**Comment by jpivarski** [comment]
I don't think this needs to be changed. No one is holding us to compliance with Datashape. At this point, I think we can say that our type string representation was "inspired by" Datashape. There are some aspects of our type strings that will never adhere to Datashape (because they're beyond the scope of Datashape).

Also, we have a Datashape parser that uses our in-house conventions.
