### ISSUE TITLE
form.select_columns takes an hour for ~1500 columns

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2535]
### Version of Awkward Array

2.2.3

### Description and code to reproduce

Encountered when first implementing https://github.com/scikit-hep/uproot5/pull/905. 
There appear to be some implementations of `_select_columns` for the derived form classes that are very slow.

Reproducer, which may not take an hour but is still excessively slow:
```python3
import uproot

events = uproot.dask({"https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root": "Events"})
form = events._meta.layout.form
form.select_columns(form.columns())
```
This is what https://github.com/scikit-hep/uproot5/pull/905 was doing with column-optimization turned off until I worked around it, but you can imagine if the number of columns is large it's still a problem!

**Comment by agoose77** [comment]
Thanks for adding this! I'll take a look and let you know what I find.

**Comment by jpivarski** [comment]
This is very surprising! There must be some hidden $\mathcal{O}(n^2)$ thing in it; 1500 strings is not something that should lead to an hour of processing. Maybe it's unnecessarily running up and down the tree structure or something.

Anyway, this is not a situation in which we were expecting that kind of performance. Even if it didn't have a bad impact on real use-cases, it would be wrong anyway.
