### ISSUE TITLE
Form and np.dtype inconsistencies 

### ISSUE THREAD

**Issue by ianna** [scikit-hep/awkward#2551]
### Version of Awkward Array

2.2.4

### Description and code to reproduce

Hi @agoose77 - here are some very minor issues I run into when conversion an `np.dtype` to a string required by a Form. Perhaps, we should to handle this in a more consistent manner... Please, have a look. Thanks.

- [ ] `EmptyArray` can have `parameters`, but:

```python
Issue: EmptyForm cannot contain parameters.
```

- [ ] Should 'int32' and 'i32'  be the same?

```python
AssertionError: assert ListOffsetForm('int32', NumpyForm('float64')) == ListOffsetForm('i32', NumpyForm('float64'))
```

- [ ] `ak.index._dtype_to_form` dict has no `bool`:

```python
    @property
    def form(self):
>       return ByteMaskedForm(ak.index._dtype_to_form[self._mask.dtype], self.content.form, self._valid_when, parameters=self._parameters,)
E       KeyError: dtype('bool')
```

using `ak.types.numpytype.dtype_to_primitive(self._mask.dtype)`:
```python
>       assert builder.form == layout.form
E       AssertionError: assert ByteMaskedForm('bool', NumpyForm('float64'), True) == ByteMaskedForm('i8', NumpyForm('float64'), True)
```

**Comment by agoose77** [comment]
@ianna RE `EmptyArray`, do you have any reproducers? From looking at the source code, we perform the same check for the form and the array.

Concerning `int32` and `i32`, my understanding is that we want a single value, and we're currently using `i32`. We don't do much validation in the forms, though, so perhaps we should.

As for the `_dtype_to_form`, we only support integer types for masks, even booleans. How are we ending up with a boolean?

**Comment by ianna** [comment]
> @ianna RE `EmptyArray`, do you have any reproducers? From looking at the source code, we perform the same check for the form and the array.
> 
Oh... yes, my fault. I should update the `Empty` layout builder to check that `parameters` are always `None`.
```python
>>> layout = ak.contents.EmptyArray(parameters={"When I was one": "I just begun"})
<stdin>:1: DeprecationWarning: In version 2.2.0, this will be an error.
To raise these warnings as errors (and get stack traces to find out where they're called), run
    import warnings
    warnings.filterwarnings("error", module="awkward.*")
after the first `import awkward` or use `@pytest.mark.filterwarnings("error:::awkward.*")` in pytest.
Issue: EmptyArray cannot contain parameters.
>>> layout = ak.contents.EmptyArray(parameters=None)
```
> Concerning `int32` and `i32`, my understanding is that we want a single value, and we're currently using `i32`. We don't do much validation in the forms, though, so perhaps we should.
> 
> As for the `_dtype_to_form`, we only support integer types for masks, even booleans. How are we ending up with a boolean?

I'm creating a `GrowableBuffer(np.bool)` for the `mask`...

**Comment by ianna** [comment]
closing it as discussed at the meeting
