### ISSUE TITLE
request for highlevel `.to_typetracer_array()` or something similar

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2576]
### Description of new feature

```python3
out = ak.Array(out.layout.to_typetracer(forget_length=True), behavior=out.behavior)
```

Is a very common pattern for people writing library code, or people hacking stuff into dask from whatever they're doing in their analysis. This comes up any time someone needs to `map_partitions` some custom operation.

It would significantly simplify code that has to interact with typetracer high level arrays to have in the highlevel Array class a corresponding `.to_typetracer_array()` (or whatever is most appropriate to call it) that performs the above operation.

**Comment by jpivarski** [comment]
Maybe

```python
ak.to_backend(out, "tt", forget_length=True)  # other backends ignore forget_length?
```

or

```python
ak.to_backend(out, "forget_length")  # implicitly typetracer backend
```

or

```python
ak.to_typetracer(out, forget_length=True)  # specially named function with an argument
```

I like the last one best.

**Comment by lgray** [comment]
My vote's for the last one as well, especially if it handles highlevel and layouts as expected. Tidy descriptive interface!

**Comment by jpivarski** [comment]
Is this still relevant, now that the dust has cleared on Coffea 2023?

**Comment by lgray** [comment]
~~It would be nice to have, rather than need to have. It still shows up in a few places and it would be less bookkeeping (for behaviors, attrs, etc.) to have a high level array version of `to_typetracer()`.~~

Oh, never mind this only ever shows up when I'm making a typetracer from a `from.length_zero_array()` which forgets behavior and attrs anyway so I must specify them by building a new array anyway. Given that, this feature is unnecessary.

**Comment by jpivarski** [comment]
Okay, thanks!
