### ISSUE TITLE
Upload Pyodide wheel to GH Release

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/awkward#2581]
### Description of new feature

It would be nice to upload the awkward-cpp Pyodide wheels to the GitHub release. This can probably be automated.

**Comment by jpivarski** [comment]
Would that be only the `awkward` package?

If it also includes the `awkward-cpp` package, would that be an alternative to or in addition to compiling `awkward-cpp` into Pyodide?

* [project directory](https://github.com/pyodide/pyodide/tree/main/packages/awkward-cpp)
* [most recent PR](https://github.com/pyodide/pyodide/pull/4380)

**Comment by agoose77** [comment]
It would be an alternative, useful for testing PRs to pyodide. But, the main benefit was getting awkward into pyodide, which we now directly do!

**Comment by jpivarski** [comment]
In that case, I suppose we can close this issue.

Except... only versions 22 and 26 have been accepted ([Pyodide PRs](https://github.com/pyodide/pyodide/pulls?q=is%3Apr+awkward-cpp+)), and they've never had 100% of tests passing. Does someone have to accept them manually? If so, we might be producing them faster than anyone can manually accept them.

With an `==` constraint between awkward-cpp and awkward, the use in JupyterLite will usually fail. Our [Try it!](https://awkward-array.org/doc/main/getting-started/try-awkward-array.html) has stalled, and trying to

```python
import piplite; await piplite.install("awkward-cpp"); await piplite.install("awkward>=2.0")
```

in https://numpy.org/ or https://jupyter.org/try-jupyter/ results in

```
ValueError: Requested 'awkward-cpp==28', but awkward-cpp==22 is already installed
```

So we could run Awkward 2.3.3 in the [Try it!](https://awkward-array.org/doc/main/getting-started/try-awkward-array.html) box,

```python
import piplite; await piplite.install("awkward-cpp"); await piplite.install("awkward==2.3.3")
```

although that means being aware of when Pyodide updates happen and adjusting this manually as well. (Having an old version in the [Try it!](https://awkward-array.org/doc/main/getting-started/try-awkward-array.html) box is not so bad, now that things aren't changing rapidly. The main points about what Awkward is and what it does can be made with an old version, even months old.)
