### ISSUE TITLE
We shouldn't decorate the `KeyboardInterrupt` exception

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2586]
### Version of Awkward Array

HEAD

### Description and code to reproduce

If I press control-C (or ■ in Jupyter), I don't need to be told what high-level function failed because it didn't really "fail," it was cancelled.

```
KeyboardInterrupt: 

This error occurred while attempting to slice

    <MomentumArray4D [[{pt: 63, eta: ..., ...}, ...], ...] type='299973 * v...'>

with

    'phi'
```

Similarly, we have to think about what will happen if someone cancels an asynchronous GPU process—does the background thread get informed? That's beyond this issue, though.

**Comment by agoose77** [comment]
Yes, we should catch exception and not base exception. I'm surprised this happens (without looking at the source), as it's a common pattern  that I'd expect us to have anticipated. I'll make a patch soon.
