### ISSUE TITLE
Reducers (sum/any/all) convert axis to regular axis with `keepdims=True`

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#2609]
### Version of Awkward Array

2.3.1

### Description and code to reproduce

```python
import awkward as ak

x = ak.Array([[1]])
result = ak.any(x, axis=1, keepdims=True)
```
The second axis of the results should be variable-length, because the second axis of `x` is also variable-length. However, the result is fully regular. I observe the same with `ak.sum` (among others). This did not happen in awkward version 1.10.3.

**Comment by agoose77** [comment]
Yes, this is intentional; we know that the axis has length-one, so we add that information.Is this a problem for you?

https://github.com/scikit-hep/awkward/pull/1943#issuecomment-1336197310 provides some context on the history of this decision :)

**Comment by jrueb** [comment]
I noticed this issue because I was slicing using the now-regular array, which removes a dimension.
In this case, I will use `ak.from_regular` to make sure its variable-length again. Thanks.
