### ISSUE TITLE
`to_categorical` should not use `to_list`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2625]
### Version of Awkward Array

main

### Description and code to reproduce

@jpivarski and I proposed (in a meeting) restricting this function to string-types only, and then using PyArrow's dictionary encoding (exposed via `ak.str`). 

I'm now thinking we should instead limit `to_categorical` to _primitive_ types (not just strings), and implement another kernel. C++ 17's `std::string_view` would be useful for this kernel, see #2608. My rationale for widening to non-string types is that it's easy enough to do so. My rationale for implementing a kernel is that I want to support categorical strings in pyodide, which doesn't support Arrow.

**Comment by jpivarski** [comment]
I was thinking of that: the categorical values could also be numbers without much technical difficulty. But the other side of the equation is usefulness: if categorical values could be strings, integers, and floating point values, why would anyone use anything but the strings?

(Records and lists _might_ be useful, at a cost of more technical difficulty.)

Implementations of categoricals in [Pandas](https://pandas.pydata.org/docs/user_guide/categorical.html), [Parquet](https://parquet.apache.org/docs/file-format/data-pages/encodings/#dictionary-encoding-plain_dictionary--2-and-rle_dictionary--8), and [Arrow](https://arrow.apache.org/blog/2019/09/05/faster-strings-cpp-parquet/) (chronological order) were inspired by the [factor type in R](https://www.stat.berkeley.edu/~s133/factors.html). (I don't know how far back it goes before that.) In all the discussion about them, I've never seen any non-string examples. (I think it's technically possible to make non-string dictionary encodings in Parquet and Arrow, but documentation always demonstrates it with strings.) Sometimes, the order of the strings is relevant, sometimes not, and of course it's useful to have nullable strings, but all of the motivations I've seen boil down to three points:

* wanting to be explicit about the set (and maybe order) of enumerated tokens, which are usually meaningful and human-readable
* wanting to use less memory for a big dataset of them
* wanting to use less time when doing equality comparisons among them (as in selection and group-by).

So I'm in favor of making categoricals a "stringy" thing, locating it in the `ak.str` namespace so it's easier to justify having its implementation depend on pyarrow, and only extend beyond that if a use-case ever does come up.

**Comment by agoose77** [comment]
Alright. Then, the logic is in future we could un-deprecate (or restore, if it's already removed from the API by then) `ak.to_categorical` and generalise to non-strings.

I am still in favour of `ak.categories` remaining if we deprecate `ak.to_categorical`; we can still read categorical data from other sources, even if it's only strings that users can create in Awkward?

**Comment by jpivarski** [comment]
I see, there are two possible ways to go:

1. remove the ability to _create_ categorical data of non-strings, but accept any categorical data in a `from_arrow` conversion;
2. exclude categorical data as a possibility in the construction of indexed arrays with `__array__: "categorical"`.

(1) has the advantage that more Arrow/Parquet data would be readable, but (2) has the advantage that it might be easier to do manipulations on categorical data if we can make stronger assumptions about what it contains.

I can't think of what manipulations get easier. The thing that we gain by restricting non-string data is the ability to compute uniqueness, which is only needed when making categorical data from non-categorical data. So yes, (1) does look like the best option.

**Comment by agoose77** [comment]
Agreed, (1) is the list invasive for forward thinking changes.

Closed by #2630, which adds a new function.
