### ISSUE TITLE
Support `pyarrow.array(ak.Array(...))`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2647]
### Description of new feature

Arrow provides an `__arrow_array__` interface that we *could* support.

@jpivarski how do you feel about this? The questions that arise for me are - what defaults should we choose for `ak.to_arrow`? I'm mainly concerned about enabling the extension array or not. To my mind, the extension-array mechanism is useful for serialisation, but may cause problems for strict Arrow routines.

**Comment by jpivarski** [comment]
I'm in favor, and I think it makes sense for `__arrow_array__` to invoke `ak.to_arrow` with `extensionarray=False`.
