### ISSUE TITLE
Can `_touch_data` be made public?

### ISSUE THREAD

**Issue by danielballan** [scikit-hep/awkward#2668]
### Description of new feature

I have a [use case](https://github.com/bluesky/tiled/pull/549/files#diff-40070db129d1d3432609597f627cdbcddf5f970b7bb8062862427e8501359ab1R32-R34) for calling the [`_touch_data`](https://github.com/search?q=repo%3Ascikit-hep%2Fawkward%20%22def%20_touch_data%22&type=code) methods directly. I wonder if that method can be promoted from a private method to "public but not widely advertised".

If the maintainers are receptive, I would be happy to contribute a PR. It would be easy enough to provide a backward-compatible implementation:

```py
    def touch_data(self):
        ...

    _touch_data = touch_data  # back-compat
```

if that is an important consideration here.

**Comment by agoose77** [comment]
Interestingly, we technically already expose the recursive case at the top level, with 
```python
ak.typetracer.empty_if_typetracer(array)
```

It does some other work besides touching the layout, but it should suffice for your use case, I believe :)

**Comment by danielballan** [comment]
Thanks! Let me see if I can follow how to slot that in.

Current implementation (via @jpivarski):

```py
>>> import awkward as ak
>>> array = ak.Array([[{"x": 1.1, "y": [1]}, {"x": 2.2, "y": [1, 2]}], [], [{"x": 3.3, "y": [1, 2, 3]}]])
>>> form, length, container = ak.to_buffers(array)

>>> typetracer, report = ak.typetracer.typetracer_with_report(form, forget_length=True)
>>> proxy_array = ak.Array(typetracer)
# using _touch_data, internal API
>>> proxy_array[0, "y", 1:].layout._touch_data(recursive=True)
>>> report.data_touched
['node0', 'node3', 'node4']
```

Proposed replacement:

```py
>>> typetracer2, report2 = ak.typetracer.typetracer_with_report(form, forget_length=True)
>>> proxy_array2 = ak.Array(typetracer2)
# empty_if_typetracer is deprecated; its recommended replacement is length_zero_if_typetracer
>>> ak.typetracer.length_zero_if_typetracer(proxy_array2[0, "y", 1:])
<Array [] type='0 * var * int64'>
>>> report2.data_touched
['node0', 'node3', 'node4']
```

So far, so good. What sort of extra work does it do?

**Comment by agoose77** [comment]
`ak.typetracer.length_zero_if_typetracer` recursively touches the typetracer array, and then allocates a single small buffer to create an array of zero length. We don't need that latter part, and I've observed that other users of typetracer also need this function. As such, let's just expose it, as you initially requested (although under the `ak.typetracer` namespace, I think).
