### ISSUE TITLE
ArrayGenerator parameters

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#272]
Can the following parameters used to declare `ArrayGenerator` be exposed to python: `callable`, `args`, `kwargs`?
Already `form` and `length` are available.

**Comment by nsmith-** [comment]
Alternatively, or in addition, a helper function like `VirtualArray.withlength` could be provided to make a copy of a virtual array node but with the length provided in the case where it was not available previously.

**Comment by jpivarski** [comment]
No problem (on both). I should get to that this afternoon.
