### ISSUE TITLE
ak.mean with `keepdims=True` is returning arrays of the wrong length

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2727]
### Discussed in https://github.com/scikit-hep/awkward/discussions/2726

<div type='discussions-op-text'>

<sup>Originally posted by **WWWonderer** September 27, 2023</sup>
For the code below:

```
arr = ak.Array(
    [
        [
            [1, 2], 
            [1]
        ],
        [
            [1], 
            [1], 
            [1]
        ]
    ]
)

print(f'mean: {ak.mean(arr)}') # prints mean: 1.1666666666666667
print(f'std: {ak.std(arr)}') # error
```
The mean works fine while the std gives me error with following stack trace:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/awkward/_dispatch.py](https://localhost:8080/#) in dispatch(*args, **kwargs)
     59                 try:
---> 60                     next(gen_or_result)
     61                 except StopIteration as err:

19 frames
ValueError: cannot broadcast nested list (in compiled code: https://github.com/scikit-hep/awkward/blob/awkward-cpp-23/awkward-cpp/src/cpu-kernels/awkward_ListArray_broadcast_tooffsets.cpp#L27)

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/awkward/_errors.py](https://localhost:8080/#) in handle_exception(self, cls, exception)
     80             self.decorate_exception(cls, exception)
     81         else:
---> 82             raise self.decorate_exception(cls, exception)
     83 
     84     def decorate_exception(self, cls: type[E], exception: E) -> E:

ValueError: cannot broadcast nested list (in compiled code: https://github.com/scikit-hep/awkward/blob/awkward-cpp-23/awkward-cpp/src/cpu-kernels/awkward_ListArray_broadcast_tooffsets.cpp#L27)

This error occurred while calling

    ak.std(
        <Array [[[1, 2], [1]], [[1], ...]] type='2 * var * var * int64'>
    )
```
This seems very counterintuitive to me as the std is nothing but some operations on mean. What can be done in mean in terms of broadcasting should also be doable in std. Is there a reason this is happening and how to solve this issue? Thanks!

Edit: 

I went a bit deeper into the codebase and found this in variance implementation which is used by std (https://github.com/scikit-hep/awkward/blob/main/src/awkward/operations/ak_var.py):
```
            sumwxx = ak.operations.ak_sum._impl(
                (x - xmean) ** 2, # maybe here is the broadcasting??? 
                axis,
                keepdims=True,
                mask_identity=True,
                highlevel=True,
                behavior=None,
            )
```
In the implementation of mean (https://github.com/scikit-hep/awkward/blob/main/src/awkward/operations/ak_mean.py#L156) only x is passed into ak_sum:
```
            sumwx = ak.operations.ak_sum._impl(
                x,
                axis,
                keepdims=True,
                mask_identity=True,
                highlevel=True,
                behavior=None,
            )
```
Maybe this is the cause of the issue? But is there a way to fix it? 
</div>

--------------

I looked into the implementation of `ak.std`, and found the same issue in `ak.var`. The step where it fails is when we subtract the mean from each value:

```python
xmean = ak.mean(arr, keepdims=True)
arr - xmean   # fails with "can't broadcast"
```

where

```python
>>> arr
<Array [[[1, 2], [1]], [[1], [1], [1]]] type='2 * var * var * int64'>
>>> xmean
<Array [[[1.17]]] type='1 * var * 1 * float64'>
```

The problem is not with the `var * int64` versus `1 * float64`, it's with the `2 *` versus `1 *`. It doesn't look like a problem with the definition of broadcasting, but with the output of `ak.mean` with `keepdims=True`. It should be length-2, not length-1.

(I don't know how this didn't get caught in tests! My mistake, of course, since I wrote the `ak.mean`, `ak.var`, etc. suite.)

**Comment by agoose77** [comment]
The cause of this is that `keepdims=True` for `axis=None` doesn't introduce regular nodes, unlike `axis!=None` which replaces the node at `axis` with a regular one. 

This makes sense; unlike `axis=None`, `axis=N` only operates upon a single dimension. We _probably_ want to replace list nodes with regular nodes in `_remove_structure`.

**Comment by jpivarski** [comment]
Okay! (I read this message after the PR...)
