### ISSUE TITLE
What's the best way to make CUDA-enabled Awkward available?

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#278]
Right now, @reikdas and @trickarcher are working on CUDA kernels for Awkward, which involves building a new target, libawkward-cuda-kernels.so ("gpu-kernels" in the diagram below), and if-else logic in libawkward.so ("C++ classes" in the diagram below) to pick the right kernel for pointers that reside on the GPU.

<center><img src="https://github.com/scikit-hep/awkward-1.0/raw/master/docs-img/diagrams/awkward-1-0-layers.png" width="500"></center>

(We went with the name "cuda-kernels" to allow for alternative implementations that can coexist with CUDA. Hopefully, we'll be able to move to a non-vendor-specific GPU implementation in the future.)

I think it's okay to say that we won't be building wheels on PyPI that support GPUs, but I'd like to make the GPU-enabled version a conda option. Thus, it at least needs to be _compilable_ for the GPU with pip.

So far, the only way I've managed to do that is through an environment variable. (I struggled with pip's `--global-option`, `--build-option`, and `--install-option` all morning.) That's disappointing, but it could be good enough for a system administrator who is custom-compiling the library for a machine known to have GPUs. Is is also good enough for setting up the conda build?

https://github.com/scikit-hep/awkward-1.0/blob/2f09ecad3218e78d7cdb8f64e3002d0c0220fec7/setup.py#L30-L31

Any thoughts, opinions, or suggestions, @chrisburr @henryiii @veprbl?

**Comment by jpivarski** [comment]
What if we could isolate our CUDA dependency to only be in libawkward-cuda-kernels.so and make that a completely separate project? That is, libawkward-cuda-kernels.so would be built by a different CMakeLists.txt and the main codebase would only be aware of it as a shared library that could possibly be dynamically loaded? Then it could have a different conda name (and even PyPI name) like "awkward-cuda-kernels". If it can be dynamically loaded, then GPU pointers can be dispatched to the appropriate kernel; if not, there's a runtime error.

It sounds to me like that would simplify things, if we really can isolate our CUDA dependency to just the libawkward-cuda-kernels.so. It means that we can't use `cudaPointerGetAttributes` to tell us if a pointer is a main memory pointer or a GPU pointer, but [maybe that's not possible anyway](https://stackoverflow.com/a/20592462/1623645). We might have to keep track of that information as an enum.

**Comment by chrisburr** [comment]
I've been pondering this for a while and I think a separate package is the best way to go. Especially considering conda-forge will build at least two different `libawkward-cuda-kernels.so` binaries for different CUDA versions.

I presume `awkward-cuda-kernels` and `awkward` will be versioned together? If so, it would be nice if `libawkward-cuda-kernels.so` can be built without depending on the `awkward` Python package so that it can be completely separate. (If not the first update build of the PR `awkward-cuda-kernels` will always fail due to `awkward-array` not being built yet.)

Also are you thinking `libawkward` should be a separately installable package for conda?

**Comment by jpivarski** [comment]
> Also are you thinking `libawkward` should be a separately installable package for conda?

I hadn't been thinking that, although I suppose it's a possibility. If that would allow projects that depend on C++ libawkward (such as the hypothetical FastJet interface that communicates via jagged arrays of events) to be kept in binary compatibility with the Python interface, it would be a benefit.

(I'm not sure if there's binary compatibility to maintain; [dependent-project](https://github.com/scikit-hep/awkward-1.0/tree/master/dependent-project) can dynamically link, but some of its interfaces use STL—I hadn't known at the beginning of the project that this is a bad idea.)

> I presume awkward-cuda-kernels and awkward will be versioned together?

It will likely be necessary for `awkward1` version `x.y.z` to depend on `awkward1-cuda-kernels==x.y.z`, so they're going to live in the same GitHub repository. There's no reason for `awkward1-cuda-kernels` to depend on `awkward1` or Python, though. It's a one-way dependency.

How much customization can we do in the conda recipe? I'm wary about splitting the CMakeLists.txt that makes libawkward1-cpu-kernels.so, libawkward1.so, and the Python extension module now that it works with pip. Trying to set something up that works with pip _and_ separates libawkward1.so and the Python extension module for conda sounds daunting. Can we have different CMakeLists.txt for conda? Particularly if such a thing wouldn't have to be integrated with setup.py?

**Comment by jpivarski** [comment]
@trickarcher is isolating all of the CUDA-dependent stuff in a pip-installable package named `awkward1-cuda-kernels`, which is a Python package that only announces its full path and contains a `libawkward-cuda-kernels.so`. The main codebase tries to load this Python package dynamically when it's needed. The main package will have an "extras" dependency on `awkward1-cuda-kernels` so that one can

```bash
pip install awkward1[cuda]
```

to get both (and maybe something similar in conda).

I think this is a pretty good solution.
