### ISSUE TITLE
NumPy 1.18 is not properly supported

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2784]
### Version of Awkward Array

main

### Description and code to reproduce
NumPy 1.18 is very old, so few people were actually testing this.

We were not aware of the problem until we introduced features that silently depended upon "NumPy>=1.24", which is much newer; downstream projects (coffea) tested against `1.18 < numpy < 1.24` and raised the alarm.

**Comment by jpivarski** [comment]
I'm wondering why [this test](https://github.com/scikit-hep/awkward/blob/3f623eecbc93c98f2ef0b419c6831483afb12a91/.github/workflows/test.yml#L202-L204) didn't catch it. [Here](https://github.com/scikit-hep/awkward/actions/runs/6692365704/job/18181406683) is an example of the last time it ran.

**Comment by agoose77** [comment]
See #2783!

**Comment by jpivarski** [comment]
Yikes; okay.
