### ISSUE TITLE
ak.argmin and ak.argmax with `keepdims=True` is replacing empty lists with `[None]`, rather than `[]`

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2894]
### Version of Awkward Array

HEAD

### Description and code to reproduce

```python
>>> array_of_int = ak.Array([
...     [3, 1, 5, 2],
...     [2, 2, -4, 1],
...     [],
...     [3, 7, 4]
... ])
>>> ak.argmin(array_of_int, axis=-1, keepdims=False)
<Array [1, 2, None, 0] type='4 * ?int64'>
```

is fine because there is no index to return for the minimum of `[]`, but

```python
>>> ak.argmin(array_of_int, axis=-1, keepdims=True)
<Array [[1], [2], [None], [0]] type='4 * 1 * ?int64'>
```

is just wrapping each output of the `keepdims=False` case with length 1 lists. This is not "keeping dims" and it's not useful as an array-slicer (the primary use-case for `ak.argmin` and `ak.argmax`). What we actually want, for `ak.argmin` and `ak.argmax` only (the only reducers without identities) is

```python
>>> ak.singletons(ak.argmin(array_of_int, axis=-1, keepdims=False))
<Array [[1], [2], [], [0]] type='4 * var * int64'>
```

I noticed this while writing tutorials. I'll try to make sure that the tutorial works both ways, with and without this feature. (Not hard because `None` is a placeholder for slicing.)

I'm surprised that I had never noticed this before. Have we ever discussed this behavior and did we come to the conclusion that it's _supposed_ to do this? It will be a breaking change, but I would definitely call it a bug-fix unless I can be convinced that we intentionally decided on this behavior.

**Comment by agoose77** [comment]
That's ... weird. I'm surprised? Let me do some bisection to find where this was introduced; I'm _certain_ this used to work.

**Comment by jpivarski** [comment]
Actually, this would need some sort of deprecation cycle after all. Maybe it can be introduced with a new argument to `ak.argmin` and `ak.argmax` (only), which eventually becomes default and then is finally removed as an option.

It will require downstream code to use `ak.firsts` instead of `[:, 0]`:

```python
>>> array_of_int = ak.Array([
...     [3, 1, 5, 2],
...     [2, 2, -4, 1],
...     [],
...     [3, 7, 4]
... ])
>>> array_of_str = ak.Array([
...     ["three", "one", "five", "two"],
...     ["two", "two", "minus four", "one"],
...     [],
...     ["three", "seven", "four"]
... ])

>>> old_way = ak.argmin(array_of_int, axis=-1, keepdims=True)
>>> old_way
<Array [[1], [2], [None], [0]] type='4 * 1 * ?int64'>

>>> new_way = ak.singletons(ak.argmin(array_of_int, axis=-1, keepdims=False))
>>> new_way
<Array [[1], [2], [], [0]] type='4 * var * int64'>

>>> array_of_str[old_way][:, 0]
<Array ['one', 'minus four', None, 'three'] type='4 * ?string'>

>>> array_of_str[new_way][:, 0]
Traceback (most recent call last):
...
IndexError: cannot slice ListArray (of length 4) with array(0): index out of range while attempting to get index 0 (in compiled code: https://github.com/scikit-hep/awkward/blob/awkward-cpp-26/awkward-cpp/src/cpu-kernels/awkward_NumpyArray_getitem_next_at.cpp#L21)

This error occurred while attempting to slice

    <Array [['one'], ['minus four'], ..., ['three']] type='4 * var * string'>

with

    (:, 0)

>>> ak.firsts(array_of_str[new_way])
<Array ['one', 'minus four', None, 'three'] type='4 * ?string'>
```

So it's not something that can be put in now.

> That's ... weird. I'm surprised? Let me do some bisection to find where this was introduced; I'm _certain_ this used to work.

Maybe first we should find out if it was ever how this worked. There are probably tests depending on it, and if they use `[:, 0]`, then that indicates that it was how it worked as long as that test existed.

**Comment by agoose77** [comment]
It looks like even in 1.10 the current behavior was nominal. Of course, this isn't just `argmin`; it's _all_ reducers.

I've had some more time to think about it, and in the context of "all reducers", I don't find this as surprising as I did; I think of `keepdims=True` as "preserve the list", and `mask_identity=True` as "use `None` instead of the identity".

I can see why `ak.min([], axis=-1, keepdims=True, mask_identity=True)` could logically produce `None` instead of `[None]`, but I find it increasingly a matter of preference vs an obvious bug.

**Comment by jpivarski** [comment]
I agree that the current behavior is correct for all reducers other than `ak.argmin` and `ak.argmax`; the reason I was thinking these two should be different is because they don't have identities.

For `ak.sum`, `[] → 0` with `keepdims=False` and `[] → [0]` with `keepdims=True` makes sense (depending on how we're thinking about the word "keep").

For `ak.argmin`, `[] → None` with `keepdims=False` is fine; I just thought that `[] → []` when `keepdims=True`. However, it would also mean that `ak.argmin` and `ak.argmax` would then differ from the other reducers by producing a variable-length dimension instead of a regular, length 1 dimension, and that's getting a little too exceptional.

I can see how `[] → [None]` for `ak.argmin` with `keepdims=True` makes some sense, and it's baked rather deeply into the expectations by now. Maybe it's too late. I'll withdraw the issue and not rock this boat.

**Comment by agoose77** [comment]
The same is true for `ak.min`, which has the same semantics as `ak.argmin`. I completely agree that for the purposes of an indexer it's non-ideal. It looks like we *might* have more support for a dedicated function for indexing, part of the same discussion as adding a dedicated ragged indexing accessor. I'll give it some thought!

**Comment by jpivarski** [comment]
I was going to say that `ak.min` has an identity, `np.inf` (or `MAXINT`), but usually `mask_identity=True`, so it's covered up by `None`. So yes, it has the same semantics in the default case, and this behavior probably shouldn't depend on that argument. It might be too surprising for `mask_identity` to also control whether `keepdims` produces a variable-length dimension with `[] → []` or not.

**Comment by agoose77** [comment]
We also make up identities for `argmin`/`argmax`, hence my thinking that they're quite similar to the `min`/`max` functions. I'm glad to see that you're also on the fence with respect to what we should do here! APIs are hard sometimes :P

**Comment by jpivarski** [comment]
I don't remember what identities we make up for `argmin`/`argmax`, but they can't be as meaningful as the identities for `min`/`max`. Maybe we use `-1`, just so that it's different from `0`? (Although `-1` is an index that would select the wrong element.)

But yeah, this issue is closed; we're not doing it. The tutorial shows what I've been calling the "old way" above, and the tutorial would need to be changed if this behavior changed. (I didn't want to introduce/explain `ak.firsts`.)
