### ISSUE TITLE
`ak.argmax` and `ak.argmin`: support for Boolean arrays

### ISSUE THREAD

**Issue by delannoy** [scikit-hep/awkward#2934]
### Description of new feature

`ak.argmax` and `ak.argmin` do not support Boolean arrays unless they are first cast to integer. Meanwhile, `np.argmax` and `np.argmin` can operate on Boolean arrays directly:

```python
import awkward as ak
import numpy as np

assert ak.__version__ == '2.5.1'
assert np.__version__ == '1.24.4'

np_bool_array = np.array([[1, 2, 3], [3, 2, 1]]) > 2
assert np.argmax(np_bool_array, axis=1).tolist() == [2, 0]
assert np.argmin(np_bool_array, axis=1).tolist() == [0, 1]

ak_bool_array = ak.Array([[1, 2, 3], [4, 3, 2, 1]]) > 2

try:
    ak.argmax(ak_bool_array, axis=1)
except KeyError:
    print("this doesn't work :(")

try:
    ak.argmax(np_bool_array, axis=1)
except KeyError:
    print("this doesn't work either :(")

# casting to `int` works:
ak_int_array = ak.values_astype(ak_bool_array, int)
assert ak.argmax(ak_int_array, axis=1).tolist() == [2, 0]
assert ak.argmin(ak_int_array, axis=1).tolist() == [0, 2]
```

**Comment by ianna** [comment]
@delannoy - thanks for brining it up! I think, we do want to be as close as possible to `Numpy`. Python, from version 2.3 forward, has a `bool` type which is a subclass of `int`, the standard integer type. It has two possible values: `True` and `False`, which are special versions of `1` and `0` respectively and behave as such in arithmetic contexts.

**Comment by agoose77** [comment]
Agreed with @ianna, we should support this. I'll make a PR! Thanks for the report :)
