### ISSUE TITLE
`NumpyArray.__array__` and `EmptyArray.__array__` are to be removed in 2.6.0

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2969]
They're deprecated and already raise warnings. When 2.6.0 comes, they need to be explicitly removed.

**Comment by jpivarski** [comment]
#2969 was the original issue that brought this up.

**Comment by agoose77** [comment]
@jpivarski #2969 is _this_ issue, did you make a typo? :) Ah, I'm guessing #2339

**Comment by jpivarski** [comment]
Yes, that's it! I must have had the wrong thing in my clipboard buffer.

**Comment by agoose77** [comment]
@jpivarski was this closed by https://github.com/scikit-hep/awkward/pull/2997? Assuming so.

**Comment by jpivarski** [comment]
That's correct. When 2.6.0 was released, #2997 made `NumpyArray.__array__` and `EmptyArray.__array__` an error, and so this issue reminding us that it still needs to be done is now finished.
