### ISSUE TITLE
fsspec needs a version limit in 

### ISSUE THREAD

**Issue by jasondet** [scikit-hep/awkward#3002]
### Version of Awkward Array

2.6.0

### Description and code to reproduce

I had a very old version of fsspec installed when I installed awkward. Upon import awkward I got:

```
File "/path/to/lib/python3.9/site-packages/awkward/operations/ak_from_parquet.py", line 5, in <module>
    import fsspec.parquet
ModuleNotFoundError: No module named 'fsspec.parquet'
```

I think fsspec.parquet has only been available since late 2021. The [requirements](https://github.com/scikit-hep/awkward/blob/main/requirements-test-minimal.txt) [lists](https://github.com/scikit-hep/awkward/blob/main/requirements-test-full.txt) should specify recent versions of fsspec that work.

**Comment by jpivarski** [comment]
We've been testing fsspec since November 2022 (0a80b2a09f8ae81264d1fa214c4b3c7df7fef88c), so I'll take that as the minimum version. It has `fsspec.parquet` ([proof](https://github.com/fsspec/filesystem_spec/blob/2022.11.0/fsspec/parquet.py)).

I'll get this into an Awkward version 2.6.1 right away.
