### ISSUE TITLE
`ak.zip` does not accept record objects

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#3023]
### Version of Awkward Array

main

### Description and code to reproduce

Introduced by scikit-hep/awkward#2757

**Comment by jpivarski** [comment]
Copied from https://github.com/scikit-hep/fastjet/issues/268#issuecomment-1941946630:

> I just saw your note, @agoose77: you consider it a regression but I don't! I don't think zipping over a record makes sense, since zipping is something that applies to collections. The same applies to the numerical scalars (`msoftdrop`, etc.).
>
> * If all fields of the `ak.zip` are collections (of equal length), then that's the normal case, we know what to do.
> * If some fields of the `ak.zip` are scalars (either records or numbers) and some are collections, then `ak.zip` should broadcast the scalars to the collections in order to be consistent, but that's not likely the user's intention. In this case, I thought it was pretty clear that only one overall value of `msoftdrop`, etc. is desired, not one per constituent.
> * If all fields are scalars, `ak.zip` doesn't have any clear meaning. If you want a single record to be built from those scalars, use the `ak.Record` constructor (as in the second example above).
>
> So `ak.zip` should at least refuse the all-scalars case and should probably exclude the some-scalars case. (Although I suppose that it's not excluding all-numbers right now.)

**Comment by agoose77** [comment]
I like this rationale! Closing.
