### ISSUE TITLE
awkward._nplikes.typetracer.TypeTracerArray._new needs further optimization, it is hot code 

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#3036]
### Version of Awkward Array

2.6.1

### Description and code to reproduce

The present code is below:
```python3
    @classmethod
    def _new(
        cls,
        dtype: DType,
        shape: tuple[ShapeItem, ...],
        form_key: str | None = None,
        report: TypeTracerReport | None = None,
    ):
        self = super().__new__(cls)
        self.form_key = form_key
        self.report = report

        if not isinstance(shape, tuple):
            raise TypeError("typetracer shape must be a tuple")
        if not all(isinstance(x, int) or x is unknown_length for x in shape):
            raise TypeError("typetracer shape must be integers or unknown-length")
        if not isinstance(dtype, np.dtype):
            raise TypeError("typetracer dtype must be an instance of np.dtype")
        self._shape = shape
        self._dtype = dtype

        return self
```

in particular:
```python3
        if not isinstance(shape, tuple):
            raise TypeError("typetracer shape must be a tuple")
        if not all(isinstance(x, int) or x is unknown_length for x in shape):
            raise TypeError("typetracer shape must be integers or unknown-length")
        if not isinstance(dtype, np.dtype):
            raise TypeError("typetracer dtype must be an instance of np.dtype")
```
is quite expensive at the scale of thousands of awkward array kernel calls and in normal, non-development, operation none of these if statements ever evaluate to True. They are relatively expensive to evaluate when there is no data processing, see for example typetracing in dask-awkward.

We know already that commenting out these lines brings significant performance improvements.
A reasonable alternative to that would be wrapping this code in an if block.

```python3
    @classmethod
    def _new(
        cls,
        dtype: DType,
        shape: tuple[ShapeItem, ...],
        form_key: str | None = None,
        report: TypeTracerReport | None = None,
    ):
        self = super().__new__(cls)
        self.form_key = form_key
        self.report = report

        if __development_build__:
            if not isinstance(shape, tuple):
                raise TypeError("typetracer shape must be a tuple")
            if not all(isinstance(x, int) or x is unknown_length for x in shape):
                raise TypeError("typetracer shape must be integers or unknown-length")
            if not isinstance(dtype, np.dtype):
                raise TypeError("typetracer dtype must be an instance of np.dtype")
        self._shape = shape
        self._dtype = dtype

        return self
```

Where `__development_build__` is just a stand in name. I think the only requirements would be that the parameter to the if statement is a simple bool, no lookups (etc.), as this is known to be pretty hot code.

Savings are O(1s) for a complex HEP analysis when building a single few-thousand layer task graph. This corresponds to many minutes saved in processing for full-scale analysis.

@jpivarski @agoose77 @martindurant

**Comment by martindurant** [comment]
Connected thought that occurred: should TypeTracerArray have `__slots__`?

**Comment by jpivarski** [comment]
The first check would be to determine if it _can_ have `__slots__`. If you declare something with `__slots__` and then try to assign to an unrecognized attribute, it will raise an error (in PYthon 3.10, anyway):

```python
 >>> class Something:
...     __slots__ = ["one", "two"]
...     def __init__(self):
...         self.one = 1
...         self.two = 2
... 
>>> something = Something()
>>> something.three = 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Something' object has no attribute 'three'
```

So let's try giving it `__slots__` and seeing if any of the tests fail with an `AttributeError`.

```diff
index 1e2812be..58d21b7f 100644
--- a/src/awkward/_nplikes/typetracer.py
+++ b/src/awkward/_nplikes/typetracer.py
@@ -161,6 +161,7 @@ class TypeTracerReport:
 
 
 class TypeTracerArray(NDArrayOperatorsMixin, ArrayLike):
+    __slots__ = ("_form_key", "_report", "_shape", "_dtype")
     _dtype: numpy.dtype
     _shape: tuple[ShapeItem, ...]
```

--------------------

<p align="center">♫♫ (on-hold music) ♫♫</p>

--------------------

All of the awkward, dask-awkward tests pass.

Coffea tests have these failures on my computer:

```
tests/test_dataset_tools.py::test_apply_to_fileset_hinted_form FAILED
tests/test_dataset_tools.py::test_preprocess_calculate_form FAILED
=== 2 failed, 224 passed, 3 skipped, 1 xfailed, 297 warnings in 875.36s (0:14:35) ===
```

(14 minutes!) But they're both

```
            if save_form:
                form_str = uproot.dask(
                    tree,
                    ak_add_doc=True,
                    filter_name=no_filter,
                    filter_typename=no_filter,
                    filter_branch=partial(_remove_not_interpretable, emit_warning=False),
                ).layout.form.to_json()
>               dask.base.function_cache.popitem()
E               AttributeError: module 'dask.base' has no attribute 'function_cache'

src/coffea/dataset_tools/preprocess.py:89: AttributeError
```

(I have Dask 2024.2.1). It doesn't seem to be related.

So we _can_ add `__slots__` to TypeTracerArray if it makes a performance difference.

**Comment by lgray** [comment]
Yeah the most recent coffea is not compatible with dask 2024.2.x. Once we get a new dask awkward release that'll be fixed.

**Comment by lgray** [comment]
FYI `__slots__` doesn't seem to do much of anything in terms of performance but could be used in conjunction with type checks to remove the need for the the if statements in the first place, I suppose.

**Comment by agoose77** [comment]
@lgray from a safety perspective, I am reluctant to entirely disable these checks - they serve a purpose in identifying "wrong" constructions. As I recall, Coffea builds N graphs in a loop, could we perhaps expose a context manager that disables the checks and have Coffea invoke it for `N-1` of the passes? You suggested in a previous conversation that each graph may be slightly different, is this just from a partitioning perspective? i.e. the actual business logic is identical? If this assumption doesn't hold, can you think of a strategy whereby we get good safety guarantees whilst also improving perf?

I'm thinking of something like
```python
it_runs = iter(runs)

process_run(
    next(it_runs)
)

with ak.typetracer.safety_checks_disabled():
    for run in it_runs:
        process_run(run)
```

**Comment by jpivarski** [comment]
By "removing," we're talking about wrapping the type checks in `if __debug__`, which is functionally the same as `ak.typetracer.safety_checks_disabled()` but probably faster because it's a Python built-in. Coffea users can then run with `-O` by default, but fall back to not `-O`.

Is there any way to tell, by looking at the surrounding code, whether these checks can ever fail in practice? The uses of `TypeTracerArray._new` seem to be well contained to the _nplikes/typetracer.py module, and it looks like the data types that are passed in are all strictly dtypes and shapes:

```
src/awkward/typetracer.py:    return TypeTracerArray._new(np.dtype(dtype), shape=())
src/awkward/contents/numpyarray.py:            return TypeTracerArray._new(self._data.dtype, shape=())
grep: src/awkward/_nplikes/__pycache__/typetracer.cpython-310.pyc: binary file matches
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(result_dtypes[0], shape=broadcasted_shape)
src/awkward/_nplikes/typetracer.py:                TypeTracerArray._new(dtype, shape=broadcasted_shape)
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(result_dtypes[0], shape=broadcasted_shape)
src/awkward/_nplikes/typetracer.py:                TypeTracerArray._new(dtype, shape=broadcasted_shape)
src/awkward/_nplikes/typetracer.py:                return TypeTracerArray._new(
src/awkward/_nplikes/typetracer.py:                return TypeTracerArray._new(
src/awkward/_nplikes/typetracer.py:                    return TypeTracerArray._new(obj.dtype, obj.shape)
src/awkward/_nplikes/typetracer.py:                return TypeTracerArray._new(as_array.dtype, ())
src/awkward/_nplikes/typetracer.py:                return TypeTracerArray._new(dtype, shape=tuple(shape))
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(dtype, shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(dtype, shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(dtype, shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(dtype, shape)
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(dtype, shape=())
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(dtype, shape=x.shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(dtype, (length,))
src/awkward/_nplikes/typetracer.py:        return [TypeTracerArray._new(dtype, shape=tuple(shape)) for _ in arrays]
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(x.dtype, (values.size,))
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(np.dtype(np.int64), shape=())
src/awkward/_nplikes/typetracer.py:        return [TypeTracerArray._new(x.dtype, shape=shape) for x in all_arrays]
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(x.dtype, shape=new_shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(x.dtype, tuple(new_shape), x.form_key, x.report)
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(x.dtype, (x.size,))
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(x.dtype, x.shape)
src/awkward/_nplikes/typetracer.py:        return (TypeTracerArray._new(np.dtype(np.int64), (unknown_length,)),) * len(
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(result_dtype, shape=condition.shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(x.dtype, shape=(unknown_length,))
src/awkward/_nplikes/typetracer.py:            TypeTracerArray._new(x.dtype, shape=(unknown_length,)),
src/awkward/_nplikes/typetracer.py:            TypeTracerArray._new(np.dtype(np.int64), shape=(unknown_length,)),
src/awkward/_nplikes/typetracer.py:            TypeTracerArray._new(np.dtype(np.int64), shape=x.shape),
src/awkward/_nplikes/typetracer.py:            TypeTracerArray._new(np.dtype(np.int64), shape=(unknown_length,)),
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(x.dtype, shape=x.shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(x.dtype, (size,))
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(x.dtype, shape=tuple(shape))
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(result.dtype, result.shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(x.dtype, shape=x.shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(np.dtype(np.bool_), shape=out.shape)
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(np.dtype(np.bool_), shape=x.shape)
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(np.dtype(np.bool_), shape=tuple(next_shape))
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(np.dtype(np.bool_), shape=tuple(next_shape))
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(np.dtype(np.intp), shape=())
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(x.dtype, shape=tuple(next_shape))
src/awkward/_nplikes/typetracer.py:            return TypeTracerArray._new(x.dtype, shape=tuple(next_shape))
src/awkward/_nplikes/typetracer.py:        return TypeTracerArray._new(np.dtype(dtype), x.shape)
```

**Comment by agoose77** [comment]
@jpivarski I think we actually didn't settle on one or the other. I'm in favour of the `__debug__` approach from a perf / simplicity approach, but I suspect it won't help hugely as we don't use `asserts` that much. Also, we can't toggle on/off this logic at runtime. I think we can bring the context-manager version to close performance of the debug mode simply by switching out the contractor for a no-checks variant (by patching).

@jpivarski I think you're probably right that it's not urgently needed. But I worry that by having coffea just disable these permanently, we won't be protected from regressions in code that is predominantly only tested by coffea.

**Comment by lgray** [comment]
Unfortunately the graphs will not just be different from the partitioning perspective. There *will* be some small-ish number of categories of graphs that are only different by partitions, but it is much less error prone to simply build each of the graphs. 

Asking users to guess what their code is going to do and group their datasets by that, especially as they are developing/forking it over months or years as an analysis group iterates and evolves (and the input data changes as formats evolve), will likely generate more pain and dissatisfaction than benefit. 

I suppose the physics oriented grouping for this will be essentially grouping datasets by sources of systematic uncertainties, but even in that case the calculations can differ by metadata that's be stuck somewhere deep in the task graph. Changing that after the fact will be delicate at best, and these are all issues where the user will have to manage the failures, rather than an expert.

**Comment by lgray** [comment]
@agoose77 I think your context manager setup idea would work well so long as the performance can be maintained, especially since it can be hidden from users instead of handing them arcane instructions.

**Comment by martindurant** [comment]
I am -1 on using `__debug__`, because it requires python to be run with special environment/command line options that will affect all packages, not just ours, and require extra effort from the users.

The context manager and bool variable are the same thing (the latter could be "hidden"), I see no big problem with every coffea analysis run calling `typetracer_check(off=True)` or something at the start.

What would be the consequence of letting through incorrect types here? I would bet a type/value/attribute error in code soon following. Which is fine.
