### ISSUE TITLE
Remember to add a high-level interface to sorting (ak.sort)

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#304]
It should NEP 18 to [np.sort](https://numpy.org/doc/1.18/reference/generated/numpy.sort.html). There's no equivalent for our `ascending` or their `order`, though `kind` can be partially supported because `kind="stable"` corresponds to our `stable=True`. (Is our `stable=False` one of "quicksort", "mergesort", "heapsort"?)

I meant to include this in #168, but forgot.

**Comment by ianna** [comment]
**C++’s sort()** – Introsort (Hybrid of Quicksort, Heap Sort and Insertion Sort)

- Best Case Time Complexity- O(NlogN)
- Average Case Time Complexity- O(NlogN)
- Worse Case Time Complexity- O(NlogN)
- Auxiliary Space- O(logN)
- Stable- No
- Adaptive- No

**C++’s stable_sort()** – Mergesort

- Best Case Time Complexity- O(NlogN)
- Average Case Time Complexity- O(NlogN)
- Worse Case Time Complexity- O(NlogN)
- Auxiliary Space- O(N)
- Stable- Yes
- Adaptive- Yes
