### ISSUE TITLE
from_rdataframe does not work for distributed rdataframe

### ISSUE THREAD

**Issue by AlkaidCheng** [scikit-hep/awkward#3061]
### Version of Awkward Array

2.6.2

### Description and code to reproduce

For distributed RDataFrames, e.g. with dask or spark backends, some operations are not exposed including `GetColumnType` which is used by the `ak.from_rdataframe` method.

Reproducer:
```
import ROOT
import awkward as ak
from dask.distributed import LocalCluster, Client

RDataFrame = ROOT.RDF.Experimental.Distributed.Dask.RDataFrame

cluster = LocalCluster(n_workers=4, threads_per_worker=1, processes=True)
client = Client(cluster)
rdf = RDataFrame(1000, daskclient=client).Define("x", "1")

array = ak.from_rdataframe(rdf, columns=['x'])
```

which gives the error:

```
AttributeError: 'Define' object has no attribute 'GetColumnType'

This error occurred while calling

    ak.from_rdataframe(
        NodeProxy-instance
        columns = ['x']
    )
```

One way to solve this will be to access the `GetColumnType` method internally (this is not ideal, an [issue ](https://github.com/root-project/root/issues/15039)is submitted to ROOT github):
```
rdf._headnode._localdf.GetColumnType
```

**Comment by ianna** [comment]
@AlkaidCheng - Thanks for finding and reporting the bug! I’m going to fix it asap. Thanks!

**Comment by ianna** [comment]
@AlkaidCheng - am I missing something? With the reproducer I get an empty `HeadNode`. Thanks!

```
>>> head_node = rdf.proxied_node.get_head()
>>> head_node
<DistRDF.HeadNode.EmptySourceHeadNode object at 0x175b8e050>
>>> head_node.GetColumnNames()
vector<string>{}
```
