### ISSUE TITLE
Generate unit tests for kernels

### ISSUE THREAD

**Issue by reikdas** [scikit-hep/awkward#309]
Using the roles assigned to the CPU kernels in #301 we need to generate "relevant"  tests for each of the kernels. All the kernel implementations - C++, Python, CUDA would need to pass these tests.

**Comment by jpivarski** [comment]
I think this is done; the card can be moved. (Unless you want to define "done" by having an appropriate set of proto-samples—though that could be a new card, too.)

**Comment by reikdas** [comment]
I am closing this. I'll make the appropriate set of proto-samples a new card. 
(Closed by #307)
