### ISSUE TITLE
ak.to_arrow should convert to string instead of large_string

### ISSUE THREAD

**Issue by martindurant** [scikit-hep/awkward#312]
If you load the bikeroutes from [here](https://github.com/jpivarski/2020-07-06-scipy2020/blob/c951aa50bbfa879f011c9f2c343a3d0168be28e0/bikeroutes-execution.ipynb) and try to convert to arrow, it works:
```
arr2 = ak.to_arrow(bikeroutes['features']). # cannot convert the top-level Record, so lose some attributes
t = pa.Table.from_arrays([arr2], names=['features'])
```
but this cannot be written to parquet because the schema is as follows
```
features: struct<type: large_string, properties: struct<STREET: large_string, TYPE: large_string, BIKEROUTE: large_string, F_STREET: large_string, T_STREET: dictionary<values=large_string, indices=int64, ordered=0>>, geometry: struct<type: large_string, coordinates: large_list<item: large_list<item: large_list<item: double>>>>>
  child 0, type: large_string
  child 1, properties: struct<STREET: large_string, TYPE: large_string, BIKEROUTE: large_string, F_STREET: large_string, T_STREET: dictionary<values=large_string, indices=int64, ordered=0>>
      child 0, STREET: large_string
      child 1, TYPE: large_string
      child 2, BIKEROUTE: large_string
      child 3, F_STREET: large_string
      child 4, T_STREET: dictionary<values=large_string, indices=int64, ordered=0>
  child 2, geometry: struct<type: large_string, coordinates: large_list<item: large_list<item: large_list<item: double>>>>
      child 0, type: large_string
      child 1, coordinates: large_list<item: large_list<item: large_list<item: double>>>
          child 0, item: large_list<item: large_list<item: double>>
              child 0, item: large_list<item: double>
                  child 0, item: double
```
Arrow doesn't know how to write the "large strings", but none of the input actually has any strings long enough to need that, would be 2**31 bytes, 2GB. Of course, arrow *should* be able to cope, but it does not.

**Comment by martindurant** [comment]
In practice, I believe this would need converting large_binary -> binary and LargeStringArray->StringArray in to_arrow; but I also wonder at large_list and the like.

**Comment by jpivarski** [comment]
This is a good point and worth fixing, though I know how it happened. Awkward defaults to 64-bit when not constrained by inputs, but Arrow likes 32-bit. The policy should be different: instead of trying the closest type-match, it should use minimum sizes for the scale of the array.

**Comment by jpivarski** [comment]
It's also a good first issue because the translation is all in two functions in awkward1.operatons.convert, on the Python side.

**Comment by martindurant** [comment]
> but Arrow likes 32-bit

In this case, also a limitation of parquet's string representation.
