### ISSUE TITLE
An assumption in the "Needs C++ Release" test has broken

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#3200]
This test is supposed to download a source tarball of awkward-cpp from PyPI and rebuild from the repo, then compare them to see if they are meaningfully different (and if we need to build a new awkward-cpp). When this test fails, it's time to deploy a new version of awkward-cpp to PyPI.

But now the test is failing with an up-to-date awkward-cpp ([the last version](https://pypi.org/project/awkward-cpp/#history) was released just an hour ago). Looking at the logs, it's trying to compare two files, presumably the locally built one and the downloaded one, but one file is not in the directory:

```
2024-08-02T17:12:08.5362009Z FileNotFoundError: [Errno 2] No such file or directory: 'awkward-cpp/dist/awkward-cpp*.tar.gz'
2024-08-02T17:12:08.5437373Z nox > Command python dev/check-awkward-cpp-sdist-matches-pypi.py 'awkward-cpp/dist/awkward-cpp*.tar.gz' failed with exit code 1
2024-08-02T17:12:08.5438539Z nox > Session check_cpp_sdist_released failed.
```

In the `dist` directory, this is the locally built copy, right? The compilation has no error. Does it get built to a different directory from `dist` now?

@agoose77 or @henryiii, does something immediately jump out at you, looking at [the logs](https://github.com/scikit-hep/awkward/actions/runs/10219398129/job/28277613521)?

To make sure they're persistent, I'll copy them below.

<details>

```
https://productionresultssa3.blob.core.windows.net/actions-results/fdc609a7-6c11-454d-8ec5-98088fbc66bc/workflow-job-run-63a2cb91-8ad8-5cd3-8d2b-2dfb6a036349/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-02T17%3A22%3A28Z&sig=bKd2qRZ%2BTI7MDV5bThJjIjJGRjgIqHj4iJz49Hx2JMo%3D&ske=2024-08-03T03%3A28%3A00Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-02T15%3A28%3A00Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-02T17%3A12%3A23Z&sv=2024-05-04
```

</details>

**Comment by agoose77** [comment]
Will take a look at this in twenty mins.

**Comment by henryiii** [comment]
We've bumped the minimum version of scikit-build-core in https://github.com/scikit-hep/awkward/pull/3167 from 0.2 to 0.9, and 0.5+ (IIRC) normalizes the SDist name. So `awkward-cpp/dist/awkward-cpp*.tar.gz` should be `awkward-cpp/dist/awkward_cpp*.tar.gz` now.
