### ISSUE TITLE
Change function from recursive -> iterative

### ISSUE THREAD

**Issue by reikdas** [scikit-hep/awkward#321]
There are some CPU kernels that need to be changed from being recursive to iterative (to make it easier to generate equivalent CUDA kernels)
Like - 
https://github.com/scikit-hep/awkward-1.0/blob/master/src/cpu-kernels/getitem.cpp#L274
https://github.com/scikit-hep/awkward-1.0/blob/master/src/cpu-kernels/operations.cpp#L3268

These are non-trivial with each of the recursive calls being inside loops and I spent enough hours on them, that I thought I should make them into an issue.

I am trying to do this with highest priority as it is a blocker for progress with https://github.com/scikit-hep/awkward-1.0/pull/307

**Comment by jpivarski** [comment]
Not necessary.
