### ISSUE TITLE
Argcombinations not taking negative axis values

### ISSUE THREAD

**Issue by mghern** [scikit-hep/awkward#3300]
### Version of Awkward Array

2.7.0

### Description and code to reproduce

ak.argcombinations is not accepting negative axis values. It seems to be an issue of inconsistent documentation, as the [api reference](https://awkward-array.org/doc/main/reference/generated/ak.argcombinations.html#ak.argcombinations) says negative axis values should be accepted but this value error is coded into the function class.
`    if axis < 0:
        raise ValueError("the 'axis' for argcombinations must be non-negative")
    else:`
  Is there a reason for combinations to accept negative axis numbers while argcombinations does not?

**Comment by jpivarski** [comment]
Yeah, I don't see any reason for that. `ak.argcombinations` does a little more than `ak.combinations`: it has to call `ak.local_index`. But `ak.local_index` has no problem with negative `axis`.

I just compared the `ak.argcombinations` code and the `ak.combinations` code and see no reason to exclude negative axis, so I just removed the check in #3301.
