### ISSUE TITLE
Layout indexes don't support slices

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#333]
Sometimes, when building arrays at a low level, it is useful to manipulate `Index64` and similar from python.
The usual getitem method does not accept python slices, however:
```python
import awkward1
a = awkward1.Array([[1, 2, 3], [4, 5], [6]])
a.layout.offsets[:-1]
```
gives:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-53dc196bd178> in <module>
      2 
      3 a = awkward1.Array([[1, 2, 3], [4, 5], [6]])
----> 4 a.layout.offsets[:-1]

TypeError: __getitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: awkward1._ext.Index64, arg0: int) -> int
    2. (self: awkward1._ext.Index64, arg0: int, arg1: int) -> awkward1._ext.Index64

Invoked with: <Index64 i="[0 3 5 6]" offset="0" length="4" at="0x7f869cad1a00"/>, slice(None, -1, None)
```

Amusingly, one can do `a.layout.offsets.__getitem__(0, -1)`

**Comment by jpivarski** [comment]
Since this is a known fact about these low-level objects, it might make more sense to call this a feature request. But yeah, it would definitely make life easier for developers who are building things on top of Awkward if they could treat `Index` as a normal array-like object.
