### ISSUE TITLE
Materialization issue when loading partitioned parquet files

### ISSUE THREAD

**Issue by riga** [scikit-hep/awkward#3331]
### Version of Awkward Array

2.7.2

### Description and code to reproduce

Hi!

I'm using `dask_awkward` to partially load a file, so the issue below could potentially also come from there. However, the stack trace rather points to something in `awkward` itself, which is why I opened the issue here.

---

I'm loading a parquet file with `dask_awkward` and immediately call `.compute()` on a slice of that file. By default, `dak.from_parquet` considers all partitions merged, so when loading the first, say, 1000 entries,

```python
f = dak.from_parquet("file.parquet")
events = f[:1000].compute()  # <-- works
```

the entire file (i.e., all entries) is loaded into memory, which is a situation we try to avoid. We build our parquet files to have several partitions of a certain size and intend to set `split_row_groups=True`. However,

```python
f = dak.from_parquet("file.parquet", split_row_groups=True)
events = f[:1000].compute()  # <-- fails
```

fails. You can find the full stack trace below. Also, when explicitly materializing the first partition and checking the layout,

```python
events = f.partitions[0].compute()
print(events.layout)
print(events)  # <-- fails
```

`.compute()` works, and so does `events.layout`, but `print(events)` itself fails, which seems to originate from parts of the code that build the string representation.

I created a [reproducer script](https://gist.github.com/riga/a1a6a222e1efb306df7a0efdcc6608d3) using this [input file](https://cernbox.cern.ch/s/Z99QJgvaYjX7uhS) (two partitions with 50k entries each), which produces the output below.

Thanks for having a look, I'm happy to help debugging :)

---

```
pyarrow version: 18.0.0
awkward version: 2.7.2
dask_awkward version: 2024.11.0
dask version: 2024.11.0

--------------------------------------------------------------------------------

f.npartitions=1
[{MET: {phi: 2.15, pt: 70.7}, Tau: [{...}]}, ..., {MET: {...}, Tau: [...]}]

--------------------------------------------------------------------------------

f.npartitions=2
Traceback (most recent call last):
  File "/.../partition_issue.py", line 31, in test
    print(f[:1000].compute())
  File "/.../python3.11/site-packages/awkward/highlevel.py", line 1344, in __str__
    return prettyprint_valuestr(self, 1, 80)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.11/site-packages/awkward/prettyprint.py", line 356, in valuestr
    _, strs = valuestr_horiz(data, limit_cols, formatter)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.11/site-packages/awkward/prettyprint.py", line 161, in valuestr_horiz
    cols_taken, strs = valuestr_horiz(
                       ^^^^^^^^^^^^^^^
  File "/.../python3.11/site-packages/awkward/prettyprint.py", line 236, in valuestr_horiz
    get_field(data, key), target, formatter
    ^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.11/site-packages/awkward/prettyprint.py", line 96, in get_field
    out = data._layout._getitem_field(field)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.11/site-packages/awkward/record.py", line 191, in _getitem_field
    return self._array._getitem_field(where)._getitem_at(self._at)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.11/site-packages/awkward/contents/listoffsetarray.py", line 327, in _getitem_at
    start, stop = self._offsets[where], self._offsets[where + 1]
                  ~~~~~~~~~~~~~^^^^^^^
  File "/.../python3.11/site-packages/awkward/index.py", line 235, in __getitem__
    out = self._data[where]
          ~~~~~~~~~~^^^^^^^
  File "/.../python3.11/site-packages/awkward/_nplikes/placeholder.py", line 97, in __getitem__
    raise TypeError(
TypeError: PlaceholderArray supports only trivial slices, not int64
<RecordArray is_tuple='false' len='50000'>
    <content index='0' field='MET'>
        <RecordArray is_tuple='false' len='50000'>
            <content index='0' field='phi'>
                <NumpyArray dtype='float32' len='50000'>
                    [ 2.1539881  -0.82861495 -2.652956   ... -1.2977237
                      2.7458863   0.8530113 ]
                </NumpyArray>
            </content>
            <content index='1' field='pt'>
                <NumpyArray dtype='float32' len='50000'>
                    [ 70.725204 193.27147   27.851917 ...  54.219837  35.124985
                      81.4471  ]
                </NumpyArray>
            </content>
        </RecordArray>
    </content>
    <content index='1' field='Tau'>
        <ListOffsetArray len='50000'>
            <offsets><Index dtype='int64' len='50001'>[## ... ##]</Index></offsets>
            <content><RecordArray is_tuple='false' len='##'>
                <content index='0' field='mass'>
                    <NumpyArray dtype='float32' len='##'>[## ... ##]</NumpyArray>
                </content>
                <content index='1' field='pt'>
                    <NumpyArray dtype='float32' len='##'>[## ... ##]</NumpyArray>
                </content>
            </RecordArray></content>
        </ListOffsetArray>
    </content>
</RecordArray>
```

**Comment by pfackeldey** [comment]
Hi @riga,
Thanks for the report!

To me it seems right now that there's a problem with loading the "Tau" field (you see this because in the layout there are no concrete values just "##" as placeholders). 
In fact, the "Tau" field _only_ gets loaded when one asks for everything, i.e. `ak.from_parquet("test_2p.parquet")` or `dak.from_parquet("test_2p.parquet", split_row_groups=False)`.

My expectation would be that (and I assume yours too):
```python
import dask_awkward as dak

arr = dak.from_parquet("test_2p.parquet", split_row_groups=True)

materialized_partition = arr.partition[0].compute()
print(materialized_partition)
# > ... TypeError: PlaceholderArray supports only trivial slices, not int64 ...
```
`materialized_partition ` would have "MET" and "Tau" materialized, but only for the first "chunk/partition" of events - however it doesn't load column "Tau" at all in this case

---

Now, when I explicitly tell it the columns to load (inferred from `ak.ak_from_parquet.metadata`), it works correctly:
```python
import awkward as ak

columns, *_ =  ak.ak_from_parquet.metadata("test_2p.parquet")

dak_arr = dak.from_parquet("test_2p.parquet", columns=columns, split_row_groups=True)

materialized_partition = dak_arr.partitions[0].compute()
print(materialized_partition)
# > <Array [{MET: {phi: 2.15, ...}}, ..., {...}] type='50000 * {MET: {phi: floa...'>
```

My current understanding is that `dask-awkward` does not correctly infer the columns with `ak.ak_from_parquet.metadata` for your parquet file (it seems to not pass the correct columns here: https://github.com/dask-contrib/dask-awkward/blob/main/src/dask_awkward/lib/io/parquet.py#L223).

To me this looks like a pure `dask-awkward` issue, I'll look into a fix over there :+1:

**Comment by pfackeldey** [comment]
It looks like the separator that indicates a `ListOffsetArray` is different:
- In your file: `'Tau.list.element.mass'`
- What dask-awkward passes to the [reading method](https://github.com/dask-contrib/dask-awkward/blob/main/src/dask_awkward/lib/io/parquet.py#L223): `'Tau.list.item.mass'`

In this reading method `self.columns` corresponds to `['MET.phi', 'MET.pt', 'Tau.list.item.mass', 'Tau.list.item.pt']`. If I pass the columns with `list.element` instead it works:
```python
In [0]: ak_from_parquet._load(
    ...:             [source],
    ...:             parquet_columns=['MET.phi', 'MET.pt', 'Tau.list.element.mass', 'Tau.list.element.pt'],
    ...:             subrg=subrg,
    ...:             subform=self.form,
    ...:             highlevel=True,
    ...:             fs=self.fs,
    ...:             behavior=self.behavior,
    ...:             attrs=self.attrs,
    ...:             **self.kwargs,
    ...:         )
Out[1]: <Array [{MET: {...}, Tau: [{...}]}, ..., {...}] type='50000 * {MET: {phi: f...'>
```

I'm not that experienced with parquet, maybe @jpivarski can quickly clarify the difference between `list.element` and `list.item`, and sees what's going wrong here?

**Comment by riga** [comment]
Thanks for looking into this @pfackeldey !

**Comment by riga** [comment]
Following a private discussion, I can confirm that the problem is indeed related to the difference between how `Tau.list.element.mass` and `Tau.list.item.mass` are handled, and for partitioned materialization (`split_row_groups=True`), only the latter works (not sure if this is intended though).

Parquet files created by `ak.to_parquet` already use the `*.list.item.*` node structure, but we have a custom merging step in our pipeline that manually uses a `pyarrow.parquet.ParquetWriter` instance for the job, which converts them to `*.list.element.*`. Passing `use_compliant_nested_type=True` preserves the structure and eventually did the trick.

Thanks @pfackeldey 💯
