### ISSUE TITLE
Getting the size of axes by name

### ISSUE THREAD

**Issue by kumar-neelabh-archive** [scikit-hep/awkward#3351]
### Description of new feature

![image](https://github.com/user-attachments/assets/52c9ad0f-f4b7-4de2-9d83-fc1bbe5379d4)
This may be a silly question, but I could not find any way to get the lengths of axes by name (or even by position). For example, in my code, I want to know the number of trials, timesteps, and neurons. Awkward Array has this information but there doesn't seem to be a way to access it. (I tried to access those using awkward_array.type but to no avail.)

**Comment by jpivarski** [comment]
Is [ak.num](https://awkward-array.org/doc/main/reference/generated/ak.num.html) what you're looking for? This function takes `axis` as an argument, which can be a named axis. In your case, `axis=0` would give you 275 (the length of the array) and `axis=2` would give you an array filled with 67 (the length of that regular dimension), but for the other axis, `axis=1`, it would give you an array of the lengths of each list, which are in principle variable (but might happen to be constant).

**Comment by kumar-neelabh-archive** [comment]
I considered ak.num, but it does not seem to distinguish between fixed and variable dimensions. In my case, let's say, in one particular trial, there are 68 neurons. If I understand it correctly, the array filled with 67's will now have some 68's inside it. Can we have a feature that directly outputs the length of the axis, and (let's say) NaN if it's variable?

**Comment by jpivarski** [comment]
There isn't such a function because generally, we're interested in the length of each list. But, given an array with mixed regular and irregular dimensions,

```python
>>> import awkward as ak
>>> import numpy as np
>>> array = ak.Array(np.arange(2*3*5*7).reshape(2, 3, 5, 7))
>>> array
<Array [[[[0, 1, 2, ..., 5, 6], ...], ...], ...] type='2 * 3 * 5 * 7 * int64'>
>>> array = ak.from_regular(ak.from_regular(array, axis=1), axis=3)
>>> array
<Array [[[[0, 1, ..., 5, 6], ...], ...], ...] type='2 * var * 5 * var * int64'>
```

You can look at the type,

```python
>>> array.type
ArrayType(ListType(RegularType(ListType(NumpyType('int64')), 5)), 2, None)
```

and create what you want by recursion:

```python
>>> from awkward.types import ArrayType, ListType, RegularType
>>> def shapey(t):
...     if isinstance(t, ArrayType):
...         return (t.length,) + shapey(t.content)
...     elif isinstance(t, ListType):
...         return (None,) + shapey(t.content)
...     elif isinstance(t, RegularType):
...         return (t.size,) + shapey(t.content)
...     else:
...         return ()
... 
>>> shapey(array.type)
(2, None, 5, None)
```

The [Ragged](https://github.com/scikit-hep/ragged) library is a restriction of Awkward Array to only regular and irregular lists, which is what makes it possible to report a `shape` (not possible in general with Awkward Array because of all the types ignored in the `else` clause, above). Its `shape` is implemented in this way:

https://github.com/scikit-hep/ragged/blob/17dbf70e45cba592f493f478a2c1f600da537e1f/src/ragged/_spec_array_object.py#L39-L55

**Comment by kumar-neelabh-archive** [comment]
Thanks a lot for the solution!

Also, will you recommend using Ragged in my project? I ask because it's in very early stages of development, and doesn't seem to be actively maintained.

**Comment by jpivarski** [comment]
I didn't recommend Ragged outright because it does have missing features. (Everything that is implemented is correct, and everything that isn't is a `NotImplementedError`.) Hopefully, it will be finished by a summer student next summer.
