### ISSUE TITLE
Don't forget to add a high-level ak.numbers_to_type function.

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#376]
A high-level wrapper for the function @ianna added of the same name. It should go in src/awkward1/operations/structure.py.

**Comment by ianna** [comment]
@jpivarski - I guess, it would replace `ak.astype` https://github.com/scikit-hep/awkward-1.0/blob/master/src/awkward1/operations/structure.py#L2696

**Comment by jpivarski** [comment]
I see: it would just be renamed. That looks pretty easy.
