### ISSUE TITLE
pip installing awkward causes warning in brew about unexpected files being present

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/awkward#411]
After doing a `pip install awkward-1.0`, I get the following warnings from brew:

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libawkward-cpu-kernels.dylib
  /usr/local/lib/libawkward.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/awkward/Content.h
  /usr/local/include/awkward/Identities.h
  /usr/local/include/awkward/Index.h
  /usr/local/include/awkward/Iterator.h
  /usr/local/include/awkward/Reducer.h
  /usr/local/include/awkward/Slice.h
  /usr/local/include/awkward/array/EmptyArray.h
  /usr/local/include/awkward/array/IndexedArray.h
  /usr/local/include/awkward/array/ListArray.h
  /usr/local/include/awkward/array/ListOffsetArray.h
  /usr/local/include/awkward/array/None.h
  /usr/local/include/awkward/array/NumpyArray.h
  /usr/local/include/awkward/array/RawArray.h
  /usr/local/include/awkward/array/Record.h
  /usr/local/include/awkward/array/RecordArray.h
  /usr/local/include/awkward/array/RegularArray.h
  /usr/local/include/awkward/array/UnionArray.h
  /usr/local/include/awkward/builder/ArrayBuilder.h
  /usr/local/include/awkward/builder/ArrayBuilderOptions.h
  /usr/local/include/awkward/builder/BoolBuilder.h
  /usr/local/include/awkward/builder/Builder.h
  /usr/local/include/awkward/builder/Float64Builder.h
  /usr/local/include/awkward/builder/GrowableBuffer.h
  /usr/local/include/awkward/builder/IndexedBuilder.h
  /usr/local/include/awkward/builder/Int64Builder.h
  /usr/local/include/awkward/builder/ListBuilder.h
  /usr/local/include/awkward/builder/OptionBuilder.h
  /usr/local/include/awkward/builder/RecordBuilder.h
  /usr/local/include/awkward/builder/StringBuilder.h
  /usr/local/include/awkward/builder/TupleBuilder.h
  /usr/local/include/awkward/builder/UnionBuilder.h
  /usr/local/include/awkward/builder/UnknownBuilder.h
  /usr/local/include/awkward/cpu-kernels/getitem.h
  /usr/local/include/awkward/cpu-kernels/identities.h
  /usr/local/include/awkward/cpu-kernels/operations.h
  /usr/local/include/awkward/cpu-kernels/reducers.h
  /usr/local/include/awkward/cpu-kernels/util.h
  /usr/local/include/awkward/io/json.h
  /usr/local/include/awkward/io/root.h
  /usr/local/include/awkward/python/content.h
  /usr/local/include/awkward/python/identities.h
  /usr/local/include/awkward/python/index.h
  /usr/local/include/awkward/python/util.h
  /usr/local/include/awkward/type/ArrayType.h
  /usr/local/include/awkward/type/ListType.h
  /usr/local/include/awkward/type/OptionType.h
  /usr/local/include/awkward/type/PrimitiveType.h
  /usr/local/include/awkward/type/RecordType.h
  /usr/local/include/awkward/type/RegularType.h
  /usr/local/include/awkward/type/Type.h
  /usr/local/include/awkward/type/UnionType.h
  /usr/local/include/awkward/type/UnknownType.h
  /usr/local/include/awkward/util.h

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libawkward-cpu-kernels-static.a
  /usr/local/lib/libawkward-static.a
```

I'm still wrestling with the best place to put headers and libraries, but for now, might it be a good idea to split the package into two parts; a python-only part (with the compiled python modules), and a "using python packaging to distribute a non-python module" one? For example, if you wanted to add awkward-1 to a package manager, a simple `pip install awkward-1` currently would overwrite the files. In the spirit of pytest's `--disable_test_id_escaping_and_forfeit_all_rights_to_community_support`, you could call it `awkward-c-libraries-will-install-to-your-core-folders-if-not-in-a-virtual-environment` ;). Or, more realistically, `awkward-cpp`. (`awkward-core` would make it seem like `awkward` would depend on it, which it would not).

**Comment by jpivarski** [comment]
There's already a copy of all the libraries inside the Python module's directory, which no one can complain about—I can put any data files in there. Maybe the header files should go in there, too, and then maybe

```bash
python -m awkward1 --cflags --libs
```

could output

```bash
-std=c++11 -I/path/to/awkward1/include -L/path/to/awkward1/lib -lawkward -lawkward-cpu-kernels
```

like a `XYZ-config` executable?

**Comment by henryiii** [comment]
This might be the best solution. There is a dedicated "headers" slot in wheels (though it tends to go to `<>/include/site/python3.6`), I'm not sure if that's really used much; unless you hack it, it can't do nested folders 🤦 ).

Awkward1's CMake doesn't seem to support exporting targets for `find_package` `CONFIG` or use as a submodule, is that intended eventually? That might affect where we want to put libraries.

(I should become more knowledgeable about all this within a week or so)

**Comment by henryiii** [comment]
Don't know if this is still valid, but: https://blog.ionelmc.ro/presentations/packaging/#slide:16

**Comment by jpivarski** [comment]
On all three systems (Linux, MacOS, Windows), the header files, static libraries, and shared libraries are now strictly contained within the Python package. I assume I can put anything that I want in there, and uninstalling is a one-directory cleanup. That complicates dynamically linking against `libawkward.so` because now a path has to be established, but that's the price.

Awkward now has a config tool:

```bash
$ python -m awkward1.config --cflags --libs
-std=c++11 -I/path/to/awkward1/include -L/path/to/awkward1 -lawkward -lawkward-cpu-kernels
```

and a description of how to use it in context is in the [dependent-project documentation](https://github.com/scikit-hep/awkward-1.0/tree/master/dependent-project).

Furthermore, the dependent-project is now a formal part of the tests for Linux and MacOS. We'll know if downstream linking ever gets broken. Also, those [three tests](https://github.com/scikit-hep/awkward-1.0/blob/18921bba890c69414fadf0507736ea2a3fb48d38/.ci/azure-buildtest-awkward.yml#L321-L355) act as a demonstration of how to use it.
