### ISSUE TITLE
Pip3 install awkward1 on raspibian error

### ISSUE THREAD

**Issue by TheMasterRoot** [scikit-hep/awkward#419]
im trying to install the lib on a raspibian buster  but i cant 

im usinh python 3.7 and cmake 3.13
some one can help me ?

**Comment by jpivarski** [comment]
I had intended to try this out, but I'm not going to have a Raspberry Pi set up to try to do this anytime soon. Since we don't actually support this platform (that is, we don't provide a binary wheel), this would make a better StackOverflow question.
