### ISSUE TITLE
Performance of ufuncs

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#442]
Raised by @tamasgal in https://github.com/scikit-hep/uproot4/issues/90#issuecomment-689459702:

> Another problem, which I will post in a future issue that working with these arrays is far from the numpy performance (doing things like `arr > 0.5` takes ~2ms for 100 entries, while in numpy/Julia/C it should be more around a few hundred ns), but that's another story.

Original dataset: http://131.188.167.67:8889/doubly_jagged.root

```python
import uproot4
import awkward1 as ak
trks = uproot4.open("uproot-issue-90.root:E/Evt/trks")
array = trks["trks.rec_stages"].array()
ak.to_parquet(array, "awkward-issue-442.parquet")
array
# <Array [[[1, 2, 5, 3, 5, 4], ... 1], [1], [1]]] type='145028 * var * var * int64'>
```

As Parquet (faster to download and read into Awkward): https://drive.google.com/file/d/1JbiFaBaouH_amUxvGnsSHegYAQjRTJ8u/view?usp=sharing
As Pickle (larger, but retains structure: Parquet adds option-type, which complicates the performance analysis): https://drive.google.com/file/d/1KnYebahkvLK29ZggISGROHxjcpCUdO0H/view?usp=sharing

The basic idea of performance in Awkward Array is that we don't worry about the constant-time metadata manipulation but should worry about the linear-time scaling. In particular, computing `array > 3` of a doubly jagged array is pure Python: it unwraps the doubly jagged structure and calls NumPy's own `np.greater` on the inner flat content.

Because of the constant-time unwrapping, it shouldn't be surprising that the Awkward version doesn't start scaling until the array is at least 1000 entries or so. What _is_ surprising is that the linear scaling for Awkward doesn't line up with the linear scaling for NumPy, because in theory, _it isn't doing anything other than calling NumPy_.

![quick-plot](https://user-images.githubusercontent.com/1852447/92609164-e2e85e80-f27b-11ea-869c-25ac6177d292.png)

So this is a quandary.

**Comment by tamasgal** [comment]
You were faster a little bit! Here is a bit more detailed issue: https://github.com/scikit-hep/awkward-1.0/issues/443

**Comment by jpivarski** [comment]
Looking at your issue, I don't see how they're related. They might be related. I need to do a quick profile of this because there's a lot of linear time here that isn't due to NumPy, and I can't imagine what it might be.

**Comment by tamasgal** [comment]
Yes you are right, my issue is more related to the overhead when dealing with tinier bits of data.

**Comment by jpivarski** [comment]
PR #444 fixes the linear scaling issue:

![quick-plot-2](https://user-images.githubusercontent.com/1852447/92623284-a290dc80-f28b-11ea-9a33-144257b0b5ee.png)

The initial implementation conservatively assumed that ListArray/ListOffsetArray's starts/stops/offsets are always incompatible and have to be normalized to the same structure before applying the ufunc. That's why the discrepancy with NumPy scaled linearly: that normalization adjusts all of the starts/stops/offsets as well as the content to fit. In this case, there was _only one list_ in the calculation (`array < 3`), so of course it wouldn't need to be normalized to itself!

Now we check for consistency and only do the normalization if necessary, so simple cases are brought exactly in line with NumPy because only NumPy is doing anything that scales with the size of the array. I had thought about adding a check for this before, but functionality comes before optimization and I wasn't sure if the check for consistency might be as expensive as the normalization. Your example demonstrates that it's not—not by a long shot!

It is still the case that if you have any ListArrays with gaps (e.g. `stops[i] == N` and `starts[i + 1] != N`), the full normalization applies. This is because the ufunc is not supposed to be executed on unreachable data (e.g. `content[N]`). This is partly for performance, so that you're not running the ufunc on unreachable data that won't matter to the output anyway, but also for correctness: if the ufunc would raise an error for unreachable data but not for reachable data, then the ufunc should not raise an error. That will save person-years of head-scratching!

The scaling as presented above is what we expect and strive for: the arrays have to be relatively large (10000 entries in this example) before they perform as well as NumPy. Optimizing operations on tiny arrays is out of scope for the Awkward array-at-a-time functions. The whole idea is that you have big data to work on; if it's small and there's only one of them, you don't notice the fraction of a second anyway, but if you have a lot of small arrays, that doesn't fit our vectorized model well. For that, you'd want just-in-time compilations: Numba or Julia!

**Comment by tamasgal** [comment]
Awesome, thanks for both the implementation and the fix!

...and of course for the detailed description of the whole problem
