### ISSUE TITLE
Access (initialisation) overhead

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/awkward#443]
The following issue arose while processing larger ROOT files with `uproot4` where the iterative read-in is required due to memory limitations. The analysis approach is event-by-event, which means that during the iteration, many branches needs to be accessed  while the amount of data per iteration is quite low (e.g. awkward-arrays with a few hundred or thousand entries).

The main problem is that single operations on these awkward arrays take orders of magnitude longer compared to what should be possible by the hardware (crosschecks with numpy and Julia). The reason is the overhead of access the data inside the awkward arrays and also the construction of those.

Of course I know one can request `numpy` arrays from `uproot4` explicitly via `TBranch.array(library="np")` but in our case it's a bit difficult since some branches needs to be awkward arrays, others are better as numpy arrays etc. so in the following, let's assume that our starting point is an awkward array.

Another point is that the wholemeal approach is usually the preferred way but it's complicated and ugly to extend the calculations to be done on bigger chunks of the file and many things inside the iterations needs some special care, so it's very hard to do it on single operations. Let alone the memory footprint, which can only be managed by a clever chunking... Of course, if there is no other way, we will go that path, but I want to make sure that I am not overlooking anything obvious.

Here is what I mean:

Awkward array construction (in this example from numpy arrays), which I assume does more or less the same work when e.g. creating the output array of operations (e.g. `awkward_array * 10` etc.). This means, it creates the class instance, checks the dtype and swallows the input data without copying it. The overhead seems to be somewhere in the `18us` range and is obviously not depending on the data size (no-copy):

```python
for n in (10**i for i in range(9)):
    arr = np.random.rand(n)
    %timeit ak.Array(arr)
18.5 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
18.9 µs ± 147 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
18.4 µs ± 156 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
18.4 µs ± 251 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
18.4 µs ± 87.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
18.3 µs ± 161 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
18.3 µs ± 164 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
18.3 µs ± 147 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
18.4 µs ± 97.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Whenever there is an operation on such arrays, this construction time is already the lower threshold. Furthermore, there is (let's call it) access time, which is the time the code needs to reach the underlying data. I only measured the time of the whole function call, but it's obvious that we have an access+init overhead of something around `140us`. Which means `~20us` for constructing the output array and the remaining time is `~120us` to get to the data + actual calculation (usually a few nanoseconds per item for basic arithmetic operations):

```python
for n in (10**i for i in range(9)):
    arr = ak.Array(np.random.rand(n))
    %timeit arr / 10
146 µs ± 1.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
147 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
149 µs ± 1.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
155 µs ± 2.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
157 µs ± 1.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
212 µs ± 5.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.29 ms ± 14 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
12 ms ± 61.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
105 ms ± 588 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

In one of the cases I am now trying to improve, a lot of such operations are taking place (as mentioned above) and the user is literally iterating over an (event) index and accesses such (small) arrays individually from many branches.

Here is a direct comparison between different ways to calculate the same thing and you can see that `numpy`s overhead is extremely tiny compared to `awkward1`:

```python
arr_np = np.random.rand(100)
arr_ak = ak.Array(arr_np)
%timeit arr_np / 10
%timeit arr_ak / 10
%timeit arr_ak.__array__() / 10
%timeit np.divide(arr_ak, 10)

937 ns ± 8.75 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
148 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
9.5 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
144 µs ± 1.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

Although I have many questions, one of the most important ones is what you recommend to do to get a quicker access to the underlying data, which should have a C-compatible binary layout, so in principle we should be able to reach numpy-like calculation times but this means that also the construction of awkward arrays needs to be sped up quite a lot.

What do you think?

**Comment by jpivarski** [comment]
PR #444 fixed a linearly scaling performance bug in handling jaggedness. All of your examples here are non-jagged, so that doesn't apply.

In issue #442, the overhead of doing a binary ufunc between a doubly jagged array and a scalar is about 500 µs. In these examples of a binary ufunc between a non-jagged array and a scalar is 144 µs. That's not too different, considering that the metadata-handling function does three recursive steps for a doubly jagged array and one for a non-jagged array.

If we check the scaling, we see that this is indeed a constant overhead, which is expected.

```python
In [10]: for n in (100, 1000, 10000, 100000, 1000000, 10000000):
    ...:     print(n)
    ...:     arr_np = np.random.rand(n)
    ...:     arr_ak = ak.Array(arr_np)
    ...:     %timeit arr_np / 10
    ...:     %timeit arr_ak / 10
    ...: 
100
809 ns ± 19.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
157 µs ± 1.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
1000
1.43 µs ± 24.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
160 µs ± 2.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
10000
6.19 µs ± 65.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
165 µs ± 2.29 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
100000
51.5 µs ± 693 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
212 µs ± 7.84 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1000000
637 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
808 µs ± 13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
10000000
12.3 ms ± 58.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12.8 ms ± 237 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

The whole idea of Awkward Array is that you can't eliminate the overhead of dealing with complex structures whose type is known after compile-time (i.e. not like Julia), but you can move all of it into constant-time metadata-twiddling, leaving the linear-time part for precompiled, specialized loops, most often in NumPy itself. That's the thing that's new, as far as I can tell: isolating structure manipulations to a constant-time part.

**Comment by jpivarski** [comment]
> ```python
> %timeit arr_ak.__array__() / 10
> 
> 9.5 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
> ```

The reason that the conversion to a NumPy array is not instantaneous is that it has to check to see if it's legal—i.e. if the data are rectilinear. `ak.Array.__array__` calls [ak.to_numpy](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_numpy.html), which does not return NumPy `dtype="O"` type arrays: it raises an error if the data aren't shaped right.

Perhaps it's worth investigating if this time is expected for a NumpyArray, which is just one layer to unwrap.

The fastest thing you can do if you know you have a plain NumpyArray is to pull it out as a `layout` and cast it as NumPy. The NumpyArray object is a Python buffer.

```python
In [15]: arr_ak
Out[15]: <Array [0.454, 0.245, 0.282, ... 0.362, 0.809] type='10000000 * float64'>

In [16]: arr_ak.layout
Out[16]: <NumpyArray format="d" shape="10000000" data="0.454025 0.245414 0.28192 0.23692 0.577678 ... 0.867228 0.0388754 0.484831 0.362226 0.809129" at="0x7f40c2dcb010"/>

In [17]: %timeit arr_ak.__array__()
5.43 ms ± 94.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [18]: %timeit np.asarray(arr_ak.layout)
954 ns ± 36.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

(These timings are unaffected by whether the array has 10000000 entries or 100 entries. It's all constant-time unwrapping.)

The `layout` is the "low-level but public" interface, intended for framework developers like you. When you access this layer, however, you have to be aware of low-level issues like the "unreachable data" I talked about on issue #340 

https://awkward-array.readthedocs.io/en/latest/ak.layout.Content.html

**Comment by jpivarski** [comment]
Since this issue is about small arrays (100 entries is very small!), I'm going to close it. I intend to focus more on performance issues next year, after Awkward 0 and Uproot 3 are fully and finally retired, but even then the performance issues will be the linearly scaling ones. Only overwhelmingly bad constant-time scaling issues will be addressed (which the 5 ms for NumpyArray → ndarray might be).

What I had intended to focus on today is a C++ implementation of doubly jagged numbers → Awkward, as discussed in scikit-hep/uproot4#90. The full generality has to wait until next year, but I was thinking about it and this special case is both easy and important. That might fix your problem by allowing you to work with larger arrays.

But the issue treadmill keeps going! More have come in while answering this...

**Comment by tamasgal** [comment]
Thanks Jim, that `np.asarray(Awkward.Array().layout)` is very helpful and the way to go. This issue is anyways very minor and specific to this particular analysis implementation I am about to review, so no worries!

> But the issue treadmill keeps going! More have come in while answering this...

😉 

I wish I had a bit more time to also invest in understanding the internals of awkward1 or even to contribute; I'll try harder in future.
