### ISSUE TITLE
Union of compatible types does not simplify if parameters are set

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#459]
Consider
```python
a = ak.Array(ak.layout.NumpyArray(np.arange(6, dtype=np.float32), parameters={"asdf": "something"}))
```
Then a common operation might be to mask certain values and replace them, e.g. 
```
In [51]: ak.fill_none(a.mask[a%2==0], -1)
Out[51]: <Array [0, -1, 2, -1, 4, -1] type='6 * union[float32[parameters={"asdf": "someth...'>

In [52]: ak.type(_51)
Out[52]: 6 * union[float32[parameters={"asdf": "something"}], int64]
```
but the union type is unnecessary and can be troublesome. It's not clear if we should throw away or propagate the parameters, but either way it would be nice to be able to simplify this type.

**Comment by jpivarski** [comment]
Types are different if any of their parameters are different—this is what makes a list of numbers different from a string.

But perhaps that definition could be reduced to "types are different if their `__array__` or `__record__` parameter is different."

I know that you put documentation into the parameters; that's something that shouldn't change a type.

Broadening the definition of type-equality in this way and doing nothing else would give the output of an operation like this the parameters of the _first_ object. Maybe some merging might make more sense, but I don't want to overly complicate the rule.

**Comment by nsmith-** [comment]
Good point about `__array__` or `__record__`. Since those are the two (well, also `__doc__` but we know that is ignorable) parameters that awkward1 itself readds to decide how to treat the array, they should not disappear.
I think probably the most sensible output in the case where the union doesn't have any of the above is to have no parameters. Users can always add their favorite parameters back.

**Comment by jpivarski** [comment]
So the rules would be,

   * if arrays have different `__array__` or `__record__` parameters, they are not equal;
   * if they otherwise have different parameters, the types can be equal, but merging (concatenation, option-simplify, or union-simplify) removes parameters other than `__array__` and `__record__`.

**Comment by nsmith-** [comment]
I think that makes sense, would welcome other opinions though

**Comment by jpivarski** [comment]
I'll do this one. I'm scheduling it for November, but it might slip.
