### ISSUE TITLE
Update deploy procedure, possibly adopt cibuildwheel

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#472]
This hack is no longer needed:

https://github.com/scikit-hep/awkward-1.0/blob/4ba42ac43707555d5847a50deb200b6f157f78bd/.ci/azure-deploy-awkward.yml#L111-L112

Reported by @henryiii.

But maybe we should go further and adopt [cibuildwheel](https://github.com/joerick/cibuildwheel) (not sure what that involves).

**Comment by henryiii** [comment]
> But maybe we should go further and adopt cibuildwheel (not sure what that involves).

(I can help with that, probably next week)
