### ISSUE TITLE
High-level functions to convert between integer-array slices and boolean masks

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#497]
Following up on a conversation from Slack: switching between integer indexing and boolean masking is a common task for me, so it would be nice if there were some high-level interface for these conversions.

## Boolean mask -> integer-array slice conversion

This is basically a special case of an awkward [`np.nonzero()`](https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html). In awkward0, I use:
```python
indices = mask.localindex[mask]
```
so if `localindex` gets implemented in awkward1 (#496), this direction becomes almost trivial. It might be a good idea to just make a `nonzero()` in awkward anyway, though.

## Integer-array slice -> boolean mask conversion

In awkward0, I use:
```python
mask = a.zeros_like().astype(bool)
mask[indices] = True
```
Without array mutability in awkward1, I need an alternative method to achieve this.

**Comment by jpivarski** [comment]
Copying more things here (because GitHub Issues are a more permanent, well cross-referenced record than Slack), here's a Numba implementation of the integer → boolean slice:

```python
>>> @nb.njit
... def make_mask(builder, a, indices):
...     for ai, index in zip(a, indices):
...         builder.begin_list()
...         for j in range(len(ai)):
...             contained = False     # this whole stanza, defining "contained", should be "j in index"
...             for k in index:
...                 if k == j:
...                     contained = True
...                     break
...             builder.append(contained)
...         builder.end_list()
...     return builder
... 
>>> make_mask(ak.ArrayBuilder(), a, indices).snapshot()
<Array [[], [True], [False, True]] type='3 * var * bool'>
```

Though we don't implement features in Awkward using Numba. (That would be a bad surprise to users without Numba. Besides, the above only works at one level of depth; I think we'd want something more general.) This implementation doesn't use `j in index` because of #494.

**Comment by agoose77** [comment]
I *think* this issue can be closed, now. With `ak.transform`, it's fairly easy to write a generic recursion that can build the mask from an index array.

For "boolean mask to index", we have
```python
x = ak.Array([[1, 2, 3], [], [4, 5], [5, 4, 2, 1]])
mask = x > 3

j = ak.local_index(x)
i = j[mask]
```

Meanwhile, for "index to boolean mask", one can recurse down to the penultimate dimension, and build the mask as in this issue description:
```python
def index_to_mask(index, array):
    def get_layout_offsets(layout):
        if layout.is_numpy:
            (size,) = layout.inner_shape
            offset = np.arange(0, size * layout.length + 1, size)
        elif layout.is_regular:
            offset = np.arange(0, layout.size * layout.length + 1, layout.size)
        else:
            layout = layout.to_ListOffsetArray64(True)
            offset = np.asarray(layout.offsets.data)
        return layout, offset

    def apply(inputs, **kwargs):
        index_layout, array_layout = inputs
        if index_layout.purelist_depth != 2:
            return
        assert array_layout.purelist_depth == index_layout.purelist_depth

        array_layout, array_offset = get_layout_offsets(array_layout)
        global_index = ak.flatten(ak.Array(index_layout) + ak.Array(array_offset[:-1]))

        mask = np.zeros(array_offset[-1], dtype=np.bool_)
        mask[global_index] = True
        return ak.contents.ListOffsetArray(
            ak.index.Index64(array_offset), content=ak.contents.NumpyArray(mask)
        )

    return ak.transform(apply, index, array)

mask_2 = index_to_mask(i, x)
assert ak.to_list(mask) == ak.to_list(mask_2)
```

This function looks complicated only because it handles multiple list types.

**Comment by masonproffitt** [comment]
> Meanwhile, for "index to boolean mask", one can recurse down to the penultimate dimension, and build the mask as in this issue description:
> ```python
> def index_to_mask(index, array):
>     def get_layout_offsets(layout):
>         if layout.is_numpy:
>             (size,) = layout.inner_shape
>             offset = np.arange(0, size * layout.length + 1, size)
>         elif layout.is_regular:
>             offset = np.arange(0, layout.size * layout.length + 1, layout.size)
>         else:
>             layout = layout.to_ListOffsetArray64(True)
>             offset = np.asarray(layout.offsets.data)
>         return layout, offset
> 
>     def apply(inputs, **kwargs):
>         index_layout, array_layout = inputs
>         if index_layout.purelist_depth != 2:
>             return
>         assert array_layout.purelist_depth == index_layout.purelist_depth
> 
>         array_layout, array_offset = get_layout_offsets(array_layout)
>         global_index = ak.flatten(ak.Array(index_layout) + ak.Array(array_offset[:-1]))
> 
>         mask = np.zeros(array_offset[-1], dtype=np.bool_)
>         mask[global_index] = True
>         return ak.contents.ListOffsetArray(
>             ak.index.Index64(array_offset), content=ak.contents.NumpyArray(mask)
>         )
> 
>     return ak.transform(apply, index, array)
> 
> mask_2 = index_to_mask(i, x)
> assert ak.to_list(mask) == ak.to_list(mask_2)
> ```
> This function looks complicated only because it handles multiple list types.

Can this be made into a function within awkward? That was what this issue was about. I assumed it was possible to construct such a function, but I'd like not to have to copy and paste every time I want do this.

**Comment by ianna** [comment]
@masonproffitt — you are welcome to submit a PR!

**Comment by ikrommyd** [comment]
I guess the thing about a new high-level public API is that it needs to be general and cover different levels of nestedness, layout types and axes.
