### ISSUE TITLE
awkward.argsort is wrong for arrays with dimensions > 2

### ISSUE THREAD

**Issue by yimuchen** [scikit-hep/awkward#506]
Results for awkard.argsort is wrong for arrays with dimensions greater than 2. Example output from awkward1 version 0.3.1

Code 
```
import awkward1
x = awkward1.Array([[[0.01539855, 0.45536142, 0.9510973 , 0.17593855, 0.30485241],
                     [0.57157337, 0.2281758 , 0.1437675 , 0.80287155, 0.11580015],],
                    [[0.77897828, 0.75505657, 0.61302232, 0.56694878, 0.99761142],
                     [0.38639971, 0.69037858, 0.61298759, 0.6602239 , 0.93297311],],]) # 2x2x5 array generated from numpy.random
print(awkward1.to_numpy(awkward1.argsort(x,axis=-1)))
```
Resulting output: 
```
[[[0 3 4 1 2]
  [4 2 1 0 3]]
 [[3 2 1 0 4]
  [0 2 3 1 4]]]
```

Expected output:
```
[[[0 3 4 1 2]
  [3 2 1 4 0]]
 [[3 2 1 0 4]
  [0 3 1 2 4]]]
```

**Comment by ianna** [comment]
@yimuchen - I think, it is expected since the `numpy` would give the same results:
```
>>> import numpy as np
>>> a = np.array([[[0.01539855, 0.45536142, 0.9510973 , 0.17593855, 0.30485241],
...                      [0.57157337, 0.2281758 , 0.1437675 , 0.80287155, 0.11580015],],
...                     [[0.77897828, 0.75505657, 0.61302232, 0.56694878, 0.99761142],
...                      [0.38639971, 0.69037858, 0.61298759, 0.6602239 , 0.93297311],],])
>>> 
>>> a.argsort(-1)
array([[[0, 3, 4, 1, 2],
        [4, 2, 1, 0, 3]],

       [[3, 2, 1, 0, 4],
        [0, 2, 3, 1, 4]]])
```

**Comment by yimuchen** [comment]
Hm... I hadn't tested that. Thanks for pointing this out. So is this an upstream bug in numpy?

**Comment by ianna** [comment]
> Hm... I hadn't tested that. Thanks for pointing this out. So is this an upstream bug in numpy?

I think, it's how the axis is interpreted. I'd say it's a feature ;p

**Comment by jpivarski** [comment]
Focusing on the second innermost list,

```
[0.57157337, 0.2281758 , 0.1437675 , 0.80287155, 0.11580015]
```

the actual output of

```
[4 2 1 0 3]
```

would put them in the correct order:

```python
>>> np.array([0.57157337, 0.2281758 , 0.1437675 , 0.80287155, 0.11580015])[[4, 2, 1, 0, 3]]
array([0.11580015, 0.1437675 , 0.2281758 , 0.57157337, 0.80287155])
>>> ak.Array([0.57157337, 0.2281758 , 0.1437675 , 0.80287155, 0.11580015])[[4, 2, 1, 0, 3]]
<Array [0.116, 0.144, 0.228, 0.572, 0.803] type='5 * float64'>
```

but the order you say you're expecting,

```
[3 2 1 4 0]
```

would put them in the wrong order:

```python
>>> np.array([0.57157337, 0.2281758 , 0.1437675 , 0.80287155, 0.11580015])[[3, 2, 1, 4, 0]]
array([0.80287155, 0.1437675 , 0.2281758 , 0.11580015, 0.57157337])
>>> ak.Array([0.57157337, 0.2281758 , 0.1437675 , 0.80287155, 0.11580015])[[3, 2, 1, 4, 0]]
<Array [0.803, 0.144, 0.228, 0.116, 0.572] type='5 * float64'>
```

I'm not sure what you intended, but `axis=-1` means that the deepest level of nesting gets sorted, individually for each list object. If you want to sort across inner lists, use lower values of `axis` (`axis=-1` is `axis=num_dimensions-1`, which is `2` for this 3-dimensional array).

**Comment by jpivarski** [comment]
Let me know if this is still an issue and I'll reopen it. I'm closing it now because I'm trying to get a handle on what work needs to be done—there's a lot!

**Comment by yimuchen** [comment]
@jpivarski Ah, thanks. It looks like I have misunderstood the meaning of the output: 
So basically, the `argsort` function outputs the indices to retrieve the objects to place the numbers in sorted order. While the output I was expecting was the position at which the numbers will end up. Thanks for the clarification! (I guess it was unfortunate that the first row of the example outputs has two answers coincided, so I as confused as to why the output is 'sometimes right' when it as I that was wrong all along)

So yes this issue is closed.

**Comment by jpivarski** [comment]
Aha! You thought it was the inverse, a natural assumption to make.

That is, if selecting an item from an array is a function, `f: int → dtype`, then slicing by an array, `g: int → int`, is composition: `f ⊗ g: int → int ⊗ int → dtype` or `f ⊗ g: int → dtype`. That `g: int → int` function can have an inverse, `g⁻¹`, (depending on how general we take it to be, but from argsort, it's always a permutation), and it's natural to guess that it's supposed to be `g⁻¹` when it's supposed to be `g`. They have the same `int → int` signature, after all.

That's why we check to see what NumPy does, to be sure we pick the same conventions.
