### ISSUE TITLE
*::flatten and *::count for axis != 0

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#51]
All array types, including `IndexedArray` (and `UnionArray`, if it exists when you're ready for it).

Discussion of how to interpret negative `axis` [here](https://github.com/scikit-hep/awkward-1.0/pull/45#issuecomment-573783659).

**Comment by jpivarski** [comment]
See #69 for further discussion of how to interpret negative `axis`.

**Comment by jpivarski** [comment]
The `axis` parameter for `count` (a special-case reducer introduced in PR #81) should be handled in the same way as the `axis` parameter for `flatten`. This issue (#51) should add `axis > 0` and `axis < 0` cases to both `flatten` and `count`.

**Comment by jpivarski** [comment]
@ianna I added a lot of issues yesterday, which cover the gap from the present to the [minimum viable product for users](https://github.com/scikit-hep/awkward-1.0/milestone/4) that is expected at the end of the 6-month sprint. (Every item in the [README checklist for the 6-month sprint](https://github.com/scikit-hep/awkward-1.0#checklist-of-features-for-the-six-month-sprint) has been translated into an issue.)

I've assigned the array operations to you (`flatten` and `count` being the first two) and the new array types, Python front-end, and Numba implementation to me. That's completely negotiable.

If you're wondering where to get started, it's this one (issue #51), which we discussed before. Looking ahead to operations like the reducers in #69 has consequences for how negative `axis` should be interpreted, so it would be good to read ahead about what's coming.

**Comment by ianna** [comment]
> @ianna I added a lot of issues yesterday, which cover the gap from the present to the [minimum viable product for users](https://github.com/scikit-hep/awkward-1.0/milestone/4) that is expected at the end of the 6-month sprint. (Every item in the [README checklist for the 6-month sprint](https://github.com/scikit-hep/awkward-1.0#checklist-of-features-for-the-six-month-sprint) has been translated into an issue.)
> 
> I've assigned the array operations to you (`flatten` and `count` being the first two) and the new array types, Python front-end, and Numba implementation to me. That's completely negotiable.
> 
> If you're wondering where to get started, it's this one (issue #51), which we discussed before. Looking ahead to operations like the reducers in #69 has consequences for how negative `axis` should be interpreted, so it would be good to read ahead about what's coming.

Thanks, @jpivarski - Excellent! I thought it was a plan for the end of February :-)

I'm done with **NumpyArray** for ```axis != 0```, not yet ```axis == -1```.  I need to read the issues for the latter.
I am adding more extensive tests and will open a PR either later today or tomorrow morning.

**Comment by jpivarski** [comment]
Oh, good! With your work on `NumpyArray`, however, I put in some corrections to your initial implementation (PR #45) as part of adding `IndexedArray::flatten` yesterday (PR #81). Specifically, this:

https://github.com/scikit-hep/awkward-1.0/blob/428c3db9745af34798f3f970ffa48e2db009485b/src/libawkward/array/NumpyArray.cpp#L628-L634

It's a potential merging hazard!

**Comment by ianna** [comment]
> Oh, good! With your work on `NumpyArray`, however, I put in some corrections to your initial implementation (PR #45) as part of adding `IndexedArray::flatten` yesterday (PR #81). Specifically, this:
> 
> https://github.com/scikit-hep/awkward-1.0/blob/428c3db9745af34798f3f970ffa48e2db009485b/src/libawkward/array/NumpyArray.cpp#L628-L634
> 
> It's a potential merging hazard!

No problem, I'll start with a clean area.
