### ISSUE TITLE
High-level access for deep copy

### ISSUE THREAD

**Issue by drahnreb** [scikit-hep/awkward#511]
I used to do this ([deprecated](https://github.com/scikit-hep/awkward-1.0/issues/350#issue-664526115)) for a deep copy:
```python
>>> import awkward1 as ak
>>> array = ak.Array([])
>>> array.copy() # deprecated with removal of pandas integration #350 
```
You could do this:
```python
>>> ak.Array(array.layout.deep_copy()) # unwrap and rewrap required similar to #496 
>>> # or
>>> import copy
>>> copy.deepcopy(array)
```

Would be nice to have something like this (with the same kwargs as the low-level?):
```python
>>> ak.copy(array) # or registered np.copy() which would be strictly deep as object elements aren't supported by awkward1
```

**Comment by jpivarski** [comment]
A low level function exists for this, so it will be a matter of connecting it to the high level. Overriding `__copy__` and `__deepcopy__` are good ideas, too.
