### ISSUE TITLE
Public broadcast wrapper and recursively_apply tool

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#516]
Both functions in `awkward1._util` are used a few times in coffea.
The [wrapper function](https://github.com/scikit-hep/awkward-1.0/blob/master/src/awkward1/_connect/_numpy.py#L41) that broadcasts and flattens inputs for numpy ufuncs was copied in a simplified form to coffea lookup_tools: https://github.com/CoffeaTeam/coffea/blob/master/coffea/lookup_tools/lookup_base.py#L19-L45
The recursively_apply function [is used](https://github.com/CoffeaTeam/coffea/blob/akcache/coffea/nanoevents/methods/base.py#L65-L75) to make sure a index take operates on the flat array in NanoEvents cross-references.

**Comment by jpivarski** [comment]
Finally done! See the copious documentation:

https://github.com/scikit-hep/awkward/blob/0b3806ae10ee02ac8490eb9d7623194d1f090ddd/src/awkward/_v2/operations/ak_transform.py#L9-L351
