### ISSUE TITLE
Conda-Forge Builds

### ISSUE THREAD

**Issue by Superharz** [scikit-hep/awkward#549]
It would be great to see the latest version of awkward1 on Conda-Forge (it's right now at 0.3.1).
I'd have no problem to wait for it longer should it be delayed on purpose. On the other hand, I'd love to try out the new versions.

**Comment by jpivarski** [comment]
I didn't realize they were failing; thanks! I asked about it here: https://github.com/conda-forge/awkward1-feedstock/pull/10#issuecomment-729300402

**Comment by Superharz** [comment]
That's good to hear.
Can you estimate when we can expect the next Conda-Froge release?

**Comment by jpivarski** [comment]
As described here, https://github.com/conda-forge/awkward1-feedstock/pull/10#issuecomment-731221098, this is a strange time. By around Dec 1, Uproot 4 and Awkward 1 will be pushed to packages named `uproot` and `awkward`, first as release candidates, then as real releases.

**Comment by Superharz** [comment]
The latest version of awkward1 has been uploaded to Conda-Forge.
Thanks for your work!
