### ISSUE TITLE
RuntimeError when seting a field to virtual

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#560]
Python code to reproduce:
```
import awkward1 as ak
a = ak.Array({"x": [1]})
a["y"] = ak.virtual(lambda: [2], cache={}, length=1)
print(a)
```
The last line raises the following error:
`RuntimeError: PyArrayCache has lost its weak reference to mapping`
The error only appears if the length and cache parameters are supplied.
Tested on awkward1 0.4.5

**Comment by jpivarski** [comment]
Thanks! The way we've kept track of these caches has changed a few times to avoid circular references and lost references—this fix was a lost reference because we remembered to add them in `__init__` but not `__setitem__`.
