### ISSUE TITLE
For NumPy compatibility, ak.sort's 'stable' (bool) should be 'kind' (str)

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#615]
The interface to [ak.sort](https://awkward-array.readthedocs.io/en/latest/_auto/ak.sort.html) and [ak.argsort](https://awkward-array.readthedocs.io/en/latest/_auto/ak.argsort.html) should be more like [np.sort](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) and [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html).

   * The Awkward functions have an `ascending` (bool) argument that isn't really necessary, since one can just negate the input. This `ascending` argument is passed all the way down to the underlying kernel, so the code could be simplified by eliminating it. This is not super-important because we're allowed to have _more_ features than NumPy and the code's already there. But if writing the GPU kernels is simplified by dropping the `ascending` argument, then let's do it.
   * The Awkward functions have a `stable` (bool)  to choose between C++'s stable and C++'s unstable sorting algorithm. NumPy has traditionally named explicit algorithms in a `kind` (str) argument, but since 1.15, it seems to be moving in the direction of describing only features, like "stable" vs "unstable", rather than explicit algorithms. @ianna has been thinking about GPU implementations of these sorting algorithms, and it looks like quicksort would be the most doable, so what we offer maps nicely onto the names NumPy defines:
     * NumPy's `"stable"` → our C++ stable algorithm, available only on CPU
     * NumPy's `"mergesort"` is a synonym for `"stable"`, but included only for backward compatibility → an informative error message, since our stable algorithm isn't exactly mergesort
     * NumPy's `"heapsort"` → our C++ unstable algorithm, available only on CPU, which _really is_ heapsort
     * NumPy's `"quicksort"` → the new algorithm @ianna is planning to implement by hand on CPU and GPU, the only algorithm available on the GPU.

At this stage, at least, I'll deprecate the `stable` (bool) option in favor of a `kind` (str), but leave `ascending` as it is.

Before doing this, I should create a formal roadmap with scheduled releases, since the deprecation date would not the Feb 1 date, but the one after that, whatever that is (#616).

**Comment by jpivarski** [comment]
@ianna, since the NumPy default is "quicksort", I can't do this until a quicksort exists.

But we [now have a formal roadmap](https://github.com/scikit-hep/awkward-1.0#roadmap), so if quicksort is available in January or February, then we can set the deprecation for 1.2.0 (April, 2021).

**Comment by ianna** [comment]
@jpivarski - incidentally NumPy `quicksort` has been changed to `introsort`:
https://numpy.org/doc/stable/reference/generated/numpy.sort.html

It's the same as in AwkwardArray :-)

**Comment by agoose77** [comment]
@jpivarski I *think* we can close this: Awkward _doesn't_ implement the same sorting routines as NumPy, but we do support `kind`. Now that we have dedicated NEP-18 entrypoints, we translate the kind to a stable vs non-stable sort.
