### ISSUE TITLE
Adding fields to a record array drops its parameters

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#629]
A recent change has caused the following code:
```python
import awkward as ak

a = ak.zip({"x": [1, 2, 3], "y": [2, 3, 4]}, with_name="asdf")
print(ak.type(a))
a["z"] = ak.Array([4, 5, 6])
print(ak.type(a))
```

to no longer output:
```
3 * asdf["x": int64, "y": int64]
3 * asdf["x": int64, "y": int64, "z": int64]
```
but rather
```
3 * asdf["x": int64, "y": int64]
3 * {"x": int64, "y": int64, "z": int64}
```

The change was introduced in https://github.com/scikit-hep/awkward-1.0/pull/606/files#diff-63b9cf483f8a04b770807d6cabd4098708d35ed6d124e8d1c969fcca657d9b32R852-R866
I think there's a case to be made for dropping parameters in some cases, but here is one of the rare instances where awkward appears to be letting us mutate the array (though under the hood it swaps the layout to a new one) and that distinction is probably worth keeping parameters.

**Comment by nsmith-** [comment]
Better link: https://github.com/scikit-hep/awkward-1.0/pull/606/files#diff-63b9cf483f8a04b770807d6cabd4098708d35ed6d124e8d1c969fcca657d9b32L845-R865

**Comment by jpivarski** [comment]
Well, `getitem_fields` _should_ drop parameters:

```python
array_of_records[["just", "these", "fields"]]
```

turns a record array into a record array of fewer fields, so it should no longer allow the same methods (or have the same identity as an `asdf` type of object), which might require a full set of fields.

But you've demonstrated that `ak.with_field` is losing parameters and it should not. Having _more_ fields (or the same number of fields, with one of its values replaced) is not a problem for having the same set of methods (or the same type-identity). The `ak.with_field` function is calling a `Content::setitem_field` method:

https://github.com/scikit-hep/awkward-1.0/blob/ea2d88c8df7fe2cfd3a7f8b157846e7c18d0aa1c/src/awkward/operations/structure.py#L661-L669

But... the `RecordArray::setitem_field` method _does_ return a RecordArray with the same `parameters_`:

https://github.com/scikit-hep/awkward-1.0/blob/ea2d88c8df7fe2cfd3a7f8b157846e7c18d0aa1c/src/libawkward/array/RecordArray.cpp#L429-L472

That's weird. I'll have to go into deep debugging mode to figure out where it's being lost. (Not here: https://github.com/scikit-hep/awkward-1.0/blob/ea2d88c8df7fe2cfd3a7f8b157846e7c18d0aa1c/src/awkward/highlevel.py#L1058-L1069 .) There shouldn't be a point where an array is sliced with its full set of fields, which would do nothing except drop parameters, but that's the sort of thing I'd be looking for.

**Comment by nsmith-** [comment]
Ok, I `git bisect`ed to find that PR was the culprit, but only guessed that line change to be the relevant piece of the PR.

**Comment by jpivarski** [comment]
I can see how this commit did it (the one you found with a git bisect). The commit was correct: `array[array.fields]` should drop parameters, but I used that in one line of `ak.with_fields` to avoid doubling up a key (i.e. getting two keys named `"z"`).

PR #629 removes that line, and to do so, it builds the output RecordArray manually in Python. The C++ `RecordArray::setitem_field` now appears to be completely unnecessary. I should consider removing it. Another nice feature of building the RecordArray manually is that it's only built once: the `array[array.fields]` built it one time and `RecordArray::setitem_field` built it again, which could be a performance issue for records with many fields (at best a factor of 2).
