### ISSUE TITLE
to_parquet cannot convert union struct

### ISSUE THREAD

**Issue by nongiga** [scikit-hep/awkward#640]
I'll try to do this as easy to reproduce as I can but it's a little complicated.

I have a data structure, that looks a little like this:
```
{
    "CaseNum": 1905256,
    "Isolates": [
      {
        "IsoNum": 5567545
        "SeqsPlate": "1_E5",
      }
     Seqplates: [
      "1_E5",
      "1_D5"
    ]
    ],
  }, 
```
I am loading multiple csv files and saving their content in a subfield of the structure, making a final struct that looks more like this:
```
{
    "CaseNum": 1905256,
    "Isolates": [
      {
        "IsoNum": 5567545
        "SeqsPlate": "1_E5",
      }
     Seqplates: [ "1_E5", "1_D5" ]
    ],
   "Pangenome":[
       "Gene": [gene1, gene2, ...]
      "Annotation": [annot1, annot2, ...]
    ]
  }, 
```
I did it using the following code, a bit bukly but get the job done:

```
datadir=os.getcwd()

# get names of csv files
dirnames=np.char.add(np.asarray(datadir+"/pangenome/", dtype=str), np.asarray(df.CaseNum,dtype=str))
filenames=np.char.add(dirnames,np.asarray('/gene_presence_absence.csv', dtype=str))

# keep track over which of the files exist
isfile=[os.path.isfile(fn) for fn in filenames]

# function to read csv files into awkwardarray
def get_pangenome_data(filename):
    roary_pa=csv.read_csv(filename)
    roary_ak=ak.from_arrow(roary_pa)
   # returns AK and the length of the array for later unflattening
    return roary_ak, len(roary_ak)

# loop through all existing csv files and get their data
pangenome_data=[ (get_pangenome_data(fn))  for fn in filenames[isfile] ]

# get line count in each file for unflattening
r_count=np.array([c for dat, c in pangenome_data])
count=np.zeros((len(ilp),),dtype=int) # all line counts are zero
count[isfile]=r_count # except for records that have a matching csv file

# merge csv structs together into a single awkwardarray
pangenome_data=[dat for dat, c in pangenome_data]
pangenome_data=ak.concatenate(pangenome_data)

# unflatten according to csv line counts to fit the main array/df
pangenome_data=ak.unflatten(pangneome_data,count)

# assign pangenome data to array
df['Pangenome']=pangenome_data
```

Problem is, when I try to save the file in to_parquet
`ak.to_parquet(df.Pangenome, datadir+"/up_to_pangenome.parquet", explode_records=True)`
I get:
`ArrowNotImplementedError: Unhandled type for Arrow to Parquet schema conversion: dense_union<0: string not null=0, 1: string not null=1>`

Nonetheless when I try to save the Isolates substructure within the awway:
`ak.to_parquet(df.Isolates, datadir+"/up_to_pangenome.parquet", explode_records=True)`

I get no error.

When I print the type for ak.Pangenome I get:
```
ak.type(df.Pangenome):
20 * var * union[{"Gene": option[string],  "Annotation": option[string]}]
```

But for the isolates I get:

```
ak.type(df.Isolates)
20 * var * {"IsoNum": float64, "RowNum": int64, "SampleDate": string, "SeqSubDirName": string, "LowQualityThrs": int64, "Freezer_pos": string, "Used": int64, "SiteString": string, "Seqname": string, "IsSameStrain": bool}
```

Is there a way to convert the union type to a different type within the list to circumvent this?

Thanks!

**Comment by jpivarski** [comment]
I manually moved this to a Discussion: https://github.com/scikit-hep/awkward-1.0/discussions/641

because the error is a `ArrowNotImplementedError`, not something I can fix. (You can try the [Arrow JIRA](https://issues.apache.org/jira/projects/ARROW/issues/ARROW-10904?filter=allopenissues).) The discussion would be about ways of working around this (current) Arrow → Parquet limitation.
