### ISSUE TITLE
Undefined operation after slicing a virtual array

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#655]
```python
import awkward as ak
import numpy as np

arr = ak.from_buffers(*ak.to_buffers(ak.Array({"a": [[1,2,3]]})), lazy=True)
arr = arr[np.full(len(arr), True)]
arr["b"] = np.full(len(arr), True)
arr = arr[np.full(len(arr), True)]
print(arr["a"][arr["a"] > 2])
```
The last line will produce `RuntimeError: undefined operation: VirtualArray::getitem_next_jagged(array)`. It doesn't matter where exactly the masks that are used for slicing are `True` and `False`.
Tested on version 1.0.2 and the current Git main.

**Comment by jpivarski** [comment]
The extension of laziness to allow field-slices to remain lazy (`arr["a"]`) has made it possible to enter the `VirtualArray::getitem_next_jagged` function. What these functions ought to do is simple: materialize the array and pass `getitem_next_jagged` down to the materialized array, so I just added that. It looks like the first of four cases has already been reached and implemented, so I did the other three.

Thanks for pointing this out!
