### ISSUE TITLE
Masking virtual array makes it load

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#679]
This issue is originating from the usage of Coffea's NanoEvents. It is a RecoardArray of large RecordArrays, which really need lazy loading.

When masking the array, after done some other operations, it loads the data of a large number of fields. There seems to be no need to load these fields and it takes very long in case of NanoEvents.

  <details>
    <summary>Simplified example source code</summary>
    

```python

import numpy as np
import awkward as ak

class Map(dict):
    def __getitem__(self, key):
        print(f"Loading {key}")
        return dict.__getitem__(self, key)

length = 500
form = {
 'class': 'RecordArray',
 'contents': {'run': {'class': 'NumpyArray',
                      'form_key': 'loads_very_slowly',
                      'format': 'I',
                      'has_identities': False,
                      'inner_shape': [],
                      'itemsize': 4,
                      'parameters': {},
                      'primitive': 'uint32'}},
 'form_key': '',
 'parameters': {}}

container = Map({
    "part0-loads_very_slowly-data": np.ones(length, dtype=np.int32)})
data = ak.from_buffers(form, length, container, lazy=True)

mask = np.full(len(data), True)
mask[0] = False
data = data[mask]
length = len(data)

data["test"] = 1
print("Calling ak.mask")
ak.mask(data, np.full(length, True))

```
  </details>

In the example, `ak.mask` will make `run` being loaded, even though this doesn't seem to be necessary. It is not loaded unless the masking and item setting is done. This behavior currently stops me from using `ak.mask` together with NanoEvents.

**Comment by jpivarski** [comment]
PR #680 fixes this:

```python
>>> tmp = ak.mask(data, np.full(length, True))
>>> tmp
Loading part0-loads_very_slowly-data
<Array [{run: 1, test: 1}, ... test: 1}] type='499 * ?{"run": uint32, "test": in...'>
```

It's part of a more general attack on right-broadcasting, though, which is NumPy-style broadcasting that associates elements between arrays from the deepest level up to the shallowest level (and only applies to regular, NumPy-like arrays). The deepest-to-shallowest scan is what was materializing the array. For example, it also caused scikit-hep/uproot4#244.

Right-broadcasting is needed in functions that generalize NumPy, such as ufuncs and `ak.where`, but others like `ak.mask` use the same internal function to align input arrays (e.g. to left-broadcast, from shallowest to deepest, a scalar in `ak.mask(array, True)`). I'm adopting a new policy of not right-broadcasting except where necessary for NumPy-generalization.
