### ISSUE TITLE
Segmentation fault from argsort and sort

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#686]
```python
import awkward as ak
arr = ak.layout.IndexedArray64(ak.layout.Index64([]), ak.layout.NumpyArray([1,2,3]))
ak.argsort(arr)
```
 will exit Python with the message `Segmentation fault`.
Tested on awkward version 1.0.2 and git main.

**Comment by ianna** [comment]
@jrueb - thanks for spotting it! The https://github.com/scikit-hep/awkward-1.0/pull/687 should fix it.
