### ISSUE TITLE
argmin and argmax

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#70]
Like the [NumPy functions of the same name](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html), these operations return an integer array of the _positions_ of the minimum and maximum values per subarray. (By the way, this is technically not a reducer in the sense of issue #69 and it would have an independent implementation.)

```python
>>> import numpy
>>> nparray = numpy.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6], [7.7, 8.8, 9.9]])
>>> nparray.argmin(axis=0).tolist()
[0, 0, 0]
>>> nparray.argmax(axis=0).tolist()
[2, 2, 2]
```

The old Awkward Array had a different return type for this function:

```python
>>> import awkward
>>> akarray = awkward.fromiter([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6], [7.7, 8.8, 9.9]])
>>> akarray.argmin().tolist()
[[0], [0], [0]]
>>> akarray.argmax().tolist()
[[2], [2], [2]]
```

in order to handle cases without a minimum or maximum, which are possible because of the existence of jagged arrays.

```python
>>> akarray = awkward.fromiter([[1.1, 2.2, 3.3], [], [4.4, 5.5]])
>>> akarray.argmin().tolist()
[[0], [], [0]]
>>> akarray.argmax().tolist()
[[2], [], [1]]
```

These jagged integer arrays could then be used as slices, so it was a _useful_ deviation from NumPy.

However, deviating at all from NumPy is bad, especially if the function has the same name and mostly the same meaning. Instead of what was done in the old Awkward, the above should return

```python
>>> ak.tolist(ak.argmin(akarray))
[0, None, 0]
>>> ak.tolist(ak.argmax(akarray))
[2, None, 1]
```

For regular arrays, this behavior would be identical to NumPy's; for irregular ones, users are introduced to OptionType arrays (most likely [IndexedOptionArray](https://github.com/scikit-hep/awkward-1.0/wiki/IndexedOptionArray.md), which has already been implemented, but possibly [ByteMaskedArray](https://github.com/scikit-hep/awkward-1.0/wiki/ByteMaskedArray.md) or [BitMaskedArray](https://github.com/scikit-hep/awkward-1.0/wiki/BitMaskedArray.md)).

I'll be allowing these arrays as slices in #67 (following the behavior established by `pyarrow`), so they'll also be useful.

@nsmith- might want to comment on this change in behavior.

**Comment by nsmith-** [comment]
I think for argmax indeed it makes much more sense to reduce the dimension by 1, reflecting the behavior of max.

**Comment by jpivarski** [comment]
Also relevant: the new `ak.singletons` function in #198. This is needed to turn the `ak.argmax` output into something that can select one object from each list.

Maybe there will also need to be a convenient syntax for it, since the examples in the tutorial are looking like:

```python
#  select <- to singletons <- argmax <- the cut
events.pions[ak.singletons(ak.argmax(abs(events.pions.vtx), axis=1))]
```
