### ISSUE TITLE
How to flatten awkward arrays (e.g. for plotting)

### ISSUE THREAD

**Issue by ast0815** [scikit-hep/awkward#704]
The page https://awkward-array.org/how-to-restructure-flatten.html looks like it should explain exactly what I need, but it is empty so far. Hence this issue.

**Comment by jpivarski** [comment]
Noted. In the meantime (while I compile for Python 2.7), the short story is to use [ak.flatten](https://awkward-array.readthedocs.io/en/latest/_auto/ak.flatten.html) if you want to remove a level of structure. If you have more than one level of nested arrays, either call `ak.flatten` multiple times, or pass `axis=None` to completely flatten. This actually flattens all structures, including records, so be sure this is what you want.

```python
>>> ak.flatten(ak.Array([{"x": 1, "y": 1.1}, {"x": 2, "y": 2.2}]), axis=None)
<Array [1, 2, 1.1, 2.2] type='4 * float64'>
```

Note that flatten also removes missing values (None), so it's meaningful to flatten at `axis=0` if you're trying to get rid of them.

Depending on what your intentions are, you might not want to flatten—you might actually want to do something like

```python
>>> array[:, 0]
```

or

```python
>>> ak.sum(array, axis=1)
```

which also remove dimensions, but in ways that might correspond to what you actually want. (That's what I imagined most of the text on that page to be about, when I can write it.)

Also also, some libraries don't call `np.asarray` on their arguments, so they wouldn't recognize a NumPy-compatible array (e.g. one-dimensional, after flattening). If it's complaining about not recognizing type `awkward.highlevel.Array`, then try wrapping the Awkward Array with `np.asarray`. As a side-benefit, it will raise an exception if your array is not actually compatible with NumPy, alerting you to the fact that you need to make a decision about how you want to flatten it.

Compilation's done!

**Comment by ast0815** [comment]
Thanks! `ak.flatten` seems to do what I need.

**Comment by jpivarski** [comment]
Done in #943.
