### ISSUE TITLE
isna (formerly: dropna)

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#71]
**Edit:** instead of providing the `dropna` operation in C++, it would be sufficient to provide an `isna` (which takes an `axis` and returns boolean at the level of the `axis` as to whether an element is `None` or not). This would be easier to implement and we can do `dropna` as a combination of `isna` and slicing (at the Python level if a convenience function is needed, if at all).

------------------

Named after the [Pandas function of the same name](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html), this removes `None` values from an array with OptionType.

Note that it can turn `RegularArrays` into `ListOffsetArrays`, but preserves the level of nesting. It takes an `axis` parameter, and that `axis` has to correspond with an OptionType array or it does nothing.

This operation makes the new return behavior of `argmin`/`argmax` more useful because now that users have to deal with a lot of `None` values; maybe they just want to get rid of them. @nsmith- may want to comment on this as well.

The existence of `dropna` could make it unnecessary for reducers to explicitly deal with missing values, which is a nice simplification (to issue #69). Users could call `dropna` before calling the reducer if they don't want to count/sum/whatever the missing values.

This and other "*na" functions should take a `nan_is_na=True` parameter to control whether floating-point `NaN` counts as a missing value to drop. The primary missing value is `None`, which is only possible for arrays with OptionType. `NaN` is a weird exception for agreement with Pandas, which ought to be optional. @nsmith- may have opinions about this, too.

**Comment by nsmith-** [comment]
What about `isna`? I feel like `dropna` could just be a composition of `isna` and slicing.

**Comment by jpivarski** [comment]
> What about `isna`? I feel like `dropna` could just be a composition of `isna` and slicing.

This is an excellent point. I had intended to make an issue for `isna` but got lost among all the items. As you point out, if we had an `isna`, we wouldn't need a `dropna` because slicing does that already.

Or... hold that thought. There might be cases inside of `RecordArrays` where it would be very difficult to use slicing. At least, `isna` should be a first priority and we'll see if `dropna` is really needed after that.

**Comment by jpivarski** [comment]
Implemented by PR #92 (and touched-up by 960baf57f43a638cbd46032d20cf9d972243f9ae). `ak.isna` and `ak.notna` were needed for Pandas.

I'll close this to see if the need for `ak.dropna` ever comes up in practice.

**Comment by nsmith-** [comment]
I'd like to re-open this to make sure `ak.isna` has an axis argument, as discussed in https://github.com/scikit-hep/awkward-array/issues/227
