### ISSUE TITLE
Add behavior parameter to ak.zip

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#715]
Currently the resulting array of `ak.zip` has the behavior of the inputs. However often `ak.zip` is used to construct a (highlevel) record array with some particular name from (lowlevel) basic lists or numpy arrays and thus the result is lacking behavior. Creating awkward arrays with a particular behavior of the inputs before calling `ak.zip` is inconvenient.
Thus it would be nice of `ak.zip` takes an optional parameter `behavior` that, if given, is used for the behavior of the result.

**Comment by jpivarski** [comment]
This is a good idea and I'll do it as a quick-fix, but it goes after the 1.1.0 release today.
