### ISSUE TITLE
Slices containing None don't seem to work

### ISSUE THREAD

**Issue by Dominic-Stafford** [scikit-hep/awkward#718]
Trying to slice an array with None to create a new axis produces an error in awkward 1.1.0rc5:
```
>>> arr = ak.Array([1, 2, 3])
>>> arr[:, None]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/desy.de/user/s/stafford/.local/lib/python3.8/site-packages/awkward/highlevel.py", line 1007, in __getitem__
    return ak._util.wrap(self._layout[where], self._behavior)
ValueError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`), and integer or boolean arrays (possibly jagged) are valid indices

(https://github.com/scikit-hep/awkward-1.0/blob/1.1.0rc5/src/python/content.cpp#L669)
```

Thank you

Dominic

**Comment by jpivarski** [comment]
I'm not seeing this, so I uninstalled my local Awkward and installed from pip (version 1.1.0, which is identical to 1.1.0rc5, but we want the non-RC version to be the working one, anyway).

```bash
% pip uninstall awkward
WARNING: Skipping awkward as it is not installed.
% pip install awkward
Collecting awkward
  Downloading awkward-1.1.0-cp38-cp38-manylinux2010_x86_64.whl (7.5 MB)
     |████████████████████████████████| 7.5 MB 1.7 MB/s 
Requirement already satisfied: setuptools in ./miniconda3/lib/python3.8/site-packages (from awkward) (49.6.0.post20210108)
Requirement already satisfied: numpy>=1.13.1 in ./miniconda3/lib/python3.8/site-packages (from awkward) (1.20.0)
Installing collected packages: awkward
Successfully installed awkward-1.1.0
```

```python
>>> import awkward as ak
>>> import numpy as np
>>> arr = ak.Array([1, 2, 3])
>>> arr[:, None]
<Array [[1], [2], [3]] type='3 * 1 * int64'>
>>> arr[:, np.newaxis]
<Array [[1], [2], [3]] type='3 * 1 * int64'>
```

I'm also going to recompile my latest version to see if it's there.

**Comment by Dominic-Stafford** [comment]
Sorry, I hadn't realised 1.1.0 was available now, but having installed that this also seems to work for me, so I'm not sure why the 1.1.0rc5 didn't work for me

**Comment by jpivarski** [comment]
I did some work on generalizing the behavior of `np.newaxis` recently; perhaps one of the intermediate versions was involved?

**Comment by Dominic-Stafford** [comment]
Having updated awkward a couple of times to try and work out what was going on it seems the problem was I forgot to use "python3 -m pip" rather than pip3 to get my user updated version of pip. Sorry to raise it here.
