### ISSUE TITLE
pad

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#73]
This is an operation that turns an array at some level (i.e. has an `axis` parameter) into an OptionType by putting extra `None` elements in until it reaches a given length.

Old Awkward [had an implementation of this](https://github.com/scikit-hep/awkward-array/blob/3442c51ed5dafb7d94f828c6cdc07659f9c03244/awkward/array/jagged.py#L1839-L1888), though it will probably be simpler now. Also, ignore the old `clip` parameter: that's easy enough to do with a slice after the fact. This was another proven-to-be useful operation.

Don't double-up OptionTypes: if something is already an OptionType, extend it.

The implementation might be identical for all non-OptionTypes (those are exceptional because you have to explicitly avoid doubling-up the OptionType): you just put the existing array in an `IndexedOptionArray` that points to the original array with gaps left for the new `None` values.

**Comment by ianna** [comment]
@jpivarski - I'm done with ```axis==0```, I think. The auto generated ```Content``` gets padded  without assertions. Here are some thoughts on implementation, please, comment.

 * The ```length``` in ```pad(length, axis)``` can be interpreted as a desired ```length``` of the array, e.g. ```tolength```, or as a padding with ```length``` so that ```array.length() + length == array.pad(length).length()```. I've implemented the latter.

 * The ```NumpyArray``` padding can be implemented extending its shape or not. The first is similar to numpy padding and can be extended to padding with any value. The latter adds correct number of ```None```'s at ```axis```. I'd think, this is desired behaviour, but I've implemented both.

For example:
```python
array = NumpyArray([ 0,  1,  2,  3,  4, 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],[2, 3, 5], [15, 5, 1], 0)
assert list(array) == [[[ 0,  1,  2,  3,  4], [ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]],
                            [[15, 16, 17, 18, 19], [20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]]
assert list(array.pad(3,0)) == [[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]], [[15, 16, 17, 18, 19], [20, 21, 22, 23, 24], [25, 26, 27, 28, 29]], [[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]], [[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]], [[None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]]]
assert list(array.pad(3,1)) == [[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]],
                                    [[15, 16, 17, 18, 19], [20, 21, 22, 23, 24], [25, 26, 27, 28, 29], [None, None, None, None, None], [None, None, None, None, None], [None, None, None, None, None]]]
assert list(array.pad(3,2)) == [[[ 0,  1,  2,  3,  4, None, None, None], [ 5,  6,  7,  8,  9, None, None, None], [10, 11, 12, 13, 14, None, None, None]],
                                    [[15, 16, 17, 18, 19, None, None, None], [20, 21, 22, 23, 24, None, None, None], [25, 26, 27, 28, 29, None, None, None]]]
```
vs

```python
assert list(array.pad_no_shape(3,0)) == [[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]], [[15, 16, 17, 18, 19], [20, 21, 22, 23, 24], [25, 26, 27, 28, 29]], None, None, None]
assert list(array.pad_no_shape(3,1)) == [[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], None, None, None], [[15, 16, 17, 18, 19], [20, 21, 22, 23, 24], [25, 26, 27, 28, 29], None, None, None]]
assert list(array.pad_no_shape(3,2)) == [[[0, 1, 2, 3, 4, None, None, None], [5, 6, 7, 8, 9, None, None, None], [10, 11, 12, 13, 14, None, None, None]], [[15, 16, 17, 18, 19, None, None, None], [20, 21, 22, 23, 24, None, None, None], [25, 26, 27, 28, 29, None, None, None]]]
```

**Comment by jpivarski** [comment]
I didn't know that NumPy had a `pad` function, but [there it is](https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html). That function seems to be for giving image processing applications a little more room for edge effects. It doesn't even have an `axis` parameter.

Our `pad` was introduced because some physics analyses needed it and it was designed for that use-case ([here is the old code](https://github.com/scikit-hep/awkward-array/blob/a2645fdaed1a6997c4677ae47cbb2cd0663e8a21/awkward/array/jagged.py#L1843-L1892)). Perhaps it should be called `rpad` to avoid confusion with `numpy.pad`. (I just changed the poster to say `rpad`!)

The way I defined it before, my `axis=0` was your `axis=1`. However, I think your definition makes more sense and we should go with that. It's the `pad_no_shape` version of the above that we should be using. I see that your `pad` (without `_no_shape`) does what `numpy.pad` does, and I'm sorry for the confusion.

So I think your `pad_no_shape` is the definition we should use, with your definition of `axis`. The next step would be to replace your implementation that generates UnionArrays with one that generates IndexedOffsetArrays. When all NumpyArrays are one-dimensional, this allows you to add the padding without ever modifying the array that's getting padded. For instance:

```python
>>> import awkward1 as ak, numpy as np
>>> from awkward1.layout import *
>>> array = ak.Array([[1.1, 2.2, 3.3], [], [4.4, 5.5]]).layout
>>> array
<ListOffsetArray64>
    <offsets><Index64 i="[0 3 3 5]" offset="0" at="0x5643ef230880"/></offsets>
    <content><NumpyArray format="d" shape="5" data="1.1 2.2 3.3 4.4 5.5" at="0x5643ef232890"/></content>
</ListOffsetArray64>
```

```python
>>> padindex = Index64(np.array([0, 1, 2, -1, -1, -1, 3, 4, -1]))
>>> padoffsets = Index64(np.array([0, 3, 6, 9]))
>>> padarray = ListOffsetArray64(padoffsets, IndexedOptionArray64(padindex, array.content))
>>> padarray
<ListOffsetArray64>
    <offsets><Index64 i="[0 3 6 9]" offset="0" at="0x5643ef14e860"/></offsets>
    <content><IndexedOptionArray64>
        <index><Index64 i="[0 1 2 -1 -1 -1 3 4 -1]" offset="0" at="0x5643ef236bc0"/></index>
        <content><NumpyArray format="d" shape="5" data="1.1 2.2 3.3 4.4 5.5" at="0x5643ef232890"/></content>
    </IndexedOptionArray64></content>
</ListOffsetArray64>
```

```python
>>> ak.tolist(padarray)
[[1.1, 2.2, 3.3], [None, None, None], [4.4, 5.5, None]]
```

Since we were padding elements of this NumpyArray (and not between dimensions of a multidimensional `shape`), we can just take them as they are. The `padindex` is counting consecutively everywhere there isn't a `None`; we only needed to introduce the IndexedOptionArray and replace the ListOffsetArray.

In addition, users see the distinction between a variable-dimension array that happens to have identical lengths an a truly regular-dimension array. Therefore, this function should have a different behavior (either as a parameter or as two versions of the function) for "pad and clip," which always returns a RegularArray, and "pad at least..." which always returns a ListOffsetArray.

With the same example as above, consider padding _and clipping_ to length 2:

```python
>>> padindex2 = Index64(np.array([0, 1, -1, -1, 3, 4]))
>>> padarray2 = RegularArray(IndexedOptionArray64(padindex2, array.content), 2)
>>> padarray2
<RegularArray size="2">
    <content><IndexedOptionArray64>
        <index><Index64 i="[0 1 -1 -1 3 4]" offset="0" at="0x5643ef220ff0"/></index>
        <content><NumpyArray format="d" shape="5" data="1.1 2.2 3.3 4.4 5.5" at="0x5643ef232890"/></content>
    </IndexedOptionArray64></content>
</RegularArray>
```

```python
>>> ak.tolist(padarray2)
[[1.1, 2.2], [None, None], [4.4, 5.5]]
```

Although at the level of Python lists this looks the same, high-level users will see the difference in type (these are the strings you get from `Type::tostring`):

```python
>>> ak.typeof(padarray)
var * ?float64
>>> ak.typeof(padarray2)
2 * ?float64
```
