### ISSUE TITLE
ak.unflatten should take an axis argument

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#730]
So that you don't have to do this:

```python
structure = ak.Array([[0], [2, 1]])
counts0 = ak.num(structure)
counts1 = ak.flatten(structure)
values = ak.Array([3,4,5])
array = ak.unflatten(ak.unflatten(values, counts1), counts0)
```

(It also came up in the Million Song Dataset prep.)

**Comment by nsmith-** [comment]
What would you do instead if axis were available?

**Comment by jpivarski** [comment]
Oh, not this example. This isn't adding a jagged dimension to `structure`, it's transporting that to a completely new array. Sorry, I jumped to a conclusion. I'll provide the example I saw.

**Comment by jpivarski** [comment]
```python
original = ak.Array([[1, 2, 3, 4], [], [5, 6, 7], [8, 9]])
desired = ak.Array([[[1, 2], [3, 4]], [], [[5], [6, 7]], [[8], [9]]])
```

given

```python
counts = ak.Array([2, 2, 1, 2, 1, 1])
```

Currently, you have to

```python
ak.unflatten(ak.unflatten(ak.flatten(original), counts), [2, 0, 2, 2])
```

in which the `[2, 0, 2, 2]` is determined somehow from the `ak.num(original)` and the `counts`.

We'd like to be able to just

```python
ak.unflatten(original, counts, axis=1)
```
