### ISSUE TITLE
argsort and sort

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#74]
At some level (i.e. this has an `axis` parameter), sort the array. Define the `argsort` version in C++ and we can do the `sort` with an array-slice on the Python side.

Sort orders for numbers in NumpyArray are easy to define, but something will have to be done to sort arrays and records as well. Python has an ordering defined on lists:

```python
>>> [1, 2, 3] < [1, 2]
False
>>> [1, 2, 3] > [1, 2]
True
```

but not records (dicts):

```python
>>> {"one": 1, "two": 2, "three": 3} < {"one": 1, "two": 2}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'dict' and 'dict'
```

However, our `Record` types are actually tuples—there's a defined field order (unlike Python dicts), so we should be able to inherit a definition from Python tuples:

```python
>>> (1, "a", None) < (1, "a")
False
>>> (1, "a", None) > (1, "a")
True
```

**Comment by jpivarski** [comment]
From https://github.com/scikit-hep/awkward-1.0/pull/99#discussion_r376347495

> @jpivarski - please, comment if I understand correctly what `argsort` suppose to do for #74
> Would you rather I used a different sorting algorithm then quick sort? Its average time complexity is `O(n log(n))`, but the worst case is `O(n^2)`. Its worst space complexity is `O(log(n))`

The `argsort` function produces an array of integers that, if applied as a slice, would sort the array. For any functions that have "arg" versions, we should implement the "arg" version first because it usually makes the "non-arg" version trivial. Here's a NumPy example:

```python
>>> import numpy as np
>>> array = np.array([6.6, 3.3, 4.4, 1.1, 4.4, 5.5])
>>> index = np.argsort(array)
>>> index
array([3, 1, 2, 4, 5, 0])
>>> array[index]
array([1.1, 3.3, 4.4, 4.4, 5.5, 6.6])
```

In the above, if we had an `argsort` already written, the `sort` would be just `getitem(Slice({ SliceArray(argsort_result) }))` or something, maybe `carry(argsort_result)`. (Note: this suggests that it should be implemented as an `argsort64` function returning an `Index64` taking no `axis` parameter, so that it can be internally reused, much like `count`.)

The externally visible `argsort` and `sort` functions would take an `axis` parameter, which, for NumPy, determines which direction the sorting is performed:

```python
>>> array = np.array([[6.6, 3.3, 4.4],
...                   [1.1, 4.4, 5.5]])
>>> np.argsort(array, axis=0)   # compare each top with each bottom
array([[1, 0, 0],
       [0, 1, 1]])
>>> np.argsort(array, axis=1)   # compare left-to-right
array([[1, 2, 0],
       [0, 1, 2]])
```

That makes sense when the array is rectilinear. _Maybe_ we could do the same thing with variable-length arrays:

```python
>>> array = ak.Array([[6.6, 3.3, 4.4],
...                   [1.1, 4.4]])
>>> ak.argsort(array, axis=0)   # compare top-to-bottom, missing goes first
<Array [[1, 0], [0, 1, 0]] type='2 * var * int64'>
>>> ak.argsort(array, axis=1)   # compare left-to-right
<Array [[1, 2, 0], [0, 1]] type='2 * var * int64'>
```

but I don't know how or when that would actually be useful. The physics use-case for sorting is either `axis=-1` or at least at the purelist depth. I can't imagine why we'd ever want `axis=0` above, sorting across elements that might not exist because some inner lists are shorter than others.

Maybe this function shouldn't have an `axis` parameter, but something with a new name, like `depth`. It would always sort horizontally, but `depth` controls at what level the sorting occurs.

```python
>>> array = ak.Array([[6.6, 3.3, 4.4],
...                   [1.1, 4.4]])
>>> ak.argsort(array, depth=0)   # lexographically compare [6.6, 3.3, 4.4] against [1.1, 4.4]
<Array [1, 0] type='2 * int64'>
>>> ak.argsort(array, depth=1)   # sort within each list
<Array [[1, 2, 0], [0, 1]] type='2 * var * int64'>
```

_This_ would be useful because the jagged getitem rule (issue #67, ongoing PR #111) would be able to use this result to either sort which list goes first or internally sort each list, depending on the value of `depth`.

So I'd say, let's implement this with a `depth` but no `axis` parameter. An `axis` can always be added later if someone really has a use for it, but the value of `depth` is already evident. To do this in stages, implement `depth=-1` first, since that one doesn't need to introduce a lexicographic ordering on structures, something that should be defined generally.

About which sorting algorithm to use, the main use-case is sorting a large number of small lists, not a single large list. Therefore, scaling badly with _n_ is not as much of an issue as set-up and tear-down costs. Often, the data are already sorted and a physicist just wants to make sure they're sorted, so the running time shouldn't be catastrophic for already-sorted data. (I remember from somewhere that there's a sorting algorithm that has bad time characteristics for already-sorted data.)

**Comment by ianna** [comment]
@jpivarski - thanks! Here is a test of ```argsort``` implemented in Python:

```python
>>> print(array.constructor)
<bound method NumpyArray.constructor of <NumpyArray>
    <ptr>5.0 5.1 4.2 6.2 9.7 -0.7 0.6 4.9 5.7 7.7 -0.1 8.2 7.7 5.5 8.5 5.7 5.4 4.3 1.2 4.6 4.8 3.9 4.2 8.4 9.5 3.1 2.2 0.9 8.0 3.6 3.6 9.6 2.6 1.7 4.0 6.6 10.1 5.5 0.8 4.6 6.2 -0.2 6.4 6.7 3.2 3.1 8.5 5.3 7.4 7.8 9.0 5.3 3.1 5.8 2.7 8.3 9.0 0.5 4.5 1.6 9.6 6.2 5.0 2.3 7.2</ptr>
    <shape>21 3</shape>
    <strides>3 1</strides>
    <offset>2</offset>
</NumpyArray>>
>>> print(list(array))
[[4.2, 6.2, 9.7], [-0.7, 0.6, 4.9], [5.7, 7.7, -0.1], [8.2, 7.7, 5.5], [8.5, 5.7, 5.4], [4.3, 1.2, 4.6], [4.8, 3.9, 4.2], [8.4, 9.5, 3.1], [2.2, 0.9, 8.0], [3.6, 3.6, 9.6], [2.6, 1.7, 4.0], [6.6, 10.1, 5.5], [0.8, 4.6, 6.2], [-0.2, 6.4, 6.7], [3.2, 3.1, 8.5], [5.3, 7.4, 7.8], [9.0, 5.3, 3.1], [5.8, 2.7, 8.3], [9.0, 0.5, 4.5], [1.6, 9.6, 6.2], [5.0, 2.3, 7.2]]
>>> indices = array.argsort()
>>> print(list(indices))
[5, 41, 10, 57, 6, 38, 27, 18, 59, 33, 26, 63, 32, 54, 52, 45, 25, 44, 29, 30, 21, 34, 22, 2, 17, 58, 19, 39, 20, 7, 62, 47, 51, 16, 37, 13, 8, 15, 53, 61, 40, 3, 42, 35, 43, 64, 48, 9, 12, 49, 28, 11, 55, 23, 46, 14, 56, 50, 24, 60, 31, 4, 36]
>>> sorted_array = []
>>> for i in range(len(indices)):
...     sorted_array.append(array.ptr[indices[i]])
... 
>>> print(list(sorted_array))
[-0.7, -0.2, -0.1, 0.5, 0.6, 0.8, 0.9, 1.2, 1.6, 1.7, 2.2, 2.3, 2.6, 2.7, 3.1, 3.1, 3.1, 3.2, 3.6, 3.6, 3.9, 4.0, 4.2, 4.2, 4.3, 4.5, 4.6, 4.6, 4.8, 4.9, 5.0, 5.3, 5.3, 5.4, 5.5, 5.5, 5.7, 5.7, 5.8, 6.2, 6.2, 6.2, 6.4, 6.6, 6.7, 7.2, 7.4, 7.7, 7.7, 7.8, 8.0, 8.2, 8.3, 8.4, 8.5, 8.5, 9.0, 9.0, 9.5, 9.6, 9.6, 9.7, 10.1]
>>> 

```

**Comment by jpivarski** [comment]
We would want it to sort within arrays, like

```python
>>> array.argsort(depth=-1)
[[0, 1, 2], [0, 1, 2], [2, 0, 1], [2, 1, 0], [2, 1, 0], [1, 0, 2], [1, 2, 0], [2, 0, 1], [1, 0, 2], [0, 1, 2], [1, 0, 2], [2, 0, 1], [0, 1, 2], [0, 1, 2], [1, 0, 2], [0, 1, 2], [2, 1, 0], [1, 0, 2], [1, 2, 0], [0, 2, 1], [1, 0, 2]]
```

The primary use-case of this is to sort particles within an event (which is why an algorithm that scales well with _n_ is not as important as the constant-time part of set-up and tear-down). Also, operations shouldn't eliminate structure like this—they should do _something_ with it.
