### ISSUE TITLE
ak.Array should have a convenience method `to_numpy`

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#749]
It would just pass through to [ak.to_numpy](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_numpy.html), but it's much more convenient if it's a method, both for typing and so that third party libraries can check for its existence and call it (without `import awkward`!). @tacaswell suggested this and pointed out that it's like Pandas:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html#pandas-dataframe-to-numpy

and almost like xarray:

http://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_array.html#xarray-dataset-to-array

(which is unfortunately spelled differently: `to_numpy` vs `to_array`; I like `to_numpy` better).

The [ak.Array.tolist](https://awkward-array.readthedocs.io/en/latest/_auto/ak.Array.html#ak-array-tolist) method was spelled without the underscore because of the precedent set by [np.ndarray.tolist](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.tolist.html), but maybe it should have a second spelling (a synonym!) with an underscore, for symmetry. It has an underscore in [ak.to_list](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_list.html).

**Comment by keewis** [comment]
be aware that a better name for `xarray.Dataset.to_array` would probably be `to_dataarray`: it tries to combine all data variables into a single `DataArray`. `Dataset` itself doesn't have something like `to_numpy` (you would have to use `to_array` first), but for `DataArray` the `values` property can be used. I think we're open to adding something like `to_numpy`, though, see pydata/xarray#3245.
