### ISSUE TITLE
ak.zip for scalars should return a Record

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/awkward#758]
For example,
```python
>>> ak.zip({"x": 1, "y": 0, "z": 0})

TypeError: 1 cannot be converted into an Awkward Array
```
could in principle return a record, e.g.
```
>>> ak.Record({"x": 1, "y": 0, "z": 0})
<Record {x: 1, y: 0, z: 0} type='{"x": int64, "y": int64, "z": int64}'>
```

**Comment by jpivarski** [comment]
So if they're _all_ scalars, we could remember that fact, turn them into arrays, run the whole process, and (based on the "are they scalars?" flag) turn the resulting length-1 RecordArrays into Records?

What if some are scalars and some are not?

**Comment by nsmith-** [comment]
A motivating example is that, though mixin functions like:
```python
    def r2(self):
        return self.x ** 2 + self.y ** 2
```
can accept Record or Array objects, functions like
```python
    @awkward.mixin_class_method(numpy.add, {"TwoVector"})
    def add(self, other):
        return awkward.zip(
            {"x": self.x + other.x, "y": self.y + other.y},
            with_name="TwoVector",
        )
```
cannot but would be with this change. Such a Record construction would be valid only if all arguments are scalars. If one argument is an array, in principle the arguments may be broadcast-compatible.

I would suggest the zip operation checks first if all elements are scalars or ak.Record types, and if so make a new ak.Record. Else, attempt to broadcast the arguments and do the array construction, else fail.

**Comment by jpivarski** [comment]
Okay, the flag can be set to `True` if they are _all_ scalars, but in any case, scalars are turned into length-1 arrays. Then if there's a mixture, the non-scalars would naturally broadcast the length-1 arrays if possible. That would handle your three cases.

**Comment by jpivarski** [comment]
PR #839 implements

```python
assert isinstance(ak.zip({"x": 1, "y": 0, "z": 0}), ak.Record)
```

If any element is not a scalar, the result will be `ak.Array` (and the elements that _are_ scalars will be singletons, which would get broadcasted).
