### ISSUE TITLE
Return of issue: in dependent project, ak.layout fails to convert to ak::Content

### ISSUE THREAD

**Issue by raymondEhlers** [scikit-hep/awkward#774]
Unfortunately, it seems that issue #483 has resurfaced after updating to the new versions of awkward (1.2.0rc2) and pybind11 (2.6.2). Just trying to pass an awkward array into a c++ function on ubuntu 18.04, I get:

```
========================================================================================== FAILURES ===========================================================================================
______________________________________________________________________________________ test_numpy_array _______________________________________________________________________________________

    def test_numpy_array() -> None:
>       pba.awkward_test_numpy_array(ak.Array([1,2,3]).layout)
E       TypeError: awkward_test_numpy_array(): incompatible function arguments. The following argument types are supported:
E           1. (arr: awkward::NumpyArray) -> awkward::NumpyArray
E
E       Invoked with: <NumpyArray format="l" shape="3" data="1 2 3" at="0x562381da0240"/>


tests/test_simple.py:6: TypeError
_____________________________________________________________________________________ test_awkward_array ______________________________________________________________________________________

    def test_awkward_array() -> None:
>       pba.awkward_test(ak.Array([1,2,3]).layout)
E       TypeError: awkward_test(): incompatible function arguments. The following argument types are supported:
E           1. (arr: awkward::Content) -> awkward::Content
E
E       Invoked with: <NumpyArray format="l" shape="3" data="1 2 3" at="0x562381dada40"/>


tests/test_simple.py:9: TypeError
=================================================================================== short test summary info ===================================================================================
FAILED tests/test_simple.py::test_numpy_array - TypeError: awkward_test_numpy_array(): incompatible function arguments. The following argument types are supported:
FAILED tests/test_simple.py::test_awkward_array - TypeError: awkward_test(): incompatible function arguments. The following argument types are supported:
====================================================================================== 2 failed in 0.30s ======================================================================================
```

The full reproducer is here: https://github.com/raymondEhlers/pybind11-awkward-array-test . It was a few c++ functions in `pybind11_awkward/src/binding.cpp`, and then the tests leading to the failures above are in `tests`. It uses poetry, but you should be able to build it with pep 517:

```bash
# in some virtualenv
pip install .
pytest tests/test_simple.py
```

Recall that this doesn't seem to occur on macOS, but only on linux. Perhaps I've forgotten to somehow link everything properly? In any case, I must be doing something trivially wrong, but I can't seem to find it. Any advice is appreciated!

(I created a new issue because I realized I couldn't reopen the previous one and I didn't want it to get lost. We can return there if preferred)

_Originally posted by @raymondEhlers in https://github.com/scikit-hep/awkward-1.0/issues/483#issuecomment-789061311_

**Comment by jpivarski** [comment]
Something peculiar is going on. I checked out raymondEhlers/pybind11-awkward-array-test, compiled it, and ran the tests, but they passed for me (on Linux):

```
% pytest -vv -rs tests
============================= test session starts ==============================
platform linux -- Python 3.8.8, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /home/jpivarski/miniconda3/bin/python
cachedir: .pytest_cache
rootdir: /tmp/pybind11-awkward-array-test
plugins: anyio-2.1.0
collected 2 items                                                              

tests/test_simple.py::test_numpy_array PASSED                            [ 50%]
tests/test_simple.py::test_awkward_array PASSED                          [100%]

============================== 2 passed in 0.26s ===============================
In function for NumpyArray
In function
% python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import awkward
>>> awkward.__version__
'1.2.0rc2'
```

It looks like your pybind11 submodule is pointing at the same commit as Awkward Array's (8de7772), but I wasn't able to check it out that way:

```
% git clone --recursive https://github.com/raymondEhlers/pybind11-awkward-array-test.git
Cloning into 'pybind11-awkward-array-test'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 63 (delta 26), reused 58 (delta 21), pack-reused 0
Unpacking objects: 100% (63/63), 36.85 KiB | 539.00 KiB/s, done.
Submodule 'pybind11' (git@github.com:pybind/pybind11.git) registered for path 'pybind11'
Cloning into '/tmp/pybind11-awkward-array-test/pybind11'...
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pybind/pybind11.git' into submodule path '/tmp/pybind11-awkward-array-test/pybind11' failed
Failed to clone 'pybind11'. Retry scheduled
Cloning into '/tmp/pybind11-awkward-array-test/pybind11'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:pybind/pybind11.git' into submodule path '/tmp/pybind11-awkward-array-test/pybind11' failed
Failed to clone 'pybind11' a second time, aborting
```

So I did the test by recursively copying mine, from the scikit-hep/awkward-1.0 directory. That might be a clue to why it succeeded for me.

Since it might be related to the issue, I tried a recursive checkout of scikit-hep/awkward-1.0 and there were no problems.

Thanks for including the minimally reproducing repo!

**Comment by raymondEhlers** [comment]
Thanks for taking a look! Indeed something quite strange is going on.

I'm guessing that submodule is failing because I used ssh for the pybind11 submodule instead of https?

```
[submodule "pybind11"]
    path = pybind11
    url = git@github.com:pybind/pybind11.git
```

For completeness, I cloned the reproducer and awkward in a clean directory, copied pybind11 from awkward to the reproducer, rebuilt, and the tests still fail :-(

Since the tests passed on your system, I tried out a Debian machine with python 3.9, and the tests passed (I don't think they did in the past, so I suppose this is progress). So I suppose it's somehow a bad combination of ubuntu 18.04, gcc (Ubuntu 7.5.0-3ubuntu1~18.04), and python version (3.7.7 from pyenv with `--enable-shared`).

At some point I got it working after the previous pybind11 upgrade, so it must be possible, but I suppose I'll have to write it off as system specific (it's a cluster, so I'm not fully in control, but will figure something out). Thanks for your help, and sorry for the noise!

**Comment by raymondEhlers** [comment]
If I make any progress I'll post some updates here. I'm not looking for any action at this point, but just documenting for anyone else who gets into trouble.

For now, on the debian machine, I've managed to get the reproducer repo to pass the tests, but fail the full package. So in principle, I should be able to isolate it. But of course, easier said than done.

I now think it may be something about PEP 517 builds vs native poetry builds. Totally unclear why this should matter, but it seems to pretty consistently fail with PEP 517 builds in a clean environment (ie: `poetry shell; pip install .`), while `poetry install` in a clean environment seems to work
