### ISSUE TITLE
Dead link to "how-it-works tutorials for developers" in CONTRIBUTING.md

### ISSUE THREAD

**Issue by simonthor** [scikit-hep/awkward#777]
Hello,

I was reading through CONTRIBUTING.md and noticed that the hyperlink to the "how-it-works tutorials for developers" under the [performance considerations](https://github.com/scikit-hep/awkward-1.0/blob/main/CONTRIBUTING.md#performance-considerations) section (first paragraph) had a link that redirected to [this 404 page](https://scikit-hep.org/awkward-1.0/how-it-works.html). Would it be possible to replace this link with a new one, as I assume the page has been moved?

**Comment by jpivarski** [comment]
I pushed a correction to the text directly to master. This link went to a stub for documentation that hadn't been written, then the structure got reorganized.

Thanks for catching it!
