### ISSUE TITLE
ak.flatten fails to flatten 1D array

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/awkward#782]
I have a simple array, repr looks like this:
`<Array [-0.0848, -0.00858, 0.13, -0.0658] type='4 * float32'>`

Applying `ak.flatten` yields this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-80600ed80be4> in <module>
     13         c = px - mc_px
     14         print(repr(c))
---> 15         ak.flatten(c)
     16         delta_px = np.append(delta_px, ak.flatten(px) - ak.flatten(mc_px))
     17 

/usr/local/lib/python3.8/site-packages/awkward/operations/structure.py in flatten(array, axis, highlevel, behavior)
   1665 
   1666     else:
-> 1667         out = layout.flatten(axis)
   1668 
   1669     if highlevel:

ValueError: axis out of range for flatten

(https://github.com/scikit-hep/awkward-1.0/blob/1.1.2/src/libawkward/array/NumpyArray.cpp#L1568)
```
I am not sure what exactly the problem is, but `ak.flatten` should also work on arrays of any dimension.

**Comment by jpivarski** [comment]
The default `axis` of [ak.flatten](https://awkward-array.readthedocs.io/en/latest/_auto/ak.flatten.html) is `axis=1`, and a one-dimensional array doesn't have such an axis (it is out of range).

The main purpose of this function is to reduce the dimension of an array by one, which can't be done to a one-dimensional array. If you want to reduce the dimension of _any_ array _to_ one, that's `ak.flatten` with `axis=None` (following NumPy conventions).

```python
>>> ak.flatten(ak.Array([-0.0848, -0.00858, 0.13, -0.0658]), axis=None)
<Array [-0.0848, -0.00858, 0.13, -0.0658] type='4 * float64'>
```
