### ISSUE TITLE
Can np.zeros_like(awkd_array) have a dtype argument?

### ISSUE THREAD

**Issue by HenryDayHall** [scikit-hep/awkward#813]
Normally np.zeros_like can be given a dtype argument, like;
```python3
import numpy as np
cat = np.array([1, 2])
mask = np.zeros_like(bird, dtype=bool)
```
It's particularly useful when creating masks, but I've used it to ensure and array is an int array too.
When used on an awkward array this throws an error;
```python3
In [1]: import awkward

In [2]: import numpy as np

In [3]: dog = awkward.from_iter([2, 5])

In [4]: mask = np.zeros_like(dog, dtype=bool)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-8daf51a4c0a1> in <module>
----> 1 mask = np.zeros_like(dog, dtype=bool)

<__array_function__ internals> in zeros_like(*args, **kwargs)

~/Programs/anaconda3/envs/tree/lib/python3.7/site-packages/awkward/highlevel.py in __array_function__(self, func, types, args, kwargs)
   1396         See also #__array_ufunc__.
   1397         """
-> 1398         return ak._connect._numpy.array_function(func, types, args, kwargs)
   1399
   1400     @property

~/Programs/anaconda3/envs/tree/lib/python3.7/site-packages/awkward/_connect/_numpy.py in array_function(func, types, args, kwargs)
     26         return NotImplemented
     27     else:
---> 28         return function(*args, **kwargs)
     29
     30

TypeError: zeros_like() got an unexpected keyword argument 'dtype'
```
There are plenty of ways round this, but it would be neat if it did work.

**Comment by jpivarski** [comment]
I agree. If `ak.zeros_like`, `ak.ones_like`, and `ak.empty_like` had a `dtype` argument, it would be implemented by simply running the function as usual and replacing the output with a call to [ak.values_astype](https://awkward-array.readthedocs.io/en/latest/_auto/ak.values_astype.html).

Here's where the three "like" functions are defined (in terms of each other):

https://github.com/scikit-hep/awkward-1.0/blob/4a860e775502f9adb953524c35c5a2de8f7a3181/src/awkward/operations/structure.py#L1050-L1240

I'd welcome a pull request that does this. (Note that `values_astype` is [defined in the same module](https://github.com/scikit-hep/awkward-1.0/blob/4a860e775502f9adb953524c35c5a2de8f7a3181/src/awkward/operations/structure.py#L4164-L4207), so its name does not need to be qualified.)

**Comment by HenryDayHall** [comment]
Neat, I'd love to give that a try, but I don't know the etiquette. Is it normal to include updates to the unit tests in the same pull request when adding a feature?

**Comment by jpivarski** [comment]
Including a test would be ideal; the naming convention for test files is derived from either the issue number (0813) or the PR number (some PRs aren't associated with an explicit issue). That way, you don't need to modify any other test files, but you can use them as an example of format. Other than that, it's a normal PR process.

Since this is a Python edit, you don't need to use the localbuild.py script described for incremental development in the [CONTRIBUTING.md](https://github.com/scikit-hep/awkward-1.0/blob/main/CONTRIBUTING.md), you can use

```
python -m pip install -v -e .
```

which I just learned about. The `-e` means that when you edit a Python file, it immediately shows up in the installed library. I need to add a description of that to CONTRIBUTING.md.

**Comment by HenryDayHall** [comment]
Thanks, that makes sense. Also CONTRIBUTING.md is very helpful, that preempted a lot of the mistakes I would have made. I will give it a go now.

**Comment by HenryDayHall** [comment]
For what it's worth, `python -m pip install -v -e .` didn't work for me but `python localbuild.py --pytest tests` did work. 
Here is the tail end of the install;
```
    [100%] Built target awkward
    Install the project...
    -- Install configuration: "Release"
    -- Installing: /home/henry/Programs/awkward-1.0/build/lib.linux-x86_64-3.9/awkward/libawkward-static.a
    -- Installing: /home/henry/Programs/awkward-1.0/build/lib.linux-x86_64-3.9/awkward/libawkward.so
    -- Installing: /home/henry/Programs/awkward-1.0/build/lib.linux-x86_64-3.9/awkward/libawkward-cpu-kernels.so
    -- Installing: /home/henry/Programs/awkward-1.0/build/lib.linux-x86_64-3.9/awkward/libawkward-cpu-kernels-static.a
    -- Installing: /home/henry/Programs/awkward-1.0/build/lib.linux-x86_64-3.9/awkward/_ext.cpython-39-x86_64-linux-gnu.so
    error: can't copy 'build/lib.linux-x86_64-3.9/awkward.cpython-39-x86_64-linux-gnu.so': doesn't exist or not a regular file
ERROR: Command errored out with exit status 1: /home/henry/Programs/anaconda3/envs/awkddev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/henry/Programs/awkward-1.0/setup.py'"'"'; __file__='"'"'/home/henry/Programs/awkward-1.0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/henry/Programs/anaconda3/envs/awkddev/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/home/henry/Programs/anaconda3/envs/awkddev/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/home/henry/Programs/anaconda3/envs/awkddev/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 391, in run
    installed = install_given_reqs(
  File "/home/henry/Programs/anaconda3/envs/awkddev/lib/python3.9/site-packages/pip/_internal/req/__init__.py", line 80, in install_given_reqs
    requirement.install(
  File "/home/henry/Programs/anaconda3/envs/awkddev/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 764, in install
    install_editable_legacy(
  File "/home/henry/Programs/anaconda3/envs/awkddev/lib/python3.9/site-packages/pip/_internal/operations/install/editable_legacy.py", line 49, in install_editable
    call_subprocess(
  File "/home/henry/Programs/anaconda3/envs/awkddev/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 258, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /home/henry/Programs/anaconda3/envs/awkddev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/henry/Programs/awkward-1.0/setup.py'"'"'; __file__='"'"'/home/henry/Programs/awkward-1.0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-4lxgyewy'
```

Not that is really matters.

**Comment by jpivarski** [comment]
I've never tried `pip install -e .` with Awkward Array before; thanks for being the guinea pig! I had assumed that it would just work, and depending on how much it did incrementally, we might have been able to retire the localbuild.py script. Oh well, the localbuild.py script does work, even though it's non-standard (and it's only for developers—the wheel-building and deployment is a standard `pip install`).

**Comment by HenryDayHall** [comment]
So I've been looking at this in https://github.com/scikit-hep/awkward-1.0/pull/814/files/82eb2f2ba94a06a553b14c9afc7449de7891a57a..63c8a0cf9db0e31407d16ef5c99838b4c64f21ec
and I realise that `np.zeros_like(awkward_array)` will convert a bytestring or string like; `b"dog"` goes to `b"0"` or `"dog"` to `"0"`. As in, they remain bytestrings or strings, but take the new value. Conversely, if `ak.values_astype` is called on an array containing strings or bytestrings it specifically ignores the bytestrings and strings. Only things that are not bytestrings or strings get converted. 

This means that a simply calling the values_astype function when the dtype parameter is set gives weird behaviour for arrays with strings or bytestrings in. The value gets changed, but the type does not. For example;
```python3
In [0]: cat = ak.Array([5.6, b"meow"])

In [1]: np.zeros_like(cat, dtype=int)
Out[1]: <Array [0, b''] type='2 * union[int64, bytes]'>

In [2]: np.ones_like(cat, dtype=int)
Out[2]: <Array [1, b'1'] type='2 * union[int64, bytes]'>
```
Would the best solution be to add an arguments to `ak.values_astype` called `include_string` and `include_bytes`, which, if switched on would cause it to act on strings and bytes? May I include this in the same pull request?

**Comment by jpivarski** [comment]
The string behavior (odd as it is) was made to agree with what NumPy does in its `astype` method. What does `np.ones_like(array, dtype=int)` do to a NumPy `array` of strings?

If it's different, the right way to handle it is to put most of the implementation of `values_astype` into a hidden function, `_values_astype`, with an extra argument so that `zeros_like`/`ones_like`/`empty_like` have a "back door" to specify a different behavior. But the public `ak.values_astype` shouldn't make this back door visible.

Thanks again and sorry for this unforeseen complication!

**Comment by HenryDayHall** [comment]
No worries, writing an implementation is an excellent way to find hidden complexity in a simple idea. I think that is great fun.

So actually, that isn't the behaviour I get for numpy's `astype`. With numpy (versions 1.17.4 and 1.20.2) I get;
```python3
>> import numpy as np
>> say = np.array(['4', '3', '1', '1', '0'])
>> say.astype(int)
array([4, 3, 1, 1, 0])
```
Where as from awkward (version from github, 1.3.0rc1) I get;
```python3
>> import awkward as ak
>> say = ak.from_iter(['4', '3', '1', '1', '0'])
>> ak.values_astype(say, int)
<Array ['4', '3', '1', '1', '0'] type='5 * string'>
```
Looking at the code in `values_astype`, it looks pretty intentional, so I wondered if the reason for calling it `values_astype` rather than just `astype` was that it only acts on numerics?

**Comment by jpivarski** [comment]
I think we put in some effort to make `ak.zeros_like` do the right things for string types but we didn't do the same for `ak.values_astype`. That's not why it's called "`values_astype`" instead of just "`astype`," the reason is because it doesn't try to coerce lists or records into a chosen dtype like `int`; it descends to the leaves of the tree and applies it there (a consideration that NumPy doesn't have to make). We briefly considered calling it "`leaves_astype`," but that would be confusing, especially if the surrounding context involves ROOT TTrees.

It may be too much to try to fix `ak.values_astype` so that passing `dtype=int` changes strings representing numbers into the corresponding integers. That would go deep into the C++. For this project, it would be best to assume that `values_astype` has the correct behavior, use it, and someday we'll fix `values_astype`.

**Comment by HenryDayHall** [comment]
Here is the pull request for this; https://github.com/scikit-hep/awkward-1.0/pull/814
I'm not sure if it goes to the right branch, and if the tests I wrote have the idiomatic form?

Also, I cannot figure out how to link it to this issue, sorry.
