### ISSUE TITLE
Version 1.2.1 missing macOS 3.9 wheel

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/awkward#821]
Version 1.2.1 is missing the macOS wheel for Python 3.9. causing it to try to build from source. The wheel was present in 1.2.0.

**Comment by henryiii** [comment]
Guessing from https://github.com/scikit-hep/awkward-1.0/runs/2290370917 , I'd say macOS Python 3.7 is missing too.

**Comment by henryiii** [comment]
When I work on the build infrastructure, one key piece is to only upload if all jobs complete successfully, via a deploy pipeline (Azure) or a `needs:` job (GHA). That element was part of the original azure-wheel-helpers, but seems to have been removed here. This is what it was supposed to protect against.

@jpivarski maybe you can retrigger the two failed jobs?

**Comment by jpivarski** [comment]
I've retriggered, and I would be in favor of this "all or nothing" logic.

**Comment by jpivarski** [comment]
Retriggered, which solves the immediate issue. Should we leave this PR open until the "all or nothing" logic is (re)added?

https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=6207&view=results

**Comment by henryiii** [comment]
I'll be adding that anyway when following the Scikit-HEP developer guidelines, so I think this is closable.
