### ISSUE TITLE
`ak.is_none` returns NumpyArray as-is

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#863]
Reproducer:
```python
>>> import awkward as ak
>>> ak.is_none(np.arange(12))
<Array [0, 1, 2, 3, 4, 5, ... 7, 8, 9, 10, 11] type='12 * int64'>
```

I assume that the cause is [this final `else` clause](https://github.com/scikit-hep/awkward-1.0/blob/4aaae9a4ddbff3b42d633b38d07f047794463d62/src/awkward/operations/structure.py#L2546-L2558), which is visited as `NumpyArray` is not considered by the `zeros` case. I would assume the solution is just to add another type to the `isinstance` call?

Version Info
```python
>>> import awkward as ak
>>> ak.__version__
ak.__version__
```

**Comment by jpivarski** [comment]
Yes, this was a bug and #864 fixes it; thank you!
