### ISSUE TITLE
`ak.from_parquet` lazy loading does not consider `columns` arg early enough

### ISSUE THREAD

**Issue by drahnreb** [scikit-hep/awkward#865]
When using `ak.from_parquet()` with `lazy=True` the function seems to take a different code path that ignores the `columns` argument in the early stages. Not sure if this is a bug or intended behavior because `ak.layout.VirtualArray` requires it (but then it seems to be undocumented - apart from datetime fields generally not supported)?

The following fails (a particularly useful example to exclude fields of yet (#835 🎉 ) unsupported datatypes):
```python
>>> import awkward as ak
>>> ak.__version__
'1.2.3'
>>> example_df_with_datetime_col = pd.DataFrame({
             'timestamp': [1621164368000000000],
             'datetime': [pd.to_datetime(1621164368000000000)]
})
>>> example_df_with_datetime_col.to_parquet('table_with_datetime_col.parquet')
>>> ak.from_parquet('table_with_datetime_col.parquet', columns=['timestamp'], lazy=True)

ValueError: cannot convert NumPy dtype with kind M into a NumpyForm
(https://github.com/scikit-hep/awkward-1.0/blob/1.2.3/src/libawkward/Content.cpp#L232)

# in contrast:
>>> ak.from_parquet('table_with_datetime_col.parquet', columns=['timestamp'])  # works as expected
>>> ak.from_parquet('table_with_datetime_col.parquet')  # fails as expected
ValueError: cannot include dtype 'M' in a buffer
```

**Comment by jpivarski** [comment]
Is the only unsupported field type datetime and timedelta? If so, then #835 would solve it. Nevertheless, I can check to see if it's building Forms for columns that aren't in the requested set of columns and prevent that, since they won't be used later. Thanks for catching this.

**Comment by drahnreb** [comment]
> Is the only unsupported field type datetime and timedelta?  If so, then #835 would solve it.

Yes, great PR. I saw. Those field types seem to be the only ones affected. At least from what I experienced.

> Nevertheless, I can check to see if it's building Forms for columns that aren't in the requested set of columns and prevent that, since they won't be used later.

Great, I think PR #867 should fix it.
