### ISSUE TITLE
Issue on page /how-to-restructure-pad.html

### ISSUE THREAD

**Issue by mswiatlo** [scikit-hep/awkward#872]
Hi @jpivarski ,

I'd be interested in this documentation/example, if you have one! Thanks!

Cheers,
Max

**Comment by jpivarski** [comment]
Okay, it's bumped up in priority; thanks!

Just to be sure you know about it, the [ak.pad_none](https://awkward-array.readthedocs.io/en/latest/_auto/ak.pad_none.html) reference documentation has a few examples.

**Comment by mswiatlo** [comment]
Thanks! I found that too and it also seemed helpful!

**Comment by jpivarski** [comment]
Done in #943.

**Comment by mswiatlo** [comment]
Thanks @jpivarski !
