### ISSUE TITLE
`__getitem__` gives wrong result when called with masked indices from `NumpyArray` with offset

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/awkward#876]
For example:

```python
>>> import awkward as ak
>>> indices = ak.Array([0, 1, 2, 3, 4, 5])
>>> array = ak.Array([0, 10, 20, 30, 40])
>>> indices_with_offset = indices[3:4]
>>> indices_with_offset
<Array [3] type='1 * int64'>
```
the following should give `[30]`
```python
>>> array[indices_with_offset.mask[[True]]]
<Array [0] type='1 * ?int64'>
```
it's fine without the masking
```python
>>> array[indices_with_offset]
<Array [30] type='1 * int64'>
```
also fine with masking, but when the `NumpyArray` does not have an offset
```python
>>> indices_without_offset = ak.Array([3])
>>> array[indices_without_offset.mask[[True]]]
<Array [30] type='1 * ?int64'>
```

```python
>>> import awkward as ak
>>> ak.__version__
'1.3.0rc4'
```

Found this while experimenting with the `_apply_global_index` function from `coffea.nanoevents` - tagging @nsmith-

**Comment by jpivarski** [comment]
I confirm:

```python
>>> i = ak.Array([0, 1, 2, 3, 4, 5])
>>> x = ak.Array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6])
>>> x[i[3:4].mask[[True]]]
<Array [1.1] type='1 * ?float64'>
>>> x[i[3:4][[True]]]
<Array [4.4] type='1 * float64'>
```

The problem isn't in converting this index (`i`) into a slice:

```python
>>> ak._ext._slice_tostring(i[3:4].mask[[True]])
'[missing([0], array([3]))]'
>>> ak._ext._slice_tostring(i[3:4][[True]])
'[array([3])]'
>>> ak._ext._slice_tostring(i[3:4])
'[array([3])]'
```

but apparently, the `SliceMissing` is ignoring an offset at some level. I'm looking into it.

**Comment by jpivarski** [comment]
It also doesn't require the target array (`x`) to be flat:

```python
>>> i = ak.Array([0, 1, 2])
>>> x = ak.Array([[1.1, 2.2, 3.3], [], [4.4, 5.5]])
>>> x[i[2:][[True]]]
<Array [[4.4, 5.5]] type='1 * var * float64'>
>>> x[i[2:].mask[[True]]]
<Array [[1.1, 2.2, 3.3]] type='1 * option[var * float64]'>
```

**Comment by jpivarski** [comment]
Almost a year ago, all of the kernel functions were converted from taking array offsets as arguments to just being given the correct pointer position. To make this easier, an `Index64::data` method was added that returns the pointer position with offset accounted for, but this was a corner case that still had `.ptr().get()` instead of `.data()`.

c8821f7 fixes it, but I'm going to look for any other instances of the old idiom. It's disturbing to get the wrong answer from a slice—thanks a lot for finding this and isolating it so it could be easily fixed!

**Comment by lgray** [comment]
Can this please be integrated into a bugfix release?

**Comment by jpivarski** [comment]
Actually, it's time for a new minor release: [1.3.0](https://github.com/scikit-hep/awkward-1.0/releases/tag/1.3.0).

[Track its progress here.](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=6444&view=results)

**Comment by lgray** [comment]
Awesome :D
