### ISSUE TITLE
non-PrimitiveType `what` should fail in `ak.with_field()`

### ISSUE THREAD

**Issue by drahnreb** [scikit-hep/awkward#879]
```python
>>> import awkward as ak
>>> ak.__version__
1.2.3
>>> test = ak.Array({'': []})
# this should fail (or create a type `?unknown` ?)
>>> test = ak.with_field(
    base=test,
    what=None,
    where='non-PrimitiveType_field'
)
>>> test
python3.8/site-packages/awkward/_util.py in highlevel_type(layout, behavior, isarray)
   1412 def highlevel_type(layout, behavior, isarray):
   1413     if isarray:
-> 1414         return ak.types.ArrayType(layout.type(typestrs(behavior)), len(layout))
   1415     else:
   1416         return layout.type(typestrs(behavior))

ValueError: Numpy format "O" cannot be expressed as a PrimitiveType
(https://github.com/scikit-hep/awkward-1.0/blob/1.2.3/src/libawkward/array/NumpyArray.cpp#L81)
```

I think this should fail early and not only at ak._utils / repr(test).
A type check should be around [these (structure.py#L963)](https://github.com/scikit-hep/awkward-1.0/blob/22501ba218646dc24dc515c4394eb22f126d340d/src/awkward/operations/structure.py#L963) lines?

Sorry for bringing up all these null-typed issues... I can try to PR for this issue later this week.

**Comment by drahnreb** [comment]
I know that the following is broadcasted and is working as expected (to get `unknown` typed):
`what=[None]`
or
`what=[None for _ in range(len(test))]` (`if len(test) != 0`)

But the above should still raise a ValueError early (if not broadcasted to one of those alternatives).

**Comment by jpivarski** [comment]
Yes, if `what is None` on the line you linked to, then the appropriate thing to convert `what` into is

```python
>>> what = ak.layout.IndexedOptionArray64(
...     ak.layout.Index64(nplike.full(len(base), -1, np.int64)),
...     ak.layout.EmptyArray()
... )
>>> what
<IndexedOptionArray64>
    <index><Index64 i="[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]" offset="0" length="10"/></index>
    <content><EmptyArray/></content>
</IndexedOptionArray64>
>>> ak.Array(what)
<Array [None, None, None, ... None, None, None] type='10 * ?unknown'>
```

If you could make a PR, I'd really appreciate it. Thanks!

**Comment by drahnreb** [comment]
Will do, including test.

**Comment by agoose77** [comment]
@jpivarski is your suggestion here to special-case the `what is None` argument to `with_field` such that it is broadcast to the array shape? 

EDIT: I always forget the UK is a bit ahead of the states! I've made a PR #880 where we can discuss this :)
