### ISSUE TITLE
`ak.unzip` does not fail for unions of heterogeneous records

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#898]
Given two record arrays with different fields, e.g.

```python
>>> a = ak.Array([{"this": 100}])
>>> b = ak.Array([{"this": 90, "that": 100}])
```
the concatenated array has a union type:
```python3
>>> c = ak.concatenate((a, b))
>>> c.type
2 * union[{"this": int64}, {"this": int64, "that": int64}]
```

This union should fail to unzip, because the second array has field `that` whilst the first array does not. At present, this does not fail:
```python
>>> ak.unzip(c)
(<Array [100, 90] type='2 * union[int64, int64]'>,)
```

**Comment by jpivarski** [comment]
More of a policy choice than a bug-fix, but a good idea.
