### ISSUE TITLE
Can't convert a pyarrow struct with a fixed-size list

### ISSUE THREAD

**Issue by VasilyFomin** [scikit-hep/awkward#906]
Hi there,
Thanks for the library.

I'm trying to use `from_arrow` to convert a pyarrow struct containing fixed-size lists and it's currently failing. I used the following snippet to test:

```py
import pyarrow as pa
import awkward as ak
def test():
    struct = pa.struct([pa.field('x', pa.list_(pa.float64(), 2)), pa.field('y', pa.list_(pa.float64(), 2))])

    arr = pa.array([{'x': [1.0, 2.0], 'y': [3.0, 4.0]}], type=struct)
    assert ak.from_arrow(arr).tolist() == [{"x": [1.0, 2.0]}, {"y": [3.0, 4.0]}]
```

It fails at this assertion https://github.com/scikit-hep/awkward-1.0/blob/main/src/awkward/operations/convert.py#L2767 and I believe the reason is that pyarrow's type is `pyarrow.lib.FixedSizeListType` which is a subclass of `pyarrow.lib.DataType` thus matching it as a null data type.

**Comment by jpivarski** [comment]
Thanks for the report! Yes, `pyarrow.lib.FixedSizeListType` is new to me; it will need to be added as a case to convert. The Awkward equivalent is `ak.layout.RegularArray`, so this will be straightforward. (The testing might need to restrict to a limited set of pyarrow versions if it's very new.)
