### ISSUE TITLE
`from_parquet` with `lazy` raises `ArrowInvalid` 

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#932]
This is a weird bug that I can only trigger for certain forms. This form fails, but if you remove any of the inner-most fields, or remove an outer set of list brackets, it no longer fails.

```python
import io

import awkward as ak

array = ak.Array(
    [[{"addr": {"aget": 3,  "cobo": 0}}]]
)

f = io.BytesIO()
ak.to_parquet(array, f)
f.seek(0)

restored = ak.from_parquet(f, lazy=True)
ak.materialized(restored)
```

**Comment by agoose77** [comment]
~~OK, this is a fiddly one. I think what's happening is that `read_row_group` is being given the wrong column name; the column name seems to be `".list.item..."` whereas Arrow uses `""`~~

**Comment by agoose77** [comment]
This is being tracked in https://issues.apache.org/jira/browse/ARROW-13151

**Comment by jpivarski** [comment]
This was fixed in some version of Arrow. By now (Arrow 6.0.0), it's no longer a problem.
