### ISSUE TITLE
`argsort` produces invalid layout for `ListOffsetArray` with `offset[0] != 0`

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#967]
Given the following layout
```python3
layout = ak.layout.ListOffsetArray64(
    ak.layout.Index64([1, 4]),
    ak.layout.NumpyArray(np.arange(64)),
)
```
calling `argsort` does not produce a valid layout. It appears that the `index` parameter is not projected to start at 0:
```python3
>>> ak.argsort(layout, highlevel=False)
<ListOffsetArray64>
    <offsets><Index64 i="[1 4]" offset="0" length="2" at="0x00000ba033d0"/></offsets>
    <content><NumpyArray format="l" shape="3" data="0 1 2" at="0x000003c7b190"/></content>
</ListOffsetArray64>

```

**Comment by agoose77** [comment]
@ianna Jim mentioned that you might have an idea of where I should look to fix this. 

I *think* the issue might be that we assume any `ListOffsetArrayOf<int64_t>` has `offsets[0] = 0` because we always convert other `ListOffsetArrayOf` with `toListOffsetArray64(True)`.

https://github.com/scikit-hep/awkward-1.0/blob/main/src/libawkward/array/ListOffsetArray.cpp#L1892-L1908

**Comment by ianna** [comment]
> @ianna Jim mentioned that you might have an idea of where I should look to fix this.
> 
> I _think_ the issue might be that we assume any `ListOffsetArrayOf<int64_t>` has `offsets[0] = 0` because we always convert other `ListOffsetArrayOf` with `toListOffsetArray64(True)`.
> 
> https://github.com/scikit-hep/awkward-1.0/blob/main/src/libawkward/array/ListOffsetArray.cpp#L1892-L1908

@agoose77 - thanks for spotting it! Here it is - `argsort` assumes that the offsets do not change: https://github.com/scikit-hep/awkward-1.0/blob/ffb4ec846d4d5ca26a0c337ce2662bc0670efbbe/src/libawkward/array/ListOffsetArray.cpp#L2045

**Comment by ianna** [comment]
@agoose77 - I just checked, it's the same for `sort`

**Comment by agoose77** [comment]
Thanks @ianna, I'll make a note to address these next week.

**Comment by ianna** [comment]
> Thanks @ianna, I'll make a note to address these next week.

greatly appreciated! 

The fix should be simple. The content is contiguous, so are the offsets. The following shift works, but a new kernel function is needed, I think:

```diff 
(base) yana@iannas-macbook-pro-1 awkward-1.0 % git diff
diff --git a/src/libawkward/array/ListOffsetArray.cpp b/src/libawkward/array/ListOffsetArray.cpp
index 6d7adb2..ec56698 100644
--- a/src/libawkward/array/ListOffsetArray.cpp
+++ b/src/libawkward/array/ListOffsetArray.cpp
@@ -1824,9 +1824,14 @@ namespace awkward {
 
       outcontent = outcontent.get()->carry(outcarry, false);
 
+      Index64 outoffsets(offsets_.length());
+      for (int64_t i = 0; i < offsets_.length(); i++) {
+        outoffsets.data()[i] = offsets_.data()[i] - offsets_.data()[0];
+      }
+
       ContentPtr out = std::make_shared<ListOffsetArray64>(Identities::none(),
                                                            parameters_,
-                                                           offsets_,
+                                                           outoffsets,
                                                            outcontent);
       return out;
     }
@@ -1856,9 +1861,14 @@ namespace awkward {
         negaxis, util::make_starts(offsets_), nextparents,
         offsets_.length() - 1, ascending, stable);
 
+      Index64 outoffsets(offsets_.length());
+      for (int64_t i = 0; i < offsets_.length(); i++) {
+        outoffsets.data()[i] = offsets_.data()[i] - offsets_.data()[0];
+      }
+
       ContentPtr out = std::make_shared<ListOffsetArray64>(Identities::none(),
                                                            parameters_,
-                                                           offsets_,
+                                                           outoffsets,
                                                            outcontent);
       return out;
     }
``` 
```python
>>> import awkward as ak
>>> import numpy as np
>>> layout = ak.layout.ListOffsetArray64(
...     ak.layout.Index64([1, 4]),
...     ak.layout.NumpyArray(np.arange(64)),
... )
>>> sarr = ak.sort(layout, highlevel=False)
>>> sarr
<ListOffsetArray64>
    <offsets><Index64 i="[0 3]" offset="0" length="2" at="0x7ff1834ed110"/></offsets>
    <content><NumpyArray format="l" shape="3" data="1 2 3" at="0x7ff18348f920"/></content>
</ListOffsetArray64>
>>>
```

**Comment by agoose77** [comment]
Thanks for the advice! Is it possibly a good idea to make use of the existing `toListOffsetArray64(true)` vs writing a new kernel function to normalise the offsets?

**Comment by ianna** [comment]
> Thanks for the advice! Is it possibly a good idea to make use of the existing `toListOffsetArray64(true)` vs writing a new kernel function to normalise the offsets?

It will not help because the resulting sorted content is a copy of the original array's and is trimmed.

**Comment by ianna** [comment]
ha, it's already there: 
```python
Index64 outoffsets = compact_offsets64(true);
```

**Comment by agoose77** [comment]
> ha, it's already there:
> 
> ```python
> Index64 outoffsets = compact_offsets64(true);
> ```

Haha, well this PR just became considerably easier!

**Comment by ianna** [comment]
thanks, @agoose77! fixed - piggyback on https://github.com/scikit-hep/awkward-1.0/pull/946

**Comment by agoose77** [comment]
Great, thanks for fixing this Ianna.
