### ISSUE TITLE
Review `ak.ptp` implementation

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#992]
### Version of Awkward Array

1.4.0

### Description and code to reproduce

The existing implementation of `ak.ptp` works, but it probably doesn't handle `None` types very well; if the existing array already contains `None`s, these will probably be filled by https://github.com/scikit-hep/awkward-1.0/blob/4fe53b0a0a9b20b8d32f7cc7780e64885e63c60e/src/awkward/operations/reducers.py#L670

This might need to be implemented at a lower level in order to be able to perform this filling step for only the appropriate entries.

**Comment by jpivarski** [comment]
I fixed this when I was scanning for instances of `fill_none` without an `axis`.

https://github.com/scikit-hep/awkward-1.0/pull/917/commits/218f1510a18d494d220940600e4f3dd12d2425cc#diff-a3b1e9523d57fff0b3a1aaa1602078a7e413dd05cfc4781e3addbdaaa4c71f16

If the replacement value is a number (`0`), then the `axis` must be `-1` or else you'll get a union. Only `axis=-1` has numbers; all other levels have lists and records.

I see that the intention here is to make the point-to-point difference for empty lists zero, though `ak.min` and `ak.max` return `None` for empty lists. Even if the min/max reduction is performed at some `axis != -1`, their output will be `None` at `axis == -1` anywhere that zero values are included in a given min/max. So as a post-processing step, filling the nones with `axis=-1` is correct, regardless of the `axis` used in the reduction.

**Comment by agoose77** [comment]
My concern here is where we call ptp on an array that already contains none, shouldn't these nones remain unchanged?

**Comment by jpivarski** [comment]
At lowest level (`axis=-1`), they ought to have been eaten by the reducer. Let me try to come up with examples.

**Comment by jpivarski** [comment]
Actually, there are two problems here. First, though, the theory:

![](https://raw.githubusercontent.com/scikit-hep/awkward-1.0/main/docs-img/diagrams/example-reduction.png)

```python
array = ak.Array([
    [   0,    1, None      ],
    [None,    3            ],
    [                      ],
    None,
    [   4,    5, None,    6],
])

######## Using ak.sum:

assert ak.sum(array, axis=-1).tolist() == [
    1,         # 0 + 1
    3,         # 3
    0,         # list is empty
    None,      # list is missing
    15,        # 4 + 5 + 6
]

assert ak.sum(array, axis=-2).tolist() == [
        4,    9,    0,    6,
    # 0+4
    #     1+3+5
    #         no data
    #                     6
]

######## Using ak.min:

assert ak.min(array, axis=-1).tolist() == [
    0,         # min([0, 1])
    3,         # min([3])
    None,      # list is empty
    None,      # list is missing
    4,         # min([4, 5, 6])
]

assert ak.min(array, axis=-2).tolist() == [
        0,    1, None,    6,
    # 0,4
    #     1,3,5
    #          no data
    #                     6
]
```

One problem is that the two Nones in `ak.min(array, axis=-1)` would get conflated. This is what you were concerned about and you were right to be concerned about it. The application of `ak.fill_none` should be at the lowest level, but after reduction, we can't tell the difference between the lowest level and the second-to-lowest level.

We can fix that by using `keepdims=True` in `ak.min` and `ak.max`, then applying the `ak.fill_none` to `axis=-1`.

```python
>>> ak.min(array, axis=-1, keepdims=True)
<Array [[0], [3], [None], None, [4]] type='5 * option[var * ?int64]'>

>>> ak.fill_none(ak.min(array, axis=-1, keepdims=True), 999, axis=-1)
<Array [[0], [3], [999], None, [4]] type='5 * option[var * int64]'>

>>> ak.min(array, axis=-2, keepdims=True)
<Array [[0, 1, None, 6]] type='1 * var * ?int64'>

>>> ak.fill_none(ak.min(array, axis=-2, keepdims=True), 999, axis=-1)
<Array [[0, 1, 999, 6]] type='1 * var * int64'>
```

Of course, `ak.ptp` would be filling nones with `0`, not `999`, but this is for illustration and to distinguish from the first row/column. Everywhere that there's a 999 is a place where the maximum of an empty list would be subtracted by the minimum of the same empty list: horizontally in the `axis=-1` case and vertically in the `axis=-2` case.

If `keepdims=False` in the `ak.ptp` function, then we have to remove that extra dimension manually:

```python
>>> ak.fill_none(ak.min(array, axis=-1, keepdims=True), 999, axis=-1)[..., 0]
<Array [0, 3, 999, None, 4] type='5 * ?int64'>
```

The other problem is that reducers are producing double-masks (`??`):

```python
>>> ak.min(array, axis=-1)
<Array [0, 3, None, None, 4] type='5 * ??int64'>
```

which would have prevented `ak.fill_none` from taking effect if we didn't `keepdims=True`. Although `keepdims=True` works around that, this, too, should be fixed. I'll open a PR.

**Comment by agoose77** [comment]
It's a clever trick to use keepdims in order to distinguish the masks, thanks for raising it!
